### ISSUE TITLE
Make the realtime-preview for editing markdown files much faster

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#10]
I unfortunately am often turning off the markdown editor realtime preview, since on every keystroke it renders the whole preview on the right... which starts to lag.   Some ideas for improving matters:

- only render at most every k seconds, for some value of k.  This would help enormously.   Possibly vary k based on how long rendering actually takes on the browser.

- use React to render the markdown, so that it only changes the part of the DOM that actually changed. This could be very fast, but requires having a React component that renders markdown *and* isn't just cheating.  It really has to express everything in terms of React's DOM.   For example, https://github.com/acdlite/react-remarkable at first looks perfect, but if you look into the actual code it really just does `return <span dangerouslySetInnerHTML={{ __html: this.renderMarkdown(child) }} />;`.   If nobody has created a genuine react component yet, I think one could be authored by forking the code of a library like marked and making it generate react components instead of html as output, or by parsing the html string it generates.   Forking/modifying marked would also make it possible to edit directly in the output area, or at least to click there and give reverse search (i.e., move cursor to corresponding point in input).

**Comment by haraldschilly** [comment]
Could a webworker help? In theory, it wouldn't block the main UI. There could be one global webworker sitting in the background, for various tasks, and it receives command/id/data instructions and sends back the rendered html data and the id when finished. A dispatcher routes the message back to the correct location. I've no idea about all the details, though. http://www.html5rocks.com/en/tutorials/workers/basics/

**Comment by williamstein** [comment]
Almost certainly the problem is the DOM render time not the md to html
conversions...

On Tuesday, June 9, 2015, Harald Schilly <notifications@github.com> wrote:

> Could a webworker help? In theory, it wouldn't block the main UI. There
> could be one global webworker sitting in the background, for various tasks,
> and it receives command/id/data instructions and sends back the rendered
> html data and the id when finished. A dispatcher routes the message back to
> the correct location. I've no idea about all the details, though.
> http://www.html5rocks.com/en/tutorials/workers/basics/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/10#issuecomment-110320875>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
Use underscore.debounce.

**Comment by williamstein** [comment]
Done, long ago, using underscore debounce.
