### ISSUE TITLE
Side chat exhibits odd redraw behavior on window resize

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#1008]
When you resize the window and side chat is open, shrinking vertically can cover the input area and shrinking horizontally is very slow. Opening and closing the side chat redraws as expected with any new window size.

**Comment by williamstein** [comment]
raising priority -- this is actually really bad and easy to reproduce.

flex model!

**Comment by williamstein** [comment]
I'm working on a complete rewrite of side chat and editor placement/sizing.   Some screenshots:

<img width="1440" alt="screen shot 2016-11-06 at 11 44 32 am" src="https://cloud.githubusercontent.com/assets/1276278/20040987/88629352-a416-11e6-9e0a-82df47b8c038.png">
<img width="1438" alt="screen shot 2016-11-06 at 11 44 12 am" src="https://cloud.githubusercontent.com/assets/1276278/20040988/88641826-a416-11e6-997c-cbc2040da55c.png">
<img width="1440" alt="screen shot 2016-11-06 at 11 44 07 am" src="https://cloud.githubusercontent.com/assets/1276278/20040989/88643996-a416-11e6-9e90-9b0142fc57d1.png">

**Comment by williamstein** [comment]
Fixed right in the sidechatright branch.
