### ISSUE TITLE
saving sagews: unable to read json message in worksheet: [empty string?]

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1012]
There are several warnings when saving a sagews, appearing in sagews.coffe: `SynchronizedWorksheetCell.output`, where "x" seems to be an empty string. Could be a symptom of a more severe issue ...

**Comment by haraldschilly** [comment]
Via debugging I can see, that this warning always happens when there is a cell without any output.

**Comment by williamstein** [comment]
fixed by pr 1013
