### ISSUE TITLE
Simplify create project component

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1015]
Change explanation text to "A project is your own private computational workspace that you can share with others. Each project is free. What's not free is members only hosting and direct use of internet resources. Project resources like ram, cpu, and disk space can be upgraded. If you have any questions, please email help@sagemath.com immediately."
Have three buttons:
"Create project without any upgrades"
"Create project with members only hosting and direct internet access"
"Create project with customized upgrades"

Subscription/billing only show up if the 2nd button is clicked and upgrade is not possible without changing subscription/upgrade allocation or the 3rd button is clicked.

**Comment by williamstein** [comment]
Please move comments to #1016.  This is just one issue.
