### ISSUE TITLE
Deleted projects don't free their upgrades

### ISSUE THREAD

**Issue by paulsmart** [sagemathinc/smc#1024]
I can't think of any reason that a project would need its upgrades when it is in a deleted state.
It's currently manual and time consuming to track down all upgrades being used by deleted projects.

Could a project release all its upgrades when it is deleted please?

**Comment by haraldschilly** [comment]
Yes, you're right, for me this is kind of an oversight, too. However, there is already #282 and we just weren't able fix it.
