### ISSUE TITLE
when using %exercise in sagews, you have to click on the left side of the "Go" button.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1027]
Try this:
```
%exercise
title    = "Sum the first n integers, like Gauss did."
n        = randint(3, 100)
question = "What is the sum $1 + 2 + ... + %s$ of the first %s positive integers?"%(n,n)
answer   = n*(n+1)//2
```
Bizarrely the "Go" button has to be clicked on the left side.

**Comment by DrXyzzy** [comment]
If browser window is so narrow that title moves under Go button, the entire Go button is live.

**Comment by williamstein** [comment]
Wow, under the hood the whole interact rendering thing desperately needs to be completely rewritten using react!
