### ISSUE TITLE
when a latex file has an error, put a button right in the preview pane, and a remark that you must fix this error to see the rest of the document

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1032]
People are getting constantly confused by this.

The other option would be to replace the "stop on first error" behavior by the previous "try to compile everything", but have a timeout or do something to detect output that indicates a potential hang (so output stops getting sent to stderr or stdout)....

**Comment by haraldschilly** [comment]
Also, one of the issues with stoponerror was, that the error didn't came up at all. Latex just ended somewhere in the middle ... very stupid :-)

**Comment by williamstein** [comment]
closed, since we disabled stoponerror.
