### ISSUE TITLE
Public worksheets (and other objects?) are writable to creator

### ISSUE THREAD

**Issue by billpage** [sagemathinc/smc#104]
Several times I have unintentionally modified a Sage worksheet that I had previously made Public. Public worksheets are displayed ReadOnly when opened by other users but not the owner.  I guess I more or less think of something I have made Public as similar to being Published, so it is unexpected to me that I am still allowed to modify it after I have made it Public.  Perhaps I should have to first change to the worksheet backup to the non-public state or copy it to a new worksheet before even I am allowed to change it?. Then afterwards make it public again.  That way the system would prevent me from making the mistake of screwing up something to which I have made a public reference and really wanted other people to see in it's original form.

I tried to do something at a low level in a terminal to protect my Public worksheet from unintentional change by removing the write permission:
   % chmod u=w SageWorksheet.sagews
This works in as much as changes are not really saved (as shown by date and size in the terminal) but if I do make a changes the Save button just continues to rotate without any error message.  And more oddly, my changes seem to be stored somewhere because they are retained even if I do shift-reload.  Is this the expected behaviour?

**Comment by williamstein** [comment]
- chmod stuff is now fixed and works in realtime.

- regarding meaning of "published"... we don't use that word anymore (instead "Share").
