### ISSUE TITLE
when editing a file, the CTRL-I keyboard shortcut (which changes the split view mode) looses the scroll position but should not (the button does not loose scroll position)

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1044]
I often hit CTRL-I so can I go edit something else without losing track of where I was previously editing. When I hit CTRL-I both panes are scrolled to top. I think at least the one I was editing shouldn't scroll.

**Comment by williamstein** [comment]
Please provide slightly more precise steps to replicate this.   What's a pane?  What sort of file were you editing?  Thanks!

**Comment by timothyclemansinsea** [comment]
@williamstein https://cloud.sagemath.com/projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/files/work/Recording%20%231.mp4 shows that the second time I click CTRL-I on a .cjx file that the left side scrolls to the top. It should stay where it is at.

**Comment by williamstein** [comment]
Your video is impossible to use, but I figured out what you mean and changed the title to reflect this.
