### ISSUE TITLE
comments before doctype

### ISSUE THREAD

**Issue by billpage** [sagemathinc/smc#105]
http://lists.w3.org/Archives/Public/public-html/2011Feb/0253.html

Show source shows:

    

    <!DOCTYPE html>
    <html>
    
    ...

The comments occurring before the doctype is known to cause problems is some browsers and perhaps firewalls/proxies.  In any case they seem unnecessary since they also occur later after the html tag as expected.

**Comment by williamstein** [comment]
fixed by webpack switch
