### ISSUE TITLE
jupyter not showing up on samsung tablet

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1051]
the browser's user agent is: `Mozilla/5.0 (Linux; Android 6.0.1; SM-T715 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Safari/537.36`

**Comment by williamstein** [comment]
None of us devs has a samsung tablet...

**Comment by timothyclemansinsea** [comment]
https://testcloud.xamarin.com/devices has Galaxy Tab

**Comment by williamstein** [comment]
@johnjeng can you test jupyter on your ipad at least?

i'm closing since this is almost surely fixed now.

**Comment by johnjeng** [comment]
Yeah, I'll test cocalc.com with my ipad this week and probably make a number of fixes for webapp for it.
