### ISSUE TITLE
Make student names "mailto:" links in list for an assignment

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#106]
Graded an assignment and needed to email three students.  It'd be convenient if when viewing the list of all the students for a single assignment if the names (in first column) were also "mailto:" links for the email address of their account.  I could have easily harvested them from the links rather than going somewhere else to collect them.

**Comment by williamstein** [comment]
Done.

**Comment by rbeezer** [comment]
Excellent, just what I had in mind.  Thanks.
