### ISSUE TITLE
published files no longer work

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1064]
1. select a file to share it publicly (tried with an ipynb file [should end up in the ipynb viewer], html or pdf)
2. publish tag is there, copy the provided public access link
3. open it in private browsing → default landing page appears

**Comment by johnjeng** [comment]
Accessing public files while logged in is also broken.

**Comment by williamstein** [comment]
I mostly addressed https://github.com/sagemathinc/smc/issues/1064.  It was nontrivial!  I basically had to reimplement most of it from scratch.

It's NOT DONE, and I won't be able to work on this until Thursday again.  What remains is:
  - 1. the "download" and "copy to my project" functionality is broken still.  
  - 2. I didn't do anything sensible with binary images yet at all -- if you look at the old editor.coffee it shows how to properly detect them...  Right now it'll just try to display them as text.

However, I hope at least having sagews and ipynb/html working again will make some people happy.
