### ISSUE TITLE
serious problems with delete and what files show as will be deleted.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1068]
A file says it will be deleted but isn't checked:

<img width="633" alt="screen shot 2016-10-18 at 8 46 33 am" src="https://cloud.githubusercontent.com/assets/1276278/19485278/8294d7f2-950f-11e6-9635-8abc49ddf889.png">

Checking the file makes it get deleted **twice**?

<img width="766" alt="screen shot 2016-10-18 at 8 46 53 am" src="https://cloud.githubusercontent.com/assets/1276278/19485279/829a75ae-950f-11e6-9b73-f0176374546f.png">

**Comment by johnjeng** [comment]
Urgh. Having a tough time replicating this.

**Comment by williamstein** [comment]
Lowering priority since I've not seen this again, and nobody else has reported.  May close in a few days.  Was likely a side effect of some craziness in the react switch.

**Comment by williamstein** [comment]
I can't replicate this now.
