### ISSUE TITLE
latex doesn't make the issues tab red on error unless you click the tab

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1069]
This is horrendously bad, but whem making a mistake in a latex document, it does NOT clearly indicate so in red at the top until you click on the errors button.   Basically a lot of  the latex workflow is just busted right now making it horrible.  I probably somehow broke this when fixing some other latex bug, or it was broken by the top down rewrite.  I don't know.

**Comment by johnjeng** [comment]
Tentatively, this seems to be fixed by #1073. At least on my test server, every time I save a LaTeX document which generates an error, the button becomes red.

**Comment by haraldschilly** [comment]
I'm testing this (rolled out on test server) and discovered, that clicking save works, but autosave doesn't. I.e. autosave saves indeed, but no recompilation is triggered.

Just for completeness, this  could be related to #1080

**Comment by johnjeng** [comment]
Seems to be fixed with Autosave.
