### ISSUE TITLE
Jupyter notebook bugs: export pdf and print preview

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#107]
We are getting **tons** of support emails from people who can't convert jupyter notebooks to pdf, due to bugs in nbconvert.  If you hit this, right now the best thing to do is open a terminal and type

    ipython nbconvert --to pdf FILENAME.ipynb  

and try to *work around* the problems that pop up.

---
More from Harald:

 Firstly, the «export to PDF» function Returns a 500 error. I’m going to assume that this is because PDFs are now created using the –to pdf option, instead of –to latex –post pdf.
 
In addition, the «print preview» is also bugged, refusing to show «{» or «}» displayed as pure text With the LaTeX string «\{» or «\}». This makes turning in Math Projects very frustrating, since I now can’t print them out in any way. (I can’t get the PDF export on my local machine to work either)

[example notebook](https://cloud.sagemath.com/projects/ff4c5c50-6300-4120-8e3d-dbf79bfdade8/files/Oblig_2.ipynb)

**Comment by srdoty** [comment]
Also, the «print preview» does not refresh changes. In other words, if I first generate a «print preview», then make changes in the notebook, and try to generate another «print preview», I always get the original one, which does NOT reflect the changes I made. 

See [here](https://cloud.sagemath.com/projects/cf3c717d-ec7a-473b-b1cb-4900ecc48b04/files/optional-project-2/optional-project-2.ipynb) for the notebook on which I experienced this trouble.

**Comment by jasongrout** [comment]
@minrk - it looks like you are the main author of the pdf exporter, at least according to git blame.  Any comments?

**Comment by minrk** [comment]
Not really, I just did the move from postprocessor to standalone exporter. The only comment I have is that the PDF export via latex is super unreliable. We can work on issues as they are reported, and there's an open issue to at least relay the horrible nightmare of an error message that latex provides to the user, so we get useful bug reports to fix the myriad issues one by one.

**Comment by williamstein** [comment]
Workaround 

Type ipython nbconvert --to pdf file.ipynb

in a terminal. Then you can download the pdf it produces, or fix any issues that arise in latex.

**Comment by williamstein** [comment]
Closed in favor of https://github.com/sagemathinc/smc/issues/107
