### ISSUE TITLE
clean up rendering of history and preview

### ISSUE THREAD

**Issue by simonluu** [sagemathinc/smc#1074]
History and Preview rendering got messed up when #1038 updated the messages.

**Comment by haraldschilly** [comment]
I've merged #1075 since it is clearly better to have that in sooner than later. I don't know about this ticket  ... sounds very vague to me. Should we close it and you open up one with more specific goals? Just comment when you read this, no hurry ...

**Comment by simonluu** [comment]
Ok, that sounds good. I was just trying to mention this because of the change of the messages.
