### ISSUE TITLE
project tab list suddenly in responsive mobile mode

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1085]
I was just switching tabs back and forth, and suddenly the top part of SMC looked like this.looks like some responsive-mode got triggered. but how? I didn't even really resize my window... and regarding that, resizing my window to any width I want doesn't change it. It's stuck as this dropdown ...

![smc-responsive-error](https://cloud.githubusercontent.com/assets/207405/19558565/8952df18-96cb-11e6-8522-4c5f2320f303.png)

**Comment by haraldschilly** [comment]
happened again. this time, I was in the main projects listing page, typed in something to filter for a project, and did hit return. I was quite fast, though, so this might also be a race condition?

**Comment by williamstein** [comment]
My bet: just reading the source code will make it clear what is going on, and that there is some badly designed code in there.

**Comment by williamstein** [comment]
I just hit this.  I had my browser somewhat skinnier than usual when it happened. VERY ANNOYING.

**Comment by johnjeng** [comment]
Oh. I bet I know why. Right now the code does this when it thinks you have so many project tabs open that you can't possibly see the titles. So it changes to a drop down.

**Comment by haraldschilly** [comment]
@johnjeng well, that's a good idea, but despite that there are some layout and style issues (it's not really at the top, etc. … and more importantly, once I click to open another project, that drop-down should close. it just stays there until I explicitly close it.

**Comment by johnjeng** [comment]
Yeah, I need to fix it up some.

**Comment by williamstein** [comment]
I'm getting really tired of this bug.  Raising priority to high:

<img width="1051" alt="screen shot 2016-10-23 at 4 22 35 pm" src="https://cloud.githubusercontent.com/assets/1276278/19630311/0d8e9740-993d-11e6-841b-9796053a6dab.png">

**Comment by johnjeng** [comment]
@williamstein Which solution do you want implemented? It's trivial to revert it so that tabs just keep piling up on each other. I could also make a drop-down on the right side for projects more than a certain amount. 

Or just fix the issues Harald brought up like closing on click?

**Comment by williamstein** [comment]
Please revert it so tabs just keep piling up.  Isn't that was Chrome, Firefox, etc. do?
