### ISSUE TITLE
redo the CSS styling in project_page.cjsx

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1108]
In https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/project_page.cjsx, there's this sort of code:
```
    render : ->
        page_styles ='
            #smc-file-tabs-fixed>li>a {
                height:36px;
                padding: 8px 10px;
                border-radius: 5px 5px 0px 0px;
            }
            #smc-file-tabs-files>li>a {
                padding: 13px 15px 7px;
                border-radius: 5px 5px 0px 0px;
                -webkit-touch-callout: none; /* iOS Safari */
                -webkit-user-select: none;   /* Chrome/Safari/Opera */
                -khtml-user-select: none;    /* Konqueror */
                -moz-user-select: none;      /* Firefox */
                -ms-user-select: none;       /* Internet Explorer/Edge */
                user-select: none;           /* Non-prefixed version, currently
                                                not supported by any browser */
            }
            .smc-file-tab-floating {
...
```

that @johnjeng wrote.   There are some problems with this:

1. It uses the id tag  `#smc-file-tabs-fixed` for CSS selection.  According to the CSS spec, a given id tag should be used at most once in the DOM, but obviously these id's are used for every project.  

2. All this code should be in a sass file.  There's no reason whatever for this to be strings in the cjsx file.  That would maybe be faster, provide nice syntax highlighting, etc.

So, please rewrite this and any similar code.

**Comment by johnjeng** [comment]
1. Right now at any given time, there's only one project ever rendered to the screen so the set of open files is unique.

2. Okay.

**Comment by williamstein** [comment]
> Right now at any given time, there's only one project ever rendered to the screen so the set of open files is unique.

OK, cool - in that case add a comment ?

**Comment by haraldschilly** [comment]
I'll have a look at this, and we can also remove this `user-select: none` craziness. It's supported by all browsers, see: http://caniuse.com/#feat=user-select-none

**Comment by haraldschilly** [comment]
@johnjeng made a PR that probably solves this, but please review. I did this more or less blindly ...

pro-sass-tipp: in case this comes up again, here is how I did this. after copy/pasting the CSS and moving the indentation to the left, I did `sass-convert -F css -T sass -i _projects.sass`. then I used the mixin for the user select (see `index.sass`) and changed IDs to classes.

**Comment by johnjeng** [comment]
@haraldschilly Notice that a bunch of those green boxes have little yellow dashes which means they are supported *with* a prefix.
