### ISSUE TITLE
Possible improvements of the payment options

### ISSUE THREAD

**Issue by stumpc5** [sagemathinc/smc#111]
Here are quite a few random thoughts I had about possible improvements, they also come in random order.

1. Add **Paypal** support, and possibly also **Amazon checkout** and **Google wallet**, though I do not know how much they charge for the service. Two advantages I see there are that (a) only supporting credit card support limits the options and my credit card usage was declined various times (b) I can use something I know that it works without sending my credit card info to yet another company.

2. Emphasize the **advantages of the upgrades**. For me this seems currently mainly the usage of the **members-only servers** (you could even give some benchmarks showing that it is worth using that server). I think that many (including me and according to g+ also some others) do currently not really see any reason for purchasing the upgrade, except for *I want to support the project*. Another advantage is mentioned at #35: the free servers are rebooted too often to do long computations.

3. Add **course support with the $99/month upgrade** to enable that also the working students use the members-only server. If that's being used, you could limit this to a certain number of students (say e.g. 25) and one can add another 25 students for $49/month. Or something similar so that the students do not need to pay individually (the later is suggested in www.beezers.org/blog/bb/2015/09/grading-in-sagemathcloud/).

4. Harald mentioned "Finally, it's possible to add advertising for free users. Theoretically that could be quite a nice sum of additional income, because the  session time". I would think this would be a big using blocker for professional mathematicians who I would expect to be very critical concerning ads on their working screen (but this is obviously only my personal impression). On the other hand, some ads that might be interesting are **job advertisements** for people using the SMC.

5. Looking at my receipts of the upgrade, I see that both my receipts say "Subscription
to One Year Standard Membership". William mentioned that he thinks of changing this to "One Year Standard Upgrade Package". Nevertheless, if I purchase the *same upgrade the same day, the two receipts are identical* (which is really bad for getting the money reimbursed from my grant). So **adding some individual purchase number** would be good.

6. You could maybe also say on the pricing page, that even for using the cloud, **you suggest to support it by paying for an upgrade**. I and others considered paying without any need for the actual upgrade, so making that hint explicit does not hurt.

7. I think it would be worth **adding a** "Please support the SageMathCloud with an upgrade" **banner** on top (similar to the "support wikipedia" banner that you see sometimes there, I actually also saw it for the first time on the arXiv page the other day, see http://arxiv.org/new#sept10_2015) pointing people to the upgrade options. It could appear every time someone logs in, with an option to x it away. When reading that you had another 600 new accounts created in a single day, I would hope that it would be worth again and again trying to convince free users to pay for the usage.

8. After reading the "perfect tool for interviews" article William pointed to, I really wonder: **why should your SageMathCloud be free for non-mathematicians using it in professional context** (thus making money / reducing costs / etc with it) ? Do you consider to introduce a general fee for using the sage cloud which is waved for users in research / teaching / non-money-making contexts ?

9. Getting back to my request for publishing the upgrade numbers and Harald's "Another idea could be to publish a list of projects to implement requested features with a price tag ... like a tiny small
kickstarter": maybe instead of making the raw numbers public, you could **have a counter how many upgrades are still needed** in order for the SageMathCloud to support itself / to become faster / to become more reliable / other stuff people are interested in. Given some answers on g+, people including me seem to like to see some explicit goals to achieve. Also, you could list some specific features people might be interested in. When paying for the upgrade, they could then vote on which features they would prioritize. (Adding an actual price tag seems really hard to me, though.)

10. Now the upgrades section shows the possible upgrades, I think that's great! It might be worth **reconsidering what to put in the top row**. Currently, I see

        Projects | MyProject1 | MyProject2 |                             | MyName | Help | Notifications | Info

    Looking at the top row at Dropbox, I see

                            | Upgrades | Notification | MyName

    and at gmail, I see

        Google |                           Search         | MyName | OtherProducts | Notifications | MyPicture

    When clicking on MyName or MyPicture on either, further options show up. After briefly looking at the possibilities, I would suggest to do

        Projects | MyProject1 | MyProject2 |              | Upgrades | Help | Notifications | Info | MyName

    and clicking on MyName opens another box to click on "Settings", "Upgrades", "Log out".

    This way, it will be much more visible to every user that there are upgrade options. Finally, I would move the "Billings" to the bottom of the "Upgrades" section.

    Okay, overall I must confess that I would first need to implement this before seeing whether that actually makes sense. But maybe you can use it as a suggestion to slightly modify the bar to make the upgrade options better visible...

**Comment by williamstein** [comment]
Christian,

We discussed your suggestions at length yesterday, and they matched or
complemented many of the things we have wanted to do. Many thanks for
formalizing them!

William

On Mon, Sep 14, 2015 at 1:13 AM, Christian Stump <notifications@github.com>
wrote:

> Here are quite a few random thoughts I had about possible improvements,
> they also come in random order.
>
>    1.
>
>    Add *Paypal* support, and possibly also *Amazon checkout* and *Google
>    wallet*, though I do not know how much they charge for the service.
>    Two advantages I see there are that (a) only supporting credit card support
>    limits the options and my credit card usage was declined various times (b)
>    I can use something I know that it works without sending my credit card
>    info to yet another company.
>    2.
>
>    Emphasize the *advantages of the upgrades*. For me this seems
>    currently mainly the usage of the *members-only servers* (you could
>    even give some benchmarks showing that it is worth using that server). I
>    think that many (including me and according to g+ also some others) do
>    currently not really see any reason for purchasing the upgrade, except for *I
>    want to support the project*.
>    3.
>
>    Add *course support with the $99/month upgrade* to enable that also
>    the working students use the members-only server. If that's being used, you
>    could limit this to a certain number of students (say e.g. 25) and one can
>    add another 25 students for $49/month. Or something similar so that the
>    students do not need to pay individually (the later is suggested in
>    www.beezers.org/blog/bb/2015/09/grading-in-sagemathcloud/).
>    4.
>
>    Harald mentioned "Finally, it's possible to add advertising for free
>    users. Theoretically that could be quite a nice sum of additional income,
>    because the session time". I would think this would be a big using blocker
>    for professional mathematicians who I would expect to be very critical
>    concerning ads on their working screen (but this is obviously only my
>    personal impression). On the other hand, some ads that might be interesting
>    are *job advertisements* for people using the SMC.
>    5.
>
>    Looking at my receipts of the upgrade, I see that both my receipts say
>    "Subscription
>    to One Year Standard Membership". William mentioned that he thinks of
>    changing this to "One Year Standard Upgrade Package". Nevertheless, if I
>    purchase the *same upgrade the same day, the two receipts are
>    identical* (which is really bad for getting the money reimbursed from
>    my grant). So *adding some individual purchase number* would be good.
>    6.
>
>    You could maybe also say on the pricing page, that even for using the
>    cloud, *you suggest to support it by paying for an upgrade*. I and
>    others considered paying without any need for the actual upgrade, so making
>    that hint explicit does not hurt.
>    7.
>
>    I think it would be worth *adding a* "Please support the SageMathCloud
>    with an upgrade" *banner* on top (similar to the "support wikipedia"
>    banner that you see sometimes there, I actually also saw it for the first
>    time on the arXiv page the other day) pointing people to the upgrade
>    options. It could appear every time someone logs in, with an option to x it
>    away. When reading that you had another 600 new accounts created in a
>    single day, I would hope that it would be worth again and again trying to
>    convince free users to pay for the usage.
>    8.
>
>    After reading the "perfect tool for interviews" article William
>    pointed to, I really wonder: *why should your SageMathCloud be free
>    for non-mathematicians using it in professional context* (thus making
>    money / reducing costs / etc with it) ? Do you consider to introduce a
>    general fee for using the sage cloud which is waved for users in research /
>    teaching / non-money-making contexts ?
>    9.
>
>    Getting back to my request for publishing the upgrade numbers and
>    Harald's "Another idea could be to publish a list of projects to implement
>    requested features with a price tag ... like a tiny small
>    kickstarter": maybe instead of making the raw numbers public, you
>    could *have a counter how many upgrades are still needed* in order for
>    the SageMathCloud to support itself / to become faster / to become more
>    reliable / other stuff people are interested in. Given some answers on g+,
>    people including me seem to like to see some explicit goals to achieve.
>    Also, you could list some specific features people might be interested in.
>    When paying for the upgrade, they could then vote on which features they
>    would prioritize. (Adding an actual price tag seems really hard to me,
>    though.)
>    10.
>
>    Now the upgrades section shows the possible upgrades, I think that's
>    great! It might be worth *reconsidering what to put in the top row*.
>    Currently, I see
>
>    Projects | MyProject1 | MyProject2 |                             | MyName | Help | Notifications | Info
>
>    Looking at the top row at Dropbox, I see
>
>                        | Upgrades | Notification | MyName
>
>    and at gmail, I see
>
>    Google |                           Search         | MyName | OtherProducts | Notifications | MyPicture
>
>    When clicking on MyName or MyPicture on either, further options show
>    up. After briefly looking at the possibilities, I would suggest to do
>
>    Projects | MyProject1 | MyProject2 |              | Upgrades | Help | Notifications | Info | MyName
>
>    and clicking on MyName opens another box to click on "Settings",
>    "Upgrades", "Log out".
>
>    This way, it will be much more visible to every user that there are
>    upgrade options. Finally, I would move the "Billings" to the bottom of the
>    "Upgrades" section.
>
>    Okay, overall I must confess that I would first need to implement this
>    before seeing whether that actually makes sense. But maybe you can use it
>    as a suggestion to slightly modify the bar to make the upgrade options
>    better visible...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/111>.
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
Done or won't do or other tickets.
