### ISSUE TITLE
terminal width after project reset is width of welcome message

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1111]
Seen with Chrome and Firefox.
1. Open a .term and enter a long shell command (70 char should be enough):
   
   ```
   echo "There are more than 50 links on this page. Many users might find it easier There are more  than 50 links on this page. Many users might find it easier"
   ```
2. Restart the project while the .term tab is open. Return cursor to term tab, hit any key, and wait for terminal to restore after the project restart.
3.  Use command history to bring back the long command line. Line is truncated and wrapped:
   
   ```
   easier"sier There are more than 50 links on this page. Many users might find it e
   ```
4. Workaround when this happens is to adjust width of browser window.

**Comment by williamstein** [comment]
Probably not too hard to fix -- have to throw in a resize at some point.  Be careful not to BREAK things though by resizing when shouldn't and getting corruption/codes.   Also, we really need to do the next phase of terminal dev, which is react rewrite + better support for multiple users at once with different size screens!

**Comment by williamstein** [comment]
Seems to no longer be a problem.  I rewrote a lot of relevant code lately.
<img width="1116" alt="screen shot 2016-11-22 at 1 57 57 pm" src="https://cloud.githubusercontent.com/assets/1276278/20543699/b6307ebe-b0bb-11e6-887a-a63efd43cb5e.png">

**Comment by williamstein** [comment]
I tried again and replicated this.
