### ISSUE TITLE
Add multi-window support using PhosphorJS

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1116]
I believe using JupyterLab has made me more productive as I code a webapp. Jupyter itself seems pretty limited compared to SMC and I wish multi-window support was in SMC. I find JupyterLab's multi-window support far easier to use than Windows'. 

If multi-window support was added to SMC I would like to have the ability to mix things from multiple projects. For example I would want internal SMC dev chat on the right side but my primary working project files next to it on the left.

**Comment by haraldschilly** [comment]
I'm wondering, why multi-window support needs to be done in PhosphorJS? Can't it just be based on what we have right now?

**Comment by timothyclemansinsea** [comment]
@haraldschilly just seems to be a really nice feature rich framework for multi-window support.
