### ISSUE TITLE
removing myself from project collab leads to neverending "loading" notifications

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1135]
1. add someone else as a collaborator to a project
2. switch to that user's identity
3. "remove myself" from that project

now:

1. the project is still "open" (although everything except "files" is gone)
1.  in the top bar, there is a "Loading ..." spinner, which will never get the data it needs.

expected:

just close the project as a whole, don't register any store notifications, remove the disfunctional tab from the top bar, etc.

**Comment by williamstein** [comment]
Assigning @johnjeng, since this is yet another react-rewrite induced bug.

**Comment by williamstein** [comment]
I'll do this as a warm up since obviously very easy -- probably one line

**Comment by haraldschilly** [comment]
yes, I wasn't sure where to look ... today seems to be the day of one-liners
