### ISSUE TITLE
Long Handout Names Looks Unprofessional

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#1144]
Top handout is current. Bottom handout is proposed change.

**Edit:** Going to adjust the `trunc_middle` value.

![long handout names problem](https://cloud.githubusercontent.com/assets/618575/19744207/49a810da-9b81-11e6-80e8-f56868a99524.png)

**Comment by williamstein** [comment]
Also make the font size smaller?

**Comment by johnjeng** [comment]
Which font size?

**Comment by williamstein** [comment]
The font size of the "Long Handout Name".

**Comment by johnjeng** [comment]
The title above the `Edit Handout` button or the abbreviated title to the left of `Distribute...`? Both?

**Comment by williamstein** [comment]
The title in the first picture, which is taking up too much space.  Make it smaller so it takes up less space.
