### ISSUE TITLE
md *AND* html (and sagews) editor: left/center/right/justify buttons do nothing

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1156]
there is no markdown for adjusting text. maybe just get rid of these buttons?

alternatively, the selected text needs to be wrapped in a div, etc.

**Comment by williamstein** [comment]
Just as with colors, I think the buttons should stay, but be implemented using HTML, as HTML is a "subset" of Markdown...

**Comment by williamstein** [comment]
And yes, definitely a bug!

**Comment by williamstein** [comment]
'twas a stupid scoping mistake!
