### ISSUE TITLE
a name like "akić" doesn't appear correctly in our pdf invoices

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#118]

**Comment by williamstein** [comment]
Have to probably use a different latex backend engine...

**Comment by haraldschilly** [comment]
going through their bugtracker, switching the font seems to be a good idea. we have to find one which deals with more special characters. here is one of the [relevant tickets](https://github.com/devongovett/pdfkit/issues/76#issuecomment-13294290)
