### ISSUE TITLE
regenerate plots in the R worksheet(s) in the sage-examples repo

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1183]
See  https://github.com/sagemath/cloud-examples/tree/5db6a2be9dbae7edd100cd3fcba31128faeea90d/r

Just re-run the worksheet, save it. Done.  Commit and done.

**Comment by williamstein** [comment]
It is a but that all the plots are broken...

**Comment by DrXyzzy** [comment]
See: sagemath/cloud-examples/pull/15

**Comment by DrXyzzy** [comment]
Done. Repos updated by @haraldschilly:
- merged sagemath/cloud-examples/pull/15
- also updated parent repo https://github.com/sagemathinc/smc-examples
