### ISSUE TITLE
duplicate SSO account associations

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1187]
for reasons I don't know it must be somehow possible to associate more than one account with the same SSO address.

**Comment by williamstein** [comment]
> for reasons I don't know

Hmmm.  Maybe I just completely forgot to make it so you can't.    It's extra work to make it so you can't, isn't it?    Glad you created this issue.

**Comment by haraldschilly** [comment]
so, this is a race condition, when two account creations are initiated by the client at the same time.

**Comment by williamstein** [comment]
For starters, let's change the client (and the level of client.coffee) to make this impossible....  that should be very easy.
