### ISSUE TITLE
add forecast to R packages

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#119]
add `forecast` about here

https://github.com/sagemathinc/smc/blob/ced13344ce5492ebfac47aa4ea44e3abfe773880/salvus/build.py#L611

**Comment by williamstein** [comment]
This might only be an option once we upgrade Sage (or the R in Sage), since

     package ‘forecast’ is not available (for R version 3.2.0)

**Comment by williamstein** [comment]
I've added it here.  It'll either work and get added next time Sage gets upgraded or not

   https://github.com/sagemathinc/smc/commit/c9690ba1f5fb5ddd20bf1ef4f27510267e838f55
