### ISSUE TITLE
Proposal: Auto notify subscribers of upcoming charge

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1190]
I just dealt with a large company charging me for a annual subscription I don't use. I know this has happened with SMC. While the people got refunded ASAP I think it would be nice if we do what Microsoft does and auto remind people via email of an upcoming charge. A VPN provider I use also does this.

**Comment by timothyclemansinsea** [comment]
@williamstein Should I wait for the Postgres rewrite to work on this? I'm thinking some SQL query that generates a list of email addresses to email and a CRON job to send the emails and mark in a dataset who's been alerted.

**Comment by williamstein** [comment]
Yep, wait for the rewrite.   Let's makes the notification customized based on usage patterns -- e.g., if somebody isn't using SMC at all, ask one thing (and warn); if they are using it a lot say THANKS, and ask a different thing.

**Comment by williamstein** [comment]
Closing in favor of https://github.com/sagemathinc/smc/issues/863
