### ISSUE TITLE
grey background for opened notification bell menu

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1191]
just like it is for opened projects and the account tab

**Comment by DrXyzzy** [comment]
@haraldschilly please check if this is still a problem & suggest how to reproduce. I see some items grayed out in bell menu but don't know whether that is correct or not.

**Comment by williamstein** [comment]
Still a problem -- there is no visual indicator that the bell just got clicked on.
<img width="473" alt="screen shot 2017-02-21 at 10 28 08 am" src="https://cloud.githubusercontent.com/assets/1276278/23178780/8496ff70-f820-11e6-8dc0-7f06188dbff0.png">

**Comment by haraldschilly** [comment]
it's merged, closing it
