### ISSUE TITLE
sagews button bar: inserting code put a blank line at the top

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1201]
This is surely a bug in the misc_page codemirror plugin that inserts the mode itself, and will probably be easy to fix.

**Comment by haraldschilly** [comment]
I'm looking into this. Point is, anything that's being inserted adds an additional line.

**Comment by haraldschilly** [comment]
So, there are a couple of odd ends. E.g. the code snippets to insert actually contain newlines as their first character! That's of course going to add a newline. I'm fixing this in all the snippets and do some cleanup.

There is also some odd behavior for wrapping code, which is better tracked in a new ticket.
