### ISSUE TITLE
allow locking individual sage cells

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1204]
This is similar to locking parts of a document in graphics software to prevent accidental overwriting of work.

1. Add a `Show Cell Locking` entry to the Modes menu at upper left of sage worksheet.
1. `Show Cell Locking` will toggle between displaying cell lock status and hiding it.
1. When `Show Cell Locking` is active, an icon displays to left of the top line of each cell. The default would be unlocked, and clicking the icon toggles state of the cell between locked and unlocked and toggles the icon between `open lock` and `lock`.
1. A locked cell cannot be edited or executed and its output cannot be deleted.

The names `open lock` and `lock` come from Unicode. If we want to use UTF-8 for the icons, here  is the encoding:

- `lock` [U+1F512](http://www.fileformat.info/info/unicode/char/1f512/index.htm)
- `open lock` [U+1F513](http://www.fileformat.info/info/unicode/char/1f513/index.htm)

**Comment by williamstein** [comment]
Choose icons from http://fontawesome.io/icons/

**Comment by williamstein** [comment]
Tom Judson -- a longtime sagews lover -- was considering switching to Jupyter notebooks **just because this is missing in sagews**.  Let's address this.  Critical for students.

**Comment by williamstein** [comment]
dup of #871
