### ISSUE TITLE
avoid duplicate sign up for existing SSO account

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1208]
I don't know if the situation described below is already taken care of or not. Still, I want to write this down such that we check this.

1. sign up using google SSO
2. some day later, entering the same gmail email + password in the "create account" box.

What happened? Did this create a new account with the gmail address? It shouldn't. Instead, it should alert the user that there is already an existing account and the only way to sign in is to either reset the password or use google SSO.

This of course also applies to all other SSOs that provide email addresses (e.g. I think we get no email addresses from twitter)

**Comment by williamstein** [comment]
Definitely fixed in postgresql rewrite.  Not sure about live.  Won't matter soon.

**Comment by DrXyzzy** [comment]
Tested ok just now. Second attempt to create account gets white-on-red warning, "This e-mail address is already taken."

**Comment by williamstein** [comment]
This is enforced robustly now, both in the client, individual hub servers, **and** at the database level via a unique column constraint!
