### ISSUE TITLE
Error installing smc in a multi-machine environment

### ISSUE THREAD

**Issue by miguelmarco** [sagemathinc/smc#1218]
We are trying to install smc in a cluster, with different machines dedicated to different tasks.

So far we have been able to setup the web front ends, load balancers, database and hubs, by following the instructions in Install.md file (with minor tweaks, such as update directory names). But we have encountered problems with the compute nodes.

Here is a short list of the problems:

In Install.md it says to run

`~/smc/src$ ./install.py compute --all`

But  that fails with this message:

```
usage: install.py [-h] {pull,hub,webapp,primus,pyutil,sagews,project,all} ...
install.py: error: invalid choice: 'compute' (choose from 'pull', 'hub', 
'webapp', 'primus', 'pyutil', 'sagews', 'project', 'all')

```

What actually works is the following:

`ubuntu@calculo-2:~/smc/src$ ./install.py all --compute`

Also, in  INSTALL.md it says to use:

```
crontab -e

@reboot /home/salvus/smc/src/compute start > /home/salvus/.compute.log 2>/
home/salvus/.compute.err

```

But that is wrong, what works is:

```
/home/ubuntu/smc/src/smc-hub/scripts/compute start > /home/smc/.compute.log 
2>/home/smc/.compute.err
```

So far these are small problems in the documentation. But here comes the real problem. The coffeescript process that runs the compute nodes has trouble finding the dependencies:

```
ubuntu@calculo-2:~/smc/src$ coffee
coffee>  require 'c'
module.js:341
    throw err;
    ^
Error: Cannot find module 'c'

```

We can solve it by changing the require statement to be called as a function, and call it with the path and extension. But that same problem happens in many places in the source code:

```
coffee>  require('./c.coffee')
module.js:341
    throw err;
    ^
Error: Cannot find module 'smc-util/misc'

```

That is, if we change all statements in the .coffee files like the following:

` global.misc = require('smc-util/misc')`

to something like 

` global.misc = require('./smc-util/misc.coffee')`

I have seen that there is some function dedicated to solve this problem, but for some reason it is not called.

Is this a problem with a missing step in the documentation? Or is there some problem in the source code? In any case, could you please solve it?

**Comment by haraldschilly** [comment]
On Wed, Nov 9, 2016 at 11:57 AM, miguelmarco <notifications@github.com> wrote:
>
> So far these are small problems in the documentation. But here comes the real problem.


Yes, those two are documentation issues or what's missing is to generalize it.

Regarding c.coffee: did you try sourcing the smc-env file first? It
does some setup and is probably necessary for all those commands
buried inside the smc source tree.

-- harald

**Comment by miguelmarco** [comment]
We keep trying to install our own SMC cluster, but are finding the following problems:

- The code is a moving target and the installation documentation does not keep up to date
- Right now, it seems to deppend on gcloud tools. That makes the current setup incompatible with any installation that is not running phisically in google machines.

Is it actually possible to install a smc cluster outside of google infrastructure? Is there any documentation about it?

-- Miguel

**Comment by haraldschilly** [comment]
There is no hard dependency on gcloud tools. The only detail are backups of storage files, but that's not a necessity. There is no updated documentation and also no support for on premises installs.

**Comment by williamstein** [comment]
> and also no support for running SMC via on premises installs.

... except for the Docker image, which we do "support", in the sense that we encourage usage.  It is very easy to install.   https://github.com/sagemathinc/smc/blob/master/src/dev/docker/README.md

I'm going to close this issue.
