### ISSUE TITLE
Read/write lock can persist

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#1219]
`path_read -- file is currently being read or written` happens when users attempts to read and write at the same time. It should disappear after 15 seconds but a scenario happened where it persisted for 12 minutes at which point the project was restarted.

@williamstein mentions that this will be almost impossible to replicate so it will have to be solved mentally.

**Comment by williamstein** [comment]
This is very, very likely caused by autosave.  If two clients had the minimal 15s autosave (or just a few with a bigger one), this would happen due to another bug I'm fixing now.
