### ISSUE TITLE
"pure html" mode for html previews

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#122]
*"My idea would be to simply and purely not use any CSS rule for displaying HTML, that is to have the raw version but inside the preview window. This is just for pedagogical reason rather than practical ones. This would avoid to have to open the HTML page using the "raw" mode.*"

Personally, I think it's nice that there is a default CSS, but I see that this is useful. Idea how to do this: next to the "preview" checkbox, add a "raw" checkbox. If raw is true, the content of the preview box is an `<iframe>` pointing to the `../raw/..` html file and reloaded automatically (via a debounce logic).

(Another idea might be to look into those "shadow dom" technique. I think this might also be able to do this)

**Comment by williamstein** [comment]
close in favor of https://github.com/sagemathinc/smc/issues/327
