### ISSUE TITLE
autocomplete with * [space] variable

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1225]
Case 1. This does not autocomplete in sagews:
```
z = 45.9 * units.len[tab]
```
but this does
```
z = 45.9 + units.len[tab]
```

Case 2. This does not autocomplete:
```
class TC:
    def __init__(self, xval):
        self.x = xval
y = TC(49)
-- new cell --
z = 12 * y.[tab]
```
but this does:
```
z = 12 + y.[tab]
```

Autocompletion also succeeds if the operator is omitted.

**Comment by haraldschilly** [comment]
I think that's solved, closing it -- reopen if I'm wrong.
