### ISSUE TITLE
make it possible to allow user B to allocate upgrade credits purchased by user A.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#123]
Requested by Paul Smart. 

His use case is multiple people managing a course and wanting to be able to let everybody involved upgrade the student projects.   One mechanism to enable this would be for Paul to explicitly allow X to allocate his credits in any circumstance.

**Comment by paulsmart** [comment]
Hi William,
Do you have any update in this please?
Recent problems around not assigning enough RAM to a project can only be corrected by me. If I am not available, my team can't resolve the problem.

Thanks

**Comment by williamstein** [comment]
Unfortunately, I haven't been able to implement this yet.

On Wed, Nov 4, 2015 at 1:19 PM, Paul Smart <notifications@github.com> wrote:

> Hi William,
> Do you have any update in this please?
> Recent problems around not assigning enough RAM to a project can only be
> corrected by me. If I am not available, my team can't resolve the problem.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/123#issuecomment-153868554>.
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
Duplicate of https://github.com/sagemathinc/smc/issues/183
