### ISSUE TITLE
typeset_mode (and any other % mode) is incompatible with _ (underscore) for last output

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1230]
REPORTED BY: Brian Brady

[Example worksheet](https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-11-14-190805-_-typeset.sagews)

<img width="773" alt="screen shot 2016-11-14 at 7 12 51 pm" src="https://cloud.githubusercontent.com/assets/1276278/20291891/62d670b6-aa9e-11e6-98f3-e86b156d9517.png">

---

How to fix?   Learn more deeply how _ assignment works, e.g., with sys.displayhook, then modify show to explicitly call into that API.... if possible (maybe it isn't exposed).  If the api isn't exposed for setting _ then we will have to implement the whole _ thing from scratch ourselves, I guess.  Note that obviously just setting _ won't work, since once explicitly set, Python then no longer automatically sets it.

**Comment by DrXyzzy** [comment]
I don't think this is a bug. `%show` is an alias for `show()`, which returns `None`. The effect of returning `None` in the REPL is to leave `_` unchanged. Example:
<img width="120" alt="screenshot 2016-11-29 21 49 29" src="https://cloud.githubusercontent.com/assets/528072/20739134/c60e553c-b67d-11e6-99b4-18ade6b28239.png">

**Comment by williamstein** [comment]
@hal -- OK -- wll re-open if there are further periodic complaints from users.
