### ISSUE TITLE
the link for editing ~/.ssh/authorized_keys is completely broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1231]
In project settings, click "SSH", then "SSH into your project: First add your public key to ~/.ssh/authorized_keys, " and the link yields a red error message that some api was changed.  This is VERY RECENT, since it isn't even a problem in a docker image I built a week ago.

See:

<img width="781" alt="screen shot 2016-11-14 at 7 32 34 pm" src="https://cloud.githubusercontent.com/assets/1276278/20292315/68f04636-aaa1-11e6-89c5-673c0c708a0f.png">

**Comment by haraldschilly** [comment]
yes, fixed in #1232
