### ISSUE TITLE
Got a no response error in terminal

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1240]
This only happens on test.sagemath.com not cloud.sagemath.com: `{"event":"error","id":"7c06e62f-8ec7-4a76-a6d7-567cbadf8bcc","error":"no response"}` No clue what I'm supposed to do to resolve this.

Opening the exact same file in cloud.sagemath.com shows a new terminal

**Comment by williamstein** [comment]
Closing unless there is a clear reproducible issue.  There are many ways you can get an error, and an error was displayed...

**Comment by timothyclemansinsea** [comment]
Hey no I like the cloud.sagemath.com behavior of just resetting the
terminal. With this new behavior there seems to be nothing I can do but
delete the terminal.

**Comment by williamstein** [comment]
How do I reproduce this problem?

**Comment by timothyclemansinsea** [comment]
Use a terminal on a heavily loaded free server on test and within minutes
you should have this problem.

**Comment by timothyclemansinsea** [comment]
Also maybe just restarting the project causes this. Let me try that.

**Comment by timothyclemansinsea** [comment]
Maybe nvm. None of the problematic terminals are giving me an error on test
anymore.

**Comment by williamstein** [comment]
> Maybe nvm. None of the problematic terminals are giving me an error on test
anymore.

For what it is worth, yesterday I made some code changes that should (and provably are today!) result in some major improvements to the free server performance (especially after reboot).
