### ISSUE TITLE
Size of search in file listing if off for non-default zoom

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1248]
<img width="1075" alt="screen shot 2016-11-17 at 11 58 38 am" src="https://cloud.githubusercontent.com/assets/1276278/20405292/4c427824-acbd-11e6-8a98-76e903e3a6da.png">

**Comment by johnjeng** [comment]
Well...
https://github.com/twbs/bootstrap/issues/15840

I'm not gonna try to fix this then.

**Comment by williamstein** [comment]
It's a chrome bug!  Also a bug in safari (I just checked).   Not a bug in Firefox.
