### ISSUE TITLE
smc_sagews tests depend on current working directory

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1251]
when running those tests, they fail if I'm in a parent directory (i.e. `python -m pytest -x smc_sagews/tests/`) ... uhm, they even fail, if I run them exactly as explained in the tests readme file.

```
assert 'stdout' in {'done': False, 'event': 'output', 'id': 35, 'stderr': 'Error in lines 1-1\nTraceback (most recent call last):\n  File "...ttach\n    raise IOError(\'did not find file %r to attach\' % fname)\nIOError: did not find file u\'a.sage\' to attach\n'}
```

i propose, that there should be a change of the working directory, at least for those tests where the file is being attached.

**Comment by DrXyzzy** [comment]
Done.
