### ISSUE TITLE
sagews autocomplete 2*sq[TAB]

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1252]
<strike>After #1239 is in</strike> Ok, it was broken before, too.

The autocompletion of `2*sq[TAB]` for e.g. `2*sqrt(2)` is not working.

**Comment by DrXyzzy** [comment]
Also `2+sq[TAB]` is not working, and it goes through different code.

**Comment by DrXyzzy** [comment]
Done.
