### ISSUE TITLE
when printing plots in sagews worksheets, they should never be so large they go off the page

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1255]
For example, just do
```
plot(tan(x),(x,-2*pi,2*pi),ymin=-10,ymax=10,detect_poles="show")
```
and print it.

<img width="1074" alt="screen shot 2016-11-18 at 1 21 01 pm" src="https://cloud.githubusercontent.com/assets/1276278/20447110/f6f8fb06-ad91-11e6-83a8-58a8dbbe4c71.png">

**Comment by haraldschilly** [comment]
thank's to the powers of `adjustbox` this can be closed
