### ISSUE TITLE
embedded youtube video broken?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1264]
the error `Uncaught ReferenceError: ytcfg is not defined` suggests that there is something wrong with the embedded youtube video

**Comment by williamstein** [comment]
Generally bug with hundreds of complaints in the last week: http://stackoverflow.com/questions/40622204/uncaught-referenceerror-ytcfg-is-not-defined

**Comment by williamstein** [comment]
This is something we can't fix, and it'll get fixed automatically by google/youtube.  I couldn't even find any workarounds.

**Comment by williamstein** [comment]
This is something we can't fix, and for which I couldn't find any workarounds either.   It'll get fixed automatically by Google.

**Comment by haraldschilly** [comment]
that's fixed, closing.
