### ISSUE TITLE
shift click to select a range of files is now broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1285]
@johnjeng your fix so that copy/paste works for filenames in the listing **amusingly** seems to have forgot the whole reason for this issue in the first place -- namely one wants to select one file, then **shift-select** another, and have the whole range of files be selected.  This is now broken -- shift click behaves the same as click.

**Comment by johnjeng** [comment]
lol wat. I'll be sure to fix this today. Driving to Olympia right now.

**Comment by williamstein** [comment]
> lol wat.

Yep.  Even worse is that I reviewed this and didn't bother to check that case!  It'll probably take you only 30min to fix.

Have a fun Thanksgiving!
