### ISSUE TITLE
latex editor doesn't respect custom command on very first run

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1294]
this is just a hunch and needs some investigation. Check, if the very first time after opening up a latex file with a custom build command (specs at the bottom as a comment), it is instead still built with the default command. Expected behavior is to run it with the custom command the very first time!

**Comment by williamstein** [comment]
I can't replicate this.  I made this custom command 
```
date > abc; pdflatex -synctex=1 -interact=nonstopmode '2016-11-23-093156.tex'
```
and every time I open the latex file, the `abc` definitely and immediately does get updated.  So the custom command is getting run.

Please come up with a precise way to replicate this... or close.

**Comment by williamstein** [comment]
Closing since can't replicate.
