### ISSUE TITLE
sagews and %javascript -- doesn't re-evaluate if input doesn't change

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1297]
Put this in a cell and evaluate it over and over again:
```
%javascript
print(new Date())
```

The output doesn't change.  However, if you change the input at all, suddenly the output does change.  HMM...

**Comment by DrXyzzy** [comment]
But this updates whenever it is evaluated.
```
%javascript(once=True)
print(new Date())
```
I'm going to check if flag semantics is inverted in the UI.

**Comment by DrXyzzy** [comment]
I can no longer reproduce this problem. There may be a second or two latency when first re-executing in a worksheet that has been stopped, but after that the date updates every time the cell in the initial report is evaluated.

I recommend closing this issue. We can reopen if the problem occurs.
