### ISSUE TITLE
Allow video chat for all file editor types

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#13]
It's a little incongruous that the chat only works in the TeX editor, when it might be just as useful outside of it.  Maybe it should be a meta-thing that works at a project level and you can switch between things?

**Comment by williamstein** [comment]
> Maybe it should be a meta-thing that works at a project level

We now have chat rooms.  That would be the place to add video chat.   We should add it there.

All other editors having their own chat will happen when we rewrite the appropriate level in react.

**Comment by williamstein** [comment]
Somebody should make some other tickets and close this one:
 - add video chat to chat rooms
 - ensure that the editor refactoring results in a chat for all editors uniformly.

**Comment by kcrisman** [comment]
For reference (since no one did it when closing!) #713 and #714 are the followups.
