### ISSUE TITLE
latex editor on firefox -- either remove (or strongly disable when not selected) the PDF tab

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1313]
Christian Schmid says:
> The pdf file is occasionally downloaded automatically -- for example, when starting to edit the
> document, or when opening or closing the chat window.
> The pdf issue disappeared, but reappeared when I changed the standard
> pdf handling in Firefox from 'Preview in Firefox' to 'Open in Evince'.

That kind of makes sense -- when it updates the pdf, then it opens it in evince, which involves downloading.  Thanks for providing a way to replicate this.  The change we'll have to make is to ensure the embedded pdf isn't updated (in fact it's got to be completely removed the DOM) whenever that tab isn't visible.  Alternatively, maybe I'll just completely remove the "PDF" tab on Firefox.

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/1314

**Comment by haraldschilly** [comment]
after merging this branch above, the PDF tab is doing a download in firefox. that's a simple stopgap until it works.
