### ISSUE TITLE
address performance issues with Firefox and (probably) the flex layout

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1314]
To replicate -- open a file in the editor -- say with about 1000 lines, and try to type.

The issue is far less obvious on  OS X Firefox.   However, on Linux Firefox (in a VM
over X11 + ssh) I do see a significant performance issue.    Exactly the same tests with
Chrome + Linux work fine.  The main recent change to SMC is to make much more extensive use of Flexbox.  A quick search, shows there seem to be a ton of major open issues involving Firefox's performance when using Flexbox:

https://bugzilla.mozilla.org/buglist.cgi?quicksearch=flexbox+slow

e.g., "Firefox slow to the point of hanging when rendering nested flexbox layout with overflow-y: scroll":

     https://bugzilla.mozilla.org/show_bug.cgi?id=1281137

As that ticket mentions, Chrome, Edge, and Safari all work fine.

This ticket  has a simple jsfiddle link to a very simple test case that takes like 20s or more (or kills firefox), and it was reported well over a year ago:

   https://bugzilla.mozilla.org/show_bug.cgi?id=1209697

Try out this jsfiddle on Linux Firefox to see how broken Firefox is:

  http://jsfiddle.net/lukebmay/aghfkwmc/1/

When I tried it under Linux, Firefox 50 got stuck at 100% for a minute, and I gave up.  When I tried exactly the same page under OS X (with Firefox 50), it was a little slow, but worked fine. 

It took me weeks of hard work to rewrite SMC to properly use flexbox layout for editors and side chat, and there are many advantages to doing so (much better code, cleaner layout, etc.).   I don't think there is going to be an easy fix for this issue, beyond writing a lot of new ugly code in SMC specifically to workaround firefox's flex layout on Linux being severely broken.  Judging by the age and easy of replication of https://bugzilla.mozilla.org/show_bug.cgi?id=1209697, the Firefox devs just don't care or have the resources to ever fix this, unfortunately.

**Comment by williamstein** [comment]
I put "probably" in the title, since @johnjeng did testing on firefox awhile ago --for the react top down rewrite -- before there was much flexbox usage, and he said there were major performance problems.  He is using Linux.  So there could be some other unrelated problems involving firefox and SMC.

**Comment by williamstein** [comment]
Further note -- see 

for a stopgap.  Also, I have no way to test on Firefox windows, so no idea if things work fine there or not...  I should install Windows on a partition on a laptop for testing.

**Comment by williamstein** [comment]
Update: the original reporter says "2 people also told me about this;  they were using Firefox on Windows."  This confirms the problem is also on Windows.

**Comment by williamstein** [comment]
I also tested -- the problem is also on Windows.

From OP -- definitely caused by flexbox:

> Just FYI: I tried an SMC installation where I replaced the smc-webapps and webapp-lib folders with versions from Nov 2. The performance issue is gone there.

Idea for addressing this -- move all flex styles to CSS, and have some special case code run only on firefox that replaces those CSS rules by something that doesn't explicitly use flexbox... then use Javascript to fake it on every window resize.

**Comment by emilio** [comment]
Just FYI, I landed a fix for the Firefox bug that this issue points to. Could you please verify that SageMath works as expected now with a Firefox Nightly build? (https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)

**Comment by DrXyzzy** [comment]
I just tested the jsfiddle snippet at the link above:
- __Ubuntu 16.04.1 and FF 51.0.1 over SSH from my Mac running xorg-server:__  After clicking `Run` on the snippet, CPU load jumps to 47% at 3 seconds and rises to 100% for the next 12 seconds, then returns to less than 3%, and FF is usable after that.
- __OS X 10.11.6 with FF 51.0.1:__ After clicking `Run`, CPU load rises to 60% or so at 5 seconds, then drops to normal after 8 seconds.

**Comment by DrXyzzy** [comment]
@emilio I have confirmed that `Firefox Nightly 54.0a1` (2017-02-07) on Ubuntu 16.04.1 and OS X 10.11.6 show __virtually no CPU load spike__, less than 10% on both, and that is only for a few seconds after clicking `Run` on the jsfiddle test snippet.

**Comment by DrXyzzy** [comment]
Blocked pending release of Firefox later than 51.0.1 that includes the above fix.

**Comment by williamstein** [comment]
This is fixed in Firefox 52.  I just tested it.

**Comment by williamstein** [comment]
time: 0:05
