### ISSUE TITLE
set "reply-to" field in invitation emails to user's email address

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1316]
in transactional invitation emails, set the "reply-to" email address to the user's email address. don't set the "from" email field, otherwise it's spam and breaks dkim!

the outcome should be, that replies to invitations no longer end up in our email servers.

(and well, if there is no email address set, don't set the reply-to field)

**Comment by haraldschilly** [comment]
working on this one, which will include a full api update to version 3 (our version 2 is deprecated)

**Comment by williamstein** [comment]
you did this already.
