### ISSUE TITLE
task list and chat focus

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1318]
Currently the chat on the side of task lists is unusable since the task list keyboard shortcuts maintain their focus.  

(This may suck to fix, since the fix will just have to be rewritten when tasks is rewritten using react...)

**Comment by johnjeng** [comment]
So, I actually have a fix for this (it's nearly identical to the case for opening file notifications) but it's a little hacky. 
The alternative is for me to finish my work on a keybindings system in smc. Keybindings don't have much to do with react so thoughts on me doing the latter to fix this bug?

**Comment by williamstein** [comment]
Thoughts: +1 to **fixing this right** (which should be a our goal at this point with everything related to editors), which should definitely be via a keybindings system.   If it takes more than 1 day, that's ok, since chat on tasks didn't exist at all until a few days ago.

(Note that I had to deal with similar focus issues with console.coffee recently.  However, there it is very subtle and painful, due to there being a hidden textarea, which must be properly focused, in order for paste to work, and similar subtle issues involving copy.)
