### ISSUE TITLE
disable the message "Your internet connection is unstable/down or SMC is temporarily not available. Therefore SMC is not working." or make it work properly

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1320]
I opened my laptop -- as it connects to a fast campus network -- and this is what I see:

<img width="1385" alt="screen shot 2016-11-30 at 11 06 08 am" src="https://cloud.githubusercontent.com/assets/1276278/20766933/23093012-b6ed-11e6-86c1-09c0177cf7eb.png">

I also looked at the errors people are seeing and they frequent get the above.

We need to disable this message or make it work properly.  It's clearly way way too sensitive -- its not the sort of thing one should routinely see.

**Comment by williamstein** [comment]
@haraldschilly 
Can you look at this again.  If frequently see this the moment I unsuspend my laptop, which is really silly.

**Comment by Eulerianial** [comment]
Is it fixed or still in progress?
