### ISSUE TITLE
sometimes -- maybe 1 in 50 -- when switching to a codemirror editor tab, the cursor and scroll positions aren't restored properly

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1327]
If you then close and open the tab (without touching the editor), it does properly restore them.

This is thus likely some sort of race condition.  I'm sure it was introduced by my rewrite of editor stuff recently, since I removed pages (?) of hacks and replaced them with much less nice code... but.

This is quite annoying and important to fix, given the constant page switching one does in SMC.

**Comment by haraldschilly** [comment]
I wasn't able to reproduce this, so I can only speculate around. Maybe the race condition is between syncdoc's `@editor._set( ... )` and then initializing the cursor activity ... while a tick later the editor does restore the location? I'll experiment more around by removing the `setTimeout` in the editor ... maybe that needs to be replaced by explicitly triggering `restore_cursor_position` when it is really ready.

**Comment by williamstein** [comment]
> I wasn't able to reproduce this

Thanks for looking -- for what it is worth, I've hit this about **15 times a day** while working on the postgres rewrite.   I'll try making some of the changes you suggest above asap, then see if I hit this today.

**Comment by williamstein** [comment]
Commenting out these two lines in editor.coffee:
```
        for cm in @codemirrors()
            cm?.refresh()
```
basically causes this issue every time.  So there is very likely a race where the screen hasn't fully rendered but refresh is called.  Fix -- just call refresh, then call it again after a short timeout.  I think its safe to call it at any time ever, with the only possible drawback being efficiency -- refresh is how codemirror lays itself out based on measuring itself.

**Comment by williamstein** [comment]
I worked all day and didn't see this bug once.  So it's fixed.

**Comment by williamstein** [comment]
I saw this just now agan.  So... not fixed, but much less likely.

**Comment by williamstein** [comment]
*REPLICATED!*  Open a file, scroll around, click the time travel button, do NOT close the original file, sroll around in time travel, then click "Open file" from within time travel.  For me, every single time  do this, it messes up the original file position.

**Comment by DrXyzzy** [comment]
I'm able to replicate above as noted Dec 9. Also:
1. If I do the same steps a second time (scroll in file, scroll in time travel, open file), the bug does not recur.
1. If I scroll in time travel, then scroll in file, then go back to time travel, cursor is always repositioned at top of time travel view.

**Comment by haraldschilly** [comment]
this must be a stupid name clash. I'll look again if I see it. I predict we'll all cringe once we know the cause.

**Comment by williamstein** [comment]
Definitely fixed now :-)

**Comment by williamstein** [comment]
time: 2:10
