### ISSUE TITLE
\$ gets rendered as \$ in markdown

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1329]
E.g., try this in a chat message
```
Get some $ money \$
```
and you'll see `\$` rather than just $.

**Comment by williamstein** [comment]
Obviously, this is a bug in the sense that nothing is implemented to prevent this.  However, we need a way to enter dollar signs in text, and \$ (escaped dollar sign) is a reasonable way to do it, and is something I **did** implement for other markdown converters in SMC (just not the react one used in chat).

**Comment by williamstein** [comment]
Related: the link to github flavored markdown that we give should be replaced to a link to our own wiki, which documents use of mathjax and \$, and then has a link to github flavored markdown.

**Comment by johnjeng** [comment]
I'm slightly confused by this ticket.

In my testing,
```
Get some $ money \$
```
gets rendered exactly as such. However,
```
Get some \$ money \$
```
renders to
```
Get some $ money $
```
as expected?

**Comment by williamstein** [comment]
> as expected?

No.  The very first thing should just result in `Get some $ money $`.

**Comment by johnjeng** [comment]
>In no case should \$ every actually show a \

Gotcha.
