### ISSUE TITLE
bugs in the SMC archive application when the input is a .tar.gz file and a .tar file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1334]
1. create a 30MB .tar.gz file (say).
2. click on it in the UI -- it will offer to gunzip it, but that is it (it should view it as a tar archive, and offer to extract it!)
3. One unziped, try clicking on the .tar file -- you'll get the message: "file 'blah.tar' size (=38.47168MB) too large (must be at most 4MB); try opening it in a Terminal with vim instead or write to help@sagemath.com".  However, there's no reason to be opening the file as a syncstring, so that message shouldn't happen.

**Comment by DrXyzzy** [comment]
Replicated with 13 MB file created using part of smc source checkout:
```
cd
tar -czf junk.tar.gz smc/src/node_modules/
==> 12677069 .. junk.tar.gz
```

**Comment by williamstein** [comment]
Are you 100% sure you replicated exactly what I state above, especially after refreshing your browser?  I just pushed something that would address this an hour ago...

**Comment by DrXyzzy** [comment]
Refreshed everything and it works now. Clicking "Extract Files..." for "junk.tar" yields Contents listing.
