### ISSUE TITLE
remove jupyter hack when certain upstream bug is fixed

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1343]
Hack introduced here:  https://github.com/sagemathinc/smc/commit/09e4a7e5383864bfdb150e6d80fc412ce67cab0d

Bugfix PR is here: https://github.com/jupyter/notebook/pull/1956

**Comment by williamstein** [comment]
The upstream fix has been closed and maybe released.  @jasongrout emailed to tell me.

**Comment by williamstein** [comment]
I tried to fix this but in fact 4.3.1 breaks other things... so reverted.

**Comment by jasongrout** [comment]
@williamstein - Is it the token mechanism that breaks things? You can turn off the token authentication using the config file or the command line: `--NotebookApp.token=""`. It's probably better to implement something to use the token authentication, or it may not matter as much for you if you have bigger sandboxing going on.

**Comment by jasongrout** [comment]
I should have looked at your diff before writing that - you already knew about the token mechanism and how to disable it. Let us know if there are other things upstream that are causing problems.

**Comment by williamstein** [comment]
irrelevant now due to rewrite
