### ISSUE TITLE
sometimes right when starting editing a file in a newly refreshed editor, the first saved edit disappears

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1344]
This doesn't happen anymore in that session. Undo doesn't bring back the one single edit that vanished and it isn't in the log.    It only happens once in the session (so everything is fine until the next page refresh).

**Comment by DrXyzzy** [comment]
I was not able to replicate this issue. I started with a new .md file and tried single edits with the new file and after refreshing the browser tab, both waiting for autosave and manually clicking save, and could not get any edits to disappear.

**Comment by williamstein** [comment]
Let's close it.  Recent changes I've made would have very directly addressed this.
