### ISSUE TITLE
broken mathjax for published ipynb

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1347]
1. enter some latex into an ipynb, e.g. a markdown cell with `# $U_1$`
2. publish it
3. open the html file in incognito mode

expected result: mathjax runs and the formulas are converted.

**Comment by haraldschilly** [comment]
also noteworthy, opening the html file directly (e.g. [this one](https://cloud.sagemath.com/14eed217-2d3c-4975-a381-b69edcb40e0e/raw/scratch/latex.html) ) shows the formulas. So it must be something with the iframe embedding into smc.

**Comment by williamstein** [comment]
For completeness:
 - This should work but doesn't: https://cloud.sagemath.com/projects/14eed217-2d3c-4975-a381-b69edcb40e0e/files/scratch/latex.html
 - This does work and should be the same as the above, but isn't: https://cloud.sagemath.com/14eed217-2d3c-4975-a381-b69edcb40e0e/raw/scratch/latex.html
 - This also **does** work via a third party nbviewer iframe embed: https://cloud.sagemath.com/projects/14eed217-2d3c-4975-a381-b69edcb40e0e/files/scratch/latex.ipynb

**Comment by williamstein** [comment]
now fixed!
