### ISSUE TITLE
when creating a project when the commercial server setting is false (e.g., in docker) the one button is "Create project without upgrades" -- it should just say "Create project"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1348]
<img width="598" alt="screen shot 2016-12-08 at 11 20 32 am" src="https://cloud.githubusercontent.com/assets/1276278/21024191/5d87fae2-bd38-11e6-8ef1-7dac3f0c79d7.png">

**Comment by timothyclemansinsea** [comment]
My PR related to project upgrading at project creation addresses this

**Comment by timothyclemansinsea** [comment]
PR #1309 fixes this
