### ISSUE TITLE
maybe we should somehow display or warn on invisible unicode characters in the input of a sage worksheet...?

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1349]
This drove me crazy for a bit!

<img width="780" alt="screen shot 2016-12-08 at 1 31 06 pm" src="https://cloud.githubusercontent.com/assets/1276278/21028577/9b0e11aa-bd4a-11e6-9663-b6417df74232.png">

See https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-12-08-131537.sagews

This is exactly the sort of funny thing people are likely to do, since they copy/paste out of PDF or other funny files, or work with other editors (Word?) and paste into SMC...  Yes, this came from a support request.

**Comment by haraldschilly** [comment]
I've another idea. I bet there is only a handful of such invisible characters and we should search for a list of them. Then, whenever a user pastes something into codemirror, all those characters are replaced by a space.

What won't work are those ligature characters, e.g. that "ft" is a one-character letter. In theory, we could also detect them and replace them with two characters.

**Comment by williamstein** [comment]
That wikipedia table looks great.  

It's probably best to do two things:

 - one scanning for these characters on the backend  **WHEN THERE IS AN ERROR (and only then!)** and adding that message in the output.  That's all @DrXyzzy did, I think.   So your funny unicode examples would be fine if there is no error.

- also do something on the frontend...   THOUGH, that's actually less clear to me.  E.g., what if the user is pasting these into a string, where everything would work fine.

**Comment by williamstein** [comment]
I merged https://github.com/sagemathinc/smc/pull/1350 which does something useful.  However, probably something much better client side involving paste and non-visible characters should get done too.

**Comment by DrXyzzy** [comment]
Merged solution is not perfect but there haven't been specific suggestions for awhile. Let's close this.
