### ISSUE TITLE
"Failed to open link"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1359]
I have seen this new -- horribly mysterious and useless -- error message several times after merging some recent PR from @johnjeng:

<img width="432" alt="screen shot 2016-12-11 at 8 45 11 pm" src="https://cloud.githubusercontent.com/assets/1276278/21088321/e1b118ba-bfe2-11e6-9986-0df8f5553f84.png">

This message is useless, as it doesn't say what the file is.   

This might only be something that admins see when they try to visit a link for a project they are not a collab on.  Not sure.  Anyway, I *AM* able to open said file if I just click on it.

**Comment by haraldschilly** [comment]
I'm closing this ,since after merging #1367 the error message is definitely different
