### ISSUE TITLE
<style> doesn't work in .html files

### ISSUE THREAD

**Issue by AndreWin** [sagemathinc/smc#137]
Hi!

I created new .html file and typed in it:

```
<style>
    #mdp_help .helpHeader {
        font-size: 20px;
        color: red;
    }
</style>
<div id="mdp_help">
    <div class="helpHeader">
        My header
    </div>
    <div class="helpContent">
        Content of my help.
    </div>
</div>
```

This code wasn't work. I opened developer tools of firefox and looked at the source code of right part of html document. I saw the following:

```
<span data-line=1 data-ch=0 class='smc-pos'></span>    #mdp_help .helpHeader {
<span data-line=2 data-ch=0 class='smc-pos'></span>        font-size: 20px;
<span data-line=3 data-ch=0 class='smc-pos'></span>        color: red;
<span data-line=4 data-ch=0 class='smc-pos'></span>    }<span class='smc-html-cursor'></span>
<span data-line=5 data-ch=0 class='smc-pos'></span><span data-line=5 data-ch=0 class='smc-pos'></span>
```

As you can see \<style\> tag doesn't work because of \<span\> tags in it. Then I decided to modify my html code as following:

```
<style> #mdp_help .helpHeader {font-size: 20px;color: red;}</style>
<div id="mdp_help">
    <div class="helpHeader">
        My header
    </div>
    <div class="helpContent">
        Content of my help.
    </div>
</div>
```

As you can see I removed all newlines between \<style\> tags. Because of this action rendered \<style\> in right part of document stopped to contain \<span\> tags and began to work properly. It's strange that other tags at right part of document also contain many \<span\> tags in them.

It's interesting that there is no such problem in .md files, because \<style\> tags doesn't contain any \<span\> tag (I'm about right part of document). But sometimes \<styles\> doesn't work in .md files. Firefox developer tools show me that \<style\> tag is in \<p\> tag at this case. But I don't know when this bug appears.

**Comment by williamstein** [comment]
Closed in favor of https://github.com/sagemathinc/smc/issues/327
