### ISSUE TITLE
Make a "sage-latest" kernel for Jupyter notebooks

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#138]
Make a kernel for Jupyter notebooks that always points to the latest stable/installed version of Sage.

But name it "Sage", not "sage-latest".  And maybe this can be done in a "symlink" manner.

Keep versioned kernels (ie "Sage-6.9") for those not interested in moving, for whatever reason.

**Comment by williamstein** [comment]
done long ago...
