### ISSUE TITLE
Chat stays open if logged out and opening public version

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#1384]
Noted by @williamstein 
>If I have chat opened for a file when signed in, when I later try to open that same file publicly it consults local storage and decides to open chat too... which makes no sense in public mode (or maybe chat should be available?).

I think by default chat should be unavailable (there's not even a button..) but could be an option to the user in the future. It totally makes sense to have read only files and allowing chat. But I think we have to default to assuming no chat for privacy reasons.

**Comment by williamstein** [comment]
I strongly agree with what you think above.
