### ISSUE TITLE
Add "convert Jupyter notebook to Sage worksheet" to frontend

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1386]
In one of Hal's blog posts he gives the following code to convert a Jupyter notebook to SMC worksheet:

```
$ cp Assignment\ 2.ipynb assgn2.ipynb
$ smc-ipynb2sagews assgn2.ipynb
/usr/local/bin/smc-ipynb2sagews: Creating SageMathCloud worksheet 'assgn2.sagews'
$ open assgn2.sagews
```

I think this should be apart of the frontend to encourage people to use Sage Worksheets.

**Comment by williamstein** [comment]
> I think this should be apart of the frontend to encourage people to use Sage Worksheets.

Can you suggest a couple of ways in which this might work?   My ideas:

 - when you check the box to the left of an ipynb file, one of the options (in addition to delete, move, etc.) is convert to sagews.

 - Add a button to the SMC jupyter button bar (next to history, about, etc.), which is "open as sage worksheet..."

 - ...?

**Comment by williamstein** [comment]
time: 20 minutes

process: improve backend nbconvert module to support sagews; then use it.
