### ISSUE TITLE
Make a page "Why instructors should consider using SageMathCloud" and link to it from landing page

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1388]
Include data that could be used to show that we're cheaper and more reliable than competitors such as Coursera and self hosting.

**Comment by DrXyzzy** [comment]
I don't have the data requested, but info from the [JMM flyer](https://cloud.sagemath.com/projects/92848d19-8432-46c8-ba59-2b0d9521c9f2/files/marketing/jmm2017/flyers/jmm2017-flyer-why-v2.pdf) is reworked at https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/BLOG/why-smc-2.md. We could make that a wiki page, say __SMC for Students and Teachers__ and link from the landing page. Or is it redundant with info already there?  

@williamstein or @haraldschilly, what do you think?

**Comment by haraldschilly** [comment]
as long as the content is correct, I'm happy with an additional wiki page. at least, that we have that material written down somewhere and publicly accessible.

**Comment by DrXyzzy** [comment]
Wiki page https://github.com/sagemathinc/smc/wiki/SMC-for-Students-and-Teachers created.

**Comment by DrXyzzy** [comment]
On landing page, how about replacing
```
Quotes | Courses | Course management tutorial
```
with
```
Quotes | Courses | Course management tutorial | Advantages
```
and linking `Advantages` to the new wiki page?

**Comment by haraldschilly** [comment]
I've merged the link and hence implicitly the wiki page @DrXyzzy created. Hence, I'm closing the ticket, but someone speaking proper English should review the wiki page
