### ISSUE TITLE
internal links in chat/react-markdown (are suddenly) opening in a new browser tab

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1391]
This seems new -- not sure what is causing this.

**Comment by haraldschilly** [comment]
starting to go through links in various places, and sure enough, there are also other broken ones. e.g. a link to a local file in a sagews markdown part, adds one "/" too many.

**Comment by williamstein** [comment]
This is precisely the sort of thing that my new automated testing code will be good at testing...  I should really just merge it into master and start adding tests like this.  I still need to make some tests illustrating how to programmatically: create files, change their content, verify that rendering has certain properties, etc. 

BTW, writing these tests is a very useful way to document how to programmatically do **everything** related to SMC's frontend!  E.g., wonder how to programmatically open a tab, open a project, do something in it, etc. -- it's in (or will be in) a test with a description that is easy to find.

**Comment by haraldschilly** [comment]
solved this riddle. the interesting take-away is, that when the html of a component is mangled around (jquery, or whatever), previously registered event listeners to elements in there are removed during subsequent modifications. that's completely obvious,  but hidden in the abstractions. I'll make a PR for this which definitely needs some testing and thinking about it.

**Comment by williamstein** [comment]
>  I'll make a PR for this which definitely needs some testing and thinking about it.

I'll make a quick revert of @johnjeng's patch which caused this in the first place (related to \$).

**Comment by williamstein** [comment]
OK, I just did a quick trivial re-ordering so that link opening will work again: https://github.com/sagemathinc/smc/commit/0dcaca011d6fd7ab5f6abd59a007644288c6d9f2
