### ISSUE TITLE
How to start single (any) component with mimial dependencies

### ISSUE THREAD

**Issue by podshumok** [sagemathinc/smc#14]
Hello,

I'm trying to make a docker-compose setup for smc. With docker it is easy to setup nginx, cassandra, stunnel and tinc.

Suppose, I have them up and running in separate containers listed in `/etc/hosts` in current container.

Now I want to run smc-specific components, Hub for example.
I have managed cloning this repo, `--build_node_modules`, `--build_python_packages` and `make_coffee`.
What is the next step to configure and run Hub or Compute?

**Comment by williamstein** [comment]
addressed by the new smc/src/dev/laptop directory...

**Comment by williamstein** [comment]
Also this is a question, not an issue...
