### ISSUE TITLE
user install of R packages not working since R update to 3.3.2

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1404]
Since update of R to 3.3.2, installing packages as user appears to succeed, but the installed package is not seen by the Jupyter R 3.3.2 kernel, probably because sage is on an older version of R. The following completes but the installed package is not usable from sagews.
```
$ sage -R
...
> install.packages('ElemStatLearn')
```

Workaround is to install R package as user from sagews or jupyter notebook, avoiding dialogue. Example from sagews in %r mode. The USA IA CRAN mirror URL is used in the example. The install.packages step may take a minute or two, but yields a usable package.
```
%sh
mkdir ~/R/x86_64-pc-linux-gnu-library/3.3
---
%r
.libPaths(c(.libPaths(), "~/R/x86_64-pc-linux-gnu-library/3.3"))
install.packages("ElemStatLearn", repos="https://mirror.las.iastate.edu/CRAN/", lib="~/R/x86_64-pc-linux-gnu-library/3.3")
---
%r
library(ElemStatLearn)
```

**Comment by DrXyzzy** [comment]
A little nicer workaround is to put this near top of worksheet:
```
%auto
%r
local({
  r <- getOption("repos")
  r["CRAN"] <- "https://mirror.las.iastate.edu/CRAN/"
  options(repos = r)
  lpath <- "~/R/x86_64-pc-linux-gnu-library/3.3"
  .libPaths(c(.libPaths(), lpath))
})
```

**Comment by DrXyzzy** [comment]
Maybe it's a bad idea to "fix" `sage -R` package installs. How about I change the wiki page, and post to blog and sage-cloud group, with revised method for user R package install that does not use sage? In a way it's better to install R packages from the same worksheet or notebook that uses them.

**Comment by haraldschilly** [comment]
So, the thing is, there are two "R"s. I think we have to change the wiki pages, that's all. From my perspective, your very first command should actually be

```
$ R
...
> install.packages('ElemStatLearn')
```

which is what anyone familiar with R would do. `R-sage` is also R, but the one in sage -- same as the not so obvious `sage -R`.

**Comment by DrXyzzy** [comment]
Ok, will update wiki. Assigning issue to myself.

**Comment by DrXyzzy** [comment]
Done. Wiki page https://github.com/sagemathinc/smc/wiki/Programming updated.
