### ISSUE TITLE
the simplest test of typesetting math in markdown/chat now broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1412]
1. Open a chatroom
2. Type `$x^3$`
3. See `$x^3$` rather than math typesetting.

Some other things like `$$x^3$$` do work, of course.

I think this is some pretty serious fallout from a recent attempt to make \$ work.

**Comment by haraldschilly** [comment]
working again on this. found funny highlights in the code like this beauty:

```
@_x = markdown.markdown_to_html(v)
v = require('./misc_page').sanitize_html(v)
```

(second line is completely pointless)

**Comment by haraldschilly** [comment]
another one: `@_x?.has_mathjax?` is true, even when `has_mathjax` is false. 

anyways, I think I got it now.
