### ISSUE TITLE
course management: show email addresses of students for which the instructor has explicitly enterered their email address (otherwise not due to security model)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#142]
This is straightforward except that we don't store the email address if the student already had an account, so we need to change to do that.

**Comment by SylvainCorlay** [comment]
Thanks

**Comment by williamstein** [comment]
fixed in https://github.com/sagemathinc/smc/commit/6cd3b12f144c19aaf0f97336ec053cd452621bdf
