### ISSUE TITLE
Student names not getting updated in courses

### ISSUE THREAD

**Issue by SylvainCorlay** [sagemathinc/smc#143]
- I have a student named `Foo Bar`, with an email address `fb666@baz.edu`.
- This student updated their settings with their real name and the collaborator search proposes `Foo Bar` when I look for this email.
- However, this name is not (always) reflected in a course where I have added this student by email.

A consequence is that I have a number of students who appear by email only in my course. Some of them also sent me screenshots confirming that they had set up their account with their full name...

**Comment by williamstein** [comment]
fixed
