### ISSUE TITLE
Add %java support in sagews

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1437]
I need to learn Java for Android development. Unfortunately there doesn't seem to be %java support.

**Comment by williamstein** [comment]
+1 -- though maybe not in a worksheet.  Maybe split screen with run button.

Make a %java anyways though -- just check out our simple %go by typing `go??`

**Comment by williamstein** [comment]
Done!

**Comment by williamstein** [comment]
Oops -- not done.  But close.

**Comment by timothyclemansinsea** [comment]
@williamstein what's not done?
