### ISSUE TITLE
allow sorting of students in course

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#1447]
When you go to a list of students in a course, there isn't any obvious way to sort them.  But one should be able to sort by last name, first name, email address, and (crucially) by last usage time.  Perhaps also by points etc., but I haven't used that capability yet.

**Comment by kcrisman** [comment]
Related to #108

**Comment by aarontresham** [comment]
One issue I've run across is that students don't input their own names very well when they register for SMC. Some only use their first name, others include a middle name or initial, some have Jr., etc., some have compound names, some don't put a space between their first and last name, and so on.

I would like to see the student list numbered, with the option of the instructor manually changing the numbers and sorting by number. Then I could put my students in the same order as they appear on my roster. I could also keep track of different sections this way.

**Comment by johnjeng** [comment]
For the sake of breaking this up into parts here's what I'll be working on:

- [ ] Sort by first/last name that students have used to sign up for
- [ ] Sort by email.
- [ ] Sort by last used
- [ ] Sort by a custom ranking.
- [ ] A "Save this ordering" ability.

**Comment by williamstein** [comment]
> A "Save this ordering" ability.

No -- Just make the current sort preference always be saved in localStorage on that client browser.  That's a simple UI that is consistent with everything else.

And please make it so the sorting is all the same and just like in OS's -- just put in column headings and make clicking on them sort by that heading.

**Comment by johnjeng** [comment]
Oh, that was confusing since really the last two on that list are the same thing.

**Comment by johnjeng** [comment]
Closing in favor of #1623.

**Comment by williamstein** [comment]
This is now mostly implemented and now live.
