### ISSUE TITLE
add Rscript script to /usr/local/bin/

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#145]
There should be a script /usr/local/bin/R. We should make a file /usr/local/bin/Rscript based on that. then copy it to the other compute machines.

**Comment by williamstein** [comment]
Make sure to add something to build.py about this... since it should have been in sage but isn't.

**Comment by haraldschilly** [comment]
So, R is a binary and Rscript is also one. So, I'm doing this as kind of a trick:
```
#!/usr/bin/env bash
SAGEDIR=$(dirname $(readlink -f $(which sage)))
exec sage -sh -c "$SAGEDIR/local/bin/Rscript $@"
```
It should really be in sage properly …

**Comment by haraldschilly** [comment]
and http://trac.sagemath.org/ticket/16694 suggests that it might be slightly broken, too :sleepy:

**Comment by haraldschilly** [comment]
it's on the compute nodes, hence close
