### ISSUE TITLE
if commercial ui elements is "no" (see admin account settings), then the "Create with hosting..." etc. buttons should never be displayed

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1472]
If this is no in admin account settings:

<img width="352" alt="screen shot 2017-01-08 at 9 38 37 am" src="https://cloud.githubusercontent.com/assets/1276278/21750646/4597058e-d586-11e6-8055-c272e0ab1f54.png">

then these buttons should NOT be shown:

<img width="918" alt="screen shot 2017-01-08 at 9 39 10 am" src="https://cloud.githubusercontent.com/assets/1276278/21750649/5452f39e-d586-11e6-9773-1147b61ed43b.png">

**Comment by timothyclemansinsea** [comment]
I set mine to no and see 
![image](https://cloud.githubusercontent.com/assets/12617436/21754762/c881a014-d5bb-11e6-8959-c7dafc5b82a5.png)

**Comment by williamstein** [comment]
I was clearly confused.  Thanks for checking.
