### ISSUE TITLE
the open terminal command (in smc_pyutil) should use smc-new-file to create a file instead of open(filename,'w').close()

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1476]
1. In a terminal, type `open a.tex` with no file `a.tex`.
2. Get a blank tex file instead of one with a template file in it.  This is annoying and broken.

Instead -- try "+New" and a tex file and it works properly, because it uses `smc-new-file`.

**Comment by haraldschilly** [comment]
ohhh, that also explains why jupyter notebooks are broken.
