### ISSUE TITLE
get rid of the "File drop disabled To upload a file, drop it onto the files listing or the "Drop files to upload" area in the +New tab." warning message when using codemirror

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1478]
Codemirror supports drag and drop of text.  However, I often see the message

<img width="491" alt="screen shot 2017-01-09 at 2 08 09 am" src="https://cloud.githubusercontent.com/assets/1276278/21759205/77c11ec0-d610-11e6-8ca6-112287ea2f23.png">

when dragging around text.  Disable this on file editing page...

**Comment by DrXyzzy** [comment]
To replicate:
1. open a .md file
1. type a line of text
1. select part of the text just typed, i.e. highlight with cursor & don't click
1. drag selected text using primary mouse button or equivalent and drop somewhere new
1. selected text is cut and pasted to new location AND the "File drop disabled" warning appears.

**Comment by haraldschilly** [comment]
the weird thing is, I have a really hard time replicating this. I saw it once, but then never again. still, keep it opened and assigned to me.

**Comment by DrXyzzy** [comment]
Maybe it's easier to replicate with Firefox. That's what I used. It happened all the time.
