### ISSUE TITLE
octave input() not supported in jupyter and sagews

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1489]
Upstream issue open: Calysto/octave_kernel#59.

**Comment by DrXyzzy** [comment]
This PR says it's fixed in octave_kernel 0.20.0: https://github.com/Calysto/octave_kernel/pull/60

**Comment by timothyclemansinsea** [comment]
Is this M-Low, M-Medium, M-High?

**Comment by williamstein** [comment]
> Is this M-Low, M-Medium, M-High?

Definitely M-high (at least), since it's a blocker for a large number of courses (especially a famous MOOC) to be able to use Jupyter at all.

**Comment by haraldschilly** [comment]
this works in jupyter and we have 0.21 installed. it's not working in sagews ...

**Comment by DrXyzzy** [comment]
I can do the sagews part. It should be similar to code for python2&3 input(). There is still a problem with `pause`, I think, which may require another upstream issue.

**Comment by DrXyzzy** [comment]
Just an update, the sage_jupyter.py jupyter client is not receiving the expected message on the jupyter message protocol stdin channel when user octave code `input(prompt)` executes. I'm looking into why.

**Comment by DrXyzzy** [comment]
process: After upgrade to octave_kernel 0.26.2, `input()` and `pause` are working in jupyter notebooks.

process: Proposed sagews fix is in PR #1799. pytest cases were not added because rewrite of jupyter bridge is expected soon per #1754, but manual test cases are provided in the PR.

**Comment by DrXyzzy** [comment]
process: There's a defect in handling of `input()` and `pause` for python3 and octave kernels in jupyter bridge. If either call happens in the middle of a code block, the input call happens before any of the code is run. Fix would be to use equivalent of sage_parsing block parser on the code string, but this is moot pending rewrite in #1754.

**Comment by williamstein** [comment]
> If either call happens in the middle of a code block, the input call happens before any of the code is run.

Is this just a fundamental Jupyter design decision and users have to adapt their notebooks/code accordingly?  I don't know.  But it could be...

The block parsing code in sagews only makes sense for python code, not octave.

**Comment by DrXyzzy** [comment]
Jupyter notebooks for Python3 and Octave handle prompting & blocking for input in the middle of an input cell correctly, the latter with latest `octave_kernel` update. I just checked. So it's probably a logic error of mine in the soon-to-be-replaced sage_jupyter code.

Fix deployed & verified in jupyter notebook and sagews worksheet in production.
