### ISSUE TITLE
reference search

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1496]
implement a search for references, most likely via the mendeley api. 

1. register as sagemath.com
2. register SMC
3. get the client secrets (for a secret stored in the hubs)
4. implement a small internal service to query it (needs to refresh the access token on error, see bottom of "authorization" documentation)

docs:
* authorization: http://dev.mendeley.com/reference/topics/authorization_overview.html (do it for "client credentials" only!)
* api: http://dev.mendeley.com/methods/#search-by-query

**Comment by timothyclemansinsea** [comment]
Is this M-Low, M-Medium, or M-High?

**Comment by williamstein** [comment]
This is a repeatedly reported very clear blocker for a core feature that is extremely popular with a main target market.

**Comment by timothyclemansinsea** [comment]
" a core feature that is extremely popular with a main target market." What core feature? Is there an issue for it?

**Comment by williamstein** [comment]
> What core feature?

Reference search.   You're writing a paper and need to look up a citation and add it to the paper. 

>  Is there an issue for it?

Yes, it's #22 !  @haraldschilly shouldn't this #1496 be closed as a dup of #22?
