### ISSUE TITLE
Make a subscription advisor

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1501]
Support gets many emails asking about what subscriptions to buy for courses. I think we should make an automated way of telling instructors what subscriptions to get. This would also need to recommend free trial request when appropriate.

**Comment by williamstein** [comment]
No. 
(1) It's valuable to have discussions with professors who are possibly spending thousands -- this is how sales works. You're completely missing the value of this.
(2) If the subscriptions are really so hard to understand that we need an automated subscription advisor, then we change the subscriptions and how they are presented, not add yet another feature to maintain.
