### ISSUE TITLE
sagews %octave plots are too small and octave plot fails pytest

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1506]
It looks as if scaling octave plots by 0.66 with %octave mode is no longer needed with recent updates.

**Comment by DrXyzzy** [comment]
Jupyter message protocol with octave_kernel 0.20.0 is sending extra stdout messages with plot images.

**Comment by DrXyzzy** [comment]
Also in one test run I got `sage_server start time 8.08109712601 sec`. I increased the startup time threshold from 8 to 10 seconds.

**Comment by williamstein** [comment]
@DrXyzzy -- is this now fixed?

**Comment by DrXyzzy** [comment]
Yes.
