### ISSUE TITLE
show red video icon when side chat video is active

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1507]
the red active video chat icon is only shown, when the side chat is visible. I.e. by default, an active video chat isn't visible. The goal of this issue is to show the red video button when such a chat is active by rearranging a little bit what is drawn when and where.

**Comment by haraldschilly** [comment]
ok, maybe that's not a real issue at all ... seems like if someone *else* joins the video chat, the chat icon is read to indicate something.

**Comment by williamstein** [comment]
> ok, maybe that's not a real issue at all ...

Should we close this?

**Comment by johnjeng** [comment]
I'm closing this. I don't think one more icon is worth it in the extremely rare case (imo) that someone wants to know people are video chatting *and* they haven't been told by anyone that the video chat is happening *and* have yet to open chat to see any messages.
