### ISSUE TITLE
if you type shift+enter when editing a non-sagews codemirror file (and no special handling/action is defined), show an error

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1523]
I'm tired of getting support requests and losing users, because they don't make a sage worksheet and try to evaluate code, finding it doesn't work.  The attempts we have now to prevent empty extensions, etc., just don't work for everybody.

I'm fine with just calling the ugly red alert_message popup for now.  Later using @haraldschilly's new status bar might be relevant (not sure).

**Comment by slel** [comment]
In a markdown file, I would wish "shift enter" to act just the same
as "enter". This is what happens in almost any other environment
that does not define a special behavior for shift-enter.

Is there a setting to avoid this red alert_message popup?
