### ISSUE TITLE
the terminal cursor on a dark background is very hard to see

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1528]
1. In account settings, change your terminal preferences to something like "Solarized Dark" (a dark background).

2. Open a new terminal.  Then start rapidly typing, not pausing much.  The cursor will stay *always* black.   Instead, while "in action" the cursor should always be white if the background is black.

**Comment by williamstein** [comment]
@haraldschilly this seems like the sort of thing you like to fix...

**Comment by haraldschilly** [comment]
compensating for the border: 08f8992e71630e1e38202dc562d704216ce0b8b0

**Comment by williamstein** [comment]
I'm closing this since it is no longer hard to see the cursor.   I don't necessary like the cursor now, but this is definitely fix.
