### ISSUE TITLE
Send a little questionnaire to all users

### ISSUE THREAD

**Issue by stumpc5** [sagemathinc/smc#154]
(I still think about how to convince users to pay for the service.)

You could maybe prepare a little online questionnaire asking only very few questions such as

-> for what purpose do you use smc? with checkmark answers "sage", "jupyter notebook", "class", ...
-> what is your favourite feature of smc? again a few checkmarks and an open text box
-> which feature would you like to have? ...
-> what would we need to do in order to convince you to purchase one of the upgrades? Again some checkmarks + open box

I would send this questionnaire by email to all users that have an account for at least one month, together with the information about the different upgrade packages. And would then auto-send it to everyone after one month after signing up.

I think of having these and/or similar infos being interesting, but not the main effect. The main reasons I think about this are: 1. how many people are willing to answer a quick online questionnaire (this might be a superset of those willing to pay, though many people are generally annoyed by such questionnaire requests). 2. Everyone is reminded by email about upgrade options, and everyone answering the questionnaire is asked to actively think about an upgrade.

Finally, if you send out such an email, you can easily measure its influence on the upgrade-purchases, so it is simple to evaluate whether that makes sense, or how to improve it.

If you think that's a good idea, I could prepare a first version of the questionnaire using SurveyMonkey or any other online tool for that, but I am clearly lacking the knowledge about the various features, user experiences, and most used services.

**Comment by haraldschilly** [comment]
I've started to write one 1 1/2 years ago and recently worked on it again. I rather tend to make it a large one, but all questions optional. Despite that thank you for your ideas :-)

**Comment by williamstein** [comment]
@johnjeng did this. It was useful...  I don't think this goes in issues (more of general strategy).
