### ISSUE TITLE
In %coffeescript: ReferenceError: require is not defined

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1542]
require is defined in the terminal version of coffee but not in the sagews version

**Comment by williamstein** [comment]
This ticket doesn't make sense.

**Comment by timothyclemansinsea** [comment]
@williamstein I didn't realize until after that %coffeescript is client side. I wrote up a stupid %coffee to get me by.

**Comment by haraldschilly** [comment]
some time ago I experimented with the ijavascript jupyter kernel. it works ok-ish, but I haven't deployed it. there is also a coffeescript kernel, but I think I didn't got it to run. maybe you can give it a try and then we can alternatively have coffeescript as a jupyter kernel
