### ISSUE TITLE
Implement chat threads

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1549]
Inspired by http://www.forbes.com/sites/alexkonrad/2017/01/18/slack-adds-threads-to-popular-messaging-software-in-pursuit-of-bigger-customers/#4a4b7ca95149 This would be M-high if M were "companies using open source software"

**Comment by williamstein** [comment]
Marking vague because there are probably a dozen+ ways to do this.

I might rather have hashtags on messages, and have reply copy the tags...

**Comment by timothyclemansinsea** [comment]
I forgot about the hasttags idea.
