### ISSUE TITLE
enable http2 on nginx

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#155]
The GCE infrastructure supports it and nginx too. https://www.nginx.com/blog/nginx-1-9-5/

**Comment by williamstein** [comment]
How do we do it?  I've wanted to do this forever....

**Comment by haraldschilly** [comment]
I'll play around on my dev1 and see, if I can get my http2 browser indicator extension to show a green lightning bolt :zap:

**Comment by williamstein** [comment]
How or is this relevant given we use cloudflare?

**Comment by haraldschilly** [comment]
I'm closing it, I bet this will work out of the box at some point anyways.
