### ISSUE TITLE
Singular Jupyter Kernel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1553]
> The kernel needs a current Singular (>=4.1.0), as there is in Sage. To 
run it, the python packages
> 
> PySingular (https://pypi.python.org/pypi/PySingular) and
> 
> jupyter-kernel-singular (https://pypi.python.org/pypi/jupyter-kernel-singular/)
> 
> are needed. Both are available on PyPI. The first package is a C++ modulefor both Python2 and 
> Python3, interfacing the Singular parser via LibSingular. The second 
> package is the Jupyter kernel.

**Comment by jdemeyer** [comment]
This is done, right?

**Comment by haraldschilly** [comment]
oh yes, don't remember why it is still open.
