### ISSUE TITLE
Add 'Singular' alias in addition to 'singular'

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#1554]
Please add 'Singular' (in addition to 'singular') as an alias to 'sage --singular'.

- Most Singular users expect to launch Singular with the command `Singular`, not `singular`.
  So I'd say it's important in order to make SageMathCloud friendly to Singular users.

- Additionally, this would make it easier to get the Jupyter kernel for Singular working.

**Comment by haraldschilly** [comment]
maybe just edit the kernel.json file? I usually have to do this to make them work in smc.

**Comment by haraldschilly** [comment]
ok, done
