### ISSUE TITLE
TikZ doesn't obey -interact=nonstopmode

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#156]
This minimal TikZ document:
```latex
\documentclass[border=10pt]{standalone}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \node {Formulas} child { node {single-line} }
  \node {Formulas} child { node {single-line} };
\end{tikzpicture}
\end{document}
```
causes this prompt/error message
```
! Package tikz Error: Giving up on this path. Did you forget a semicolon?.
 
See the tikz package documentation for explanation.
Type  H <return>  for immediate help.
 ...
 
l.6   \node
            {Formulas} child { node {single-line} };
^C! Interruption.
```
despite that default build command:
```
pdflatex -synctex=1 -interact=nonstopmode 'tkiz-error.tex'
```
and hence the UI LaTeX editor stalls with "`undefined`".

**Comment by williamstein** [comment]
yep, replicated here.  We can switch to piping from dev/null instead of using `interact=nonstopmode`.

**Comment by williamstein** [comment]
I'll try this now...

**Comment by williamstein** [comment]
Fixed in https://github.com/sagemathinc/smc/commit/37fd71ca15104aa49fad59f165d6fcd153ee0543

**Comment by williamstein** [comment]
I'm re-opening this.  People clearly find the behavior of "stop on the first bug" very confusing, as we've seen with multiple support requests.  I'll come up with a better fix.

**Comment by williamstein** [comment]
Looking further it simply seems totally impossible to do better than "stop on first bug".   Sorry world, but latex just can't do better in general.  Something about the halting problem.

**Comment by williamstein** [comment]
After more user feedback, I'm reverting my attempt to fix this and re-opening this.  But lowering the priority.
