### ISSUE TITLE
latex errors/issues line numbers don't work with spaces in filename

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1567]
1. create a tex filename with spaces, like "homework 02.tex"
2. errors/issues in the problem tab point to line numbers, but they don't work.

This is either a simple bug in SMC or an upstream issue of https://github.com/sharelatex/latex-log-parser-sharelatex

**Comment by haraldschilly** [comment]
so, this comment here suggests strongly that this is an upstream issue: https://github.com/sharelatex/latex-log-parser-sharelatex/blob/master/src/coffee/latex-log-parser.coffee#L237

> Our heuristic for detecting file names are rather crude
> A file may not contain a space, or ) in it
> To be a file path it must have at least one /

**Comment by williamstein** [comment]
An upstream issue ... in what?  That's just a link to some sharelatex source code.

**Comment by haraldschilly** [comment]
In the file `latex-log-parser.coffee` and the method `@consumeFilePath`. That's the code used to parse the latex log. In SMC there is a modified version of that.

**Comment by haraldschilly** [comment]
the ticket is merged, hence I'm closing this.
