### ISSUE TITLE
if you remove yourself from an open project, the tab at the very top breaks

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1568]
This is what you see until you **refresh your browser tab** (which sucks to ever have to do):

<img width="923" alt="screen shot 2017-01-22 at 8 42 05 am" src="https://cloud.githubusercontent.com/assets/1276278/22184002/d8959f50-e07e-11e6-9cbc-aae8e29dd695.png">

**Comment by johnjeng** [comment]
Likely my fault. Will fix this week.

**Comment by johnjeng** [comment]
Can no longer reproduce this bug.

**Comment by williamstein** [comment]
Yep fixed.  I do this all the time when doing support, and it  works fine.
