### ISSUE TITLE
Unable to compile latex with \usepackage{sagetex}

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/smc#1576]
Hi,
I get an error:

> LaTeX Error: File `sagetex.sty' not found.
> 
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty)
> 
> [...]

how to add an additional latex libraries to smc?

**Comment by haraldschilly** [comment]
Can you send us a link to your file to help@sagemath.com please? That we we can have a look what's going on.

**Comment by arm2arm** [comment]
Ok Sorry, I forgot to mention that I run docker container of smc locally on my vm-ubuntu 16.04.
The latex file is simple example from your git repo: presentation.tex

**Comment by haraldschilly** [comment]
ohh, well. then this is yet another docker issue. 

The solution is to set a symlink into the installation of sage. I don't know the paths in docker, but it's just one `ln -s` away. I.e. something like

    cd /usr/share/texmf/tex/latex
    ln -s $SAGE_ROOT/local/share/texmf/tex/latex/sagetex sagetex

**Comment by arm2arm** [comment]
Ok, this can be done, but $SAGE_ROOT is not defined in the docker image, would be nice to have it system wide.

**Comment by arm2arm** [comment]
hmm, it doesnot help:(
should I rehash or something else?
`drwxr-xr-x` 7 root root 4096 Jan 23 13:50 ./
drwxr-xr-x 4 root root 4096 Jan 23 10:36 ../
drwxr-xr-x 2 root root 4096 Jan 19 15:05 lm/
drwxr-xr-x 2 root root 4096 Jan 23 10:36 preview/
drwxr-xr-x 2 root root 4096 Jan 19 15:05 prosper/
lrwxrwxrwx 1 root root   53 Jan 23 13:50 sagetex -> /usr/lib/sagemath/local/share/texmf/tex/latex/sagetex/
drwxr-xr-x 2 root root 4096 Jan 19 15:05 tex-gyre/
drwxr-xr-x 2 root root 4096 Jan 19 15:06 tipa/
root@1299d0f3707d:/usr/share/texmf/tex/latex# pwd 
/usr/share/texmf/tex/latex
`

**Comment by haraldschilly** [comment]
yes, SAGE_ROOT was just meant to be a "mental" variable. I don't know what's exactly in the docker image and in the sagetex directory in sagemath. Also, latex itself has to look into those paths, but they're the usual ones, so that shouldn't be an issue. For reference, below is the setup in the SMC online service:

```
~$ ls -l /usr/share/texmf/tex/latex/sagetex
lrwxrwxrwx 1 root root 55 Jan 23 13:38 /usr/share/texmf/tex/latex/sagetex -> /projects/sage/sage/local/share/texmf/tex/latex/sagetex

~$ ls -l /projects/sage/sage/local/share/texmf/tex/latex/sagetex
total 244
-rw-r--r-- 1 salvus salvus   399 Aug 22  2015 CONTRIBUTORS
-rw-r--r-- 1 salvus salvus 23558 Aug 25  2015 example.tex
-rw-r--r-- 1 salvus salvus  2470 Aug 26  2015 extractsagecode.py
-rw-r--r-- 1 salvus salvus  2565 Aug 26  2015 makestatic.py
-rw-r--r-- 1 salvus salvus 65241 Aug 26  2015 py-and-sty.dtx
-rw-r--r-- 1 salvus salvus 17136 Aug 22  2015 remote-sagetex.dtx
-rw-r--r-- 1 salvus salvus 12822 Aug 26  2015 remote-sagetex.py
-rw-r--r-- 1 salvus salvus  2988 Aug 26  2015 run-sagetex-if-necessary.py
-rw-r--r-- 1 salvus salvus 55292 Aug 26  2015 sagetex.dtx
-rw-r--r-- 1 salvus salvus  5141 Aug 24  2015 sagetex.ins
-rw-r--r-- 1 salvus salvus 10699 Aug 26  2015 sagetex.sty
-rw-r--r-- 1 salvus salvus  5375 Aug 26  2015 sagetexparse.py
-rw-r--r-- 1 salvus salvus 17303 Aug 24  2015 scripts.dtx
```

**Comment by williamstein** [comment]
> this is yet another docker issue.

It's an existing Docker issue: https://github.com/sagemathinc/smc/issues/1346
