### ISSUE TITLE
support a catalogue of jupyter themes

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1578]
See https://news.ycombinator.com/item?id=13460680

This would be similar to the editor and terminal themes.

**Comment by haraldschilly** [comment]
whoever looks into this should also check if we can support [jupyter dashboards](http://jupyter-dashboards-layout.readthedocs.io/en/latest/) and similar extensions. they might interfere with those themes, which might make this a bit brittle.

**Comment by williamstein** [comment]
Our jupyter uses our integrated codemirror theme select in account settings now.  any further theming would be  SMC-wide hence not specific to jupyter.
