### ISSUE TITLE
make it so this long list of instructions simpler

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#158]
Search for "https://cloud.sagemath.com" in 

https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/00-Preface.ipynb

There's a nice argument for how useful SMC is.   Then there are 5 steps about how to take that whole book and download it into SMC.   

Think about some design that would make this simpler.   I'm not sure what yet.

**Comment by rbeezer** [comment]
Here are some high-level ideas about books in SMC.

Readers: get a list of available books as part of the user-interface (like current help section, say).  It is organized by discipline, topic, level, license, last update, etc, etc.  Maybe all this is backed by a small database, which is searchable.

When the author updates the book, the reader is informed and can *choose* to upgrade.  If the reader has annotated their copy of the book, the old version is snapshotted for later review, and/or the reader's changes get applied to the author's new edition (perhaps in a way that makes it obvious what are the reader's changes).

If a reader notices a mistake, they can hit a button and get a copy of the offending page that they can edit and send to the author (as a pull request).  This might not be a change to the author's source, but it would be easy for the reader, and the author could evaluate and track down the change easily (though perhaps not automatically).  David Farmer and I have talked about this a lot.


Authors: make their book available as a git repository on GitHub.  There is some agreed-on scheme for the reader-level content to reside in certain directories, eg smc/jupyter, smc/sagews, etc.  Much of the above talk about changes could be determined by standard git functions, or maybe some of this could be done with SMC filesystem tools (snapshots, diffs, etc).


SMC: maintains a single master copy of the book, "installing" copies into a user's account, maybe with pre-/post-install hooks, etc.  Thus comparisons can be made to the author's copy (cloned from GitHub) and individual user's copies (lagging, dirty working directory, etc).  The user would not have to even ever know the author's source was there (maybe it should be hidden?), just the presentation as SMC worksheets, Jupyter notebooks, etc., and interaction with the repository could be automatic.

Some level of vetting books would be a good idea, I think, or clearly mark books as "in progress" or "preliminary.  This would be a service that would enhance SMC's value to instructors, students and everybody else.  Something like AIM's textbook board, though maybe not as rigorous.

**Comment by williamstein** [comment]
This is too speculative and high level I think for an issue for now....
