### ISSUE TITLE
create an additional help message in the context of course payment

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1583]
If a student has paid and is still seeing a “you must pay” box, we should also provide them with instructions as I just gave in help – namely, if you are taking only one class, go to the settings page for your other project, remove the upgrades from there, then add them here. That resolved the problem for everybody.

Implementation-wise, this just involves looking at the code path that results in the "you must pay" box for courses.  Then, when showing it, also check to see if the users has any upgrades.  If so (and only then), show this additional box.   Include a link also to https://cloud.sagemath.com/settings/upgrades, which shows their allocations.

**Comment by williamstein** [comment]
I just explained this sort of thing to 3 separate students and all responded with "I was able to do switch the upgrades. Thank you! "

**Comment by johnjeng** [comment]
I think this is a perfect ticket for @timothyclemansinsea.

**Comment by williamstein** [comment]
> "Go to the settings in your project and click the "Adjust  your quotas..." button, then click the checkboxes next to network and member hosting.  If it says you don't have enough quota, visit https://cloud.sagemath.com/settings/upgrades and see where the upgrades are, remove them from that other project, then try again."

**Comment by timothyclemansinsea** [comment]
@williamstein this no longer is needed right now that we have added upgrade in place to course fee required

**Comment by williamstein** [comment]
This is definitely needed.   I just explained it to a student yet again.  Also, they could use this in case they paid in another way.

**Comment by williamstein** [comment]
And they said: "Thanks, that worked!"

**Comment by williamstein** [comment]
implemented
