### ISSUE TITLE
singular jupyter kernel - add sagews pytest and %singular mode

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1586]
Ref: #1553

**Comment by DrXyzzy** [comment]
Since there is already `singular(x, type='def')` among sage interfaces, I propose naming the jupyter bridge `singular_mode`.

**Comment by williamstein** [comment]
What about `singular_jupyter` or `singular_kernel`.  

Keeping our existing singular interface makes a lot of sense, because it is actually really really good (it's a C++ interface).

**Comment by DrXyzzy** [comment]
`singular_kernel` it is

**Comment by williamstein** [comment]
I made a remark at the bottom here:  
https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/singular.sagews

Remind me to update this when `singular_kernel` exists.

**Comment by williamstein** [comment]
@DrXyzzy  I added you to the project, so you can update that worksheet.

**Comment by DrXyzzy** [comment]
I updated the first cell of https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/singular.sagews to be
```
%auto
%default_mode singular_kernel
```
and re-ran all the cells to verify output.

_Note: to pick up the new smc_sagews package, I moved `~/.local` to `~/.local0` in that project and restarted the sage_server process._
