### ISSUE TITLE
support 3d graphics in sage mode in Jupyter notebooks

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#159]
Replicate:
- Open ipython notebook 
- Choose current SageMath kernel
- In a codecell enter the code 

```
x, y = var('x y')
S = sphere((0,0,0),size=0.3, color='red', aspect_ratio=[1,1,1])
show(S, figsize=8)
```
- No plot appears...

Correct url for jsmol.min.js is broken.

**Comment by williamstein** [comment]
This url at least has that file: http://chemapps.stolaf.edu/jmol/jsmol/

**Comment by williamstein** [comment]
Still broken:

  https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-125146-issue159.html

**Comment by williamstein** [comment]
Bug since it silently fails.

**Comment by williamstein** [comment]
This is exactly this problem: https://github.com/jupyterhub/jupyterhub/issues/401

It's I guess a bug in Sage.  It's still a problem in sage-7.4

**Comment by williamstein** [comment]
If we make it so https://cloud.sagemath.com/nbextensions/jsmol/JSmol.min.js serves the file JSmol.min.js, then this may work fine for us.   This JSmol.min.js is I think not updated much (maybe not once in 3 years).  It's 223K and is in `/projects/sage/sage-7.4/ocal/share/jsmol/JSmol.min.js`.

**Comment by williamstein** [comment]
No, that's just too ugly -- we really need to do this right by fixing sage.   Also, our static content really should get served via /static.

**Comment by williamstein** [comment]
OK, giving up on this for now.

**Comment by williamstein** [comment]
I reported it upstream to the sage-devel list.

**Comment by williamstein** [comment]
Potentially very useful discussion: https://groups.google.com/forum/#!topic/sage-devel/VR6YEwCTsE4

**Comment by williamstein** [comment]
Maybe fixing this would just involve serving the relevant jmol 3d files from the right url via nginx.   If you try to draw a 3d plot in jupyter sagemath mode, and watch the terminal, you'll see what absolute path from sage it fails to pull in.  It's trying to download several megabytes of javascript/html/etc. -- some sort of automatic generated js (from java).   It fails because Volker doesn't understand jupyter base url stuff.  But we could actually fix it to work by just making that path be available (bundling it up as part of making the production site), and that would also be much faster (getting the html/js from our cdn rather than via an http tunnel).

**Comment by amirsagiv** [comment]
Hello, I just wanted to say that we've tested it on development version 7.5.beta3 (0c6824fff559e93b5517e53cd90ac1f1b04accf9) (git://github.com/sagemath/sage.git), and it seems to work. The test was performed on Debian testing xenial. All the examples were displayed correctly with Jupyter. 
Thanks!

**Comment by williamstein** [comment]
@amirsagiv  -- thanks.  The problem is that Sage's 3d graphics are supported via some very hacky techniques, and do not properly support Jupyter's base_url functionality.  This means they can't work in SMC, without some significant changes.

(For anybody reading this, 3d graphics do work well in Sage worksheets in SMC.)

**Comment by haraldschilly** [comment]
I've deployed a workaround, closing it.

**Comment by amirsagiv** [comment]
thanks. It works now!
