### ISSUE TITLE
if you don't set your last name, then you can't delete your account

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1597]
1. Make an account with no last name
2. Try to delete it.

**Comment by DrXyzzy** [comment]
- Account can be deleted if you type a space after the first name in the confirmation dialogue.
- Similar problem if there is no first name, but account can be deleted if space is entered before the last name in the dialogue.

Looks like this line around 498 in https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/r_account.cjsx#L498
```
user_name     = {@props.first_name + ' ' + @props.last_name}
```

**Comment by DrXyzzy** [comment]
PR deployed. Verified in production.
