### ISSUE TITLE
keyboard shortcut to switch between tabs

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#16]
I am so used to using Cmd-Shift-[ or -] to switch between tabs in my (Mac) browsers that it's just second nature.  It's super annoying not to be able to do this in SMC - say, between a .tex file and a .bib file.  Since Cmd-s saves in SMC, not the usual behavior of saving the actual webpage, I assume it's possible to implement something like this in SMC, even if the specific shortcut is something other than that.

**Comment by williamstein** [comment]
Look at the section labeled keyboard shortcuts under account settings.

On Thursday, June 11, 2015, kcrisman <notifications@github.com> wrote:

> I am so used to using Cmd-Shift-[ or -] to switch between tabs in my (Mac)
> browsers that it's just second nature. It's super annoying not to be able
> to do this in SMC - say, between a .tex file and a .bib file. Since Cmd-s
> saves in SMC, not the usual behavior of saving the actual webpage, I assume
> it's possible to implement something like this in SMC, even if the specific
> shortcut is something other than that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/16>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by kcrisman** [comment]
Got it.
