### ISSUE TITLE
reconnect to switch hubs is now broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1617]
This PR https://github.com/sagemathinc/smc/pull/1614  I think completely broke clicking reconnect to switch hubs.

@haraldschilly

**Comment by haraldschilly** [comment]
well, that PR didn't change anything with the actual logic. besides that, I just clicked on reconnect and got another hub ... even tried it twice. there are also no exceptions.

hence this is either somehow browser specific (and was always broken) or super weird.

**Comment by williamstein** [comment]
I was just wrong -- switching wasn't working when I was testing, since nothing was working at all then.

**Comment by Eulerianial** [comment]
What was the fix for it? I also see this while launching the docker image for cocalc.

**Comment by haraldschilly** [comment]
Does it persist? The problem here was related to erroneous handling of some hub internals. Besides that, AFIAK the docker image only has one hub...
