### ISSUE TITLE
implement wysiwyg html editing for sagews

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1618]
This might use prosemirror... ?

See https://groups.google.com/forum/#!topic/sage-support/kR73jg53Zg8

This is very hard in SMC due to realtime sync.

**Comment by kcrisman** [comment]
This is probably already https://github.com/sagemathinc/smc/issues/434

**Comment by williamstein** [comment]
You're right!  Arg.  I should remember the tickets I already made... and even implemented and deleted.
