### ISSUE TITLE
billing: make very hard for a user to get charged twice (fix PR 1625 properly)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1627]
https://github.com/sagemathinc/smc/pull/1625

i.e. let users confirm that they really want to create a second subscription, etc.

**Comment by williamstein** [comment]
Yes.  or change message to "Please wait a few seconds before creating another subscription."

**Comment by williamstein** [comment]
Even #1625 as is, doesn't do a very good job -- we had at least 2 double charges (out of maybe 10) successful charges after it.  The double charges are ALWAYS students paying the $9/fee -- we've never had them in any other case, so doing something to specifically mark the specific project being paid for may help a lot (it has an id)...

**Comment by williamstein** [comment]
Bug, because clearly people don't expect this behavior.  We still don't know how it happens though (or what they are doing).

**Comment by DrXyzzy** [comment]
See also #1534.

**Comment by williamstein** [comment]
I did push out a commit yesterday related to this  -- we'll see if it works...

**Comment by williamstein** [comment]
Absolutely 100% of issues involving "double charging" involve student confusion in paying.  I'm opening a new ticket for this.
