### ISSUE TITLE
stop seeing warning about firefox

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1650]
Every time I refresh SMC in Firefox I see the same warning about performance issues  "There are major performance issues with Firefox ..." and I have to click to dismiss it. How about a button in the warning that says `Don't show this warning again`?

**Comment by williamstein** [comment]
1. How bad are the performance issues now? 

2. Have you tested the "nightly betas" of firefox -- the claim to have totally fixed the problems there.

**Comment by DrXyzzy** [comment]
I haven't been testing nightly FF betas. The only issue I see consistently these days that I think is FF specific is left edit pane doesn't scroll down all the way with mouse with .md and .tex files. Workaround is to use arrow keys to move cursor down. As I recall, there were occasional 100% CPU spins attributed to FF, but I haven't seen one of those for a few weeks.

**Comment by williamstein** [comment]
There is a ticket with a way to replicate the 100% cpu spins.  If it is gone... we can just remove this message.  It sounds like it is gone.

**Comment by DrXyzzy** [comment]
CPU spins seem to be mentioned at #1314. I just tested the snippet listed there on Linux and OS X Firefox and saw a CPU load spike with each, but neither had a stuck process, details at #1314. Based on that and my past few weeks' experience without CPU spin, I recommend removing the message.

**Comment by DrXyzzy** [comment]
Hardly any CPU spike running latest Firefox Nightly build on OS X and Ubuntu, see #1314.

**Comment by DrXyzzy** [comment]
Let's keep this open until the fix in Nightly makes it into a Firefox release, then remove the warning.

**Comment by timothyclemansinsea** [comment]
Wouldn't we want the warning to appear for older versions of Firefox?

**Comment by DrXyzzy** [comment]
Or change the warning on older versions of firefox to recommend upgrading.

**Comment by DrXyzzy** [comment]
Blocked, waiting for firefox release.

**Comment by DrXyzzy** [comment]
Oh, and there is one more issue with FF. SMC won't let you open a jupyter notebook from firefox because of truncation, issue #1537

**Comment by williamstein** [comment]
I'm removing the message and closing.

I don't want to mess with complicated (possibly brittle) code for detecting old versions -- there's a ton that can go wrong with each older version, with no end in site.  Users not using the latest version are not supported.
