### ISSUE TITLE
sagemathcloud.com should redirect to cloud.sagemath.com

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1667]
@haraldschilly -- in the last week I saw a *LOT* of people typing sagemathcloud.com into their browsers...  and it works but not via redirect.  The proliferation of url's/links could be bad.

No hurry.

**Comment by haraldschilly** [comment]
closing. watch what happens, when you open https://www.sagemathcloud.com/projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/files

**Comment by williamstein** [comment]
PERFECT!
