### ISSUE TITLE
Don't show the "Warning: Create a file with no extension?" message for filenames that don't have extensions

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1668]
This screenshot should make the point of this issue clear:

<img width="1247" alt="screen shot 2017-02-11 at 6 52 39 pm" src="https://cloud.githubusercontent.com/assets/1276278/22859287/5d4622da-f08b-11e6-8184-9d5334697d2d.png">

**Comment by timothyclemansinsea** [comment]
I'm a little unclear on what's wanted here. Is the idea to have a list of
filenames to not show the warning for? I'm not finding a list. I tried
Googling
https://www.google.com/search?q=common+file+names+without+extensions&oq=common+file+names+without+extensions&aqs=chrome..69i57j0.7456j0j7&sourceid=chrome&ie=UTF-8

**Comment by williamstein** [comment]
fixed
