### ISSUE TITLE
add a "Find next" button to full-text search in the text editor.

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#17]
cmd-f in Mac gives a find window, but although it highlights all the found items, there doesn't seem to be an easy way (say, Enter) to cycle through them; it's easier to use the browser's search, which is of course suboptimal in the long run for SMC.   I thought the "Forward" and "Inverse" buttons were about this but I couldn't suss out what they did. Interestingly, these are not available in the plain text editor that comes up for bibtex.

**Comment by kcrisman** [comment]
I'd close this one myself as it's apparently a shortcut cmd-g or something, but maybe there could be a tooltip or something when things are highlighted?

**Comment by williamstein** [comment]
"Find next" is documented under keyboard shortcuts in account settings.   However, it would be nice to add a button that does the same thing.  This whole search functionality is part of Codemirror though, not SMC, so you might want to make a request upstream to them to implement it...

**Comment by williamstein** [comment]
Forward and inverse search are by definition "{forward-inverse-search} is a technology for having synchronization between source and preview, e.g., being able to Ctrl-click (or similar) in the source and jump to the corresponding place in the preview of the document, and vice versa."  From here: http://tex.stackexchange.com/questions/tagged/forward-inverse-search

**Comment by kcrisman** [comment]
>
> "Find next" is documented under keyboard shortcuts in account settings.
> However, it would be nice to add a button that does the same thing. This
> whole search functionality is part of Codemirror though, not SMC, so you
> might want to make a request upstream to them to implement it...
>
>

Oh!  I didn't know that.  I'll let this sit open if someone wants to do
that, but I don't know that I have the street cred to report to a non-math
project.

**Comment by williamstein** [comment]
Good news -- somebody else is about to redo the Codemirror search functionality -- see here: https://github.com/codemirror/CodeMirror/issues/3337

**Comment by williamstein** [comment]
close in favor of https://github.com/sagemathinc/smc/issues/311
