### ISSUE TITLE
%python3 getpass hangs in sagews

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1703]
To reproduce:
```
%python3
import getpass
p = getpass.getpass("pw: ")
```
Running that cell hangs the worksheet.

**Comment by williamstein** [comment]
I definitely never implemented password stdin for sagews, so there's really no way to do this.   I fully implemented this for Jupyter2.  This issue should just disappear when jupyter2+ sagews are unified.

**Comment by DrXyzzy** [comment]
Closing. __wontfix__

**Comment by williamstein** [comment]
For the record, we *do* want this to work.  It's just that the way to do it is going to be sort of automatic via jupyter + sagews merge...
