### ISSUE TITLE
Opening a LaTeX document the first time always incorrectly displays "Invalid LaTeX document" due to a race condition

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1751]
1. Create a new Latex document (or open one you have not opened before).
2. In the preview page see the following wrong message on the right:
<img width="1334" alt="screen shot 2017-03-06 at 3 10 06 pm" src="https://cloud.githubusercontent.com/assets/1276278/23634459/20c08e80-027f-11e7-995a-6ee189030358.png">

This is probably due to a race condition related to waiting for the file to be opened.

**Comment by haraldschilly** [comment]
For me, that's a "can't reproduce".

Probably relevant, before the check for the content is run, there is this test: `if not @latex_editor.syncdoc._fully_loaded` → `callback & return` to skip doing anything further. Maybe back then when you saw this, that `_fully_loaded` didn't work 100%?

**Comment by williamstein** [comment]
I can no longer reproduce.
