### ISSUE TITLE
img link to image in another project is broken.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1778]
given you're in project X in a chat or md file and want to embed an image from project Y, where you're also a collab, this fails:

`<img src="https://cloud.sagemath.com/projects/<Y project id>/files/path/image.png">`

i.e. that's the url in smc, and hence no proper detection and translation to the raw url happens.

I don't remember if that ever worked, but I know that I've touched some code related to this a while ago. Hence I've assigned it to me.

**Comment by williamstein** [comment]
time: 10 minutes
