### ISSUE TITLE
pdf viewer: keep scroll and zoom

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1790]
this applies to the pdf viewer and the embedded one in the latex editor. scroll position and zoom aren't preserved between reloads or refreshes. the first question is if this can be done at all.

**Comment by williamstein** [comment]
I'm giving this bug tag, since users reasonably expect scroll position to be preserved, since it is for all other editors.

It's unclear that this is possible though...

**Comment by williamstein** [comment]
Relevant page -- at least one can **SET** the page number (in chrome): http://stackoverflow.com/questions/28137033/embed-a-page-from-a-pdf-in-html

**Comment by williamstein** [comment]
This question asks the other direction and has no useful answers (except "switch to pdf.js", which sucked when I last tried...), which is very worrisome.   http://stackoverflow.com/questions/30149407/get-current-page-number-of-embedded-pdf

**Comment by williamstein** [comment]
Another stackoverflow saying "Not possible": http://stackoverflow.com/questions/36076296/how-to-get-current-page-number-of-pdf-document-which-embed-to-meteor-app-by-emb

Maybe we should close this issue.

**Comment by DrXyzzy** [comment]
I can try some tests with pdf.js & see what I can find out.

**Comment by williamstein** [comment]
> I can try some tests with pdf.js & see what I can find out.

Cool -- I think it is the default for Firefox.

**Comment by DrXyzzy** [comment]
It appears that PDF.js is the default for Firefox: https://support.mozilla.org/t5/Learn-the-Basics-get-started/View-PDF-files-in-Firefox/ta-p/2671

I uploaded [this pdf](http://web.uconn.edu/~ch351vc/pdfs/spin1.pdf) to a project and compared two views in Firefox, the SMC file tab for the pdf, and browsing directly to the external link for the pdf.
- both views show the same controls, confirming PDF.js use in FF
- zoom and scroll are preserved in the external link view when I switch browser tabs and when I refresh the page
- zoom and scroll are also preserved in the SMC file tab when I switch browser tabs and when I refresh the page
- zoom is preserved, but scroll is __not__ preserved, in the SMC file tab when I switch between SMC tabs

**Comment by DrXyzzy** [comment]
A little more about setting scroll and zoom. The following seem to apply regarding parameters for opening a pdf:
- https://github.com/mozilla/pdf.js/wiki/Viewer-options
- http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf

The following work in Chrome and FF:
- http://web.uconn.edu/~ch351vc/pdfs/spin1.pdf#page=2
- http://web.uconn.edu/~ch351vc/pdfs/spin1.pdf#page=2&zoom=200,250,100

With Firefox, zoom and scroll can be removed from location in the top URL bar, and then when the link (without parameters) is refreshed, the previous zoom and scroll settings are preserved. That is not the case with Chrome. Also with FF, current page number and zoom setting are displayed in the toolbar, so these could possibly be read from the DOM.

Nevertheless, I think the effort to set, store, retrieve, and refresh zoom and scale is greater than value provided and recommend closing this issue with __wontfix__.
