### ISSUE TITLE
use latexmk by default

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#18]
Suggested line `latexmk -pdf -bibtex -synctex=1 -interaction=nonstopmode '<FILENAME>.tex'`.

Says John P.: You can tell latexmk about sagetex: https://bitbucket.org/ddrake/sagetex/wiki/UsingSageTeX. Then it works well, in my experience. Should that code be put into a global latexmk RC file?

**Comment by haraldschilly** [comment]
about the command, one thought is to throw `-xelatex` in there, too.

**Comment by haraldschilly** [comment]
ok, just saw a problem again, we should switch to this as the default command. Doesn't make things worse.
