### ISSUE TITLE
Using the "open" command in terminal for a url

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#180]
Using "open" for a link pasted in the SMC terminal (e.g. http://sagemanifolds.obspm.fr/examples/sws/SM_Kerr.sws) creates a massive error/pop-up across a large part of the screen for the user and fails... I suggest either allowing users to use the open command to render the file (rather than going to create a new file with the same name with the create a new file button) or making the error message coherent.

**Comment by williamstein** [comment]
This is now https://github.com/sagemathinc/smc/issues/409
