### ISSUE TITLE
upgrade client side codemirror

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1810]
Consider this example from coffeescript.org:
```
class Person
  constructor: (options) ->
    {@name, @age, @height = 'average'} = options

tim = new Person name: 'Tim', age: 4
```
It works if you put it in a file, say `foo.coffee` and compile and  run on command line with `coffee` and `node`. Adding `console.log tim` produces the expected output:
```
Person { name: 'Tim', age: 4, height: 'average' }
```

But if you put the above example in a sagews cell, starting with directive `%coffeescript`, the console log shows multiple error messages like the ones below, and more are added every time a cell is executed. And the coffeescript-mode function `print` produces no output.
```
[31h48m22.51s Δ 0s] Error rendering worksheet SyntaxError: unexpected =
Stack trace:
[stdin]:6:27: error: unexpected =
    {@name, @age, @height = 'average'} = options
                          ^  smc-08fa4586d2c69c034175.js:12:4104
[31h48m22.52s Δ 0.01s] Error rendering worksheet SyntaxError: unexpected =
Stack trace:
[stdin]:6:27: error: unexpected =
    {@name, @age, @height = 'average'} = options
                          ^  smc-08fa4586d2c69c034175.js:12:4104

```

**Comment by williamstein** [comment]
There is a difference in the version of Coffeescript running on the server versus on the client:

<img width="1009" alt="screen shot 2017-03-28 at 4 10 37 pm" src="https://cloud.githubusercontent.com/assets/1276278/24431517/20831010-13d1-11e7-99d5-75a58225187e.png">

Please change the title to "upgrade client side codemirror"...

**Comment by williamstein** [comment]
This is trickier...

src/smc-webapp/misc_page.coffee at line 1651 is where coffeescript gets loaded.

That looks like maybe the old way before we used npm much or webpack.

Yep, that’s from smc/src/webapp-lib/coffeescript and is actually a big file checked into the repo.

It may be best to assign this to @haraldschilly

**Comment by DrXyzzy** [comment]
Note from @williamstein:
> It’s not so simple. https://cloud.sagemath.com/projects/10f0e544-313c-4efe-8718-2142ac97ad11/files/smc/src/smc-webapp/misc_page.coffee at line 1651 is where coffeescript gets loaded.

> That looks like maybe the old way before we used npm much or webpack.

>Yep, that’s from smc/src/webapp-lib/coffeescript and is actually a big file checked into the repo.

**Comment by haraldschilly** [comment]
ok, I understand what's going on. that's from the old "salvus" days :-)

**Comment by DrXyzzy** [comment]
time: 1 hour
