### ISSUE TITLE
in +New, pasting in a URL to github should clone that repo.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1818]
This used to work, but is totally gone now.  

1. Click +New
2. Enter https://github.com/plotly/python-user-guide and hit enter or "download from network".
3. Get nothing good!

**Comment by haraldschilly** [comment]
I think this never worked. There is support for either `git@github.com:...` repos or downloading directly a file (changing the url to be "raw" and "blob"). Adding a case for cloning a `https`-repo shouldn't be too hard, though.

time: 15 min
