### ISSUE TITLE
Story of a weird Error

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1819]
The stacktrace below is our current #1 error, but I have no idea how to solve it. Gave it the label "hard" and I definitely don't have a full picture of what's going on. My theory circles around  `EventEmitter` prototyping of `emit`:

1.  how `Primus` does it in `webapp-lib/primus/primus-engine.js` and how we use it in `client_browser.coffee`
2. what `jshint.js` and `mocha.js` do.

I don't know what happens if we do not emit an error in `client_browser.coffee` upon an error event ... or maybe we have to wrap it into something such that it isn't an `Error`-error? Anyways, below are my notes:

reported stacktrace:

```
Error
   at t.prototype.emit (https://cloud.sagemath.com/static/smc-74163f95a1c120d6d2ee.js?74163f95a1c120d6d2ee:30:14083)
   at Anonymous function (https://cloud.sagemath.com/static/smc-74163f95a1c120d6d2ee.js?74163f95a1c120d6d2ee:151:1002)
   at emit (eval code:1:3372)
   at error (eval code:1:24408)
   at emit (eval code:1:3372)
   at next (eval code:1:2325)
   at e._wrapper (https://cloud.sagemath.com/static/lib-74163f95a1c120d6d2ee.js?74163f95a1c120d6d2ee:117:25710)
   at Anonymous function (https://cloud.sagemath.com/static/lib-74163f95a1c120d6d2ee.js?74163f95a1c120d6d2ee:117:27230)
```

first off, the second frame is in `client_browser`:

```
conn.on 'error', (err) =>
    log("error: ", err)
    @emit("error", err)
```

top frame: fails in `if(t=arguments[1],t instanceof Error)throw t`

```
t.prototype._events=void 0,
t.prototype.setMaxListeners=function(e){if(!r(e)||e<0||isNaN(e))throw TypeError("n must be a positive number");return this._maxListeners=e,this},
t.prototype.emit=function(e){var t,r,s,a,l,c;if(this._events||(this._events={}),"error"===e&&(!this._events.error||i(this._events.error)&&!this._events.error.length)){if(t=arguments[1],t instanceof Error)throw t;var u=Error('Uncaught, unspecified "error" event. ('+t+")");
```

this is **either** in `smc-webapp/node_modules/jquery-ui/external/jshint/jshint.js` **or** `mocha/mocha.js`.
The code looks identical and the surroundings in the minified code give me no hints. In the end, I think it doesn't matter.

```
EventEmitter.prototype.emit = function(type) {
  var er, handler, len, args, i, listeners;

  if (!this._events)
    this._events = {};

  // If there is no 'error' event listener then throw.
  if (type === 'error') {
    if (!this._events.error ||
        (isObject(this._events.error) && !this._events.error.length)) {
      er = arguments[1];
      if (er instanceof Error) {
        throw er; // Unhandled 'error' event
      } else {
        throw TypeError('Uncaught, unspecified "error" event.');
      }
      return false;
    }
  }
```

and this is in `primus/primus-engine.js`:

```
EventEmitter.prototype.emit = function emit(event, a1, a2, a3, a4, a5) {
  var evt = prefix ? prefix + event : event;

  if (!this._events || !this._events[evt]) return false;

  var listeners = this._events[evt]
    , len = arguments.length
    , args
    , i;

  [ .... ]
```

**Epilog**

of course, many other ugly things might be going on with primus not using the same `EventEmitter` code as it thinks it is using. Maybe that also explains other problems, like the reconnection flakiness...  I don't know. I also don't remember when mocha.js was added, maybe that correlates with some of the primus issues.

time: 45 min

**Comment by williamstein** [comment]
Quick remark:  I'm fine with removing mocha entirely from the frontend.  I would rather do testing via mocha extensively... but 100% on the server... of frontend code.  That's how I'm testing jupyter, and it's much better.

**Comment by williamstein** [comment]
I think the solution is to replace
```
conn.on 'error', (err) =>
    log("error: ", err)
    @emit("error", err)
```
by 
```
conn.on 'error', (err) =>
    log("error: ", err)
```
Because:
1.  It is definitely correct EventEmitter behavior to raise an exception if you emit an event called 'error' and nobody is listening for it.  
2. Nothing is listening on 'error' for client -- (a) I grepped, and (b) I don't remember ever making anything listen for it, and (c) there is no reason I can think of to do so.  Only the client should care about maintaining the connection.   
3. 'error' is probably a reasonable thing for the conn to sometimes raise, e.g., in case of weird disconnects at random times... That said, I don't know specifically why Primus would raise 'error'.  but  [this section of the primus docs](https://github.com/primus/primus#primusonerror) says there are lots of routine reasons it could happen and also specifically says "Unlike Node.js, we do not throw an error if no error event listener is specified", which I take to mean that we shouldn't either.  By rebroadcasting the error event, we **are** causing an error to be thrown. 

So I'll fix this.

**Comment by williamstein** [comment]
And I think I didn't know that error events that aren't caught result in exceptions in general when I wrote that line of code...

**Comment by williamstein** [comment]
time: 10 minutes

**Comment by williamstein** [comment]
process: RTFM.  Seriously, reading the primus docs is incredibly helpful.
