### ISSUE TITLE
include ~/.local/bin/  in the PATH for projects so that scripts installed using pip --user work.

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#184]

**Comment by williamstein** [comment]
Still not done.  Could be very confusing not having this.  Probably easy to fix...

**Comment by williamstein** [comment]
Maybe would get added in smc-compute script...

**Comment by haraldschilly** [comment]
assigning myself, I have an idea how to do this

**Comment by haraldschilly** [comment]
uhm, correction. I think I've done this a long time ago. I just don't know why all my .bashrc explicitly add `~/.local/bin` to the path; and that skewes my testing a bit

**Comment by williamstein** [comment]
> I think I've done this a long time ago

So closing.
