### ISSUE TITLE
make transparent background the default for three.js rendering

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1840]
See #1836.

1. Enable three.js rendering with 'transparent' background.
1. Make 'transparent' the default background.
1. Update docstring for sagews `show()`,

**Comment by DrXyzzy** [comment]
As @williamstein pointed out in chat, axis color (looks like cyan to me) is not good when background is 'transparent' if edit theme is default.

Please try this line (no patch needed) and see if the axis color is acceptable in default and dark edit themes:
```
show(icosahedron(color='green', opacity=.5, mesh=5, spin=10),
  background='transparent',foreground='gray')
```

If so, then I can make a PR to:
1. Set foreground to `gray` if background is `transparent`
2. Add text to docstring explaining that setting `foreground` in `show()` will set axis colors.

**Comment by williamstein** [comment]
**yes** this is beautiful, imho.

**Comment by DrXyzzy** [comment]
Verified in production.
