### ISSUE TITLE
add r" for the latex code insert in SMC worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#185]
Suggested by:  Aaron Tresham

> Anyway, I think this little "r" should be added to the example when you select "Text" from the Plots drop-down menu in SMC.  In fact, it would be nice to include a TeX example in the help file for text in Sage. Then the need for raw strings could be mentioned there.

**Comment by evelynmitchell** [comment]
I've added r" to the plots drop down menu, and created a Pull request. I'll look at the help file for text.

**Comment by williamstein** [comment]
Thanks!  There's a massive refactor of code happening right now, which will be done in a few days (hopefully this weekend), so please double check in a week that your pull request was properly merged.

**Comment by evelynmitchell** [comment]
It didn't merge, I'll check in a week. Thank you!

**Comment by evelynmitchell** [comment]
This hasn't been properly merged, but also, it looks like the build isn't working. I'll check back in a couple of days.

**Comment by williamstein** [comment]
Fixed: https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-122645-issue185.sagews
