### ISSUE TITLE
Add student by name is buggy

### ISSUE THREAD

**Issue by stumpc5** [sagemathinc/smc#1867]
I searched on smc for my student in the "add student by name or email" (can send name by private mail if needed).

Search for "Firstname Lastname" shows no matches. Searching for "Firstname" shows many hits (not in lex order, which makes it a little annoying), including the one I first searched for.

**Comment by williamstein** [comment]
I'm going to close this. Please make a support request to help@sagemath.com and include the exact info about the student. We'll make an issue here if there is indeed a bug.

**Comment by williamstein** [comment]
There are two (contradictory) tickets related to this already:

https://github.com/sagemathinc/smc/issues/1626

and

https://github.com/sagemathinc/smc/issues/1788
