### ISSUE TITLE
sage3d plot breaks in chrome

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1884]
the plot in [that sagews file](https://cloud.sagemath.com/projects/14eed217-2d3c-4975-a381-b69edcb40e0e/files/scratch/broken-plot3d.sagews) causes chrome to hang

**Comment by williamstein** [comment]
Which version of Chrome?  This works fine for me in Version 57.0.2987.133 (64-bit) on OS X.

**Comment by haraldschilly** [comment]
Mine is Version 58.0.3029.68 beta (64-bit) in Ubuntu Linux 16.04.

**Comment by williamstein** [comment]
I just upgraded, and plotting **also** works fine on OS X with Chrome Version 58.0.3029.81 (64-bit).   This may be a Linux-only problem, or issue with your 3d setup.

**Comment by haraldschilly** [comment]
closing this, seems to be browser+os specific.
