### ISSUE TITLE
add a "check your spam folder" message (in bold/red) to the "reset your password" dialog, and fix some other clumsy bugginess in that modal

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#189]
In the very rare case a password reset message doesn't work, when we get to the bottom of it, the user says:

> Thank you very much for your help. indeed the password reset emails had gone to the spam.

**Comment by williamstein** [comment]
We still need to to do this.  The message now only says not this.  

<img width="597" alt="screen shot 2016-09-23 at 12 22 58 pm" src="https://cloud.githubusercontent.com/assets/1276278/18798688/8b23a1fe-8188-11e6-8a84-66c7806befd6.png">

Also, the forgot password modal popup doesn't even autofocus the input.

Clicking on the modal at all (e.g., to copy paste) just closes the dialog, which is disconcerting.

This whole thing should be rock solid, not a mess, given how important it is...

**Comment by haraldschilly** [comment]
for the sake of mentioning it, my old branch for a completely different way how passwords are done is here: https://github.com/sagemathinc/smc/tree/password-reset-plain

**Comment by williamstein** [comment]
(it is a major stretch that this is a bug... but it is really important.)

**Comment by williamstein** [comment]
fixed and live now.
