### ISSUE TITLE
display of mathjax in safari (in markdown output) is completely broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1895]
1. Open a chatroom (or anything involving markdown) using Safari.
2. Type `hello $x^3$`
3. See nothing where the math should be.  It might appear for a moment then vanish.

If we don't fix this in the next 1-2 days, we should put a big red "don't use safari" error that appears when you try to use SMC with safari...

**Comment by DrXyzzy** [comment]
Could this be related: mathjax/MathJax#1732 `MathJax fails silently when run locally with RequireJS` ? Doesn't explain why we only see the problem with Safari, but thought I'd mention it.

**Comment by williamstein** [comment]
I disabled requirejs already and the problem persists, I think.  It may have been a problem for a while....?

**Comment by haraldschilly** [comment]
I don't have safari, so hard to test. Same holds true for math output in sagews? As far as I know there was no change to how it is setup or even Mathjax's version. Maybe Safari was updated recently?

**Comment by haraldschilly** [comment]
one hint: [mathjax 2.7.1](https://github.com/mathjax/MathJax/releases/tag/2.7.1)

the only weird thing is it was updated on npm only a few hours ago. but maybe it went in earlier with the latest update? or maybe there was a broken npm release and updating again will fix it? we should first check such a safari browser against 2.7.1 before drawing conclusions on our smc setup here.

**Comment by haraldschilly** [comment]
is it safari 10.1? there are upstream bugs mentioned at mathjax, e.g. https://github.com/mathjax/MathJax/issues/1709

**Comment by DrXyzzy** [comment]
As of latest merge, Mathjax in markdown displays in Safari 10.1 logged-in sessions. But it still does not display when the file is published and viewed with Safari 10.1 from a non-logged-in session; note the test is done in regular viewing mode, not private browsing mode. Private browsing mode has issues with local storage and should not be used with SMC.

**Comment by williamstein** [comment]
Technically we could enable public viewing (when not logged in) without localStorage.   I just haven't yet, due to lack of effort.

**Comment by williamstein** [comment]
Assigning me and unassigning @haraldschilly , since duh -- he doesn't have a mac or safari so can't test this.

**Comment by williamstein** [comment]
> Same holds true for math output in sagews? 

NO -- everything works fine there.  It's a bug in our complicated markdown rendering pipeline. Should be easy to isolate by commenting out things.

**Comment by williamstein** [comment]
time: 22 minutes

process: comment out in the process flow for rendering the HTML component
