### ISSUE TITLE
safari in private browsing: show_local_storage_warning broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1898]
in `smc-webapp/feature.coffee`:

```
    # Check for local storage
    if not require('smc-util/misc').has_local_storage()
        require('./smc-react').redux.getActions('page').show_local_storage_warning()
```

and then in `smc-webapp/init_app.coffee`

```
    show_local_storage_warning: =>
        @setState(local_storage_warning : true)
```

fails for reasons I don't know

screenshot made by @DrXyzzy 

![private-browse-safari](https://cloud.githubusercontent.com/assets/207405/25384750/b856f1f8-29c1-11e7-9a7e-9a3c122af6f6.png)

**Comment by williamstein** [comment]
Fixed.  There is still a stacktrace though, but it's harmless (I think).
