### ISSUE TITLE
video chat "Enter room" button doesn't work in chromebooks and chrome browser

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1899]
> [@williamstein] Kevin lui reports (and I confirm) that video chat (via appear.in) doesn’t work on chromebooks. In particular, clicking the “Enter room” button leads to a traceback:
```
ScreenShareAction: check-extension message: undefined
4libs.facb87b2.js:2 Unhandled error from JOIN_ROOM: already in a room
(anonymous) @ libs.facb87b2.js:2
serviceworker.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
```
> Probably best solution is add a link to the top of our window that pops up saying: if room doesn’t work, click to open room here…

**Comment by DrXyzzy** [comment]
"Enter room" button also does not appear when using Google Chrome 57.0.2987.133 (64-bit) on OS X 10.12.4. Clicking "Video Chat" button in a chat panel pops up a blank window.

**Comment by DrXyzzy** [comment]
Updated chrome to 58.0.3029.81 (64-bit) and problem is still there.

**Comment by haraldschilly** [comment]
with some details how we embed it we could email them at feedback@appear.in

On Apr 25, 2017 20:27, "Hal Snyder" <notifications@github.com> wrote:

"Enter room" button also does not appear when using Google Chrome
57.0.2987.133 (64-bit) on OS X 10.12.4. Clicking "Video Chat" button in a
chat panel pops up a blank window.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sagemathinc/smc/issues/1899#issuecomment-297122718>,
or mute
the thread

**Comment by williamstein** [comment]
Problem isn't there for me on chrome, and never has been. Weird.

**Comment by DrXyzzy** [comment]
Might be two different problems, since there are no tracebacks or console error log messages with Google Chrome. Just a blank window. I tried whitelisting sagemath.com and appear.in in the popup list, but no change.

**Comment by DrXyzzy** [comment]
This is repeatable for me with Chrome:
1. Open a chat file.
1. While `Video Chat` button is white, hover cursor over it, wait for it to change to gray backgound, then wait for the "Toggle Video Chat" pop-up.
1. Click `Video Chat`. Pop-up appears and __`Enter room` button is visible__ (and it works, but don't enter the room right now).
1. Legend on the video chat button has changed to `1 Video Chat` with red foreground. Hover cursor over it til background is gray and click it, then leave cursor there. Chat pop-up window disappears.
1. Legend on the video chat button changes back to `Video Chat` with black foreground and background is still gray. Click it. Popup appears but __Enter button is not visible__.
1. Click `1 Video Chat` button again to close the pop-up.
1. Move cursor to right gutter, not over any buttons, and click so that `Video Chat` button background returns to white. You can now go back to the second step and repeat the entire sequence.

**Comment by haraldschilly** [comment]
So, I think that's an appear.in problem. Exceptions for their window look like this:

```
libs.facb87b2.js:2 ScreenShareAction: check-extension message: undefined
2main.5c64252a.js:1 Error getting access to storage. Are cookies blocked?
value @ main.5c64252a.js:1
main.5c64252a.js:1 Error getting access to storage. Are cookies blocked?
value @ main.5c64252a.js:1
5aa8943…:1 Uncaught (in promise) [IndexedDB] Could not access IndexedDB
5aa8943…:15 GET https://signal.appear.in/protocol/socket.io/v1/?socketType=room&EIO=3&transport=polling&t=LkcnAaV&sid=mjm3plYfeTQfV64hBxbs 400 ()
nrWrapper @ 5aa8943…:15
i.create @ libs.facb87b2.js:7
i @ libs.facb87b2.js:7
o.request @ libs.facb87b2.js:7
o.doPoll @ libs.facb87b2.js:7
r.poll @ libs.facb87b2.js:7
r.onData @ libs.facb87b2.js:7
(anonymous) @ libs.facb87b2.js:7
r.emit @ libs.facb87b2.js:7
i.onData @ libs.facb87b2.js:7
i.onLoad @ libs.facb87b2.js:7
hasXDR.t.onreadystatechange @ libs.facb87b2.js:7
nrWrapper @ 5aa8943…:15
5aa8943…:1 WebSocket connection to 'wss://signal.appear.in/protocol/socket.io/v1/?socketType=room&EIO=3&transport=websocket&sid=mjm3plYfeTQfV64hBxbs' failed: WebSocket is closed before the connection is established.
5aa8943…:15 POST https://signal.appear.in/protocol/socket.io/v1/?socketType=room&EIO=3&transport=polling&t=LkcnAcd&sid=mjm3plYfeTQfV64hBxbs 400 ()
```
![screenshot from 2017-04-25 22-21-08](https://cloud.githubusercontent.com/assets/207405/25406006/811c818c-2a05-11e7-945b-37fd7b45c022.png)

**Comment by DrXyzzy** [comment]
For the Google Chrome issue, resizing the video popup makes the `Enter room` button appear if it is not already visible. It might help to set the iframe size explicitly to e.g. 480x480. See the answer here: http://stackoverflow.com/questions/35459719/no-webcam-stream-when-embedding-webrtc-in-flask-app/35518008 I don't have a chromebook to test.

**Comment by williamstein** [comment]
Why don't we just replace the entire embedding business with showing a link to the chatroom?

**Comment by DrXyzzy** [comment]
I experimented with replacing `video_window()` with the following. When `Video Chat` is clicked in a chat file, a new browser tab is created for the chat, but the state of the `Video Chat` button isn't tracking the state of the newly-created tab correctly, i.e. closing the video chat tab does not cause the `Video Chat` foreground to change back to black despite the event listener for unload on the chat window.
```
# The pop-up window for video chat
video_window = (title, url) ->
    w = window.open(url)
    return w
```

**Comment by DrXyzzy** [comment]
Created #1913 and self-assigned.
