### ISSUE TITLE
make it possible to click and drag to move the position of the document in the latex preview

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#19]
Right now you can move the document by scrolling vertically or horizontally using your mouse, which is OK if you have a super-good mouse.  However, it would also make sense to be able to click and drag the preview to change its position, especially since click and drag currently does nothing.

This is a feature requested by Mani Chandra.

**Comment by haraldschilly** [comment]
Quick search:
http://www.debiki.com/dev/utterscroll
or just http://hitconsultants.com/dragscroll_scrollsync/scrollpane.html

look like a good match for this ...

**Comment by haraldschilly** [comment]
Utterscroll enables it everywhere, but just to get a feeling for it:

```
%coffeescript
$.getScript '//rawgit.com/debiki/utterscroll/master/jquery-scrollable.js', ->
    $.getScript '//rawgit.com/debiki/utterscroll/master/debiki-utterscroll.js', ->
        debiki.Utterscroll.enable scrollstoppers: '.CodeMirror, .ui-resizable-handle'
```

It's probably super trivial to extract the essential parts of utterscroll and just apply it dynamically to the div-scrollable areas (besides the latex preview, I'm also thinking about the pdf, image viewer, etc.)

**Comment by williamstein** [comment]
still not fixed/done...

**Comment by haraldschilly** [comment]
other candidates are https://www.npmjs.com/package/react-dragscroll or maybe even https://www.npmjs.com/package/react-scroll-box ... pending rectification of the latex editor (and all the viewers for pdf and images, too) of course
