### ISSUE TITLE
Published Jupyter notebook does not render in Firefox

### ISSUE THREAD

**Issue by moorepants** [sagemathinc/smc#190]
I have this notebook:

https://cloud.sagemath.com/projects/ebb30a0f-930e-45a6-b727-53df0c36a484/files/2015-10-23-140959.html

That doesn't render in Firefox 41.0.2 on Ubuntu 14.04.
![eme 150a - mozilla firefox private browsing _025](https://cloud.githubusercontent.com/assets/276007/10737393/3370c280-7bcf-11e5-8752-23160a8e88c6.png)

**Comment by williamstein** [comment]
I can confirm this.  Things work fine on OS X with chrome or Safari, but not with Firefox.  The new "Open Plain File" link that we added does work now on Firefox though.

**Comment by haraldschilly** [comment]
I just rolled out a fix, can you please confirm that it works?

**Comment by williamstein** [comment]
I can confirm that the fix works on Firefox OS X.

**Comment by moorepants** [comment]
This is what I see now:

![selection_051](https://cloud.githubusercontent.com/assets/276007/13577876/9b586212-e449-11e5-98c3-47f097073517.png)

But, to tell you the truth, I forget what I was expecting to see in the first place.

**Comment by williamstein** [comment]
You must open the file not logged in or as a user not collaborating on that
file.

On Monday, March 7, 2016, Jason K. Moore <notifications@github.com> wrote:

> This is what I see now:
>
> [image: selection_051]
> <https://cloud.githubusercontent.com/assets/276007/13577876/9b586212-e449-11e5-98c3-47f097073517.png>
>
> But, to tell you the truth, I forget what I was expecting to see in the
> first place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/190#issuecomment-193366984>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by moorepants** [comment]
Got it. It works! Thanks.

![sagemathcloud - mozilla firefox private browsing _052](https://cloud.githubusercontent.com/assets/276007/13578033/7367474a-e44a-11e5-8356-a0d6f013795f.png)
