### ISSUE TITLE
change peer-grade assignment to have peer-grade at the start of the name

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1910]
One silly thing: you did the switch so "graded-" is first, but NOT the switch so "peer-grade" is first; right now it is still last.

**Comment by johnjeng** [comment]
Unlike graded path, the peer-related paths are just various paths with `-peer-grade` appended or inserted into the middle of a path.

**Comment by williamstein** [comment]
So, should we close this?

**Comment by johnjeng** [comment]
I'm going to say yes. It's slightly inconsistent, but I don't think it's worth changing unless it comes up again...
