### ISSUE TITLE
Notify user when hit disk quota and make it easy to empty trash

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#192]

**Comment by timothyclemansspd** [comment]
Would like a true delete button instead of send to trash button

**Comment by haraldschilly** [comment]
This is also necessary when the project starts up. A logic like: project doesn't start after a timeout -> check quotas -> if disk quota full, show button to delete `.trash`

**Comment by williamstein** [comment]
#484 -- we've decided the trash serves no real purpose given the snapshots.
