### ISSUE TITLE
Kernel Logo blinking.

### ISSUE THREAD

**Issue by Carreau** [sagemathinc/smc#1927]
While in edit mode, there is a small area next to the "Trusted" indicator that make the kernel logo flicker.
It does not seem to happen on command mode. See attached GIF. 

![kernel-logo-blinking](https://cloud.githubusercontent.com/assets/335567/25775468/7cd91eac-325a-11e7-9447-d06dd2022595.gif)

**Comment by williamstein** [comment]
time: 29 minutes

process: refactor code (e.g., Logo out of file) for good measure; then move the logo outside the tooltip.
