### ISSUE TITLE
!important css rules  lead to double border.

### ISSUE THREAD

**Issue by Carreau** [sagemathinc/smc#1928]
Most of the buttons groups seem to have double border in between buttons. 

See seem to be due to the following rules in `_editor.sass`:
```
.btn-group
  .btn +
    .btn, .btn-group
      margin-left : 0 !important
  .btn-group +
    .btn, .btn-group
      margin-left : 0 !important
```

It was probably inserted on purpose in 2014, but now have side effect on many UI element.
Removing it seem to make like it make the UI a bit better:

<img width="265" alt="screen shot 2017-05-06 at 13 37 42" src="https://cloud.githubusercontent.com/assets/335567/25775746/4d967372-3261-11e7-92bf-a2fa30b9eef3.png">

<img width="266" alt="screen shot 2017-05-06 at 13 37 35" src="https://cloud.githubusercontent.com/assets/335567/25775745/4d949fa2-3261-11e7-8a72-78d725622cc2.png">

**Comment by williamstein** [comment]
Right you are!

**Comment by williamstein** [comment]
time: 4 minutes
