### ISSUE TITLE
jupyter2: problem with too much output?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1932]
Running this cell causes execution to hang (in anaconda's python3):

```
import numpy
from scipy.integrate import odeint
def dxdt(x, t):
    return [ x[0]**3 - 4. * x[1],
             x[0] - x[1] ]

t = numpy.linspace(0, 5, 1001)

for x0 in range(128):
    xp = odeint(dxdt, [x0, x0], t, mxstep=1000, full_output = 1)
```

Variations to try: `full_output = 0` (doesn't work either) or `mxstep = 10`.

it works in a .py file on the command line in anaconda...

**Comment by williamstein** [comment]
time: 1 hour 50 minutes

process: narrow it down; write test cython code to confirm my suspicion (based on my experience with writing the sage pexpect interfaces!); read node.js docs; change options... and it worked.

https://cocalc.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2017-05-07-did-hang.ipynb
