### ISSUE TITLE
jupyter2: help for R broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1933]
I'm not sure about this. In classical jupyter in R, `?c` gives me the help page for "Combine Values into a Vector or List". In jupyter2, it does nothing. Also, `help(c)` doesn't work either. Is this known?

**Comment by williamstein** [comment]
process: study the result of
```
k=require('./jupyter').kernel(name:'ir',path:'a.ipynb')
k.execute_code(code:"?c", all:true, cb:(a,b)->global.b=b)
```
and adjust the output-handler.  Also worry about multiple users and having the determination of introspection done only server side...
