### ISSUE TITLE
absolute links in project log are broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1939]
1. Type this in a terminal:
```
 open /projects/sage/sage-7.5/local/lib/python2.7/site-packages/sage/modular/modsym/ambient.py
```
2. It opens fine -- yeah.  Close it.
3. Now go to the project log and click on it -- the leading slash is missing so it doesn't work.

**Comment by DrXyzzy** [comment]
Verified fixed in production.
