### ISSUE TITLE
HTML version of Jupiter notebook only works on Chrome

### ISSUE THREAD

**Issue by projetmbc** [sagemathinc/smc#194]
Here is [a link](https://cloud.sagemath.com/projects/bcf4f485-52db-49db-ac8d-07e1b9b39795/files/mandelbrot_faster.html) showing the problem.

**Comment by williamstein** [comment]
The demo is gone.   I made a new example just now and it worked fine in firefox.

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-120721-issue194.html
