### ISSUE TITLE
public file listing should gracefully handle filenames containing invalid characters that can't JSON

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1941]
The octave kernel sometimes produces empty files with strange filenames (only shown as `???` or so). The `public_directory_listing` API call [defined here](https://github.com/sagemathinc/smc/blob/master/src/smc-util/message.coffee) runs a Python function from here

   https://github.com/sagemathinc/smc/blob/master/src/smc_pyutil/smc_pyutil/smc_compute.py#L590

to get the listing.  It fails.  

In the past we worked around similar issues for directory listings, which you can see here:

   https://github.com/sagemathinc/smc/blob/master/src/smc_pyutil/smc_pyutil/git_ls.py

`smc-ls` crashes (?) when it tries to read them.

To construct an example, take a filename that can't be JSON'd.  Invalid utf8 will do it.  Example here? http://stackoverflow.com/questions/1301402/example-invalid-utf8-string

**Comment by DrXyzzy** [comment]
Along with PR #1945, created related upstream takluyver/bash_kernel#61

**Comment by DrXyzzy** [comment]
Verified in production.
