### ISSUE TITLE
HTML table output

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#195]
Not a bug, but it would be nice if `html.table(list)` was implemented

```python
File: /projects/..../.sagemathcloud/sage_salvus.py 
Source: 
def table(self):
  raise NotImplementedError, "html.table not implemented in SageMathCloud yet"
```

A good first step would be for the function to have another argument, so the not-implemented error would be raised in the situation where it would normally be used.

**Comment by williamstein** [comment]
Still true: 

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-120437%20issue%20195.sagews

**Comment by williamstein** [comment]
Also there is a normal table command, which doesn't work in typeset mode: https://github.com/sagemathinc/smc/issues/89

**Comment by haraldschilly** [comment]
Rolled out and verified, that the examples from https://github.com/sagemathinc/smc/pull/1055 work.
