### ISSUE TITLE
copy/paste from jupyter output in firefox loses newlines

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1958]
Run a cell with this code with `Python 3 (Anaconda)` kernel:
```
z = """abc
def
ghi"""
print(z)
```

Insert a markdown cell. Copy the output of the above cell into clipboard and paste into the markdown cell.
- result using Google Chrome:
```
abc
def
ghi
```
- result using Firefox 53.0.2:
```
abc def ghi
```

 Note: it appears while highlighting that selecting the output in Firefox does not include newlines.

**Comment by williamstein** [comment]
What happens in sagews and jupyter classic?

**Comment by DrXyzzy** [comment]
Line breaks are visible with Firefox when copying from python3 output and pasting into the input of a markdown cell in sagews and jupyter classic notebook. I tested classic notebook by spoofing `general.useragent.override`.

I was not able to duplicate missing line breaks copying from text in github or pasting into github.

**Comment by williamstein** [comment]
> I tested classic notebook by spoofing general.useragent.override.

You could also click "Plain Jupyter Server" in project settings.

**Comment by DrXyzzy** [comment]
I only see missing line breaks when copying from output in the jupyter rewrite; in that case, line breaks don't show up, wherever I paste clipboard contents after that. If I copy text from output of the same code in sagews or classic jupyter, the line breaks show up when clipboard is pasted anywhere.

**Comment by williamstein** [comment]
This is nearly 17-year old bug in firefox that they've fixed, broken again, bike shedded, etc. evidently!  See https://bugzilla.mozilla.org/show_bug.cgi?id=116083 and https://bugzilla.mozilla.org/show_bug.cgi?id=116083

Thus I guess I'll try to program around it... :-(  Which sucks because properly using CSS is so nice.
