### ISSUE TITLE
don't prevent users to navigate away upon SSO

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1967]
while in private browsing:

* goto cloud.sagemath.com -- you aren't signed in
* click on twitter, google, ... any of the SSO
* it asks you if you really want to navigate away

expected: it shouldn't ask when the user isn't authenticated

**Comment by williamstein** [comment]
ARGH!  Somebody rewrote the unload checking functionality to completely not use the file `src/smc-webapp/exit_confirmation.coffee`... and didn't bother to delete that file.

**Comment by williamstein** [comment]
time: 26 minutes

22 minutes was because `src/smc-webapp/exit_confirmation.coffee` existed but was not used.
