### ISSUE TITLE
Extra \ character added to long lines in sagews PDF

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#197]
At the end of a line of text from a sagews document which is too long to fit into a single line in a generated PDF, the generated output is displayed with an additional (unwanted) "\" character at the end of the line

**Comment by haraldschilly** [comment]
I can't reproduce this, text just wraps fine. Can you be more specific, please?

**Comment by Ahuchala** [comment]
Input: print '4444444444444444444444444444444444444444444444444444444444444444444444'

**Comment by williamstein** [comment]
Yep https://cloud.sagemath.com/4a5f0542-5873-4eed-a85c-a18c706e8bcd/raw/support/2016-09-23-115914-issue197.pdf?nocache=0.4287346391431739 

results in 

https://cloud.sagemath.com/4a5f0542-5873-4eed-a85c-a18c706e8bcd/raw/support/2016-09-23-115914-issue197.pdf?nocache=0.4287346391431739

**Comment by williamstein** [comment]
This is intentional. The backslash means that there is one long line that is being split.  It's standard in python and other languages.  Otherwise there is no way to know that it isn't to separate lines of output.
