### ISSUE TITLE
Clicking on video chat starts displaying user's video feed but only after opening chat twice

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#198]
In a sagews document, clicking the video chat button starts recording the user (and doesn't open up chat) and even after checking once, the video is not displayed. Need to open chat twice to display video feed. Also after ending a video chat which was successfully displayed, it leaves behind a white box blocking half of chat from view until chat is opened and closed again.

**Comment by williamstein** [comment]
Closed in favor of a new video chat system: https://github.com/sagemathinc/smc/pull/883
