### ISSUE TITLE
do Sage worksheets automatically stop running after a certain amount of time for no reason?

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#20]
There have been multiple reports of computations that, when run in a worksheet for many hours (or just letting a worksheet sit for a while), the underlying python process will get killed for no good reason.  Is this caused by some sort of bug in the local_hub or sage worksheet server?     If so, fix it.  If anybody gathers data about this, then this is a good place to put it.   I'll of course try to  read source code and get to the bottom of this.

**Comment by edgimar** [comment]
If you haven't already considered it, it could be that the kernel is killing the process if it consumes too much memory -- it might be worth looking at the kernel logs to see if any OOM kills are taking place.  Some info on parameters that influence OOM killing:  https://www.kernel.org/doc/Documentation/sysctl/vm.txt
