### ISSUE TITLE
File upload on error needs a useful error message

### ISSUE THREAD

**Issue by timclemans206** [sagemathinc/smc#201]
My upload is failing and no idea why. The error message is:
file upload error -- {"0":"T","1":"i","2":"m","3":"e","4":"d","5":" ","6":"o","7":"u","8":"t","9":" ","10":"a","11":"f","12":"t","13":"e","14":"r","15":" ","16":"1","17":"0","18":" ","19":"s","20":"e","21":"c","22":"o","23":"n","24":"d","25":"s","26":".","bold":"\u001b[1mTimed out after 10 seconds.\u001b[22m","strip":"Timed out after 10 seconds.","stripColors":"Timed out after 10 seconds.","trap":"ͳ༏ӍξԂ ǾƱŦ ȺӺͳ੬Ɍ 10 ϞΣϾØŋԀ§.","zalgo":"T̵̯̺͔̦̹͔̖͇̩̪̳͍͙̣̞̮̫̭̞̘̻̤̼͕̟̤͖͈̺̗̙͈̗̻͓͍̙͉̱̭̗̤͒́̑̍ͩͣ̆͂̏̍̆ͯ͊ǐ͇̘̮̼̜̤͇̜̺̼̳̼̗͎͕̱̫̙̹͚̪͉̝͕͓̠͚͈̱͉̣̹͕̖̱̰̟̩̱̲͓̭ͥ̿̐̌͑̈̍̎̏̃ͯ̃̔̏ͣ͟ͅm̴͉͚̙̜͚̙̳͓̺̪̦̖̥̹̘̱̰̤̖̳̜̟̲̤̰͚̖̱̞̖͓̦͓͉̰͙͓̗̟̪̖͇͉̳͈̗̹̳̭̗͕͖̑̈̓̒̃̓ͬͯ̓ͦ̅͐̌ͅͅe̸̪̹̟̯͕̳͍̯̣̼͔̯͉̭̜̹͈̦̝͍̭͚̣̪͈̺͈̗͍̟̦͈̲̳̼̙͖̙̟͍̤̜̮̠͖ͭ͂ͫ̏͑̅̿̈͗͒ͦ͌ͤ...","zebra":"T\u001b[7mi\u001b[27mm\u001b[7me\u001b[27md\u001b[7m \u001b[27mo\u001b[7mu\u001b[27mt\u001b[7m \u001b[27ma\u001b[7mf\u001b[27mt\u001b[7me\u001b[27mr\u001b[7m \u001b[27m1\u001b[7m0\u001b[27m \u001b[7ms\u001b[27me\u001b[7mc\u001b[27mo\u001b[7mn\u001b[27md\u001b[7ms\u001b[27m.","rainbow":"\u001b[31mT\u001b[39m\u001b[33mi\u001b[39m\u001b[32mm\u001b[39m\u001b[34me\u001b[39m\u001b[35md\u001b[39m \u001b[33mo\u001b[39m\u001b[32mu\u001b[39m\u001b[34mt\u001b[39m \u001b[31ma\u001b[39m\u001b[33mf\u001b[39m\u001b[32mt\u001b[39m\u001b[34me\u001b[39m\u001b[35mr\u001b[39m \u001b[33m1\u001b[39m\u001b[32m0\u001b[39m \u001b[35ms\u001b[39m\u001b[31me\u001b[39m\u001b[33mc\u001b[39m\u001b[32mo\u001b[39m\u001b[34mn\u001b[39m\u001b[35md\u001b[39m\u001b[31ms\u001b[39m\u001b...","random":"Timed out after 10 seconds.","america":"Timed out after 10 seconds.","reset":"\u001b[0mTimed out after 10 seconds.\u001b[0m","dim":"\u001b[2mTimed out after 10 seconds.\u001b[22m","italic":"\u001b[3mTimed out after 10 seconds.\u001b[23m","underline":"\u001b[4mTimed out after 10 seconds.\u001b[24m","inverse":"\u001b[7mTimed out after 10 seconds.\u001b[27m","hidden":"\u001b[8mTimed out after 10 seconds.\u001b[28m","strikethrough":"\u001b[9mTimed out after 10 seconds.\u001b[29m","black":"\u001b[30mTimed out after 10 seconds.\u001b[39m","red":"\u001b[31mTimed out after 10 seconds.\u001b[39m","green":"\u001b[32mTimed out after 10 seconds.\u001b[39m","yellow":"\u001b[33mTimed out after 10 seconds.\u001b[39m","blue":"\u001b[34mTimed out after 10 seconds.\u001b[39m","magenta":"\u001b[35mTimed out after 10 seconds.\u001b[39m","cyan":"\u001b[36mTimed out after 10 seconds.\u001b[39m","white":"\u001b[37mTimed out after 10 seconds.\u001b[39m","gray":"\u001b[90mTimed out after 10 seconds.\u001b[39m","grey":"\u001b[90mTimed out after 10 seconds.\u001b[39m","bgBlack":"\u001b[40mTimed out after 10 seconds.\u001b[49m","bgRed":"\u001b[41mTimed out after 10 seconds.\u001b[49m","bgGreen":"\u001b[42mTimed out after 10 seconds.\u001b[49m","bgYellow":"\u001b[43mTimed out after 10 seconds.\u001b[49m","bgBlue":"\u001b[44mTimed out after 10 seconds.\u001b[49m","bgMagenta":"\u001b[45mTimed out after 10 seconds.\u001b[49m","bgCyan":"\u001b[46mTimed out after 10 seconds.\u001b[49m","bgWhite":"\u001b[47mTimed out after 10 seconds.\u001b[49m","blackBG":"\u001b[40mTimed out after 10 seconds.\u001b[49m","redBG":"\u001b[41mTimed out after 10 seconds.\u001b[49m","greenBG":"\u001b[42mTimed out after 10 seconds.\u001b[49m","yellowBG":"\u001b[43mTimed out after 10 seconds.\u001b[49m","blueBG":"\u001b[44mTimed out after 10 seconds.\u001b[49m","magentaBG":"\u001b[45mTimed out after 10 seconds.\u001b[49m","cyanBG":"\u001b[46mTimed out after 10 seconds.\u001b[49m","whiteBG":"\u001b[47mTimed out after 10 seconds.\u001b[49m","greyBG":"\u001b[49;5;8mTimed out after 10 seconds.\u001b[49m"}

**Comment by williamstein** [comment]
Just to add, I think he was uploading a 142MB file, which exceeds the internal limit of about 40MB.
