### ISSUE TITLE
Some bash commands doesn't work in %sh mode with nonlatin simbols.

### ISSUE THREAD

**Issue by AndreWin** [sagemathinc/smc#211]
Hello!

I tried in SMC:

```
%sh
touch файл.txt
```

`touch` command doesn't work when filename contains nonlatin symbols. I tried the same `touch файл.txt` in console line in file manager and in .term file &mdash; it works fine there.

Best regards, Andrey.

**Comment by williamstein** [comment]
fixed, probably by @DrXyzzy https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-110912-issue211.sagews

**Comment by AndreWin** [comment]
Many thanks!
