### ISSUE TITLE
task: investigate commercial software

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#212]
Contact each of the following vendors and find out how much it would cost to 100% legally purchase and make available their software on a 4-core SMC compute VM, so that it is usable by all (or a certain number simultaneously) of SMC projects:

 - Mathematica
 - Maple
 - Magma: http://magma.maths.usyd.edu.au/magma/ordering/
 - Matlab

Right now it may be too expensive to provide any of the above systemwide.  However, there could be a cross-over point where it is affordable.

**Comment by williamstein** [comment]
"If we got to a sufficient scale, one could imagine all the Ma's just being pre-installed on the "members only" VM's, and SageMath, Inc. pays whatever the license fee is to install those programs.   It's not unusual for an organization or company to buy any of the Ma software, install it on their computers, and have members of that organization (say of SMC) use it.  That's part of the double edged sword of commercial software licenses -- you sell the software to whoever pays you the money to buy it."

**Comment by kedlaya** [comment]
An alternative pricing model would be for users to pay for upgrades for particular software packages. For instance, I would gladly pay for a Magma upgrade to my SMC account (despite the fact that I can use it for free via the Simons agreement) but I have no pressing interest in any of the other Ma's.

**Comment by williamstein** [comment]
The pricing model also must be a function of the model charged by the vendor of the Ma.  I think at least Magma and Mathematica charge based on the number of computers you install on, not the number of simultaneous users of the binary.    Magma might charge also based on the number of cores.   From
http://magma.maths.usyd.edu.au/magma/ordering/ it says "The subscription cost depends upon the number of machines and the processor type. As a general indication, an educational institution taking out a three year subscription for: One desktop machine (maximum of 6 cores):	 	US$1440 (€1040); Two to four desktop machines (maximum of 24 cores):	 	US$2160 (€1560)".  

I clicked the button to request a quote for Magma on all members-only machines.  I hope they don't just respond "infinity"... but we'll see.  I'll post here about their response. 

I think Mathematica is similar. 

I think Matlab might have a price depending on the number of concurrent users.

**Comment by haraldschilly** [comment]
from what I've seen at my university: both mma and matlab were rolled out using a licensing server. they bought a yearly license for a number of X simultaneously active sessions, and each installation did negotiate with the licensing server if it is allowed to run. the fun experience I had was, when I did run some parallel computations in matlab, eating up all available licenses.

later, they switched on a per-desktop licensing scheme. I don't know why, or if that's cheaper, or just because of accounting. 

in any case, I'm sure something can be worked out. I doubt they'll trust us (e.g. linux group permissions) to restrict access to just the ones who pay. Therefore, I assume the way to go is to roll this out with a licensing server.

Interesting question for me is, if this server needs to be run under the wings of SMC at all. I.e., since all instances are connected through the internet anyways, is it enough to handle the installation of the software and setting up an infrastructure for reselling the license? The license activation then runs through their machines, anyways.

Another details might be, that although projects are single linux users, multiple actual users have access. Is this a problem?

**Comment by williamstein** [comment]
I think we should just make it so all paying customers get access to the
Ma's as part of their member benefits.  And that's it. No additional fee.
Like Netflix.  There is some amount per year that would make this totally
worth it.

On Thursday, February 25, 2016, Harald Schilly <notifications@github.com>
wrote:

> from what I've seen at my university: both mma and matlab were rolled out
> using a licensing server. they bought a yearly license for a number of X
> simultaneously active sessions, and each installation did negotiate with
> the licensing server if it is allowed to run. the fun experience I had was,
> when I did run some parallel computations in matlab, eating up all
> available licenses.
>
> later, they switched on a per-desktop licensing scheme. I don't know why,
> or if that's cheaper, or just because of accounting.
>
> in any case, I'm sure something can be worked out. I doubt they'll trust
> us (e.g. linux group permissions) to restrict access to just the ones who
> pay. Therefore, I assume the way to go is to roll this out with a licensing
> server.
>
> Interesting question for me is, if this server needs to be run under the
> wings of SMC at all. I.e., since all instances are connected through the
> internet anyways, is it enough to handle the installation of the software
> and setting up an infrastructure for reselling the license? The license
> activation then runs through their machines, anyways.
>
> Another details might be, that although projects are single linux users,
> multiple actual users have access. Is this a problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/212#issuecomment-188950249>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by jasongrout** [comment]
FYI, there may be a difference in licensing between making it available to employees (like at a university or company), and making it available to paying customers.

**Comment by williamstein** [comment]
Does anybody have any interest in investigating?  I.e., just contacting
sales at these companies and finding out exactly how much it would cost for
us to fully provide their product through SMC to all paying users?

 -- William

On Thu, Feb 25, 2016 at 12:56 PM, Jason Grout <notifications@github.com>
wrote:

> FYI, there may be a difference in licensing between making it available to
> employees (like at a university or company), and making it available to
> paying customers.
>




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/212#issuecomment-188982353>.
>



-- 
William (http://wstein.org)

**Comment by haraldschilly** [comment]
I can contact them, sure

**Comment by williamstein** [comment]
I'm going to close this.  There are very real dangers in us just becoming some sort of resellers for commercial software and depending on them.  Compared to now, we give up our independence and can be crushed like a bug.  We undercut our main *raison d'être*.
