### ISSUE TITLE
add typescript mode

### ISSUE THREAD

**Issue by jasongrout** [sagemathinc/smc#215]
When I create a file with a `.ts` extension, typescript highlighting is not enabled.  I think you may be able to just add typescript to the codemirror extension map at https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/editor.coffee#L73.  You might also use the internal codemirror mode dictionary at https://github.com/codemirror/CodeMirror/blob/master/mode/meta.js to automatically have up-to-date mode information, instead of making a static list of your own.

**Comment by williamstein** [comment]
Solved with https://github.com/sagemathinc/smc/commit/9ed15b018a47e7b15ea2011323ef3aacd43a2d6d
