### ISSUE TITLE
rewrite http://www.sagemath.org/calctut/ as public Sage worksheets that work: calculus tutorial

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#217]
This old tutorial http://www.sagemath.org/calctut/ is an extremely popular thing on the Sage website.   It's very popular anyways.  It's just an undergrad student project I paid one student to make in maybe 2009 or 2010 as a project.   

Somebody, sit down and rewrite the whole thing as (1) a bunch of sagews files (with linking between them) in a public project, and (2) make sure everything works.

**Comment by KrazyKoreanKid** [comment]
I'm going to work on rewriting this. I'll post a link to the project shortly, and criticism will be very welcome. I have a lot to learn.

**Comment by codyryu** [comment]
Posting on a non-obscene account. Sorry about that, won't happen again.

**Comment by haraldschilly** [comment]
sounds good. do not bother about those javascript parts and line-number popups. just write down the codeblocks and briefly explain what they are doing … i.e. it doesn't need to be exactly the same and don't hesitate to reinterpret what's there.

**Comment by codyryu** [comment]
Here's the rewrite. It's finished for the most part, but I'll be revising for style consistency.

https://cloud.sagemath.com/projects/c71ef2fe-f1b2-482d-ab29-c91dba1e241a/files/Tutorial/Introduction.sagews

**Comment by williamstein** [comment]
Very nice!!!

Trivial things --   I looked at 

https://cloud.sagemath.com/projects/c71ef2fe-f1b2-482d-ab29-c91dba1e241a/files/Tutorial/Review.sagews

and noticed that sin, cos, etc., should be \sin, \cos, etc., so they don't appear in italics.

Similar remarks here, e.g., about lim, which should be \lim:

https://cloud.sagemath.com/projects/c71ef2fe-f1b2-482d-ab29-c91dba1e241a/files/Tutorial/Limits.sagews

Great work!

**Comment by codyryu** [comment]
@williamstein The issues you brought up have been resolved
It's been polished to the point where Andy and I are fine with having this shared

**Comment by haraldschilly** [comment]
best would be to add this in a directory "calctut" at https://github.com/sagemath/cloud-examples

**Comment by haraldschilly** [comment]
I'm closing this issue, expecting a PR at the mentioned repo. @codyryu contact me if something is unclear, I can also check in the files in your name if you are confused -- or add me to a project where I can do it for you.
