### ISSUE TITLE
install PLINK (http://pngu.mgh.harvard.edu/~purcell/plink/tutorial.shtml)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#222]
REQUESTED BY: Eric Chen on sage-cloud-dev mailing list.

> Dear Sage-cloud developers: We are planning to use sage cloud for teaching a bioinformatics course next semester. I wonder if it is possible to install some bioinformatics tools on the Sage cloud, for example PLINK (http://pngu.mgh.harvard.edu/~purcell/plink/tutorial.shtml)? Any help will be appreciated. Thanks.

Harald Schilly looked into this:

> ok ,the 64 bit linux binary seems to do something. it’s just that it checks for a web interface to open up. to disable this by default, the switch --noweb needs to be added.   what I would do: (1) install it into /usr/local/bin on compute4 and the push it out;  (2) install a global alias with --noweb via a file in /etc/proifile.d/ across the compute nodes; [(3) add to build.py]"

I wonder: 

> "Why not a wrapper shell script? Isn’t that more robust, especially for people who might use different shells?"

There's also Debian packages somewhere.  Not sure if there are Ubuntu packages or an Ubuntu ppa.  By far the optimal way to install would be if there was an **Ubuntu PPA**.

**Comment by haraldschilly** [comment]
cool, I've not assumed it's in debian. the package `plink` has the same version as the most recent one on download from their website. I'll install it. I'm not sure how to install a wrapper script, it's probably not necessary anyways, because the error message is explicit anyways.

**Comment by haraldschilly** [comment]
PLINK is installed on all compute nodes. Run it via `p-link` and to avoid waiting for the update check for the version (which doesn't work because network access is disabled for free projects), run it via `p-link --noweb`
