### ISSUE TITLE
sagews tracebacks MUST show line number and line where problem happened! 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#223]
Idea: in a sage worksheet, when rendering tracebacks, modify line number of code pointing to the worksheet itself to somehow match the current line numbers in the worksheet..

See [this worksheet](https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-11-02-170011-line-numbers-git-issue-223.sagews).  

What we need to do:

- [ ] create a new output type called "traceback", which is not just stderr.   This would involve adding code to `src/smc_sagews/smc_sagews/sage_server.py`.  See the Message business (look at how stderr is implemented).

- [ ] in the evaluation code, when a traceback is hit, produce a traceback object as output, rather than a string in stderr.

- [ ] when displaying a traceback (like in the worksheet linked to above), it currently starts with "Error in lines 2-2".  Where it says "lines 2-2" we need to dynamically change that to actually show the line to the left.  This means that traceback output has to get re-rendered whenever the line that it is on changes.  There's nothing like this in sagews now -- it's a totally new crazy thing.    ALTERNATIVELY, an easier (lamer) solution would be to just rewrite the traceback and replace say "lines 2-2" with "the line `a / 0`", i.e., put the actual content of the line there.  This would not be as good, but could be done once only on the server so is easier. 

There may also be interesting subtleties with all the other modes, e.g.,%r, %latex, etc...

**Comment by williamstein** [comment]
Note -- the solution IPython takes is to just show the input in context as part of the exception:

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-11-02-170316-line-numbers.html

<img width="798" alt="screen shot 2015-11-02 at 5 07 31 pm" src="https://cloud.githubusercontent.com/assets/1276278/10898904/3adc4886-8184-11e5-8e45-ed1f73b31e04.png">

**Comment by novoselt** [comment]
Related but not the same issue is dealing with warnings (which are not handled correctly by IPython and Sage). I've done this in SageMathCell, but there has to be a better way:
https://github.com/sagemath/sagecell/commit/bf5b926bd382768029a0fc9d3c7895855ddeb366

**Comment by novoselt** [comment]
And examples how it works are here: https://groups.google.com/d/topic/sage-devel/-KiMrG--5x8/discussion

**Comment by williamstein** [comment]
Alternative - have another gutter that has line numbers starting from 1 for each input cell (so two columns of line numbers: one local and one global).

**Comment by williamstein** [comment]
I'm closing this as now we have per cell line numbers.  That's not exactly 100% this, but it is a good foundation.
