### ISSUE TITLE
In a sagews, the rest of the line to the right of a cell divider is editable, and evaluating can cause cell to be uneditable

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#225]
Steps to reproduce:

1) Open a sagews
2) Click in the text area of line 1, type in a valid command (e.g. the command "print '5'"), and then evaluate it (shift + enter by default). The input line "print '5'" should be visible on line 2, as well as a new output block with the character 5 on it on line 3.
3) On the far right side of line 1, click and type a valid command (e.g. the command "print '6'"), and evaluate it.

The input which was originally on line 2 disappear (and be thus uneditable), leaving only the output which was originally on line 3. The text "print '6'" should still be visible and editable on the right side of line 1, but it should not have successfully evaluated.

**WORKAROUND:**
> Is there a better way of deleting a sagecell (which preferably only involves
> the use of a keyboard)?

Just use shift+arrow keys to highlight anything you want to delete,
then hit backspace.

**Comment by Ahuchala** [comment]
In step 3, the first character you type will be at the end of the line of text, causing the word "print" to become "rintp"... need to retype it for the bug to be reproduced

**Comment by williamstein** [comment]
I think all such issues like this are fixed...
