### ISSUE TITLE
Configure Jupyter Sage kernel system-wide

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#24]
@edgimar on gitter says: 

By looking at the result of calling _install_spec(), it looks like the JSON you need for /usr/local/share/jupyter/kernels/ is the following: `{"display_name": "Sage 6.7", "argv": ["/usr/local/sage/sage-6.7/sage", "-python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"]}`

NOTE from william: probably need to format the JSON on multiple lines -- I've noticed ipython weirdly doesn't work otherwise...

**Comment by williamstein** [comment]
Volker Braun says: 

> The easiest way to get Sage plots is to use the Sage kernel. Its 
apparently not in the list of IPython kernels on SMC, so you need to 
open a terminal and run "sage --notebook=ipython" once to register the 
Sage kernel (which creates ~/.sage/ipython-3.1.0/kernels/sage_6_7). 
Then abort (Ctrl-C) and reopen your IPython notebook. Go to Kernel -> 
Change kernel -> Sage 6.7 and you can use Sage plots.

**Comment by edgimar** [comment]
This may work for creating a local kernel configuration for Jupyter, but it would be preferable to just install this `sage_6_7` file in the global config location for Jupyter.

**Comment by williamstein** [comment]
Sorry -- the directions above are useful to me so that I know how to create the sage_6_7 file to include globally.

**Comment by williamstein** [comment]
done long ago....
