### ISSUE TITLE
Set R's working directory path to the one of sagews

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#240]
When running `%r` in a sagews which is in a subdirectory, the R interpreter is still running in the home directory. Call R's `setwd()` appropriately when starting it up.

**Comment by williamstein** [comment]
Still broken
```
%r
getwd()
```
https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-102034-issue240.sagews

Seems pretty damned serious too.

**Comment by williamstein** [comment]
Switching to the Jupyter R kernel would just fix this:
```
ir = jupyter('ir')
```
---
```
%ir
getwd()
```

and it works fine.

**Comment by williamstein** [comment]
@DrXyzzy  any thoughts about just switching to the R jupyter kernel...?

**Comment by DrXyzzy** [comment]
+1.

**Comment by haraldschilly** [comment]
this works, ticket is merged, closing bug
