### ISSUE TITLE
show what other users are doing in my project in realtime

### ISSUE THREAD

**Issue by peoplesnsa** [sagemathinc/smc#243]

**Comment by williamstein** [comment]
Could you suggest a design?

On Sunday, November 8, 2015, peoplesnsa <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/243>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by peoplesnsa** [comment]
I'm thinking a message box at bottom where latest action shows for about 5
seconds.

**Comment by williamstein** [comment]
done!
