### ISSUE TITLE
PDF export doesn't work

### ISSUE THREAD

**Issue by lanphan** [sagemathinc/smc#249]
Hi,
I tried to export to PDF from my IPython notebook (R code, Python code) on sagemath cloud, but it raised 500 error.
I used https://try.jupyter.org and everything is fine there.
Is it possible to upgrade / fix this bug for sagemath cloud?

Thanks so much.

**Comment by haraldschilly** [comment]
please send us the exact URL link to your file to help@sagemath.com such that we can investigate this in detail. thank you.

**Comment by lanphan** [comment]
@haraldschilly 
Just send it to you, my request to help@sagemath.com is numbered 604.

Thanks in advanced,
