### ISSUE TITLE
there are frequent issues with ipython/Jupyter notebooks and "download as --> pdf (via latex)" print preview etc

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#255]
These are due to bugs in ipython that have been reported.  In the meantime, since such problems represent a significant fraction of support requests, we should do something about it!

The symptom is that printing anything where the latex file has any problem (e.g., with ligatures in text, etc.) results in a useless error page:

```
500 : Internal Server Error
The error was:
nbconvert failed: PDF creating failed
```

The temporary workaround is for users to open a terminal and type `ipython nbconvert --to pdf file.ipynb` and change their document to eliminate any errors that prevent compilation.

Alternatively, in SMC, they can do this in a terminal:
1. `ipython nbconvert --to latex file.ipynb`
2. `open file.tex`

and use the SMC latex editor and error system to fix their issues, then download the pdf. For example, I just tried this with the latest support request, where nbconvert is putting `\begin{enumerate*}` in the latex file, which doesn't make any sense! (Somebody is confused about how to generate valid latex...?) However the files people get out of an ipython notebook -- with a single big output block, and easily be hundreds of pages long!

**Comment by bkasel** [comment]
Hello, I wanted to say that I also get those 500 errors when using 'Download as pdf. However when I run 
~~~bash
ipython nbconvert --to pdf My\ Notebook.ipynb
~~~
The pdf gets created without a hitch.

When I run the same thing with 'jupyter nbconvert' does not work.
~~~bash
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 3, in <module>
    from nbconvert.nbconvertapp import main
ImportError: No module named nbconvert.nbconvertapp
~~~
Could that be a part of the problem?

**Comment by williamstein** [comment]
Labeling high and a bug since this is a constant source of support requests, and people always think it is **a bug in sage that they must report**.

**Comment by williamstein** [comment]
We haven't hit this in a long time have we? And there are no concrete examples of what causes this here.   I'm closing.  We did complain a lot upstream, and maybe they fixed the problems. 

If this comes up again, please create a ticket with a minimal test case and report upstream.

**Comment by haraldschilly** [comment]
I'm not aware of problems either. What's working way more robustly is that "print preview", which is showing the plain html in a new tab. Printing that to PDF or just saving that HTML is always a good work around.
