### ISSUE TITLE
clarify the pricing page: add more help to the pricing page

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#256]
E.g., 

> What is meant by network
> access, idle timeout, member hosting, and CPU shares?

- network access -- free projects do not have access to the outside
network, since otherwise hackers will use SMC to launch attacks.

- idle timeout -- by default free projects stop running after 1 hour
of idle time.  This makes doing an overnight research computation,
e.g., searching for prime numbers, impossible.

- member hosting - free projects run on a general pool of *very*
heavily loaded computers; often these computers will have over 150
simultaneous projects running on them.  Member hosting means that
instead the projects run on much less heavily loaded machines reserved
for paying customers.

- cpu shares -- this determines how resources are shared between
users.  Increasing this increases the priority of a project over those
of other users on the same host computer.

**Comment by Ahuchala** [comment]
Here are some changes I made to billing.cjsx: https://gist.github.com/Ahuchala/441dca72bab2518776dc

**Comment by haraldschilly** [comment]
@Ahuchala could you make a fork and commit your changes there? Mixing in your file as a whole might lead to confusion or overwrites prior changes.

**Comment by williamstein** [comment]
Harald -- no.  We wouldn't do "Mixing in your file as a whole might lead to confusion or overwrites prior changes." -- I just wanted a quick in to make sure what he did isn't lost.   It was already mixed up with what other people were doing in the same repo.  It should be easy to take the file now and diff it against something.  And the changes are likely in one spot.

**Comment by williamstein** [comment]
Is what you added really just around line 904?

**Comment by Ahuchala** [comment]
I tried to reduce a lot of the ambiguity from lines 868 to 881, I'm not totally satisfied with where it's at currently, but I think it's more coherent than the riginal

**Comment by Ahuchala** [comment]
But just to be clear, the changed lines are from 865 to 918
