### ISSUE TITLE
http://cloud.sagemath.org and https://cloud.sagemath.org should redirect to https://cloud.sagemath.com instead of being a broken black hole

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#257]
Make these do something useful: http://cloud.sagemath.org and https://cloud.sagemath.org

**Comment by haraldschilly** [comment]
the `*.org` DNS entry is now a CNAME pointing to `.com`. Hence, due to the already existing redirects, this works now and should magically switch your browser's URL to the canonical `*.com` variant.
