### ISSUE TITLE
Error in integrate

### ISSUE THREAD

**Issue by discnerd** [sagemathinc/smc#263]
I'm trying to work with the Beta Distribution, but it looks like something is wacky with integrate.

integrate(x^(3-1)*(1-x)*(3-1),x,0,1) should be 1/30, but it returns 1/6.

**Comment by williamstein** [comment]
This should be reported to the sage developers, e.g., http://trac.sagemath.org/ and https://groups.google.com/forum/#!forum/sage-support, not here.   Thanks!
