### ISSUE TITLE
increase timeout for copying files between projects (and of course, also change params to make faster)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#268]

**Comment by haraldschilly** [comment]
Hmm, ... my first step is always to look around where the code is. Is it here in [compute-client.coffee](https://github.com/sagemathinc/smc/blob/master/src/smc-hub/compute-client.coffee#L1463) ?

**Comment by mikecroucher** [comment]
This is a recurrent issue for us. We have a class of 15, all of whom are using the paid-for servers, and when we assign a set of Jupyter notebooks at least one person gets a truncated notebook. We have to reassign several times before it takes.

**Comment by williamstein** [comment]
Please let me know if you have further problems like this, and *exactly* what the problem is.  I've re-implemented the storage backend completely from scratch during the first few weeks of December, which will impact this functionality.    Right now, copying files between projects should be very, very fast.

**Comment by williamstein** [comment]
No reported issues related to this in a year; also this has to get reimplemented from scratch for k8s anyways.
