### ISSUE TITLE
Push notifications for assignments

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#274]
SMC knows the due date of an assignment and a student's email address.  How about automatic email notifications to students?

1.  Assignment creation or "opening" date.
2.  Due date reminder (24 hours, 48 hours, configurable).
3.  Assignment returned.

The second one is time-dependent and might share code with #109.  The above could all be checkbox options in a course settings.

**Comment by williamstein** [comment]
Close in favor of https://github.com/sagemathinc/smc/issues/304
