### ISSUE TITLE
Accents and ' not exporting right into pdf

### ISSUE THREAD

**Issue by pierrequere** [sagemathinc/smc#275]
When using those kinds of letters and symbols : é, à ô, ê, I encounter a bad result as you can see below. Plus, the ' symbol, like in the word "isn't" doesn't export right either :
[2015-11-20-103333.pdf](https://github.com/sagemathinc/smc/files/40051/2015-11-20-103333.pdf)

**Comment by haraldschilly** [comment]
I don't know the exact source file to reproduce this. Can you check that it works after my recent update commit d3f0c246a4235b?

**Comment by pierrequere** [comment]
All the french accents and the ' symbol works perfectly fine, in %md  
mode as well as in comment (#) mode !!
Thanks a lot !

Harald Schilly <notifications@github.com> a écrit :

**Comment by haraldschilly** [comment]
Perfect, thank's for checking this -- closing ticket.
