### ISSUE TITLE
sagews printing -- make the size of plots be better controlled 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#279]

**Comment by haraldschilly** [comment]
yes, I was wondering. Intuitively, I would make them 50% of the textwidth, but those embedded <img> html tags need to be smaller. I used the setting "density=120" (or is it resolutiong=120), which seems to be fine for rasterized images rendered for screens (70 to 90 dpi). 

Cool would be to be able to set the width explicitly, but there are no pixels in latex and even worse, when embedded via markdown, there is no width/height.

**Comment by williamstein** [comment]
@haraldschilly  -- still a problem with your new html printing???

**Comment by haraldschilly** [comment]
just close it. images dynamically resize due to css
