### ISSUE TITLE
another regression with new landing page: "Signing you in" didn't used to show all the advertising about what SMC is...

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#286]
Before the landing page rewrite, there were two pages: (1) to make an account, and (2) to sign in.  Page (1) had the "marketing" about what SMC is, but (2) didn't.  When refreshing the page, you used to just see (2) with a Loading... for a moment.  Now you see the full landing page marketing info while being signed in.  

Fix: hide everything except "Signing you in", which should be bigger, when signing you in.  

This is like what happens with gmail, and is much less distracting.

**Comment by jlee27** [comment]
Fixed in f80a8a606c96aab0de3b8a0149d06b8d23d80d14
