### ISSUE TITLE
jupyter notebooks hidden on iPad

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#288]
when opening a jupyter notebook in an iPad browser, it is hidden down below at the bottom and there is no way to scroll down.

<img src="https://cloud.githubusercontent.com/assets/207405/11326529/3539f714-916c-11e5-82fe-a84da70751ec.jpg" height="400px" />

<img src="https://cloud.githubusercontent.com/assets/207405/11326530/353eecb0-916c-11e5-8673-10a38189cadb.jpg" width="400px" />

**Comment by haraldschilly** [comment]
The problem has been reported on "I have an iPad Mini 2 (Model ME277LL/A) running iOS 9.1 (13B143), and I use Safari as my mobile browser."

It does work on my Nexus7/Android6, Chrome 47 though. (in "mobile" view, and also when requesting the desktop version in wide screen view)

**Comment by williamstein** [comment]
It also works perfectly (surprisingly well, actually) on my iPhone 6+ with Safari.

**Comment by williamstein** [comment]
Another report from a user today.
![image1](https://cloud.githubusercontent.com/assets/1276278/11404176/7d54dfce-9355-11e5-90d3-df41ae37b681.png)

I've dug up my old ipad, and I was able to reproduce this problem on it!

**Comment by irabriones** [comment]
Hi, I reported that last screen cap posted by William. I tried desktop view on the same browser (safari) and device (iPad pro) and that worked.

![image](https://cloud.githubusercontent.com/assets/16021091/11404905/806cf5da-9372-11e5-8d25-926676449363.png)

**Comment by williamstein** [comment]
NOTE: william will email Anthony Short (search his email) when this is fixed!

**Comment by theobarnhart** [comment]
Are there any tricks for connecting to a jupyter notebook on an ipad being served from a computer on the local network? I can bring up the tree, but cannon connect to the kernel when I click a notebook. I've tried becoming a certificate signing authority to generate a non self signed certificate for SSL, but this has not helped (and adding the CA certificate as a trusted profile on the ipad). The notebook says its connecting and then it hands and says not connected. ipad pro 9.7 running safari and chrome iOS 9.3.1. Jupyter version 4.1.0
![image](https://cloud.githubusercontent.com/assets/6664825/14991143/2a6d64de-111d-11e6-8800-050e49273512.png)
![image](https://cloud.githubusercontent.com/assets/6664825/14991153/3139571e-111d-11e6-9433-69f8fb8d992c.png)

**Comment by haraldschilly** [comment]
@theobarnhart this here is about sagemathcloud, not jupyter in general. You have to ask at their bugtracker or mailing list.

**Comment by jasongrout** [comment]
@theobarnhart - I'd suggest posting to the Jupyter mailing list: https://groups.google.com/forum/#!forum/jupyter

**Comment by theobarnhart** [comment]
Thanks all, I posted the question to the jupyter github and got it figured out.

**Comment by slel** [comment]
For reference the discussion is at https://github.com/jupyter/notebook/issues/1421

**Comment by jasongrout** [comment]
Great! @haraldschilly - sounds like it's safe to close this issue.

**Comment by williamstein** [comment]
Well 'this issue', namely https://github.com/sagemathinc/smc/issues/288, has nothing to do with most of the discussion above.

**Comment by RobertTalbert** [comment]
Hi, I am also experiencing the same issue with Jupyter notebooks as was first described on this thread -- the notebook appears in the bottom 1/3 of the screen on SageMath Cloud, while the top part of the screen looks as it is supposed to look: 

![img_0230](https://cloud.githubusercontent.com/assets/3129186/16112402/24bb140c-3385-11e6-91e5-b948147388f6.PNG)

This is on Chrome on iOS 9.3.2 running on an iPad Air 2. The same happens when it's in landscape mode, and when I am using Safari. This does NOT happen when I am running Sage notebooks or other objects in SMC, only Jupyter notebooks.

**Comment by haraldschilly** [comment]
this also happens on an ipad with iOS 9.3.4.

one solution is to tell safari, to serve up the **desktop version** of that page. (in the end, well, it's a desktop version that you really want to have here with the jupyter notebook) -- credits for that insight go to Joshua Samani

**Comment by williamstein** [comment]
Fixed properly now and live.

**Comment by haraldschilly** [comment]
I've verified that it still works fine on my nexus 7 tablet.

**Comment by RobertTalbert** [comment]
Me too, it works fine now. Thanks!
