### ISSUE TITLE
implement %attach (and attach('...')) for SageMathCloud worksheets, like in sagenb and the command line

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#290]
This was something inspired by Magma long ago, which is in sagenb and the command line, and which is fairly useful.  Implement it for Sage Worksheets in SageMathCloud.

**Comment by kcrisman** [comment]
Requested again [at this SO question](http://stackoverflow.com/questions/37985846/sagemathcloud-load-python-script-with-argument/).

**Comment by williamstein** [comment]
Done!
