### ISSUE TITLE
In +New page, don't allow creating a file with no extension at all without first asking for user confirmation

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#291]
If a user clicks +New, then hits return, they get a basically useless file.  People *often* do this, expecting a sage worksheet, and get very confused that SMC is broken.  "Code won't run!"

I would bet that this might account for a significant amount of lost users.

In addition we could also make it so that if a user presses shift+enter when editing a file with empty extension, they get a message that they should instead create a sage worksheet.

**Comment by johnjeng** [comment]
Do people still often do this? Does anyone type a name expecting a file with that exact name?

**Comment by williamstein** [comment]
I can't see how this could not still be a problem.

**Comment by johnjeng** [comment]
I dunno, people used to type sage into the quick terminal and I would have expected that to also still happen but when we checked, it didn't.

**Comment by williamstein** [comment]
This is I think now **the most popular support request**.  People are constantly creating plain text files (no extension) and getting confused that they aren't Sage worksheets.   I'm promoting this to high priority.   E.g., the latest support request a few minutes ago: 

> There isn't even an option to run this code, and the top of the screen is telling me that I can no longer do anything in Sage without paying a subscription fee. What's up with this?
