### ISSUE TITLE
introspection parser doesn't complete properly on "for a in ab[tab]"

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#295]
Define a variable "abc" in a worksheet, then type -- in another cell -- "for a in ab[tab]".  It should complete, but doesn't, due to the introspection parser in smc_pyutil not being good enough.

**Comment by DrXyzzy** [comment]
This also doesn't introspect, with abc defined: `3 * ab[tab]`.

Issue is similar to #701, similar fix.

**Comment by DrXyzzy** [comment]
Done.
