### ISSUE TITLE
Meta-issue: rewrite the frontend of SMC using React.js

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#3]
So far the account settings are done and live.

**Comment by williamstein** [comment]
Note: We may use jest for testing, e.g., because of https://facebook.github.io/jest/docs/automatic-mocking.html

**Comment by williamstein** [comment]
Don't use jest.  We are using mocha...

**Comment by johnjeng** [comment]
Moving to Milestones and making a meta issue.
