### ISSUE TITLE
use travis-ci to automatically test SMC

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#31]
https://travis-ci.org/haraldschilly/smc

**Comment by haraldschilly** [comment]
this is kind of done. after you pull my latest commit from the `rethinkdb` branch and push it to the upstream repo, the build for this branch will should show up [here](https://travis-ci.org/sagemathinc/smc) and you'll get an email (as the committer). by default, all branches and pull requests will be tested when the `.travis.yml` file is present.

**Comment by williamstein** [comment]
pushed to rethinkdb branch.

Can you document somewhere in the top-level README the link to travis-ci?
