### ISSUE TITLE
lim(1/x,x=0) returns infinity instead of und.

### ISSUE THREAD

**Issue by sergy2008** [sagemathinc/smc#310]
even when I specify the algorythm to be maxima, it still returns infinity instead of und.
Don't know why, but the problem doesn't seem to be with maxima, but with your implementation of the maxima algorythm.
This issue popped up in an engineering class in Spain. I'm a student, so I'm afraid I can't provide any more help.
Cheers from Spain

**Comment by aarontresham** [comment]
I believe there is a difference between infinity and +infinity in Sage. Without a + or -, infinity refers to "complex infinity" - in complex world there is just the one infinity, so in complex world this limit is correct. At least, that's how it was explained to me.

If you do lim(1/x,x=0,dir='+'), you get +infinity, and if you use dir='-' you get -infinity, as expected.

**Comment by sergy2008** [comment]
The professor showed us an example in the documentation in which that limit returned und.  Just checked again. Infinity apparently is COMPLEX infinity, so yeah, everything is OK. He might have shown us outdated documentation.
