### ISSUE TITLE
Better document and button-ify codemirror search box (like browser search)

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#311]
Searching is frustrating me. Often what I'm looking for takes several rounds of hitting enter and then re-hitting ctrl-f and enter again.

**Comment by williamstein** [comment]
Use ctrl+g to go to next result, shift+ctrl+g to previous.

Better docs here: http://codemirror.net/3/demo/search.html

**Comment by timothyclemansinsea** [comment]
Thank you! Maybe add that to the search box?

**Comment by williamstein** [comment]
Yes, we should -- basically, as you say, we should also add some arrows like in chrome search.  These things are partly documented under keyboard here: https://cloud.sagemath.com/settings/account

**Comment by williamstein** [comment]
Marking bug and high, since I've heard precisely this confusion/complaint **dozens** of times over the years, and we've done nothing to make it better.

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/issues/17 for some work in this direction.

**Comment by williamstein** [comment]
I just improved the documentation.   No buttons -- that's going to be hard and isn't nearly so necessary (in the sense of being a *bug*).  The buttons: https://github.com/sagemathinc/smc/issues/1154
