### ISSUE TITLE
all npm run scripts sort of broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#313]
See "sh: 1: source: not found" below:

```
salvus@web4:~/smc/src$ npm run lint
 
> sagemathcloud@1.0.0 lint /home/salvus/smc/src
> source smc-env; node_modules/.bin/coffeelint -f smc-util/coffeelint.json -c *.coffee && cd smc-hub && npm run lint && cd ../smc-webapp && npm run lint && cd ../smc-util &
& npm run lint && cd ../smc-util-node && npm run lint
 
sh: 1: source: not found
  ✓ webpack.config.coffee
```

**Comment by haraldschilly** [comment]
Uhm, well, since the first line in smc-env specifies `bash`, I've changed this under the assumption that  `bash` is the canonical default and then everything runs in it (i.e. those path modification scripts only work there, etc).

The error says `sh: 1:` and hence this environment runs the old `sh` shell. What system is this? Changing the default shell to `/bin/bash` would be my suggestion. Is there even bash available?

Alternatively, all those npm commands could be instantiating an explicit bash session (I'm thinking of `"bash -c '<commands>'"`)

**Comment by williamstein** [comment]
On Thursday, December 3, 2015, Harald Schilly <notifications@github.com>
wrote:

> Uhm, well, since the first line in smc-env specifies bash, I've changed
> this under the assumption that bash is the canonical default and then
> everything runs in it (i.e. those path modification scripts only work
> there, etc).
>
> The error says sh: 1: and hence this environment runs the old sh shell.
> What system is this?
>

It's SMC!


>
>
> Changing the default shell to /bin/bash would be my suggestion. Is there
> even bash available?
>
> Alternatively, all those npm commands could be instantiating an explicit
> bash session (I'm thinking of "bash -c '<commands>'")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/313#issuecomment-161546525>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by haraldschilly** [comment]
hmm, please tell me tomorrow what's really going on. I've checked across all smc machines the default shells of all users. not a single one is set to `sh`. I have the feeling there is somewhere some deeper configuration issue hidden ...

**Comment by williamstein** [comment]
How about just get rid of setting the environment in npm run?  I also set it before running npm run anyways.

**Comment by haraldschilly** [comment]
> How about just get rid of setting the environment in npm run?

That's ok from my side, but it wouldn't solve the problem. I've no idea where `sh` comes into play and I don't know how to make this cross compatible. I'm happy to fix this by changing almost everything back to as it has been before.

**Comment by williamstein** [comment]
seems long since fixed.
