### ISSUE TITLE
Make an easy way to start a stopped project

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#316]
If a user is viewing a project in SageMathCloud, shuts their laptop for over an hour (for free projects), and then opens it, the project will be stopped but not automatically start running again. It would be handy to have a button on stopped projects to "unstop" them.

**Comment by williamstein** [comment]
Fixed in branch mentioned above. 
<img width="788" alt="screen shot 2016-01-18 at 4 45 34 pm" src="https://cloud.githubusercontent.com/assets/1276278/12406556/ec64561a-be02-11e5-9c20-965fc8aab03f.png">
