### ISSUE TITLE
Add pdb integration to ipython

### ISSUE THREAD

**Issue by evelynmitchell** [sagemathinc/smc#319]
https://github.com/gotcha/ipdb

"ipdb exports functions to access the IPython debugger, which features tab completion, syntax highlighting, better tracebacks, better introspection with the same interface as the pdb module."

**Comment by williamstein** [comment]
NOTE: You can install this into a project by typing `pip install --user --no-deps ipdb` at a terminal.

**Comment by williamstein** [comment]
@haraldschilly  -- this is just an easy package install request, so maybe you can slip it into the update you're doing regarding docker images?

**Comment by haraldschilly** [comment]
yes, tested it by installing it and then calling it. … now added to the buildfile and closing ticket.
