### ISSUE TITLE
GNUPLOT_PS_DIR and gnuplot from octave

### ISSUE THREAD

**Issue by billpage** [sagemathinc/smc#324]
The Octave command:

    saveas(h1,"figure1.png");

used to work but now I get the following message:

    Can't find PostScript prologue file prologue.ps
	    loadpath is empty
	    gnuplotrc is read from /projects/24a70e9b-9eee-4d22-8665-b589c410fa4b/share/gnuplot/5.0
	    no XAPPLRESDIR found in the environment,
	        falling back to "/etc/X11/app-defaults/"
    Please copy prologue.ps to one of the above directories
    or set the environmental variable GNUPLOT_PS_DIR
    or set the loadpath appropriately
             line 0: Plot failed!

See for example: https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/MIW2DVoronoiV1TestSagePlot.sagews

**Comment by williamstein** [comment]
Can you please create a minimal example to illustrate this? 

This webpage http://gnuplot.sourceforge.net/docs_4.2/node410.html says "If you see the error message  "Can't find PostScript prologue file ... " Please see and follow the instructions in postscript prologue (p. [*])."   Maybe somebody can read that webpage and see if it makes any sense.

**Comment by billpage** [comment]
A simple example is towards the end of

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/cloud-examples/octave/

This example is linked from https://github.com/sagemathinc/smc/wiki/FAQ#octave

**Comment by billpage** [comment]
This was my error.  I had install gnuPlot version 5 locally in my project.  After deleting the local version the example now works as expected.  Closing this issue.
