### ISSUE TITLE
Some actions on a cell sagews create an additional blank cell

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#325]
1) open a new sagews
2) type "print'5'" and evaluate it with shift + enter
3) Select the cell (click below it and drag over it)
4) In the button bar, on the left click the hide input button

A new, empty cell is created below your original cell.

Also happens if you tell sage to evaluate the same cell multiple times

**Comment by Ahuchala** [comment]
Or, you can just click the hide input button on an empty sagews...

**Comment by williamstein** [comment]
This is a design change from what I implemented.  I can see why you might find it to be more sensible....  It is annoying getting "an empty cell" appearing.
