### ISSUE TITLE
Need easy way to get the raw url of a file

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#328]
I'm trying to view HTML page I'm editing and can't remember how to get the raw url. It would be nice if there was a button.

**Comment by williamstein** [comment]
Click the checkbox then Download. It has a link.

On Sunday, December 13, 2015, timothyclemansinsea <notifications@github.com>
wrote:

> I'm trying to view HTML page I'm editing and can't remember how to get the
> raw url. It would be nice if there was a button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/328>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
I got it again in support this week

**Comment by haraldschilly** [comment]
@timothyclemansinsea what do you think about my #984 idea?

**Comment by williamstein** [comment]
Fixed!
