### ISSUE TITLE
Jupyter: File --> Download As --> PDF should first save 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#33]
When selecting File --> Download As --> PDF in Jupyter notebook, SMC should first do a save then do the download, since otherwise it prints an old version.  

![screen shot 2015-06-23 at 10 41 42 pm](https://cloud.githubusercontent.com/assets/1276278/8323429/11ea0e56-19f9-11e5-8f84-4cffa0386d5e.png)

 This is probably caused by us possibly disabling the save internally in Jupyter's javascript (not sure). 

Reported by: Troels Emtekær Linnet

**Comment by tlinnet** [comment]
I can confirm that "save first" -> "then pdf" effectively solves the problem.
I hope this can be automated, since I often "forget it". 
Thank you!

**Comment by williamstein** [comment]
@jasongrout -- any thoughts about this?

**Comment by jasongrout** [comment]
uh, yes, it makes sense to save before downloading.  I'll see if it does that normally.

**Comment by jasongrout** [comment]
By default, it seems that the notebook saves before downloading for me downloading a .py file.  However, downloading as a pdf isn't working for me right now, so I didn't test that.

**Comment by williamstein** [comment]
I can definitely confirm that this behavior persists on SageMathCloud.   Downloading pdf's is working fine for me, but definitely shows the version before save.  Also, **print preview** shows the pre-save version.

**Comment by williamstein** [comment]
this was a bug in jupyter, but it is fixed now.
