### ISSUE TITLE
improve wording regarding paid plans and upgrading

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#343]
Suggestions by Pedro Cruz and some interpretations by me.

1. first misunderstanding is, that "contributing" to "free projects" might mean, that you are paying for the projects of everyone who is running free projects ... not just an upgrade to your own. So, maybe, get rid of the word "contribution" at all and rephrase it as "upgrade". Also mix in the fact that there are no distinctions between free and non-free. Maybe call all free projects "basic plan", where what you get is just the quota you are getting for free.

1. Make the "subscription plans" page more visible from the various pages where upgrades are available and distill a short summary of what's going on.

Quote:

> " Adjust your project quota contributions" and did not get it! The question I formulated after reading it was:
> 
> is my project going to contribute to others quota?
>
> Then I read "Your contribution" and got completly lost thinking like:
> is my standard plan going to contribute for others when I'm not using it and this is the settings I want to give ?
>
> Finnaly I decided to go for help in the "Help" page and I think I got it: "contribution" means "contribute to my project" and not to the "free project".
> 
> Suggestion:
>
> improve the Settings tab with easy to understand messages or write a two sentences summary above the Settings tab describing the concept 
> "How the resouce plan you have can be distributed to YOUR projects" 
> (the word contribution is easy misunderstood here in Portugal, at least).

**Comment by haraldschilly** [comment]
More details about how to change the UI:

### Project (has exact equal meaning in Portuguese): 

area where resources (files, terminals, compilers, settings, and hardware quotas) are shared amongst selected SMC users.

### Standard Plan (and other plans): 
SMC users pay and get hardware resources (ram, disk, cpu, etc).

### Free ("gratuito" or "grátis" in Portuguese): 
Can be used, with limitations, but no money involved.

### Settings
One of them is describing "subscription vs resource" information related to 

* project settings: owner settings, colaborator settings 
* account settings

## My proposal

Usually, we think: 
* "my money". 
* "my projects". 
* "I want my money to be invested on Project1, Project2, and, 
* "want to see if "my friends" are investing their money on my projects".

My suggestion is, 

* only one place for controlling where my money is being invested: in the "Account Settings", a tab "Hardware Resources and Plan Options". 

* each "Project Settings" points to the "Account Settings" (a link "hardware resources" points to Account Settings)

In "Hardware Resources and Plan Options" I see a 2D array of information:

#### rows: 

* SMC free resources: 
* Account User (Plan name) : 
* Another User 1 who contributes to my projects (Plan name) : 
* Another User 2 who contributes to my projects (Plan name) : 
* Special last line: Button for release resources (when a project finishes) columns (all projects in which Account User collaborates or is Owner): 
* Total Purchased (in first row: a blank cell) 
* Not used yet (in first row: a blank cell) 
* Project1 (Account User collaborates or is Owner) 
* Project2 (Account User collaborates or is Owner) 
* Project3 (Account User collaborates or is Owner) 

#### Cells: 
In each cell one sees the Absolute Amount, the Relative Amount, and arrows UP/DOWN for account owner configuration.

And, a little more detail in each user row: 
* CPU cores 
* CPU shares 
* Disk Space 
etc.

#### And, outside the array: 

* A button: clean current values and optimize resources based on experience (needs agreement from all users)

> But all of this is based on what I imagine SMC is now. So, please forget all of this if this does not make any sense.

**Comment by williamstein** [comment]
A ton has been done.
