### ISSUE TITLE
sanitizing input messages in a chatroom, especially closing all open tags!

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#349]
And things go to hell!

**Comment by williamstein** [comment]
Need a sanitizer.

**Comment by haraldschilly** [comment]
it's actually any open html tag. 

quick research gives:

* https://github.com/punkave/sanitize-html ... which does look perfectly, but maybe too large?
* the caja sanizer from google: https://github.com/theSmaw/Caja-HTML-Sanitizer (AFAIK, used in their products ... ) … maybe there is a similar, but better packaged version out there. this one might be smaller due to less dependencies.  this is what we need: https://github.com/theSmaw/Caja-HTML-Sanitizer/blob/master/test/test-sanitizer.js#L103

**Comment by williamstein** [comment]
Google's main big thing is complicated because it involves a whole client/server architecture.

**Comment by haraldschilly** [comment]
Hmm, really? I though that's only javascript. I looked around on this npm site, the most downloads are this one: https://www.npmjs.com/package/sanitize-caja

**Comment by williamstein** [comment]
I think https://github.com/punkave/sanitize-html  is likely a reasonable choice; it doesn't look too bad.  I think Google caja is a client/server thing with a big Java server running somewhere....    You'll probably realize that once you try to make it work :-).

**Comment by haraldschilly** [comment]
well, I'm not sure, at least I don't understand why then the whole parsing stuff is still sitting in this sanitize-caja file.

**Comment by haraldschilly** [comment]
i.e. this bundle here: https://github.com/mapbox/sanitize-caja/blob/master/sanitizer-bundle.js

but probably doesn't matter, I am not picky about this. I just thought one small thing is better.

**Comment by williamstein** [comment]
You may be right -- I stand corrected.  That said, it's *still* not clear
that even that one sanitizer-bundle.js is smaller than the other library
(and its deps).

On Wed, Dec 30, 2015 at 9:52 AM, Harald Schilly <notifications@github.com>
wrote:

> i.e. this bundle here:
> https://github.com/mapbox/sanitize-caja/blob/master/sanitizer-bundle.js
>
> but probably doesn't matter, I am not picky about this. I just thought one
> small thing is better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/349#issuecomment-168044956>.
>



-- 
William (http://wstein.org)

**Comment by haraldschilly** [comment]
My branch for this is here: https://github.com/sagemathinc/smc/commits/ticket-349-sanitize-html and essentially ready to be merged. It uses jQuery [here](https://github.com/sagemathinc/smc/commit/fe16e09854b8a5ab6d456d45476a54dbb7591d44#diff-5a39aae6b7f3662db9ca760dc6e25492R1455) and blocks sending empty messages. Everything else is a bit of overhead for bringing the same functionality to the node backend and some comments.

**Comment by haraldschilly** [comment]
closing this. the jquery-sanitization is active for a while. it's kind of impossible to make it work in all the cases, since some aspects do clash with markdown formatting. at least, it fails in such a way, that it is still valid html...
