### ISSUE TITLE
g++ kills itself during linbox installation

### ISSUE THREAD

**Issue by darijgr** [sagemathinc/smc#35]
What I reported at http://trac.sagemath.org/ticket/18797 seems to be an SMC bug. It currently prevents me from installing Sage.

**Comment by williamstein** [comment]
Have you read https://github.com/sagemathinc/smc/wiki/SageMath-Development-on-SageMathCloud

**Comment by darijgr** [comment]
Hi William,

yes, I have; am I doing sometjhing wrong?

  Best regards,
  Darij

**Comment by darijgr** [comment]
Now it's scipy:

The following package(s) may have failed to build:

package: scipy-0.14.0
log file: /projects/1f2a5de2-58fe-4dd3-9ae9-2abee319cbee/sage-dev-images/sage-6.8.beta3/logs/pkgs/scipy-0.14.0.log
build directory:
/projects/1f2a5de2-58fe-4dd3-9ae9-2abee319cbee/sage-dev-images/sage-6.8.beta3/local/var/tmp/sage/build/scipy-0.14.0

Here is the scipy log file:

https://cloud.sagemath.com/projects/1f2a5de2-58fe-4dd3-9ae9-2abee319cbee/files/sage/logs/pkgs/scipy-0.14.0.log

  Best regards,
  Darij

**Comment by williamstein** [comment]
Hi,

You should upgrade to the $7/month plan, so you can run your project on a members only server.  The free servers are rebooted at least once per day (and can have heavy load), whereas the members-only servers stay up for a very long time.   To upgrade, put your billing information in the billing tab next to account settings, and email help@sagemath.com (include a list of up to 5 projects you want moved).
