### ISSUE TITLE
comment selected text in Sage worksheets should comment out all lines, not just first.

### ISSUE THREAD

**Issue by ursulawhitcher** [sagemathinc/smc#351]
When a block of text is selected in a Sage worksheet, hitting the "comment selected text" button should insert a pound sign in front of each line in the selected text.  Currently, only the first line is commented.

**Comment by williamstein** [comment]
Slightly hard because we have to improve how those transformations work.

**Comment by williamstein** [comment]
With multiple selections/cursors now, note that we also need to make this also work for all selections/cursors.
