### ISSUE TITLE
sagetex : intermediary files, suffix  sagetex.sout and sagetex.scmd, are not updated

### ISSUE THREAD

**Issue by dominiquelaurain** [sagemathinc/smc#353]
Editing  a tex file in smc...
Previewing PDF is done automatic or with a click on Save button and then Preview button..this is OK.

When saving tex file (button Save), most of the intermediary files (see Files listing) are updated but not the sagetex.sout and sagetex.scmd files (containing processed python code of the inline formulas).

When changing only a formula (something inside dollars and after a sage call)..and using Save..then sout and smd are not updated (you can see, from files modification times)

I have currently the issue for triangletorectangle.tex in my project (project id : 6429970e-5a78-4aee-a6b1-af1e80542481) : changing the \sage{2+2} by  \sage{2+4}...savinng and sout, smd are kept unchanged.

Wanted correction : delete and create again all intermediary files when tex file is saved (automatic or by Save).

**Comment by williamstein** [comment]
I can't replicate this.
