### ISSUE TITLE
Image cache  for the PDF previewer in the tex editor

### ISSUE THREAD

**Issue by dominiquelaurain** [sagemathinc/smc#354]
Using the tex editor...

There is a PDF previewer window which display PDF as a sequence of png files.

The png files (1.png) under https://..../myproject/raw/..../tmp/... cannot be deleted neither by forcing a new PDF previewing nor by deleting temporary files under the Files directory 'with the interface or a terminal command).

Looks like a caching issued, png files being kept either on the remote internet computer and in the image cache of my browser.

URL link of the file (https://..../myproject/raw/..../tmp/... 1.png) can be found using a right mouse click, menu Locate file in browser, displaying the remote filepath.

https://cloud.sagemath.com/projects/6429970e-5a78-4aee-a6b1-af1e80542481/files/Sagecloud%20handling%20of%20out%20and%20infile%20for%20sagetex.tex

Wanted solution : when refreshing the previewing PDF windows, delete the remote png files (in .../raw....) and produce new png files with a time of modification, forcing a download of those files.

**Comment by williamstein** [comment]
Closed in favor of https://github.com/sagemathinc/smc/issues/422
