### ISSUE TITLE
%octave mode in sage worksheets is flaky simply because Sage's own octave.eval is flaky

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#355]
Unfortunately the expect-based Sage interface to octave isn't sufficiently robust at this time. 

You'll have to find another solution until either we figure out how to install an Octave kernel for Jupyter (which might be more robust and you could use instead), or write a new interface between Octave and Sage that is better than the current one. 

Email from Daniel Krenn:
```
On Sun, Jan 3, 2016 at 8:08 AM,  wrote:
I've used SMC when teaching SageMath and Octave. With Octave, the notebook (as the interface to octave) seems to be not as stable as it should be. Here some observations and a bug (all done on the SMC-Notebook):

1) In our first lecture, we (my students) had to do a lot of restarts of the worksheet (and even the project server). Of course, when using a software for the first time, you have to get used to it. They were typing in some simple commands and for sure a lot of syntax errors, but there should not be any need to restart that often.
To be a bit more precise: During 90 minutes of class all of the 15 persons did restart the worksheet at least once; about one half of them frequently. Common reason: evaluation did not work at all anymore; weird results appeared as output (were correct after the restart).

Also when using SageMath in the SMC-notebook, it is more unstable than the sagenb-notebook was (I've really had fewer complaints in recent years when using sagenb for teaching).

Unfortunately I cannot make this all more precise...

2) In the first cell:

%default_mode octave
a = [1 2 3]

does not work (produces a Python syntax error). Only all other cells seem to be switched to octave-mode, but not this first cell. This was/is unexpected. If intended: Why?

3) %default_mode octave

randn(10)

The second cell with randn(10) hangs. randn(9) works.


Best,

Daniel
```

**Comment by haraldschilly** [comment]
about (2): One important thing to know (let's not argue if this is a bug or feature), that each cell that starts with `%auto` or `%default_mode` is in itself always in "Sage" mode. So, please try to evaluate the cell with only `%default_mode octave` in it _first_, and then the other cells.

(3) is definitely a bug with the wrapper in sagemath and should be reported upstream.

**Comment by evelynmitchell** [comment]
I found https://github.com/calysto/octave_kernel 
which is a Jupyter kernel for Octave. Looks to be under active development.

There's also octave magic from Oct2py
https://github.com/blink1073/oct2py

**Comment by billpage** [comment]
I think there are good reasons to want to continue to use Octave from a
Sage worksheet - the primary one being interoperability with other parts of
Sage and in particular Sage graphics. There have been some recent
improvements to the Sage octave interface although some problems remain in
the most recent development version of Sage. On SMC I use an improved
version of octave.py locally:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/octave.py
https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/octave.py.patch

A brief demonstration:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/Krenn.sagews

If there is some interest then I might endure the pain to get these changes
into Sage... unless someone else wants to.

Bill Page.

**Comment by williamstein** [comment]
Bill, you could make your octave interface into a Pip package (which you say "this depends on sage", for now):

http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/

Then I could just do "pip install sage-octave" (say), and it would get installed.  I would also make it so in a sage worksheet your package would be imported and provide the %octave mode for worksheets by defaults.

(All of Sage should be rewritten to be a bunch of pip packages (and semantic versioning), which we assemble regularly together for testing.  But that's a battle for another lifetime.)

**Comment by billpage** [comment]
Well, this sounds interesting but with only the referenced generic
documentation and example, it still seems daunting when the intention is
just to make a single python file easily available.  Would you happen to
have a more specific example for something similar that "depends on sage"?
If I could just copy it, substitute the file and a tweak a few
configuration parameters I think I could manage that.

**Comment by billpage** [comment]
William,

I know absolutely nothing about packaging in Python but I did find another
tutorial:

  http://python-packaging.readthedocs.org/en/latest/minimal.html

that got me, in only a few steps, to something that seems to work. See:

  http://github.com/billpage/sage-octave

I uploaded this to PyPI and can now run

  pip install sage-octave

This works on SMC and creates

  .local/lib/python2.7/site-packages/octave.py

which produces the expected results when I run Sage and do

  sage: from octave import octave

e.g. recovers syntax errors without losing synchronization.

~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath Version 6.10, Release Date: 2015-12-18                    │
│ Enhanced for SageMathCloud.                                        │
└────────────────────────────────────────────────────────────────────┘
sage: from octave import octave
sage: octave("1+1")
 2
sage: octave("x-1=3")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b14a09c062ad> in <module>()
----> 1 octave("x-1=3")

/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/interfaces/interface.pyc
 in __call__(self, x, name)
    241
    242         if isinstance(x, six.string_types):
--> 243             return cls(self, x, name=name)
    244         try:
    245             return self._coerce_from_special_method(x)

/projects/4bc39013-7b65-4a65-9d3d-bec4a4ce4d5a/expect.pyc in __init__
(self, parent, value, is_name, name)
   1303         else:
   1304             try:
-> 1305                 self._name = parent._create(value, name=name)
   1306             # Convert ValueError and RuntimeError to TypeError for
   1307             # coercion to work properly.

/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/interfaces/interface.pyc
 in _create(self, value, name)
    431     def _create(self, value, name=None):
    432         name = self._next_var_name() if name is None else name
--> 433         self.set(name, value)
    434         return name
    435

/projects/4bc39013-7b65-4a65-9d3d-bec4a4ce4d5a/.local/lib/python2.7/site-packages/octave.pyc
 in set(self, var, value)
    404         out = self.eval(cmd)
    405         if out.find("error") != -1 or out.find("Error") != -1:
--> 406             raise TypeError
("Error executing code in Octave\nCODE:\n\t%s\nOctave ERROR:\n\t%s"%(cmd,
 out))
    407
    408     def get(self, var):

TypeError: Error executing code in Octave
CODE:
        sage1=x-1=3;
Octave ERROR:
        parse error:

  invalid left hand side of assignment

>>> sage1=x-1=3;
             ^

sage: octave("1+1")
 2
sage:

--

This also works in a Sage SMC worksheet


https://cloud.sagemath.com/projects/4bc39013-7b65-4a65-9d3d-bec4a4ce4d5a/files/test%20octave.sagews

Is this more or less what you had in mind?

Bill Page.

**Comment by williamstein** [comment]
I included Octave in the SMC version of Sage, which I always merge in when installing Sage on SMC:  

https://github.com/sagemathinc/smc-sage/commit/f524d58c3db07856140f5557aa57cfa21a5895b3

**Comment by williamstein** [comment]
Confirmed that %octave mode is a total disaster. Probably should just remove or rewrite.  Wow.  


This hangs forever!
```
%octave
randn(10)
```

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-084317-octave.sagews

**Comment by williamstein** [comment]
We could easily fix this by just making octave by @DrXyzzy's new jupyter kernel!  See https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-102452-issue238.sagews

**Comment by DrXyzzy** [comment]
Done. Verified in production.
