### ISSUE TITLE
do not regenerate ssh host keys when vm's are recreated.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#356]
Harald's idea:

1. `sudo dpkg-divert --remove /usr/share/google/regenerate-host-keys` which changes the “database” of diversions in `/var/lib/dpkg/diversions`

2. change the `regenerate-host-keys.real-gce-cloud-config` script to abort with exit 0 early (i.e. it doesn’t do anything) and it logs this.

NOTE: the host keys only change when the VM switches between pre-empt and not state.

**Comment by haraldschilly** [comment]
what I did on dev0 for testing, although I do not really have a clear idea what I'm doing:

```
salvus@dev0:/usr/share/google$ cp regenerate-host-keys.real-gce-cloud-config regenerate-host-keys.smc-override

salvus@dev0:/usr/share/google$ sudo dpkg-divert --package gce-cloud-config --remove /usr/share/google/regenerate-host-keys
Removing 'diversion of /usr/share/google/regenerate-host-keys to /usr/share/google/regenerate-host-keys.real-gce-cloud-config by gce-cloud-config'

salvus@dev0:/usr/share/google$ sudo dpkg-divert --local --divert /usr/share/google/regenerate-host-keys --add /usr/share/google/regenerate-host-keys.smc-override
Adding 'local diversion of /usr/share/google/regenerate-host-keys.smc-override to /usr/share/google/regenerate-host-keys'
```

**Comment by williamstein** [comment]
Whatever you changed on dev0 has no effect.  I tried completely deleting ~/.ssh/known_hosts changed machine, logged in, changed machine, and logged in again and got this:  ARGH.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:Z/6nAAYke4A5I/Ezfcu5iZ7ercCDo2GdfYfueFzltqc.
Please contact your system administrator.
Add correct host key in /projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/.ssh/known_hosts:1
  remove with:
  ssh-keygen -f "/projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/.ssh/known_hosts" -R dev0
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.

```

**Comment by haraldschilly** [comment]
next try:

I'm chaging the file `regenerate-host-keys.real-gce-cloud-config` but I let the diversion pointing to `regenerate-host-keys.smc-override` (which does contain the original content).

Mabye that's how diversions are meant: when a package requests to install at path X, actually install it to the diverted location – and now the diverted location is no longer the actual location.

**Comment by haraldschilly** [comment]
next attempt:

write our own /etc/cloud/cloud.cfg.d/99-smc.cfg file and fill in all our keys there. according to http://cloudinit.readthedocs.org/en/latest/topics/examples.html#configure-instances-ssh-keys ... 

only caveat, there is on key (ed<and a number>) that's not mentioned in the config. maybe just disable it at all?

**Comment by haraldschilly** [comment]
my initial write of an ssh host keys freeze script is here: f57fcd90a96085c743e5dbb1ee8117dabfb2ce90

not 100% sure if that works, but it does create that config file for cloud-init in a way that can be properly parsed by it.

**Comment by williamstein** [comment]
I think you already solved this.
