### ISSUE TITLE
raw_input in sage worksheets does not work sufficiently robustly

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#358]
See [this SO question](http://stackoverflow.com/questions/34621146/double-input-and-extra-letter-in-list-in-sagemath) where the doubling nature of `raw_input` becomes clear.  I assume this is not desired?

Related: #78

**Comment by williamstein** [comment]
Simple example:
```
age = int(raw_input('Enter your age: '))
if age < 18:
    print('You may vote in {difference} years.'.format(difference = 18-age))
else:
    print('You are allowed to vote.')
```

**Comment by williamstein** [comment]
Marking hard since the coordination between frontend and backend to get this robust is really tricky.

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/78

**Comment by williamstein** [comment]
heh in that comment I said this is NOT fixed by that commit!

**Comment by williamstein** [comment]
process: got angry/curious about this while merging PR https://github.com/sagemathinc/smc/pull/1799
