### ISSUE TITLE
collaborator search email comma issue (serious)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#36]
It is a bug: put there
`wstein@gmail.com`
and it will suggest just me, but add a comma
novoselt@gmail.com,
and I will be in the end of a relatively long list starting with
"Lauren Sampson".

**Comment by williamstein** [comment]
I think it is searching for two things:

   novoselt@gmail.com

and

   [nothing]

The nothing search matches everything, but there's a limit on how many
results are returned.   Instead the fix would be to ignore the empty
search.

**Comment by williamstein** [comment]
This is closely related to #34

**Comment by johnjeng** [comment]
Having trouble reproducing this bug.

I wonder if it's been fixed outside of  exports.parse_user_search found in src/smc-util/misc.coffee

**Comment by williamstein** [comment]
works fine now.
