### ISSUE TITLE
make it so the find code for getting a list of all directories works even if there is a permissions error

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#361]
For example a user hit this when adding an assignment.

```
I cannot see the differents folder to add.   The entire comment:

Error executing command 'find' with args '.,-xdev,-type,d,-iname,**' -- 
command 'find' (args=. -xdev -type d -iname **) exited with nonzero code 
1 -- stderr='find: 
`./.....48': 
Permission denied ', . ./.gnome2 ./.Scilab ./.Scilab/scilab-5.5.1 
```

This should be easy to fix -- ignore the permission denied trees from find.  A user hit this due to another issue with homework collection, which I fixed by chmod'ing all their files -- it has to do with maybe rsync once getting interrupted.. Not sure.    But we may as well make this use of "find" more robust.

**Comment by DrXyzzy** [comment]
Here are steps to reproduce the problem and the proposed fix (in step 4) to the find command:

1. Open .term and do the following. The find command has the options used by the UI:

    ```
    mkdir -p A/B/C/D A/E/F/G
    find A -xdev -type d -iname '*'
    open test361.course
    ```
1. In the UI, select `Assignments`, put cursor in search bar at right "Add assignment by folder name..." 
1. Hit Enter and see correct indented list of directories A thru G.
1. Back in .term session, break things:

    ```
    chmod 000 A/B A/E/F/G
    find A -xdev -type d -iname '*'  <== get permission denied errors
    # here is the improved find command returning 0 exit status
    find A -xdev ! -readable -prune -o -type d -iname '*' -readable -print
    echo $?
    ```
1. Go back to UI for test361.course, click `Assignments` again, hit Enter in search area, and see that assignment search no longer fills with directory choices.
1. Cleanup work area:

    ```
    chmod 750 A/B A/E/F/G
    ```
