### ISSUE TITLE
everything breaks horribly if you modify (with vi in the terminal, say) a .sage-chat chatroom file to stupidly break the JSON.  It should fail gracefully.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#363]

**Comment by johnjeng** [comment]
Here is my quick solution for this.
https://github.com/sagemathinc/smc/compare/issues/363

Pros:
Does not break random shit horribly.

Cons:
The chat still "opens" but you can't actually do anything. It's probably confusing.
The user isn't given any option to fix anything.
The user is told that the json is broken. Might also cause confusion.

**Comment by williamstein** [comment]
this seems fixed now; not necessarily awesome but doesn't totally flake.
