### ISSUE TITLE
Student Quota sharing, decimals, and reports sigfigs

### ISSUE THREAD

**Issue by bvoight** [sagemathinc/smc#366]
Hi there -
When allocating shares/quotas to students in a course, you have to specify a fraction (multiplied by the number of students) to share out computational resources that you have paid for.

While you can specify fractions with > 1 sigfig (e.g. 0.03486), and this is calculated correctly, after you save, the number is listed as "zero" (presumably, because it is rounding to 1 sig fig), so 0.03486 rounds down to 'zero', which is annoying because it looks like you have made no allocations when in fact you have made allocations

**Comment by bvoight** [comment]
Also, truncation to 1 decimal also comes up in User settings - upgrades tab - "Upgrades you have applied to Projects"

**Comment by williamstein** [comment]
We've changed truncation to 2 decimals, rather than one.  Also, parsing fractions now works.  Now live.
