### ISSUE TITLE
pre-warm a course: have a button that starts every project in a course running

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#368]
This would be useful for an instructor to do right before a class lab starts, so that the projects are all up and running when the students open their computers.  Easy to implement.

**Comment by williamstein** [comment]
To make a project start:

     smc.redux.getProjectActions('4cc3a978-d509-434b-a083-64738ac63b03').set_directory_files('',true,false)

However, in project_store.coffee you should make a function start_project (in actions) that right now calls set_directory_files, but later does something else.  

Look at this:

        set_all_student_project_titles: (title) =>
            actions = redux.getActions('projects')
            get_store()?.get_students().map (student, student_id) =>
                student_project_id = student.get('project_id')

**Comment by williamstein** [comment]
I also talked to @rolles about this...

**Comment by johnjeng** [comment]
In staging at #427

**Comment by johnjeng** [comment]
Was fixed at #427.
