### ISSUE TITLE
course directory assignment search (should be easy)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#375]
> Yesterday, we made an assignment called 02_UNIX-I_assignment, and tried to assign it after we assigned 02_UNIX-I_prelab. However, it wouldn't show up when we searched for folders to assign until we added another 0 onto the beginning of the name to make 002_UNIX-I_assignment. I wonder if this is a bug where if 2 file names are too similar, it doesn't treat them correctly.

Reported by Katie Siewert

**Comment by johnjeng** [comment]
Could not replicate this problem.
