### ISSUE TITLE
README doesn't mention nodejs-legacy is needed to build

### ISSUE THREAD

**Issue by sidgairo18** [sagemathinc/smc#377]

**Comment by williamstein** [comment]
What is nodejs-legacy?

**Comment by sidgairo18** [comment]
When I ran npm run install-all to build on Ubuntu I was getting certain errors
which i then read about could be solved using node-js legacy.
Some issue with Node.js
http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

**Comment by williamstein** [comment]
I think one definitely shouldn't be using any Node.js ubuntu packages at
all.   Install the latest Node.js from https://nodejs.org/en/

William

On Sun, Jan 17, 2016 at 10:29 AM, Siddhartha Gairola <
notifications@github.com> wrote:

> When I ran npm run install-all to build on Ubuntu I was getting certain
> errors
> which i then read about could be solved using node-js legacy.
> Some issue with Node.js
>
> http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/377#issuecomment-172361712>.
>



-- 
William (http://wstein.org)
