### ISSUE TITLE
Suggestion: new button, called "Duplicate", in "File" operations

### ISSUE THREAD

**Issue by jpedroan** [sagemathinc/smc#378]
I see buttons: Download, Delete, Rename, Move, Copy, Share.

I was used to do "copy/paste" of a file, using the keyboard and producing "File (copy).tex", for example.  Then rename it and this is fast.

In SMC, one has to do "Copy" but to another directory,  then rename the file,  and finally move it back.
It is not possible to do "Save As"   also.

Currently, as far as I know, to solve this
* I have to open a terminal and do "cp File.tex to OtherFile,tex".
* get inside the directory of the file and use the top-right command line to write the "cp File.tex to OtherFile,tex"
* all of them need one step more that "copy/paste" ou "Save As".

**Comment by williamstein** [comment]
@rolles -- you might want to do this.

**Comment by williamstein** [comment]
Making bug since this is a basic function whose absence constantly confuses and frustrates people.

**Comment by williamstein** [comment]
It's been done.
