### ISSUE TITLE
parallelization

### ISSUE THREAD

**Issue by InonS** [sagemathinc/smc#38]
Is it even supported for the free tier? My CPU quota reads 1 (physical and virtual), so does that mean I can't (shouldn't anyway) use [parallelization](https://docs.python.org/3/library/concurrency.html) (multithreading, multiprocessing)?

@see: Web resources
http://ask.sagemath.org/question/8272/whenhow-to-use-parallel/
http://ask.sagemath.org/question/7578/what-are-my-best-options-for-taking-advantage-of-multiple-cores/?answer=11394#post-id-11394
https://groups.google.com/forum/#!msg/sage-cloud/wpIBtHKEgGI/P5vzp62z0Q0J
https://wiki.python.org/moin/ParallelProcessing

**Comment by williamstein** [comment]
Free projects may only use one cpu at present.   

This seems like a support question rather than an issue.
