### ISSUE TITLE
Button to upgrade a project to be a Sage developer project

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#380]
Quoting William Stein's idea from
https://groups.google.com/d/msg/sage-cloud/SrcpVrsoZg4/bNs80x1TBVkJ
> My *plan* which I haven't had the time to implement, has been to havea button in project settings to upgrade a project to be a "Sage Developer project".  This would start with signing some sort of little contract agreeing that you're going to use the project to do sage development.  It would then increase the disk quota, ram quota, and copy the latest sage beta into place  -- it would also set something somewhere, so that us SMC admins can spot check these projects.  There might also be a confirm feature for new users or a limit of one devel project per users (not sure).

**Comment by williamstein** [comment]
Closing because we only get maybe one request per month and it is easy to handle manually.  Doing otherwise could be very dangerous.
