### ISSUE TITLE
change an error message when opening a project you do not have access to (e.g., often due to not being logged in)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#381]
Change the error message: "project with id '2c...60' is not public" to
 "project with id '2c...60' is not public; this error happens when you aren't logged in or logged in with the wrong account. Please try refreshing your browser and check which account you're logged in under. Perhaps somebody needs to add you as a collaborator to a project. If you're confused, email help@sagemath.com."

**Comment by haraldschilly** [comment]
I've worked on this in branch [access-error-msg](/sagemathinc/smc/tree/access-error-msg) ... the only controversial thing is that I'm allowing to use some html in "Alert" to make the message easier to read. That shouldn't be an issue, though.

**Comment by haraldschilly** [comment]
handing back to @johnjeng to review this or redo it properly :-)

**Comment by williamstein** [comment]
> That shouldn't be an issue, though.

Sorry, but I really don't like that code.   (1) using dangerous unsafe html when not needed, which makes react less effective (especially thinking longrun) and potentially less secure, (2) throwing in a database query on the backend, when it isn't needed, which would make a DOS attack even easier (obviously there's a lot of this, but still), (3) it assumes the frontend that displays the error message can display html; this will cease to be the case when we have either an API or react native clients, both of which we could have pretty soon.

How about instead generating the error message on the front end as a react component.  The error happens in response to a specific request for a path in a specific project, so we could just change the backend from 

    opts.cb("path '#{opts.path}' of project with id '#{opts.project_id}' is not public") 

to

   opts.cb("not_public")   # exact error message used by client

in both cases.  Then the frontend generates the error react component to display the error.

**Comment by haraldschilly** [comment]
ah yes, I agree, that's why I did put it on a branch for discussion. In essence, a proper implementation would be to generate an object on the hub, slightly structured, that is then passed into the webapp. It's just that this "Alert" mechanism simply serializes any objects to a string, so that would need a bit of special-case handling to generate such a better error alert when there is a suitable richer object.

**Comment by johnjeng** [comment]
Here's my fix on [issues/381](https://github.com/sagemathinc/smc/compare/issues/381). 
However, the client probably should just receive a message that the project/file isn't public and the client would then generate an appropriate error message based on context.

1) No dangerous unsafe html.
2) No database query.
3) Is just a string.

Can I get an example of an easy way to trigger this ErrorDisplay in r_misc.cjsx vs the one found in alerts.coffee? 
Am I correct in saying that ErrorDisplay is an inline alert and alerts.coffee is the pop-up in the upper right hand corner?

**Comment by williamstein** [comment]
This seems good for a "quick fix".

> Can I get an example of an easy way to trigger this ErrorDisplay in r_misc.cjsx vs the one found in alerts.coffee? 

Many things in account settings trigger it; e.g., try changing your password and typing the old one incorrectly.

> Am I correct in saying...

Yes.

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/pull/872

**Comment by johnjeng** [comment]
@timothyclemansinsea Fixed this right?

**Comment by williamstein** [comment]
Closing since I think this is fixed.
