### ISSUE TITLE
Automate Julia upgrades/installs (write a Python script)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#382]
Evidently the Julia devs don't have the resources to provide an ubuntu package anymore.  That's possible unfortunate, since it means that for us upgrading Julia each time there is a new release might go from taking 0 seconds to taking 15-30minutes.  Point of this ticket: write a Python script to scrape the website http://julialang.org/downloads/, figure out what the latest generic binary name is, download it, unpack it, put files in the right places, etc., and run that script periodically whenever Julia has a new release.

**Comment by haraldschilly** [comment]
scrapping their website could look like this:

```python
def latest_julia_binary_url():
    import bs4
    import requests
    jdl = bs4.BeautifulSoup(requests.get('http://julialang.org/downloads/').text)
    for a in jdl.select("table.downloads a"):
        url = a.attrs["href"]
        if 'bin/linux/x64' in url and '64' in a.text:
            return url
```

although I've no idea how stable this is. looks like hand-written might change. Pulling the source code from the github repository and looking for newer release-* tags might work better – although then we have to compile the code.

**Comment by williamstein** [comment]
Harald, didn't you already do this by now?

**Comment by haraldschilly** [comment]
Hmm, I didn't do this, but I'm surprised about the initial statement that there is no ubuntu binary build? I always used it and it looks fine to me?

In particular, https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases has the most recent version, and the most recent update for 0.5.0 was just 3 days ago (Sept. 20, today is the 23rd). Hence I assume that PPA is alive and well.

The actual issues were about installing packages globally in a sane way, but I know how to do this and that works, too. Hence I keep this closed.

**Comment by williamstein** [comment]
> there is no ubuntu binary build? I always used it and it looks fine to me?

I made that comment nearly a year ago -- it could have been true then.
