### ISSUE TITLE
In the +New page, if you type "foo/" then click "Folder" nothing happens -- no error, nothing.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#386]
What should happen: it just works, making a folder without the slash at the end.

Or, maybe it shows an error.  But not **nothing**.

**Comment by johnjeng** [comment]
Quick fix at [issues/386](https://github.com/sagemathinc/smc/tree/issues/386). 

This does raise the question whether or not we want the user to be able to make a series of nested folders by inputting "foo/bar/baz/deeply-nested-folder/" where if each of the folders don't exist, then they will be created.

**Comment by williamstein** [comment]
Also another idea might be that typing foo/ and hitting enter should create
a directory instead of a file.  Right now what you did would not behave
that way... But of course what you did is (literally) better than nothing.

On Monday, January 25, 2016, John Jeng <notifications@github.com> wrote:

> Quick fix at issues/386
> <https://github.com/sagemathinc/smc/tree/issues/386>.
>
> This does raise the question whether or not we want the user to be able to
> make a series of nested folders by inputting
> "foo/bar/baz/deeply-nested-folder/" where if each of the folders don't
> exist, then they will be created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/386#issuecomment-174728875>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by johnjeng** [comment]
Implemented with most recent [commit](https://github.com/sagemathinc/smc/compare/28d107d361e237ddd915682107a6556b4e0dcfd0...issues/386) on [issues/386](https://github.com/sagemathinc/smc/compare/issues/386).

**Comment by williamstein** [comment]
fixed
