### ISSUE TITLE
make it so putting the mouse over the project tab shows the full project title in a popup

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#387]
For consistency with files, and to help me...

**Comment by haraldschilly** [comment]
I've added this [in that branch](/sagemathinc/smc/tree/top-navbar-tip), and since this "Tip" has a title, I've also added the start of the ID.

**Comment by williamstein** [comment]
Add added a patch to your branch so that the Tip title... contains the project title, and the description is the description.  
<img width="748" alt="screen shot 2016-01-22 at 6 01 02 am" src="https://cloud.githubusercontent.com/assets/1276278/12512490/8c49008c-c0cd-11e5-81ad-58c96177049a.png">

**Comment by haraldschilly** [comment]
yes, that makes more sense! it's merge and live.
