### ISSUE TITLE
"Pushout" folders for students

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#393]
I use a single assignment to "pushout" materials (mostly demonstration worksheets) to my classes all semester long.  It works well. But I think long-term a separate mechanism would be more obvious to new users and more convenient for everybody, especially with automatic sync.

* Same idea, but no due date, no collection/return mechanisms
* Make student copies read-only, so they are forced to make a copy for experimentation
* Automatic sync as an option - i.e. when instructor adds/edits a file, it **automatically** ends up in student's view.  Or at a minimum, one-click sync with no warnings (due to read-only setup)

Myself, I'd call them "Materials" (in contrast to "Assignments") for the tab, etc

**Comment by williamstein** [comment]
I definitely agree that I should add this functionality.

Note -- for my course this quarter I made a folder

  lectures

with subfolders

  lectures/date1
  lectures/date2
  ..

I then add lectures/date1 as an "assignment" and push it out.  It appears
for the student as a new folder "lectures/date1".   Each time I do this, I
avoid possibly copying over any changes the students have made to previous
lectures.  They also clearly see the new folder appearing in lectures/

On Sat, Jan 23, 2016 at 2:22 PM, Rob Beezer <notifications@github.com>
wrote:

> I use a single assignment to "pushout" materials (mostly demonstration
> worksheets) to my classes all semester long. It works well. But I think
> long-term a separate mechanism would be more obvious to new users and more
> convenient for everybody, especially with automatic sync.
>
>    - Same idea, but no due date, no collection/return mechanisms
>    - Make student copies read-only, so they are forced to make a copy for
>    experimentation
>    - Automatic sync as an option - i.e. when instructor adds/edits a
>    file, it *automatically* ends up in student's view. Or at a minimum,
>    one-click sync with no warnings (due to read-only setup)
>
> Myself, I'd call them "Materials" (in contrast to "Assignments") for the
> tab, etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/393>.
>



-- 
William (http://wstein.org)

**Comment by rbeezer** [comment]
I'm not that clever.  I made "demos" an assignment, and then have "latex" and 
"sage" as subfolders.  Next time. ;-)

Thanks for the heads-up.  I *will* do an updated blog post real soon, and will 
include this folder-by-folder approach.

Rob

**Comment by rbeezer** [comment]
Implementation suggestions:

 * New tab in a course file for "materials", "distribution", "stuff", ?.
 * Instructor adds folders, like creating an assignment.
 * Students see folders in their view of the course.  It is read-only for the student.
 * Changes made by an instructor (add files, change files, delete files, etc) are reflected automatically in student view.
 * No due date, no assigning, no collecting, no warnings about overwriting student work.

**Comment by rbeezer** [comment]
Rationale:

I do not really need to put *anything* in my assignment folders anymore - the students find the Sage exercises in the textbook and they know how to make a worksheet in the assignment folder.  They just name it "GRADE-ME.sagews" or similar (I don't care about the name because I don't have to manage it, SMC does that for me).

It'd be easier for me to split the "course material distribution" functionality from the "assign/collect/grade/return" functionality.  And I think it would be more obvious for newcomers.  And easier/less-inimidating to get started with the ease-of-distributing-course-materials feature without navigating the assignment mechanism.

I know my first whacks at Sage were in-class demos that I then wanted to make available to students (Sage NB files as links off course web page).  You'd provide an easy entry path for more of the toe-in-the-water types with easy distribution, I think.

**Comment by johnjeng** [comment]
This is in for review at #680. Per @williamstein's request, they are *not* read only so you do get a warning about overwriting student work.
