### ISSUE TITLE
if add/remove collaborator from a project, update any open course collaborators

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#398]

**Comment by johnsonlab** [comment]
Thanks - this will help classes like ours get started!

**Comment by williamstein** [comment]
I should note that a workaround **right now** is to simply close and open the .course file.   The update of collaborators gets triggered right now whenever the course file is opened.

**Comment by williamstein** [comment]
There's a lot that could be done here, but let's make this one single concrete task.  Namely:

1. When initializing a .course file (actions and store), get the projects store and add an `on('change', ...)` event listener, which -- whenever the projects changes, checks if the collaborators on the project that contains the course have changed.  If so, it calls the action `configure_all_projects`.

**Comment by williamstein** [comment]
Labeled both bug and enhancement.  Bug since it is really confusing to users...

**Comment by williamstein** [comment]
This should be easy to implement - about 10-15 lines of code.  On opening the file, put a listener on the projects store, and when the collaborators on this project change, re-run the course setup.  On closing the file, remove the listener.
