### ISSUE TITLE
preparser(False) is ignored in Sage worksheets right now.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#399]

**Comment by DrXyzzy** [comment]
There is a function `preparse()` imported in sagews from sage/repl/preparse.py, but it takes a string of code as first positional parameter. Changing title of this issue to `preparser(False) is ignored...`.

For more info see:
- preparse(False) (still) not working  
http://ask.sagemath.org/question/24696/preparsefalse-still-not-working/
- Last paragraph in selected section of sage docs here:  
http://doc.sagemath.org/html/en/faq/faq-usage.html#i-have-type-issues-using-scipy-cvxopt-or-numpy-from-sage

**Comment by DrXyzzy** [comment]
Sage function `preparser()` sets Sage global `_do_preparse`. This variable is ignored in Sage worksheet processing including preparsing, hence `preparser(False)` is ignored.

**Comment by DrXyzzy** [comment]
Sage FAQ typo `preparse` should also be corrected. I'm opening a trac ticket for that.

**Comment by DrXyzzy** [comment]
Done.
