### ISSUE TITLE
show does not work for LatexExpr

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/smc#40]
For example
`show(latex(x^2))`
in SageNB results in typeset `x^2`, while cloud shows LaTeX code `x^{2}`. Same for manually constructed expressions like
`show(LatexExpr("x^2"))`

This is a problem for functions that return `LatexExpr` with the idea of showing their output typeset when `typeset_mode(True)`, e.g. http://trac.sagemath.org/ticket/18852

**Comment by williamstein** [comment]
One approach could be to handle a case involving show and types in sage_salvus.py (?)
