### ISSUE TITLE
How to get python3 kernel?

### ISSUE THREAD

**Issue by dwintergruen** [sagemathinc/smc#408]
I don't understand how to enable python3 support, when installing the cloud? Do I need to build sage with SAGE_PYTHON3=yes?

**Comment by haraldschilly** [comment]
what exactly do you want to do? SageMath does not run with Python 3.

**Comment by dwintergruen** [comment]
I understood that I can setup SageMathCloud so that the Notebook can also use python3 as an option for the Kernel. I don’t really understand how to configure my settings of the cloud. Following the instructions I manage to
get everthing up, but under Kernels I only find python 2 and sage.

Cheers
Dirk

**Comment by haraldschilly** [comment]
Well, now I start to understand. You are running SMC locally on your computer? And with "Notebook", you mean the "Jupyter Notebook"? If so, you have to install all those kernels on your own. We don't have instructions for that and you have to figure that out depending on your own environment! (e.g. where the executable path is, where the libraries are, which environment variables to set, is it necessary to write a thin shell script as a wrapper, etc.). You can find our kernel setup in `/usr/local/share/jupyter/kernels` on SMC online.

**Comment by dwintergruen** [comment]
I got it, works now.
Great! Thank you very much.
