### ISSUE TITLE
octave jupyter kernel in SMC: 'ascii' codec can't encode character u'\u22c5' in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#415]
A user reports here http://ask.sagemath.org/question/32507/error-when-perform-symbolic-calculation-in-octave-of-sage/ that when using the Octave Jupyter kernel in SageMathCloud with this input:

```
pkg load symbolic
syms x
f = sin(x)^2;
diff(f)
```

they get the error in the description above.    I easily replicated this problem:  https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-02-09-185227-octave-symbolic.html

Do other people see this?   If so, any suggestions.  If not, want any more details (I run SageMathCloud).

--

Note: I reported this on the octave jupyter kernel page (https://github.com/Calysto/octave_kernel/issues/37), and they couldn't reproduce it. So it's probably some special problem to us, not something general.

**Comment by PaulDebus** [comment]
I can reproduce the issue easily:
    ```X=sym("x",[2,1])```
Looks like an encoding issue to me... but sadly no more idea.

**Comment by billpage** [comment]
It might be worth noting that there is no problem when accessing
Octave from a Sage worksheet:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/octave-symbolic.sagews

**Comment by haraldschilly** [comment]
#953 is probably the same issue, it's simply triggered by `printf("ä")`.

**Comment by haraldschilly** [comment]
reported it here: https://github.com/Calysto/octave_kernel/issues/46
