### ISSUE TITLE
Python urllib2 not working

### ISSUE THREAD

**Issue by iScienceLuvr** [sagemathinc/smc#416]
I tried to run this code on my project. It is in a python file and I ran it using the terminal of course:

    import urllib2
    response = urllib2.urlopen('http://python.org/')
    html = response.read()
    print html

I get an error message:
`AttributeError: 'module' object has no attribute 'urlopen'`

Why is this the case? I am using Python 2 so it can't be due to problems with Python 3. Therefore, I think it is a bug.

**Comment by williamstein** [comment]
I can't replicate this.   **EXACTLY** how did you "I ran it using the terminal of course:".

**Comment by iScienceLuvr** [comment]
@williamstein "python urllib.py" where urllib.py is where the code is contained.

**Comment by williamstein** [comment]
Do this: `mv urllib.py myurllib.py; rm urllib.pyc`

You are shadowing the python standard library module named "urllib".
