### ISSUE TITLE
Easy copy to clipboard for output

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#420]
I use SMC a lot to generate HTML/JSON to paste into my web stuff. Right now I find it hard to do a select all of the output for one cell to do a copy to clipboard.

**Comment by williamstein** [comment]
Strongly agree.     Solving this can be a little tricky due to browser clipboard security issues...

**Comment by timothyclemansinsea** [comment]
What about a quick way to do select all of the output?

**Comment by williamstein** [comment]
@haraldschilly fixed this already via some restyling.
