### ISSUE TITLE
urllib2 not working!

### ISSUE THREAD

**Issue by iScienceLuvr** [sagemathinc/smc#421]
I am using the code in #416 (but with myurllib.py as the name) and now I get this error:

`urlopen error [Errno 99] Cannot assign requested address`

It takes long time to run so it is doing something but the code finally gives this error. Why? Could it be a bug? It usually has something to do with the socket but I am not sure how to fix it.

**Comment by haraldschilly** [comment]
@iScienceLuvr do you have network access?

Please send us a link to your project file to help@sagemath.com

**Comment by iScienceLuvr** [comment]
@haraldschilly How do I determine if I have network access? I thought all of them have network access anyway.

**Comment by haraldschilly** [comment]
@iScienceLuvr go to the project settings and look for network access. usually, it's disabled.

**Comment by williamstein** [comment]
Look in the settings tab:

<img width="469" alt="screen shot 2016-02-15 at 12 11 42 pm" src="https://cloud.githubusercontent.com/assets/1276278/13059191/4fc63b0c-d3dd-11e5-84f5-f75371ebf2c2.png">

Projects do not have network access by default, because allowing random people to create shell accounts with network access is begging for trouble.  We used to allow this (up until about a month ago), until some jerk launched a DDOS attack on Turkey from SMC, which caused our host to shut us down, and took all SMC offline for several hours.   If we allow network access by default, any jerk can instantly get us shut down.  Not good.

**Comment by iScienceLuvr** [comment]
@williamstein it seems we have to have a paid subscription for network access... is this true? Is there a way to overcome this?

**Comment by iScienceLuvr** [comment]
@haraldschilly @williamstein have you seen the message?

**Comment by iScienceLuvr** [comment]
@haraldschilly @williamstein have you seeny message? It is really sad that we need to pay for internet connection. I might have to move one of my projects because of this...

**Comment by williamstein** [comment]
If you promise not to launch attacks and send me a link to the project I'll
add network access for free.

William

On Thursday, February 18, 2016, iScienceLuvr <notifications@github.com>
wrote:

> @haraldschilly <https://github.com/haraldschilly> @williamstein
> <https://github.com/williamstein> have you seeny message? It is really
> sad that we need to pay for internet connection. I might have to move one
> of my projects because of this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/421#issuecomment-186022196>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by iScienceLuvr** [comment]
@williamstein Can I post the link here?

**Comment by williamstein** [comment]
On Fri, Feb 26, 2016 at 12:08 PM, iScienceLuvr <notifications@github.com>
wrote:

> @williamstein <https://github.com/williamstein> Can I post the link here?
>

Sure, or email help@sagemath.com referencing this conversation and url.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/421#issuecomment-189460895>.
>



-- 
William (http://wstein.org)

**Comment by iScienceLuvr** [comment]
@williamstein https://cloud.sagemath.com/#projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/files/

**Comment by williamstein** [comment]
Done.   I gave you a free disk space upgrade too, since I noticed you were
near the quota.  Enjoy.

William

On Fri, Feb 26, 2016 at 12:23 PM, iScienceLuvr <notifications@github.com>
wrote:

> @williamstein <https://github.com/williamstein>
> https://cloud.sagemath.com/#projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/files/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/421#issuecomment-189467964>.
>



-- 
William (http://wstein.org)

**Comment by iScienceLuvr** [comment]
@williamstein thank you very much!!!
