### ISSUE TITLE
Font problems in Firefox

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/smc#43]
Our computer labs have font issues with SMC in Firefox - I am attaching a screenshot with some warnings about encoding in case that is the issue. I also have font problems with SageMathCell in these labs, so maybe the labs are just messed up. Chrome works fine. On the other hand, other people were reporting similar font issues with SageMathCell, so even if it is a misconfiguration it may be common enough that a workaround would be useful.

![image](https://cloud.githubusercontent.com/assets/1993227/8558532/0b0ca50c-24c2-11e5-8cb4-8d9267ddb6d7.png)

**Comment by haraldschilly** [comment]
On Wed, Jul 8, 2015 at 12:07 AM, Andrey Novoseltsev <
notifications@github.com> wrote:

> Our computer labs have font issues with SMC in Firefox -


​For me, it looks like there is a general problem with the font setup. Is
there some setting active, to forcefully specify which font to use?

​​


> I am attaching a screenshot with some warnings about encoding in case that
> is the issue.


​No, that's not a real iss​ue, since it reloads it (it's caused because of
the overly long license text at the top of the html page.)

**Comment by novoselt** [comment]
On Wed, Jul 8, 2015 at 4:13 AM, Harald Schilly <notifications@github.com>
wrote:

> On Wed, Jul 8, 2015 at 12:07 AM, Andrey Novoseltsev <
> notifications@github.com> wrote:
>
> > Our computer labs have font issues with SMC in Firefox -
>
>
> ​For me, it looks like there is a general problem with the font setup. Is
> there some setting active, to forcefully specify which font to use?
>

I have no idea - I didn't set them up ;-) If you tell me what (and how) to
check, I can do it.

**Comment by williamstein** [comment]
@novoselt -- still a problem?

**Comment by novoselt** [comment]
Probably - I can't easily check it, but recently in the same labs our university site had similar issues. So I am inclined to blame either our IT or Microsoft.
