### ISSUE TITLE
+New dropdown --> prompt user for filename if nothing typed in the search box to the left

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#431]
> The only minor suggestion that I might make has to do with what happens if I create a new file using the drop down from the New button.  If I create a Python file by selecting Python from the drop-down list, I get a file automatically named based on the current date.  This is rarely (actually never) what I want, and so I then have to go back to the File Manager and rename the file.    In my opinion, it would be better if the system prompts me for a name when I choose an option from the file type drop-down, and then automatically adds the appropriate extension and creates the right type of file.

Requested by: Ryan McFall

Temporary workaround: type the filename in the search box to the left of the New dropdown, and it will use that.

Longterm solution: if nothing there, make a box appear to enter the filename.

**Comment by johnjeng** [comment]
This and other improvements in development at #468.
