### ISSUE TITLE
3D colormap does not work

### ISSUE THREAD

**Issue by fchapoton** [sagemathinc/smc#44]
This is supposed to plot a colored surface:
```
from sage.plot.plot3d.parametric_surface import ParametricSurface
def g(x,y): return x, y, - x**2 + y**2
def c(x,y): return sin((x-y/2)*y/4)**2
cm = colormaps.gist_rainbow
P = ParametricSurface(g, (srange(-10,10,0.1), srange(-5,5.0,0.1)), color=(c,cm))
P
```
but the colors do not appear in the cloud. They work in jmol in the old notebook.

**Comment by williamstein** [comment]
This could be a very hard deep dive into THREE.js...

**Comment by fchapoton** [comment]
I was in part responsible for the implementation of this feature in sage. As far as I remember,
this was not implemented for the .obj format, which may be the cause of the problem, if this is
the format used to interface with three.js in the cloud.

**Comment by williamstein** [comment]
Yes, SMC does use the .obj format as the very first step of rendering surfaces.   See the course in SMC:

  https://github.com/sagemathinc/smc/blob/master/src/smc_sagews/smc_sagews/graphics.py#L320

The file I linked to above is basically responsible for turning a Sage 3d scene into a custom (but clean) python dict, which can be JSON's, passed to the browser, and rendered using some javascript and three.js code.   Please improve it!

**Comment by fchapoton** [comment]
I do not see an easy way to add the triangle colors to the .obj file format.
It seems to me that it would be much better to use (instead of the .obj) the .json provided directly by IndexFaceSet:

            sage: var('x,y')
            sage: P = plot3d(x^2-y^2, (x, -2, 2), (y, -2, 2))
            sage: s = P.json_repr(P.default_render_params())

This json output is made so that it can handle the colored faces. I can provide an example upon request.

What puzzles me is what happen next with the current custom json object obtained from the .obj representation. Do you transform it again so that it can be handled by three.js ?

**Comment by williamstein** [comment]
On Thu, Dec 31, 2015 at 8:44 AM, fchapoton <notifications@github.com> wrote:

> I do not see an easy way to add the triangle colors to the .obj file
> format.
> It seems to me that it would be much better to use (instead of the .obj)
> the .json provided directly by IndexFaceSet:
>
>         sage: var('x,y')
>         sage: P = plot3d(x^2-y^2, (x, -2, 2), (y, -2, 2))
>         sage: s = P.json_repr(P.default_render_params())
>
> This json output is made so that it can handle the colored faces. I can
> provide an example upon request.
>
> What puzzles me is what happen next with the current custom json object
> obtained from the .obj representation. Do you transform it again so that it
> can be handled by three.js ?
>
It is used as input to a browser-based rendered, which happens to be
implemented using THREE.js.  See

    https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/3d.coffee

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/44#issuecomment-168219934>.
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
fixed
