### ISSUE TITLE
python hangs when importing from petsc4py

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#45]
Reported by: Randy Leveque

Details:

I tracked down the problem with our Clawpack plotting...  the following hangs:

from petsc4py import PETSc

In fact it hangs even if this is in a try-except block, although
petsc4py itself imports ok:

```
In [1]: import petsc4py

In [2]: petsc4py
Out[2]: <module 'petsc4py' from
'/usr/lib/pymodules/python2.7/petsc4py/__init__.pyc'>

In [3]: try:
   ...:     from petsc4py import PETSc
   ...: except:
   ...:     print "cannot import"
   ...:
 <hangs>
```

This isn't essential to what we're doing since I'm not using petsc4py
and so I can easily remove this try-except block from the code, but
maybe indicates that there's something wrong with the version of
petsc4py installed on SMC?  I don't know if anyone else might be using
this, so perhaps not high priority to fix.

 - Randy

**Comment by ketch** [comment]
@dalcinl Any idea what might cause this?

**Comment by williamstein** [comment]
No longer supported.
