### ISSUE TITLE
install java 8

### ISSUE THREAD

**Issue by iScienceLuvr** [sagemathinc/smc#454]
I have been trying to install java 8 using this tutorial:

http://www.tecmint.com/install-java-jdk-jre-in-linux/

However, I cannot do this:

`mkdir /opt/java && cd /opt/java` 

It says "Permission Denied". So I made an opt/java/ folder in the directory with my projects. I continued  with the tutorial, editing anything I need to do, but then when I do this:

`update-alternatives --install /usr/bin/java java opt/java/jdk1.8.0_45/bin/java 100` 

It says:

`update-alternatives: error: alternative path is not absolute as it should be: opt/java/jdk1.8.0_45/bin/java`

How can I fix this? Is there an easier way to upgrade to java 8 on SMC?

**Comment by haraldschilly** [comment]
Hi, you are on a shared machine, and you are not allowed to change files that do have an impact on all other users. What you can do is to add these java binaries to your path! I.e. at the bottom of your `~/.bashrc` file write something like:

    export PATH="~/opt/java/jdk1.8.0_45/bin/":"$PATH"

and restart your terminal (Ctrl-d and return key)

**Comment by iScienceLuvr** [comment]
@haraldschilly and what exactly will that do? That will finish the installation for java 8? does it replace java 7 with java 8?

**Comment by haraldschilly** [comment]
@iScienceLuvr well, kind of, I'm also not sure if that works.

But: the `PATH` variable is a list of directories, where the shell searches for executable files that have the name you typed in for execution. I.e. if there is this path here in *front* of all the other paths, and the first one contains an executable file named `java`, this `java` will be picked up when you type in `$ java` in the shell -- instead of the default one in `/usr/bin` (or wherever it is)

**Comment by iScienceLuvr** [comment]
@haraldschilly thanks! it works, except I have to set it up for each terminal... is there a solution that works for the entire project... if not, that's ok...

**Comment by haraldschilly** [comment]
Yes, if you edit your `~/.bashrc` file, adding the `export PATH=...` line at the bottom, it affects all newly started terminals!

**Comment by iScienceLuvr** [comment]
@haraldschilly where is the bashrc file? I put that line in the initialization file...As you can see, I do not know much about bash stuff! :P

**Comment by williamstein** [comment]
`.bashrc`

On Sat, Mar 5, 2016 at 3:41 PM, iScienceLuvr <notifications@github.com>
wrote:

> @haraldschilly <https://github.com/haraldschilly> where is the bashrc
> file? I put that line in the initialization file...As you can see, I do not
> know much about bash stuff! :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/454#issuecomment-192761182>.
>



-- 
William (http://wstein.org)

**Comment by iScienceLuvr** [comment]
@williamstein huh? I don't understand... where is it?

**Comment by haraldschilly** [comment]
@iScienceLuvr your project, where you have your files, that's your home directory. It's something like `/projects/1234-1234-1234-1234/`

in that directory, there is a file named `.bashrc`

**Comment by iScienceLuvr** [comment]
@haraldschilly @williamstein oh!! It is a hidden file...that makes sense...thanks for your help guys!
