### ISSUE TITLE
upgrade mathjax

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#455]
Rob Beezer says in reference to "also Mathjax puts a trailing vertical line at the end of every latex formula. Do you know a quick way to fix this?"

> I believe this is https://github.com/mathjax/MathJax/issues/1300 and the short answer is that MathJax 2.6 has a fix.  I think it is specific to Chrome.

I've never seen this issue, but we may as well upgrade mathjax...

**Comment by williamstein** [comment]
Basically modify `src/smc-webapp/package.json` line 21 (the mathjax line)...   Can do automatically via some npm command.

**Comment by rbeezer** [comment]
This vertical line bug is almost an FAQ on mathjax-users the past few weeks.  2.6 has been out for two months now and seems to be stable (and fixes about 30 bugs).  Sounds like a 3.0 is on the roadmap, perhaps for 2016 sometime.

https://www.mathjax.org/whitepaper-towards-mathjax-v3/

**Comment by haraldschilly** [comment]
tested it my test project in various documents, no issues.

**Comment by williamstein** [comment]
Let's go live.

On Sat, Mar 5, 2016 at 12:53 PM, Harald Schilly <notifications@github.com>
wrote:

> tested it my test project in various documents, no issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/455#issuecomment-192733845>.
>



-- 
William (http://wstein.org)

**Comment by rbeezer** [comment]
mathjax-users thread about combining MathJax and webpack:

https://groups.google.com/d/topic/mathjax-users/1os6XOGkLOc/discussion

**Comment by williamstein** [comment]
@rbeezer -- thanks; I did once fully server mathjax via webpack, but it's a subtle disaster. Things would randomly work sometimes and randomly not others.  (I imagine it'll require some real work by the mathjax devs...)

**Comment by rbeezer** [comment]
I'm guessing, based on skimming their white paper, that their 3.0 release (a year, or more, away) is about playing nicely with lots of web apps (for lack of a better term).  Maybe @jasongrout will get it all figured out then (or it will be straightforward).
