### ISSUE TITLE
Add link to Github project in header 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#457]
Adding a link to Github project in the header will likely increase number of people who submit issues and hopefully code.

**Comment by haraldschilly** [comment]
I don't like this idea. My header is already pretty full. What about adding a link to the footer?

**Comment by timothyclemansinsea** [comment]
Sounds good

**Comment by williamstein** [comment]
In the header or footer of *what*?    We definitely shouldn't assume that very many of the users of SMC will contribute -- that's just not the nature of the project.

There is no footer, by the way.

**Comment by timothyclemansinsea** [comment]
There is a footer on projects list page

**Comment by haraldschilly** [comment]
On Sat, Mar 5, 2016 at 8:32 PM, Tim Clemans <notifications@github.com>
wrote:

> There is a footer on projects list page
>
>
​I made one for the ​pricing page and added it to selected pages to see how
it plays out. It's a good UI practice to indicate where there is an ending
of the page and at the same time it shouldn't distract at all. There is
certainly no place for a footer on all the pages where you are usually
working.

Rather, I would suggest to come up with a new concept for the "help" page.
That's something which is certainly not easy to accomplish. I.e. the first
"help" point is about pricing, which might not be the first obvious thing
someone wants to learn about... (and no, just reordering the list doesn't
help at all)

**Comment by williamstein** [comment]
Thanks -- I didn't realize that... since my project listing is so long.
The footer does look nice.

On Sat, Mar 5, 2016 at 11:32 AM, Tim Clemans <notifications@github.com>
wrote:

> There is a footer on projects list page
>
> On Sat, Mar 5, 2016 at 11:29 AM, William Stein <notifications@github.com>
> wrote:
>
> > In the header or footer of *what*? We definitely shouldn't assume that
> > very many of the users of SMC will contribute -- that's just not the
> nature
> > of the project.
> >
> > There is no footer, by the way.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sagemathinc/smc/issues/457#issuecomment-192713153>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/457#issuecomment-192713322>.
>



-- 
William (http://wstein.org)
