### ISSUE TITLE
Add fixed footer for users without subscription or projects getting upgrade from another's subscription suggesting that one upgrade to get internet access and other improvements

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#458]
I'd also suggest putting in language that upgrades help support development of Sage even if one doesn't need the upgrades so that people will be more likely to buy subscription solely to support SMC

**Comment by williamstein** [comment]
I'm uncomfortable adding a footer like this everywhere.  The interface to SMC is already too cluttered.   It is important to help people understand that there are benefits to paying, but not at the expense of cluttering the interface.

**Comment by timothyclemansinsea** [comment]
I now think it's better to mention this at time of project creation. I
hadn't created a project in a while so I forgot about this possibility.

**Comment by williamstein** [comment]
I can barely understand the title, but I think this is already done.
