### ISSUE TITLE
Create a install script and provide curl pipe sh command for it 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#459]
I haven't setup my own SMC yet. It would be nice to be able to just put in a one line command to set it up or better yet a button within SMC to do it as curl pipe sh commands are dangerous.

**Comment by haraldschilly** [comment]
I don't understand your sentence :confused: 

Such a script would also have to setup all the required software dependencies. That's really hard to figure out in a generic way. Rather, it would maybe be better to have a docker image with everything setup. But who is going to make it, and who is updating it regularly?

**Comment by timothyclemansinsea** [comment]
What about a script for just SMC?

**Comment by williamstein** [comment]
> What about a script for just SMC?

Is the script basically `git clone <smc> && npm run make` ?

**Comment by timothyclemansinsea** [comment]
yes I did a PR for this for installing on SMC https://github.com/timothyclemansinsea/smc/commit/629d99429371a3ce9bdb1e03a9dfdc7164d1088d
