### ISSUE TITLE
Auto hard refresh when red box shows up first time running SMC

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#462]
First time I ran SMC inside SMC today I got "Loading Error!
Something bad must have happened.
Try reloading the page while holding your shift-key."

The script I ran 
git clone https://github.com/sagemathinc/smc
cd smc/src
./smc-env
npm run make
cd dev/project/
./tmux-start-all

Maybe just add

    location.reload(true);

**Comment by williamstein** [comment]
I disagree.  This shows up when a time limit is reached, but maybe the connection is just slow?   Also, you really have to do a hard refresh, and location.reload(true) doesn't do one, does it?

**Comment by timothyclemansinsea** [comment]
I thought it did based on http://stackoverflow.com/questions/2099201/javascript-hard-refresh-of-current-page

**Comment by haraldschilly** [comment]
the "reloading" string in the red box is a link that does this.

https://github.com/sagemathinc/smc/blob/master/src/static/index.html#L146

the point is, that the user has to see a clear warning before the application starts that there is an issue. it's most likely a network issue.

in your case, it's most likely an issue with your application. I'm guessing that it isn't compiled or incomplete. you have to check the panels in tmux to figure it out…

**Comment by williamstein** [comment]
(1) Thanks -- I didn't know about javascript hard refresh!

(2) Good point Harald.
