### ISSUE TITLE
FEniCS on SMC - slepc error during installation

### ISSUE THREAD

**Issue by AndreTimotheo** [sagemathinc/smc#47]
I was installing (stable) FEniCS project on SMC terminal via 

curl -s http://fenicsproject.org/fenics-install.sh | bash 

and I have slepc compilation problems. 

I customize the the instalation with the instructions of
Johannes Ring (FEniCS project):

git clone https://bitbucket.org/fenics-project/fenics-developer-tools.git
cd fenics-developer-tools
cp install/profiles/fenics.Linux.yaml local.yaml
editor local.yaml

Now remove the following two lines from local.yaml:

    download: |                                                                                           
      mumps, scalapack, blacs, ml   

Finally, run:

./install/fenics-install.sh local.yaml

With $ source fenics.custom comand 
the FEniCS project is available on ipython calling from the terminal.

The native vtk plots are not available. Is there any way to 
enable it?

( Is it possible to call an old ipython notebook version associate with the 
ipython terminal in order to use FEniCS there? )

André Timótheo

**Comment by williamstein** [comment]
I'm giving up on Fenics for now...

**Comment by AndreTimotheo** [comment]
I can't import dolfin on sagemathcloud Jupyter notebook

https://cloud.sagemath.com/projects/71d17729-71d5-48f0-a7b4-c326acdcee37/files/2016-09-26-134636.ipynb

André Timótheo

Em sex, 23 de set de 2016 às 18:46, William Stein <notifications@github.com>
escreveu:
