### ISSUE TITLE
clarify the error message when viewing a project that has no public files

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#470]
Sometimes people report this error:

> I am a TA using SageMathCloud to teach Calculus. When my student tried to share his project folder with me, I saw this message:  Directory listing error  "project with id 'b9e5b094...4b154' is not public"

We get a **a lot** (daily) emails from confused users in such cases.   Let's provide a better message.  E.g., 

> Please ask the person who shared this link with you to visit their project settings at https://cloud.sagemath.com/projects/b9e5b09...b154/settings and add you via your email address (the one you are registered with on SMC) to the list of "collaborators". Then, this project will pop up in your list of projects and you can - of course - also access all files in this project.

This will save a lot of people a lot of time.

LATER -- and this requires more work and thought -- we can replace the above message by a button to _request_ to join a project.  Like a google group, the "ask to join" could have various settings, e.g.,
- a question the user has to answer, and joining must be approved
- any user can join
- only people who know the link can join
- completely private/secret -- don't even give away existence of the project with given id.

etc.

**Comment by williamstein** [comment]
@timothyclemansinsea  -- did you fix this already?

**Comment by timothyclemansinsea** [comment]
@williamstein Yes this is done. Where's the ticket for implementing request to join?

**Comment by williamstein** [comment]
Closing.

> Where's the ticket for implementing request to join?

I don't know -- maybe it got closed by accident.  Please search through closed tickets.
