### ISSUE TITLE
sagews2pdf: portuguese "ã" or "õ" in a "# comment ..."

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#471]
check, if these characters work, maybe it's necessary to add them to the special characters table for lstlistings

**Comment by haraldschilly** [comment]
ok, I can reproduce it. what I need is a full list of all such characters.

**Comment by haraldschilly** [comment]
if anyone is curious testing this in the future: these chars in a comment do work now:

```
# ÃÁÀÂÇÉÊÍÕÓÔÚÜ
# ãáàâçéêíõóôúü
```

**Comment by slel** [comment]
On a related note, see the character replacement table at
https://github.com/sagemath/publications/blob/master/pubparse.py#L923
which is probably not complete but also has some Polish accented letters.

**Comment by haraldschilly** [comment]
@slel that's LaTeX to HTML, what we need are UTF-8 chars to LaTeX
