### ISSUE TITLE
create a Python script that runs the test suites (or something) for every optional pip-installed package we install into our Sage installs on SMC

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#473]
The optional packages are listed here:

  https://github.com/sagemathinc/smc/blob/master/src/smc-build/build.py#L145

in the SAGE_PIP_PACKAGES variable.

The solution to this ticket could be a new python script we add to smc-build called, e.g.,

   src/smc-build/test-pip-packages.py

that runs, does whatever it wants, it outputs useful information.

**Comment by haraldschilly** [comment]
@DrXyzzy this overlaps a little bit with what I've already done [here in compute-integration-tests.py](https://github.com/sagemathinc/smc/blob/master/src/smc-build/compute-integration-tests.py) ... but beware, it only works inside those new smc-project images I'm working on -- but I think you get the idea.

The point is, it might be enough to solve this ticket here, if you add an additional python executable, namely `sage -python`, and a list of `PY_SAGE = [ ... ]`. That list is derived from the `build.py` file, which does contain all those pip packages.

:warning: however: wouldn't it be cool to unify py2, py3, anaconda's python 3, and sage's python2 a bit while I'm about to creating that image? I think so, and that's one of the details I'm after. I.e. to go through the list in build.py, figure out if they work in the other python environments, etc. 

missing piece of info for how to run it [is buried here](https://github.com/sagemathinc/smc/blob/master/src/k8s/smc-project/image-base/makefile#L25) … and well, overall, all of this is still in flux.

**Comment by williamstein** [comment]
I'm going to close this as too broad and vague....

**Comment by haraldschilly** [comment]
that basically already exists in that integration test.
