### ISSUE TITLE
consider changing the markdown bootstrap table style.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#474]
This is an example of how to put a table in markdown in SMC:

```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 3 is      | some wordy text | 1600 |
| col 2 is      | centered        |  12 |
| zebra stripes | and math       |  $\pi^3$ |
```

It is just a standard HTML table with the bootstrap css class 'table" added, and -- as documented [here](http://getbootstrap.com/css/#tables), there are no vertical lines in the table.  We could add table-bordered and even table-hover, to make our tables more stylish by default, including vertical lines.  Thoughts?

**Comment by johnjeng** [comment]
Not really worth discussing. Closing since it has a `will-close` tag anyways.
