### ISSUE TITLE
Project not starting!

### ISSUE THREAD

**Issue by iScienceLuvr** [sagemathinc/smc#482]
So I come and visit my project, and it says it is stopped as usual, so I press the start button, and it says "Starting" for like two seconds, and goes back to the same "Stopped" mode. I can never get it to start! It only happens for this one project. Here is the link:

https://cloud.sagemath.com/projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/files/

**Comment by williamstein** [comment]
You should email help@sagemath.com with such support requests.  Your project doesn't work because you used up all disk space.  I emptied the trash and now it starts.
