### ISSUE TITLE
settings→file sort is not respected in default file sorting

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#483]
user report: "In SMC, under preferences, i have chosen the "default file sort" to be "by name", but it doesn't work. Files are always listed by date."

**Comment by johnjeng** [comment]
Looks like this used to work and then for some reason there had to be a temporary solution that allowed sorting the files but never read any data from user's settings. Additionally, it seems that these settings aren't event being saved correctly to the database.
Though I could be completely wrong on the last bit, I'm still not entirely clear on how interfacing with the database works.
