### ISSUE TITLE
sync2/sagews: worksheet state broken after alt-return update

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#487]
steps to reproduce:

1. new worksheet
2. open twice in two windows
3. enter `1` in worksheet A, then press `alt`+`return` to evaluate it

notice, that in the other worksheet no proper output-box appears. 

to retrigger: enter something different, like `1` newline `1` and alt+return ... once again, the output bar disappears in the other window

re-opening the sagews fixes this visual error

**Comment by williamstein** [comment]
fixed long ago
