### ISSUE TITLE
Published iPython notebooks do not display properly if already logged in

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#5]
plan: when opening a static html file, if it was generated by nbconvert, just render it. Simple as that.

See https://github.com/sagemathinc/smc-public/issues/1 for a discussion.

**Comment by haraldschilly** [comment]
I went through the content of such an HTML file but wasn't able to find a reliable string to detect it. Instead, I have this simple idea: after rendering via nbconvert, replace the first line of the HTML (the doctype tag) with:
```
<!DOCTYPE html>
<!-- generated by nbconvert -->
```
and detect this when displaying the HTML page. 

Another strategy could be to search for an existing ipynb file with the same basename: i.e. if `<basename>.ipynb` exists in the same directory -> show html.

**Comment by williamstein** [comment]
> Another strategy could be to search for an existing ipynb file with the same basename: i.e. if <basename>.ipynb exists in the same directory -> show html.

One small problem with this is that it will further slow down opening the file...  I like your `generated by nbconvert` idea; that could even get upstreamed...

**Comment by williamstein** [comment]
No longer  a problem since we no longer have this .html business.
