### ISSUE TITLE
Issues with multiple people editing the same file at the same time

### ISSUE THREAD

**Issue by mchandra** [sagemathinc/smc#50]
Hi,

I have been in a situation where 4 people were editing the same file, at the same time (one day before manuscript submission) and here's some feedback from that experience:

1) When multiple people are editing the document, it would be good to show somewhere on the screen that author X is working on line # 10, author Y is working on line # 45, say.

2) Suppose two authors X and Y are working on lines # 25 and lines #150 respectively. The view for author X is fine, since he/she is at the top of the document. However, for author Y, the situation is terrible, because as author X keeps adding lines, author Y's screen keeps shifting below and is very distracting. Instead, it would better if the line numbers on the left change/scroll, rather than the view of the entire document scrolling.

Cheers,
Mani

**Comment by jasongrout** [comment]
For (1), as a UI, there could be the name tag that usually accompanies the cursor, but anchored in the upper right (for cursor positions above) or anchored at the lower right (for cursor positions below).

**Comment by williamstein** [comment]
all fixed now.
