### ISSUE TITLE
button cutoff latex editor

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#501]
The issues button is cut off, while the PDF and Build buttons are not visible.

I am currently using the latest version of Firefox.

![image](https://cloud.githubusercontent.com/assets/207405/14395058/caec6b32-fdcf-11e5-9ad7-ab8629016349.png)

**Comment by williamstein** [comment]
Rewriting in react is would fix this...

**Comment by williamstein** [comment]
Hi priority since this is really embarrassing, and we really don't want our latex editor to scare off users.

**Comment by williamstein** [comment]
Question: does anybody have any clue how to actually replicate this?  I've seen it before, but I just tried for 6 minutes with chrome and firefox and can't replicate it.

**Comment by haraldschilly** [comment]
I've noticed this yesterday several times, it's also in the "normal" md editor. So, that's not just latex... maybe there is just a reason that it is more easily happening there. I'll read that code for the preview iframe, maybe I see something...

**Comment by haraldschilly** [comment]
just FYI, I know the problem ... fixing this also means to clean up some parts.

**Comment by haraldschilly** [comment]
This commit is work in progress, I need a break since all this is a minefield.

**Comment by williamstein** [comment]
Fixed!
