### ISSUE TITLE
Better distinguish input and output cells in pdf rendering of Sage worksheets

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#504]
Asked by user sophia on Ask Sage:

http://ask.sagemath.org/question/33054/formatting-pdf-of-sage-worksheet-on-smc/

> I have a formatting query about the background colors on sagemath cloud.
> I regularly generate and print pdf of the sage worksheets on a black and
> white printer. On the printed page, its hard to distinguish between the
> cell that contains the code and the output of the cell (both have the
> same background color).
> 
> Is there any way to clearly demarcate the cell that contains the code
> and the output of the cell? Would it be possible to get the output of
> any cell with a shaded background or with a border around it, so that
> on a printed paper, the output of the cell appears clearly different
> from the contents of the cell.
> 
> I've tried some of the Editor color scheme options, but I don't see an
> option where the cell appears with a different background color.

**Comment by williamstein** [comment]
Also some improvements to the gutter of codemirror could help a lot here.

**Comment by williamstein** [comment]
@haraldschilly -- close due to your html thing, which really should be the canonical print now.??
