### ISSUE TITLE
error calling compute server -- error writing to socket

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#507]
Put in some automated testing so we'll be notified if this error is happening in the hub logs:

```
error calling compute server -- error writing to socket -- socket no
```

Or, better, figure out when it would happen, and properly reset the connection between the hub and the compute server.  This happened today on web6/0 and the above message appeared in the log 9600 times or so.   I restarted that hub and everything was fine.

**Comment by haraldschilly** [comment]
see referenced patch: adds an error counter for exactly this string and issues a restart if it is found more than 10 times
