### ISSUE TITLE
Copying files starting with '-'

### ISSUE THREAD

**Issue by aureooms** [sagemathinc/smc#516]
Trying to copy a file starting with '-' produces the following error. rsync thinks the filename is an option.

> Error executing command 'rsync' with args '-rltgoDxH,--backup,--backup-dir=.trash/,-1,0,1.sagews,plots.sagews' -- command 'rsync' (args=-rltgoDxH --backup --backup-dir=.trash/ -1,0,1.sagews plots.sagews) exited with nonzero code 1 -- stderr='rsync: -1,0,1.sagews: unknown option
> rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.1]
> ', , rsync: -1,0,1.sagews: unknown option
> rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.1]
> -- This is a BASH terminal, not a Sage worksheet.  For Sage, use +New and create a Sage worksheet.

**Comment by johnjeng** [comment]
I'm having trouble reproducing this error. I tried copying a file from one directory to another, once where it was named "-file.txt" and once when it was named "- file.txt". Both instances resulted in no errors.

Could you give me more information on the context in which this error occurs?

**Comment by aureooms** [comment]
1. open a project
2. create a SageMath Worksheet named "-1,0,1"
3. go to "Files"
4. select the file "-1,0,1.sagews"
5. click on "copy"
6. type "abcd" in destination
7. click "Copy 1 item"

> Error executing command 'rsync' with args '-rltgoDxH,--backup,--backup-dir=.trash/,-1,0,1.sagews,abcd' -- command 'rsync' (args=-rltgoDxH --backup --backup-dir=.trash/ -1,0,1.sagews abcd) exited with nonzero code 1 -- stderr='rsync: -1,0,1.sagews: unknown option
> rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.1]
> ', , rsync: -1,0,1.sagews: unknown option
> rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.1]
> -- This is a BASH terminal, not a Sage worksheet.  For Sage, use +New and create a Sage worksheet.

**Comment by johnjeng** [comment]
Got it, thanks!
Working on this. Should be fixed by the end of this week.
