### ISSUE TITLE
deploying SMC on a server

### ISSUE THREAD

**Issue by mkrnc** [sagemathinc/smc#517]
Dear SMC team!

First, thank you for many efforts you've put to your SMC project... I am absolutely a fan. I've been "given" a blade server to use at our faculty, to deploy SMC environment on it. 
I am not a great IT guy, and I'm trying to follow steps in the readme file. So far, I've managed to:

- install Ubuntu 16.04
- install latest Node.js , npm and pyYaml, in order to 
- successfully run `npm run install-all`

However, when I try to test everything with `npm test`, I get an assertion error; seems to be related to timezone, in particular:

```
      AssertionError: expected 2014-01-02 04:15:08.000 +0100 to equal 2014-01-02 03:15:08.000 +0100
      + expected - actual

      -[Date: 2014-01-02T03:15:08.000Z]
      +[Date: 2014-01-02T02:15:08.000Z]
```
      
Any comment is greatly appreciated!

**Comment by haraldschilly** [comment]
Is there no context telling you, which test this is? (line number and file name)

Apart from that, probably not relevant. I assume your server runs under local time and not UTC, hence that's maybe the root cause.

**Comment by mkrnc** [comment]
Ok, I'll try changing timezone to UTC. Let me also give perhaps more complete context:
```
> sagemathcloud@1.0.0 test /home/cloudsage/smc/src
> export SMC_TEST=true&& cd smc-util && npm test && cd ../smc-util-node && npm test && cd ../smc-hub && npm test && cd ../smc-webapp && npm test


> smc-util@1.0.0 test /home/cloudsage/smc/src/smc-util
> SMC_TEST=true node_modules/.bin/mocha --reporter progress


  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  182 passing (2s)
  1 failing

  1) parse_bup_timestamp reads e.g. 2014-01-02-031508 and returns a date object:

      AssertionError: expected 2014-01-02 04:15:08.000 +0100 to equal 2014-01-02 03:15:08.000 +0100
      + expected - actual

      -[Date: 2014-01-02T03:15:08.000Z]
      +[Date: 2014-01-02T02:15:08.000Z]
      
    at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
    at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
    at Context.<anonymous> (test/misc-test.coffee:851:23)
  



npm ERR! Test failed.  See above for more details.
npm ERR! Test failed.  See above for more details.

```

**Comment by haraldschilly** [comment]
On Fri, Apr 22, 2016 at 5:43 PM, Matjaž Krnc <notifications@github.com>
wrote:

> Let me also give perhaps more complete context:


ok, thank you. the test file and the line number is this:

src/smc-util/test/misc-test.coffee:851

​No idea what's actually there, but looking at the test might reveal what's
going on here :-)

-- harald

**Comment by mkrnc** [comment]
Thank you for your replies... changing the system time resolved (this) issue.
