### ISSUE TITLE
Create page with comparison to other software

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#521]
Suggested by Tim Clemans (@timothyclemansinsea) on 2016-04-22,
see https://gitter.im/sagemath/cloud?at=571a550e0eef754b5ea98cd5

> I really like this product comparison page, especially the disclaimer
> at top, https://about.gitlab.com/comparison/ Would be nice for SMC

**Comment by williamstein** [comment]
Closing -- this is way too broad/vague.
