### ISSUE TITLE
change sagews search to be aware of hidden control codes

### ISSUE THREAD

**Issue by billpage** [sagemathinc/smc#522]
(see comment below -- this description is from the original report and misses the root cause)

Search again (ctrl-g) after initial search does not reliably position the cursor at the next occurrence. This used to work.  In fact, after this fails once, additional new searches on the new string may not work either.

For example click the search icon and enter
  ru
then press enter.  The cursor is positioned at the first occurrence of the variable ru in my Sage code.  Then I press ctrl-g.  The cursor is now positioned at the separator bar between two cells.  Pressing ctrl-g again may position the cursor at the next ru or maybe another separator bar.  Starting a new search for
  ra
seems to work OK at first but later fails.  Starting a new search for
  ru
fails to position the cursor at the next location of ru.

**Comment by williamstein** [comment]
Technically it does, but it isn't ignoring the hidden codes (which get replaced by graphics right now).
