### ISSUE TITLE
Show for graphs with text in them does not truncate the text

### ISSUE THREAD

**Issue by danyill** [sagemathinc/smc#523]
When selecting xmin, xmax and ymin ymax in a plot, if there is a text element, e.g.

``` text(lable, midpoint(point,line_end), horizontal_alignment='left', vertical_alignment='top', fontsize='xx-small', color='black')```

which is outside the plotting boundaries it is still displayed.

See for instance this standalone code fragment
```
a = plot(x^2, (x,0,5))
b = text("hi there wonderful Sage and SMC people", (30,30), horizontal_alignment='left', vertical_alignment='top', fontsize='xx-small', color='black')
show(sum([a,b]),aspect_ratio=1, xmin=-10,xmax=40, ymin=-10, ymax=40, axes_labels=['$R$ pri. $\Omega$','$X$ pri. $\Omega$'], axes_labels_size=1)
show(sum([a,b]),aspect_ratio=1, xmin=-10,xmax=40, ymin=-10, ymax=20, axes_labels=['$R$ pri. $\Omega$','$X$ pri. $\Omega$'], axes_labels_size=1)
```

(also see here: https://cloud.sagemath.com/projects/a06e36e0-4df1-47a7-8183-8d5e65d5f504/files/quadmho.sagews)

**Comment by williamstein** [comment]
Thanks.  This should reported to the SageMath software project: http://trac.sagemath.org/

It might also be a design choice of matpotlib.  Not sure.  You could raise this issue here: https://groups.google.com/forum/#!forum/sage-support
