### ISSUE TITLE
GAP package install request -- GBNP

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#529]
Second, I would need to use a packet GAP called GBNP on sagemathcloud to compute Grobner basis of some spaces.

The installation process is quite easy, you just need to download the package in this page :

http://www.gap-system.org/Packages/gbnp.html

and put it inside the folder packages of GAP (which is already in the cloud).

Requested by: Riccardo BIAGIOLI

**Comment by williamstein** [comment]
here's what I did: 
```
cd /projects/sage/sage-6.10/local/gap/gap-4.7.8/pkg
wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/GBNP-1.0.3.tar.bz2
tar xvf GBNP-1.0.3.tar.bz2
```
where unfortunately I had to manually figure out the 1.0.3 from the website. 

Does the package now work for you?

--

Answer: nope. 

Unfortunately, I was not able to run the gap package. I used several variants of the command :

`gap.LoadPackage(‘’gbnp’’)`

but nothing seems to work. Maybe I type the wrong command.

**Comment by slel** [comment]
Your installation seems to have worked.

In a SageMathCloud terminal, I can launch GAP and run this command

    gap> LoadPackage("gbnp");

where `gap>` is the prompt, the command has double quotes, and a final semi-colon.

Or I can launch Sage and run

    sage: gap.LoadPackage('"gbnp"')
    true

where the argument of the `LoadPackage` method is a string in simple quotes containing
`"gbnp"` (ie surrounded by double quotes).

**Comment by haraldschilly** [comment]
ok, then I'm closing this issue...
