### ISSUE TITLE
Export email addresses with grades instead or in addition to names

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/smc#530]
When exporting grades, students are identified by their names.  That leads to difficulties when merging with non SMC grades in the class, since the names are often entered differently in different systems (SMC uses the names as the students entered them, usually in First Last format, but out course management system uses Last, First format, some students have their middle initial included in one system but not in teh other, etc.)  Also, what will SMC do if there are two students with the same names in the class?  Unlikely as it is, I did have that happen two years ago.  Including email addreses would help with both of these issues.

**Comment by haraldschilly** [comment]
Hmm, is this merged? I think this has been merged a while ago and therefore this can be closed.

**Comment by williamstein** [comment]
I just checked and this is merged.
