### ISSUE TITLE
Creating a file via the terminal "open" command causes it to be readonly

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#536]
- using the command "open foo.sagews" in the terminal, it will create a file called foo.sagews but the user is unable to edit it (assuming there was no previous existing file named foo.sagews, otherwise it would act as normal and open foo.sagews)
- making a blank file with the "touch" keyword and then opening it circumvents this bug
- creating files by hitting the "new" button works as normal
- opening the readonly file through either terminal or file browser doesn't change its readonly status (probably a good thing considering it's designated as readonly)
- also seen to affect .txt and .tex files

**Comment by williamstein** [comment]
I've had this in my #critical personal todo list for 22 days now.  I've added a link from there to here...
