### ISSUE TITLE
Creating and navigating to folders in home directory beginning with - errors

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#538]
The commands `mkdir` and `ls` interpret the leading `-` as an option.

**Comment by johnjeng** [comment]
Partially done at [issues/538](https://github.com/sagemathinc/smc/tree/issues/538).

**Comment by williamstein** [comment]
Is this fixed?  Also that link above is circular.

**Comment by williamstein** [comment]
Confirmed that this is still broken.

**Comment by haraldschilly** [comment]
maybe just prefix the argument with `--` all the time, like `mkdir -- name`?

**Comment by williamstein** [comment]
Also, deleting a file with leading - in the name doesn't work.

**Comment by williamstein** [comment]
https://github.com/sagemathinc/smc/tree/issues/538 was the wrong directory.  Harald's `--`  used in a few places made this easy to quickly fix.  Thanks @haraldschilly
