### ISSUE TITLE
Idea: Move buttonbars to their own repo

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#541]
Maybe each dropdown is its own JSON file. 

> Tim Clemans @timothyclemansinsea 10:42
> I think all of this should be in a database so people can easily add to it. Would be nice to not have to leave SMC to go to Google which usually links to Stackoverflow. Maybe before doing that integrating Stackoverflow search into SMC would be way to go
> *all of the buttonbars
> 
> William Stein @williamstein 10:43
> Yes, having the actual content in the source code isn't so good. I'm not sure the database is a good place either though.
> 
> Tim Clemans @timothyclemansinsea 10:44
> Maybe another repo

**Comment by williamstein** [comment]
Too unclear -- also not clearly valuable.
