### ISSUE TITLE
Users can add code from the codeedit-buttonbar to readonly files (but not remove it)

### ISSUE THREAD

**Issue by Ahuchala** [sagemathinc/smc#543]
For example, open up a readonly file and click the calculus button, then click numerical integral

**Comment by Ahuchala** [comment]
They can also revert the edit with the history slider's "Revert live version to this," which they shouldn't be able to do...

**Comment by Ahuchala** [comment]
You can also insert code by pressing the %sage button in the top right

**Comment by williamstein** [comment]
Fied!
