### ISSUE TITLE
[dev/laptop] forever is missing from $PATH

### ISSUE THREAD

**Issue by jdemeyer** [sagemathinc/smc#546]
When starting a new SMC project using the `dev/laptop` instructions, it fails with the hub logfile mentioning that the `forever` command is not found.

`forever` is a node program which is present in `$SMC_ROOT/smc-hub/node_modules/` and `$SMC_ROOT/smc-project/node_modules` but not in `$SMC_ROOT/node_modules` and only the latter is in the `PATH`. So either the `PATH` needs to be changed or `forever` needs to be installed in `$SMC_ROOT/node_modules`.

**Comment by williamstein** [comment]
Closing in favor of #548
