### ISSUE TITLE
[dev/laptop] smc-sage-server is missing from $PATH

### ISSUE THREAD

**Issue by jdemeyer** [sagemathinc/smc#547]
When starting a new SMC project using the `dev/laptop` instructions, it fails with the hub logfile mentioning that the `smc-sage-server` command is not found.

The command is in `$SMC_ROOT/smc_pyutil/smc_pyutil/bin/smc-sage-server` but this directory is not in the `$PATH`.

**Comment by williamstein** [comment]
This is #548
