### ISSUE TITLE
[dev/laptop] Python modules smc_pyutil and smc_sagews are not installed

### ISSUE THREAD

**Issue by jdemeyer** [sagemathinc/smc#548]
When trying SMC using the `dev/laptop` instructions, I get some errors which seem to relate to the fact that the Python modules `smc_pyutil` and `smc_sagews` do not exist.  Also, forever needs to be available and installed systemwide.

It's not clear to me if this is a bug in the build system, the scripts or the documentation.

**Comment by williamstein** [comment]
This is a documentation issue.
