### ISSUE TITLE
Install md5 system-wide

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#550]
I tried running `md5 some_file_name` in a smc terminal and got
`md5: command not found`.

**Comment by haraldschilly** [comment]
does md5sum work?

**Comment by haraldschilly** [comment]
I'm closing this ticket. No response for 24h and I assume a mixup between apple's BSD md5 and linux md5sum

**Comment by slel** [comment]
Yes, that was the mixup, sorry.
