### ISSUE TITLE
sage-chat scrolls to bottom on return from smc tab

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#557]
Seen in firefox browser:

- in sagemathcloud (SMC) open a .sage-chat file
- add content more than 1 screenfull
- scroll back to top of chat
- switch to a different SMC tab - select different project or file in SMC
- switch back to .sage-chat SMC tab and chat display has scrolled to bottom, losing your place

**Comment by williamstein** [comment]
The solution is likely to store the scroll location in the redux store.

**Comment by haraldschilly** [comment]
I think, what should really be stored is a timestamp for the user -- maybe even in local storage. i.e. as long as the chat is actively displayed, a new message pushes that timestamp forward. if you are away or in another tab, that timestamp isn't pushed. next time you come back. the top message is the first one >= your timestamp AND after scrolling down (in a sense signalling, that you are catching up) the most recent message sets your timestamp.

**Comment by williamstein** [comment]
Yes - good idea.  However if user is at the bottom (seeing latest chat),
switches away, then back then they definitely should still see latest
chats.   Only when they manually scroll up should the more switch to
sticking there.

On Tuesday, May 17, 2016, Harald Schilly <notifications@github.com> wrote:

> I think, what should really be stored is a timestamp for the user -- maybe
> even in local storage. i.e. as long as the chat is actively displayed, a
> new message pushes that timestamp forward. if you are away or in another
> tab, that timestamp isn't pushed. next time you come back. the top message
> is the first one >= your timestamp AND after scrolling down (in a sense
> signalling, that you are catching up) the most recent message sets your
> timestamp.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/557#issuecomment-219753132>
>


-- 
Sent from my massive iPhone 6 plus.
