### ISSUE TITLE
new file with unknown extension causes editor to be readonly

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#562]
in a terminal or the file dialog, enter a filename that does not exist with an unknown extension, e.g. `name.something`. The editor is then readonly.

I would expect to be in plaintext mode. Also note, that once I add a character (e.g. `echo x > name.something`) to the content of the file, it switches to be readwrite as it should be.

I'm guessing this is an odd corner case of the synchronization mechanism...

**Comment by williamstein** [comment]
I think this is #536.  Also "in the file dialog, enter a filename that does not exist with an unknown extension, e.g. name.something. The editor is then readonly." is not true.   

I think there is definitely nothing special going on involving unknown extensions either.
