### ISSUE TITLE
one click compile and run when editing java (and other) files

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#564]
Requested by Soo Rho (and many others):

> Automating the process of compiling and running - or solely running for noncompiled languages-, such a button will make SMC more powerful for me than any other IDE. Such a button will make SMC the best IDE for me who finds everything in SMC brilliant except a lack of such a button like Eclipse's "Run" button. A lack of such a button is the only reason why I have not been using SMC everyday in both school and home.
> 
> "javac" and "java" functions are typed in a terminal whenever I want to compile and run java files, for example.
> 
> Illustrating what I think is such a good button: 
> 1. Located between the "Print" and the "Save" buttons, 
> 2. usable for non-interactive files including java files, 
> 3. compiling and running - or solely running - the file through a terminal that will be either a previously created one or a newly created one.
> 
> In addition to 3, running only the active file, not other files, is personally thought to be good.
> 
>  I appreciate and love SMC to a great extent.
> 
> Thank You very much!

**Comment by haraldschilly** [comment]
My collection of ideas:

* support Makefiles, e.g. "run button in an IDE" is calling one of several predefined actions. that reminds me of them.

* Regarding java, we should also support maven and gradle from the UI, or even more build systems like npm, rake, etc. 

* it's also an important question to figure out, how to link a run button from the file editor with such a configuration. usually, there is a config file in the project's root directory, that does define available actions.

* and then, after clicking it, how to go from the file to a terminal, where the program is compiled (spitting out compile errors) and then running (run time errors)

**Comment by williamstein** [comment]
In addition to traditional ide's, c9.io (and several other cloud ides) have come up with their own mature solutions to many of these problems, so it's worth looking at them.  That said, a customizable 1-click run, like for latex, would in theory solve all problems (since it can just run an arbitrary script).

**Comment by haraldschilly** [comment]
cont.:

maybe a good way to go is to have a file `[projectname].smc-project`. it defines the root directory just by where it is, and it can be reached from a subdirectory automatically. if it exists, it is the source for defining such build/run actions, which can be exposed in the editor. if this file is openend, it is such a usual editor in a new tab, which allows to define these actions and also shows such a terminal when run (embedded, maybe in a tab?) ....

**Comment by williamstein** [comment]
Now live.
