### ISSUE TITLE
apostrophes in markdown pdf export for sage worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#57]
"I am currently working on example worksheets in SMC. I find that the markdown pdf export works better than it used to, which is great. I am still having an issue with apostrophes. 
For instance, the code "

```
%md
La théorie de l'intégration
```

yields: La théorie de lintégration

in the pdf generated via the printer icon.

Is there a way around that?

Reported by: Julien Giol

**Comment by williamstein** [comment]
The fix will involve editing some Python code in ~/.sagemathcloud/sagews2pdf.py

**Comment by Lazza** [comment]
A temporary, not very convenient workaround, is to write:

    %md
    La théorie de l\'intégration

**Comment by haraldschilly** [comment]
this has been addressed by my recent work on sagews2pdf. I also made sure to not break the escape functionality of a backslash and also not doing something "smart" that breaks formulas like `f'(x)`. So, once my changes are reviewed and merged, this ticket can be closed.

**Comment by williamstein** [comment]
fixed and live
