### ISSUE TITLE
In chat copying/pasting react components doesn't work

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#574]
I have this payload

```
{"sender_id":"f773a9ab-0e65-4a38-8b1d-9028a595d774","event":"chat","payload":{"content":"to \n\n```\n<gittab eventkey=\"{'branches'}\" icon=\"{'branches'}\" name=\"{'branches
'}\" title=\"{'Create\" and=\"\" switch=\"\" branches'}=\"\">\n                    <div style=\"{marginTop:'8px'}\"></div>\n                    <div>\n            <row>\n
            \n\n                \n            </row>\n        </div>\n                \n```</gittab>"},"date":"2016-05-25T19:21:49.228Z"}
```

What I entered into chat is 

```
<GitTab eventKey={'branches'} icon={'branches'} name={'branches'} title={'Create and switch between branches'}>
                    <div style={marginTop:'8px'}></div>
                    <div>
            <Row>
                <Col sm=12>

                </Col>
            </Row>
        </div>
                </Tab>
```

What appears in chat is 

```
to



<gittab eventkey=”{‘branches’}” icon=”{‘branches’}” name=”{‘branches’}” title=”{‘Create” and=”” switch=”” branches’}=””>


```

Note doublequotes not in my input are getting added to the chat

**Comment by haraldschilly** [comment]
currently, the html sanitizer uses jquery to produce valid html that doesn't break the overall html dom, when inserted as part of a chat message. I tried at least two other libraries, that either didn't work or didn't do everything we want. the current solution has the smallest footprint and always produces html that's not breaking the page. good start to continue where I've left off are my comments in misc_page: https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/misc_page.coffee#L1505

**Comment by williamstein** [comment]
Move to https://github.com/sagemathinc/smc/issues/874
