### ISSUE TITLE
SageMathCloud and LastPass

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#58]
According to Travis Scholl, SageMathCloud and LastPass are incompatible right now.  

Here's his report:

> I don’t know exactly why, but recently cloudsage has been very slow intermittently for me. Everything will just pause even though the ping is less than 50ms.  I looked at the dev tools in chrome and it has detected mammaliaforme a lot. Googling suggested it was related to lastpass. So I tried a new incognito window without lastpass enabled and it seemed to be fine. It could have been one of my other extensions possible, but it’s pretty annoying.

When we rewrite the sign up and sign in pages, we should test with lastpass to see if we get "mammaliaforme" a lot in the error log.

**Comment by tscholl2** [comment]
This doesn't seem to be an issue for me anymore. Yay!

**Comment by williamstein** [comment]
We deleted a huge amount of html/jquery/javascript code in the new release (switching mostly to react) a few days ago, so that must have fixed the problem. Thanks for reporting that it now works.
