### ISSUE TITLE
When displaying save error provide info on how to resolve as well as a project restart button

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#581]
I'm getting "Error saving smc/src/smc-webapp/editor_git.cjsx -- maximum time (=30000ms) exceeded - last error maximum tries (=5) exceeded - last error timeout; please try later" repeatly. I need say a project restart button or something to quickly get me back up and running.

**Comment by williamstein** [comment]
Closing.  Instead the bug is that this happens at all ever.  https://github.com/sagemathinc/smc/issues/928
