### ISSUE TITLE
bug in markdown/html output font size in sage worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#585]
Create a cell with some text and headers/indents using markdown in a Sage worksheet:

```
%md
# Foo
## bar
This is a test
- one
- two
```

Now use the font-size icons to increase the font.  The text increases, but the headers don't.

REPORTED BY: Joel Laakso

**Comment by williamstein** [comment]
Same problem for html, e.g., 
```
%html
<h1>
    Foo
</h1>

bar
```

**Comment by williamstein** [comment]
See https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-22-153951-issue585.sagews

**Comment by simonluu** [comment]
There was an issue, that I can't find anymore, similar to this with chats where changing the font size in account settings doesn't change the font sizes of the markdown chat messages.

**Comment by williamstein** [comment]
NOTE: So I think the right solution for pr 955 (issue #585) is to get rid of the Bootstrap CSS rule that hard codes the h1, h2, etc., font size in pixels. Just deleting that rule in chrome tools immediately fixes everything uniformly without any of that hackish code. Thoughts?

**Comment by simonluu** [comment]
That was my first solution, but I'm not sure how to do that.

**Comment by williamstein** [comment]
>  I'm not sure how to do that.

Figure out how... or if that is too hard, Harald or I will hopefully do so.

**Comment by williamstein** [comment]
In a sage worksheet, I put these lines in a file `a.css`
```
h1 { font-size: 250% !important }
h2 { font-size: 200% !important }
h3 { font-size: 170% !important }
```
Then I typed `%load a.css`. 

In the rest of the worksheet the problem is solved...  Maybe need more than just h1,h2,h3, and the choice of percents was sort of arbitrary.
