### ISSUE TITLE
Trying to install but get this error

### ISSUE THREAD

**Issue by Sullivanstatistics** [sagemathinc/smc#586]
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/bin/npm" "run" "install-all"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! sagemathcloud@1.0.0 install-all: `scripts/smc-install-all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sagemathcloud@1.0.0 install-all script 'scripts/smc-install-all'.
npm ERR! This is most likely a problem with the sagemathcloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/smc-install-all
npm ERR! You can get their info via:
npm ERR!     npm owner ls sagemathcloud
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/adam/smc/src/npm-debug.log
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v5.0.0/bin/node" "/root/.nvm/versions/node/v5.0.0/bin/npm" "run" "make"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! sagemathcloud@1.0.0 make: `npm run install-all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sagemathcloud@1.0.0 make script 'npm run install-all'.
npm ERR! This is most likely a problem with the sagemathcloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run install-all
npm ERR! You can get their info via:
npm ERR!     npm owner ls sagemathcloud
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/adam/smc/src/npm-debug.log
root@instance-2:/home/adam/smc/src#

**Comment by haraldschilly** [comment]
this doesn't tell me anything, what's your goal? look into the dev directory, since this install all script is most likely not what you want

**Comment by Sullivanstatistics** [comment]
I was following the directions to install smc. I was in the directory

/smc/src

Running either 

npm run install-all

Or 

./install.py all --web

Both give me this error.

**Comment by mseri** [comment]
It is an issue with `nan`. You can fix it by manually installing a modified `pty.js` (simply open `packages.json` and modify `nan` version from `2.0.5` to `2.3.5`) or by waiting for https://github.com/chjj/pty.js/pull/167 to be merged.

**Comment by williamstein** [comment]
closing
