### ISSUE TITLE
Fix/improve the checkbox that enables users to obtain and edit the generated latex when printing worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#589]
Here are the manual instructions:

Not easily.  However, if you make a terminal (+New --> Terminal) next to your worksheet, then type

  smc-sagews2pdf --remove_tmpdir=false Appendix.sagews

then look at the directory at the end of the output, which will look like this:

  /tmp/tmp4hf9YO

you can then type (in the terminal)

 cp -r /tmp/tmp4hf9YO .; open tmp4hf9YO/tmp.tex

You'll then see the latex version of your worksheet, where you can fine tune things.   E.g., you can remove the heading completely by putting % at the beginning of the line \maketitle. 

Whenever you save, it will recompile.   You can click the download button on the far right to download the pdf to your computer.

**Comment by williamstein** [comment]
The "Keep generated files in a sub-directory. This is useful for debugging printing issues or additional editing." checkbox when printing sagews should do exactly this...

BUT that doesn't work at all right now!

**Comment by haraldschilly** [comment]
Hmm, I just tried it, and it works :confused:

**Comment by williamstein** [comment]
I just tried with any random file.... but **NOT in the root directory**.  

I now see that (1) the generates files are in the root directory, even if the sagews is in a subdirectory.  (2) After doing the build, there is no link to the generated files.

**Comment by haraldschilly** [comment]
ok, I understand. so, it's at least an issue with the paths and I never worked on showing a link to it at all, so that aspect is also not solved either.
