### ISSUE TITLE
deal with a hack involving policy pages and webpack

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#599]
In this commit: https://github.com/sagemathinc/smc/commit/2eb1a81e547a51496209006f498ff68eb34cc329

**Comment by haraldschilly** [comment]
fix is this one: fe56158a093bba74ef2

I tested it by running it without any base url set, and it seems it's fine (i.e. all relative links are prefixed with `/` instead of `""`). Still, going through some staging to verify before making it public would be good. A change like that could have weird dependencies :zap:

**Comment by williamstein** [comment]
With k8s I now stage everything exactly as it would be in prod first (and
can roll back in like one second too!).

On Sunday, June 5, 2016, Harald Schilly <notifications@github.com> wrote:

> fix is this one: fe56158
> <https://github.com/sagemathinc/smc/commit/fe56158a093bba74ef20ca7944bd4b7b2096f0f0>
>
> I tested it by running it without any base url set, and it seems it's fine
> (i.e. all relative links are prefixed with / instead of ""). Still, going
> through some staging to verify before making it public would be good. A
> change like that could have weird dependencies ⚡
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/599#issuecomment-223818852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5duxJeLm0S8fkYY3CC8wAp8r00jZ8ks5qIuilgaJpZM4IuQiq>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by haraldschilly** [comment]
this old ticket is fixed, otherwise we would be in trouble ^^
