### ISSUE TITLE
Headings in %md cells now require a space after the pound signs

### ISSUE THREAD

**Issue by aarontresham** [sagemathinc/smc#60]
The following code no longer produces a heading:

    %md
    #heading

Now a space is required after the # sign to get a heading:

    %md
    # heading

This behavior may be correct, since the spaceless version could be interpreted as a hashtag instead of a heading.

Perhaps it's worth thinking about.

**Comment by williamstein** [comment]
What happens here?

#heading

**Comment by williamstein** [comment]
Closing since doesn't work in github either.
