### ISSUE TITLE
[CRITICAL] webpack fallout: the dropzone file upload is mostly broken

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#600]
It still works but the graphics/style are missing, there's no previews, and no status as you go.  It looks all broken.

**Comment by haraldschilly** [comment]
hmm. clearly, css styles are not working. in that directory is a file: `README-salvus.txt`: 

> NOTE: I had to make one change to the CSS in dropzone.css!!!

so, I'm trying to figure out what this change was. that could shed some light on this.

**Comment by haraldschilly** [comment]
although, that whole part needs some cleanup... it's probably time to update some of those libs, switch to npm when possible, and whip them into shape again.
