### ISSUE TITLE
put a dropzone below/above/near (?) the main file listing

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#61]
requested by Mesut Karakoç on the sage-cloud list.

**Comment by haraldschilly** [comment]
My idea would be to make the whole area where the files are a dropbox area. I.e. no matter if the thing beneath the cursor is a directory or not ... a dragged file will be uploaded in the current directory. As a visual aid, the entire area is getting grayed out while hovering over it.

that would be just like in google drive and similar services.

**Comment by timothyclemansinsea** [comment]
the whole page can be a dropzone https://github.com/enyo/dropzone/wiki/Make-the-whole-body-a-dropzone

**Comment by williamstein** [comment]
Remember that we are using React or rewriting to user react... so be
careful.  We can't just use things not properly supporting react.

On Sun, Mar 6, 2016 at 10:54 AM, Tim Clemans <notifications@github.com>
wrote:

> the whole page can be a dropzone
> https://github.com/enyo/dropzone/wiki/Make-the-whole-body-a-dropzone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/61#issuecomment-192962682>.
>



-- 
William (http://wstein.org)

**Comment by timothyclemansinsea** [comment]
There is a react dropzone and a question about doing full page
https://github.com/okonet/react-dropzone/issues/119

**Comment by williamstein** [comment]
> There is a react dropzone 

Yes, I think that's what we currently use for the +New page, which is written using react...  I do remember it being quite difficult though.

Note that we don't want full page drop -- we won't to make the file listing into a drop zone.   Since there can be multiple projects or pages (like account settings) for which drop doesn't make sense, it shouldn't be full page.  So it's probably pretty easy to do this for the file listing :-)

**Comment by haraldschilly** [comment]
just mentioning, that [drop-onto-files](https://github.com/sagemathinc/smc/tree/drop-onto-files) is my first attempt in doing that
