### ISSUE TITLE
Make worksheet publishable within editor

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#610]
When I'm in a worksheet I often want to publish it without going to files.

**Comment by haraldschilly** [comment]
you can click on the blue "i" on the left of the run button and select "share". that causes an action that brings to to the files dialog, but I think that's fine? or do you mean to replicate this share part right in the editor?

**Comment by timothyclemansinsea** [comment]
Didn't know about this. Closing.
