### ISSUE TITLE
delete project → revoke all quota upgrades

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#611]
when someone deletes a project via the project settings, also reset (and hence "free") all the applied quotas of that project. also, since this is then an action that's really changing something, add a confirmation yes/no like there is for deleting one's user account and so on.

**Comment by haraldschilly** [comment]
@johnjeng I've assigned this to you since it is maybe just like what you already did. feel free to unassign youself :-)

**Comment by williamstein** [comment]
This is #282
