### ISSUE TITLE
Redirect sagemath.com to cloud.sagemath.com

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#612]
I see don't the point of having sagemath.com It looks really nice though and I'd like to see some of the look and feel transferred to cloud.sagemath.com

**Comment by williamstein** [comment]
On Fri, Jun 10, 2016 at 12:04 AM, Tim Clemans <notifications@github.com>
wrote:

> I see don't the point of having sagemath.com It looks really nice though
> and I'd like to see some of the look and feel transferred to
> cloud.sagemath.com
>

I'm not sure I agree.

 -- William


> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/612>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dgW2pkwpvYJLGqYmsZF0dtO-pPHkks5qKOIygaJpZM4Iymt_>
> .
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
I just don't agree with transferring the look.   I think the redirect idea is good.   There's no important content at sagemath.com.... is there?

**Comment by timothyclemansinsea** [comment]
Nothing of importance is jumping out at me.

**Comment by haraldschilly** [comment]
done
