### ISSUE TITLE
Add "Collaborative Computational Mathematics" to logo on landing page

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#613]
I really like that "Collaborative Computational Mathematics" is near the logo at http://sagemath.com I wish it was in the logo on the landing page of SMC so everyone understands what SMC is about.

**Comment by haraldschilly** [comment]
the problem is, there is no logo. that's the "title" (configuration variable), so it's dynamically created.

of course, fiddling around with css to merge this is possible, but that would take some time to get it right and also needs testing across browsers.
