### ISSUE TITLE
a % command that ensures code block is ran after opening worksheet

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#619]
I have a worksheet https://cloud.sagemath.com/projects/111f81b5-d9cb-4c4c-a00e-7c6526e946d0/files/python_course.sagews that uses hidden code and interacts for quizzing the student. I need this code auto executed when worksheet is opened.

**Comment by williamstein** [comment]
To clarify, he means that it must be run every time the worksheet is opened in the browser, not just when the python process is started, which is what %auto does.  This might be `%onopen`?  Any other naming ideas?

**Comment by williamstein** [comment]
This means that the code should be evaluated whenever the worksheet is opened in the browser, NOT only when the process starts.   It might be called `%onopen`?  Any other name ideas?

**Comment by williamstein** [comment]
Too vague.  No clarification offered.
