### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc#62]
See https://github.com/sagemath/cloud/issues/180 for some of the issues surrounding this and exactly how or whether it might be accomplished.

**Comment by williamstein** [comment]
Too broad and too vague.

**Comment by kcrisman** [comment]
That's ridiculous.  One could at least repurpose this to ask for putting in whatever foundations were necessary for starting the i18n process.  Of course that would be a huge task, but just closing this basically says "we don't care about anything but English".  There should be an open ticket of *some* kind; it's not like you don't have localizable phrases all over the place in SMC.

**Comment by williamstein** [comment]
> That's ridiculous.

Our github issue tracker will only contain clearly defined do-able issues, not very broad vague issues like "Internationalization".  I will close any issues that are too vague.    

> just closing this basically says "we don't care about anything but English". 

No, it says that the github issue tracker for SMC won't be a list of vague ill-defined wishlist items.   

>  There should be an open ticket of some kind

There are many strategic and interesting development directions with no specific issue here, and always will be.
