### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#622]
"As a course instructor, it will be nice to have a panel to see the modifications to each assignment. Currently, I use the "bell" / notifications tab to see the recent updates. It will be good if I can filter the updates to see only modifications to certain assignments."

**Comment by williamstein** [comment]
> . It will be good if I can filter the updates to see only modifications to certain assignments.

You can -- just type the assignment name in the search by the bell.  Closing.
