### ISSUE TITLE
Better handling of no internet upgrade

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#624]
Come up with a way to get requests.get([external url]) to error immediately if no internet upgrade and show pay in place if internet connection error and project has no internet upgrade.

**Comment by williamstein** [comment]
It might also be possible to do a better job by changing the iptables rules.  I'm not sure.

**Comment by williamstein** [comment]
I can barely understand the description of this ticket.  Huh?

**Comment by williamstein** [comment]
closing since too vague.
