### ISSUE TITLE
[critical] peer grading is currently not entirely anonymous

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#626]
I just noticed “Use peer grading to randomly (and anonymously) redistribute collected homework to your students, so that they can grade it for you.” in the tutorial that Mike Croucher is writing. https://github.com/mikecroucher/SMC_tutorial/blob/master/course_management/course_management.md

In fact, peer grading is not anonymous due to a bug! It’s anonymous while grading, but not when returning. It is absolutely critical to fix this asap.

**Comment by johnjeng** [comment]
In staging [here](https://cloud.sagemath.com/7552f6e3-0f4f-4476-8954-38b9f14c6069/port/57488/) (along with initial refactor changes).

**Comment by williamstein** [comment]
> We already have removal of history. 

That code should be completely **deleted**.  History is no longer even stored in a file.  In the future, chat probably won't be either, but in the meantime, following what is done to remove history (rather changing it to chat) should easily work -- I don't know why you think it isn't easy to follow.

**Comment by williamstein** [comment]
I just tested out the code you put in "live staging", and everything works  perfectly fine, as far as I can tell, and you fixed the main concern of this ticket.

**Comment by johnjeng** [comment]
>I don't know why it is confusing.

More that I just got lost in the chain somewhere in the compute stuff after the hub. I probably just missed something.

Also, I think my current approach for this ticket seems a little heavy handed given that I just rm on the glob pattern `./*/GRADER*.txt`. Ideally, it should remove exactly <br/>`./#{eachStudentID}/GRADER - #{grader_name}`

However, it certainly seems to work. It's just one of those things that's a little implicit about the course manager. Like how students shouldn't move their assignments.

**Comment by williamstein** [comment]
On Wed, Jun 15, 2016 at 4:37 AM, John Jeng <notifications@github.com> wrote:

> I don't know why it is confusing.
>
> More that I just got lost in the chain somewhere in the compute stuff
> after the hub. I probably just missed something.
>
> Also, I think my current approach for this ticket seems a little heavy
> handed given that I just rm on the glob pattern ./*/GRADER*.txt. Ideally,
> it should remove exactly
> ./#{eachStudentID}/GRADER - #{grader_name}
>
> However, it certainly seems to work. It's just one of those things that's
> a little implicit about the course manager. Like how students shouldn't
> move their assignments.
>
We will have to move all the metadata like that to a single file --
analogous to the .course file, but one for each student project....


-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
fixed!
