### ISSUE TITLE
create academic subscription plans aimed at a full (academic year).

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#627]
REQUESTED BY: Paul Crowther

**Comment by cs1pra** [comment]
This would certainly simplify the management of payments etc.  We have several courses in one department expecting to use SMC across one or both semesters, and other departments also getting interested.  Some kind of unified subscription covering a growing number of modules across the institution would be good.

**Comment by johnjeng** [comment]
@williamstein You finished this right?

**Comment by williamstein** [comment]
Yep, good point!
