### ISSUE TITLE
Install some common Julia packages globally

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/smc#629]
Currently many of commonly used Julia packages are missing, and have to be installed on per-project basis.  That makes it impossible to use them in free projects without internet access.

Suggestion:  Install PyPlot and Gadfly for plotting, and SymPy for symbolic math.

## PyPlot:

```
Pkg.add("PyPlot")
```

When done from a notebook, restart the kernel before proceeding!

### To test:

```
using PyPlot
ion()
plot([1,2,3,4],[3,1,4,2],"-o")
```

## Gadfly:

```
Pkg.add("Cairo")
Pkg.add("Fontconfig")
Pkg.add("Gadfly")
```

When done form a notebook, restart the kernel before proceeding!

### To test:

```
using Gadfly
plot(x=[1,2,3,4],y=[3,1,4,2],Geom.point(),Geom.line())
```

## SymPy

```
Pkg.add("SymPy")
```

### Test

```
using SymPy
x = symbol("x")
factor(x^2 - 3x + 2)
```

Number of other useful packages will be installed as dependencies.

**Comment by haraldschilly** [comment]
as someone who doesn't know much about julia: are there some other packages which are also "must haves"? i.e. in a sense, that there is some traction behind it and it doesn't hurt to have them installed?

**Comment by williamstein** [comment]
I also just created this relevant ticket:
https://github.com/sagemathinc/smc/issues/636

On Sat, Jun 18, 2016 at 8:12 AM, Harald Schilly <notifications@github.com>
wrote:

> as someone who doesn't know much about julia: are there some other
> packages which are also "must haves"? i.e. in a sense, that there is some
> traction behind it and it doesn't hurt to have them installed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/629#issuecomment-226947483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dvONtRNByrmSVYrn3E_pdy-frPHpks5qNArMgaJpZM4I24T5>
> .
>



-- 
William (http://wstein.org)

**Comment by lahvak** [comment]
I mostly use Julia to teach intro linear algebra and numerical analysis, and so far I have only needed a plotting package and SymPy.  Both of the plotting packages, especially Gadfly, pull in with them whole bunch of required packages that are potencially useful, such as DataFrames, SortingAlgorithms etc.

**Comment by lahvak** [comment]
Now that the packages are installed systemwide, I see the following behavior in a project with no internet access:

After calling 
```
using Gadfly
```
I get
```
INFO: Precompiling module Gadfly...
INFO: Initializing package repository /projects/41eb44d2-462c-4af8-80a5-ac0c9cad99dd/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out

INFO: Initializing package repository /projects/41eb44d2-462c-4af8-80a5-ac0c9cad99dd/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out

WARNING: could not import LinAlg._chol! into FixedSizeArrays
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /usr/local/share/julia/site/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /usr/local/share/julia/site/v0.4/DataArrays/src/operators.jl:276.
To fix, define 
    +(DataArrays.DataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /usr/local/share/julia/site/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.AbstractDataArray, AbstractArray) at /usr/local/share/julia/site/v0.4/DataArrays/src/operators.jl:300.
To fix, define 
    +(DataArrays.AbstractDataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /usr/local/share/julia/site/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /usr/local/share/julia/site/v0.4/DataArrays/src/operators.jl:276.
To fix, define 
    +(DataArrays.DataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /usr/local/share/julia/site/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.AbstractDataArray, AbstractArray) at /usr/local/share/julia/site/v0.4/DataArrays/src/operators.jl:300.
To fix, define 
    +(DataArrays.AbstractDataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
```

It takes a very long time, and these error messages and warning appear.  Afterwards, I am actually able to use Gadfly, at least for basic plotting.

**Comment by haraldschilly** [comment]
Yes, it tries to still update from github, i.e. this line: `INFO: Cloning METADATA from git://github.com ... `

I have no idea how to tell Julia to not do that, and it seems quite strange, that you always need internet access to import a library (?)

**Comment by lahvak** [comment]
It only seems to happen the first time a package is loaded in a project.  I asked about it on julia-users, hopefully some useful info will come from that.

**Comment by haraldschilly** [comment]
Thank you!

**Comment by lahvak** [comment]
I got a [response] (https://groups.google.com/d/msg/julia-users/4ljv-W3h1Ho/atTQYndbBgAJ) to my question on julia-users, basically just pointing to the [official documentation](http://docs.julialang.org/en/release-0.4/stdlib/pkg/#Base.Pkg.dir).  I then did some experimenting with these results:

When calling `Pkg.dir()` from a Jupyter notebook, I got `"/projects/41eb44d2-462c-4af8-80a5-ac0c9cad99dd/.julia/v0.4"` which seems to be the default location for Julia to look for when `JULIA_PKGDIR` environment variable is unset.  The documentation for [`Pkg.init()`](http://docs.julialang.org/en/release-0.4/stdlib/pkg/#Base.Pkg.init) states that in that case, `init` tries to load METADATA from a repo, defaulting to github, which is what seems to be happening.  So it seems that in Jupyter notebook, the `JULIA_PKGDIR` variable is unset.

In terminal, the variable is set to  `"/usr/local/share/julia/site/v0.4"`, and when trying to load Gadfly in a Julia session running in a terminal, there was no attempt to load anything from github.  Instead, I got this error:
```
ERROR: SystemError: opening file /usr/local/share/julia/site/lib/v0.4/Gadfly.ji: Permission denied
 in open at ./iostream.jl:90
 in open at iostream.jl:102
 in stale_cachefile at loading.jl:439
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:235
```

It seems that Julia is trying to recompile the package for some reason (not sure how Julia decides that a cachefile is stale) and cannot write to the global cache directory.

So it seems that there are two issues:
1.   The JULIA_PKGDIR is unset when running in a Jupyter notebook.
2.   Julia tries to recompile "stale" global cache files and cannot do it due to permission issues.

**Comment by haraldschilly** [comment]
wow, thank you, that's very interesting and partially confirms my experience. I did miss that the env variable isn't set in the jupyter notebook, that's definitely something we can do. 

About recompilation: I'm currently trying to fix some permissions, or even delete and re-install everything globally. I also think, that running `Pkg.build()` as the global user managing the files in /usr/local/share/... might fix that stale recompilation issue. I'm just not sure, when and why julia decides that it wants to recompile, though. (without getting any new information, since there is no internet access, it shouldn't ever do that, right?)

**Comment by haraldschilly** [comment]
ok, `Pkg.build()` doesn't work as I thought, but when I import the package globally via `using ...`, then it triggers that entire compilation and no longer triggers one for the individual user. That means, I have to run `using ...` for all packages (again) ? seems like that. Also, I am not sure, but it seems to reset the umask of 022 back to 007. That's yet another cause for such permission denied errors.

**Comment by lahvak** [comment]
Again, I asked a [question](https://groups.google.com/d/msg/julia-users/BzSzdKl7HMg/pQBebMSABgAJ) about what triggers a recompile on the julia-users, so far there are no replies.

In a [discussion on github](https://github.com/JuliaLang/julia/issues/16409) I found this script that, as far as I can tell, recompiles everything via `using ...`:

```{.julia}
function recompile()
    for pkg in Pkg.available()
        try
            pkgsym = Symbol(pkg)
            eval(:(using $pkgsym))
        catch
        end
    end
end

pkgupdate() = (Pkg.update(); recompile())
```

That may help with the recompilation.

**Comment by haraldschilly** [comment]
nice, I understand enough julia now, to be even able to read it :grinning: 

and besides that, it indeed resets my umask of 022 to 077 ... so changing the permissions is also necessary. but ok, it looks like we're getting somewhere!

**Comment by haraldschilly** [comment]
commit 2e403032bf68f0d9 incorporates ideas from here

**Comment by lahvak** [comment]
[A reply](https://groups.google.com/d/msg/julia-users/BzSzdKl7HMg/6mDdRguLBgAJ) to my question on julia-users seem to have some interesting information.

**Comment by haraldschilly** [comment]
ok, read it, thank you. I think it's all met except that users need such an rc file? I don't know what it should contain, but ok, at least there is a clear path towards how to solve this

**Comment by lahvak** [comment]
I wonder if it would work as a global config, with root overriding it in the root's rc file?  What they may be saying is: when users do have an rc file, instruct them to have the site directory at the end of the path.

**Comment by haraldschilly** [comment]
So, julia is built as a special user account, not root, but anyways, that v0.4 path is by default the first one. I.e. it looks like that in a project and for that global user building the libraries:

```
julia> Base.LOAD_CACHE_PATH                                                                                                                                                                 
2-element Array{ByteString,1}:
 "/usr/local/share/julia/site/lib/v0.4"
 "/usr/usr/lib/julia"                  
```

however, the point seems to be to switch these paths around in each user's own .juliarc (or .juliarc.jl?) file. If there is no local .julia, then it is probably fine without that, though.

**Comment by lahvak** [comment]
Anyway, I just tested using Gadfly from terminal session and jupyter, and PyPlot and SymPy from jupyter, and everything seems to work great!   Thanks for your help!

I think this can probably be closed for now?

**Comment by haraldschilly** [comment]
yes, I'm also for closing. I saw on their mailing list, that 5.0 is coming out ... maybe that's when we start the next ticket.

btw: I just checked with another build container what's going on, and saw that this second path is `/usr/usr/lib/julia` ... the doubled `/usr` is really odd. It doesn't exist, but maybe julia still writes some build files somewhere and it's better to also take care of that permission issue there, too.

**Comment by haraldschilly** [comment]
and last note to our future selfs: the global juliarc config file seems to be in `/usr/etc/julia/juliarc.jl`

So ,the inverse strategy of above could be, to configure there that this site directory is at the end of LOAD_CACHE_PATH, but *then* tell the global user compiling julia libs to use it's own .juliarc.jl file, which turns around things. that way, users do not need to have a .juliarc.jl file.

**Comment by lahvak** [comment]
I just saw that Julia 1.0 is officially out, and is supposed to have a completely new package manager that supports things like nested environments and private package registries. Hopefully all these issues will now be easier to deal with.

**Comment by haraldschilly** [comment]
@lahvak maybe, at least it sounds like it should work for cases like cocalc, but I'm cautious until it really works, though :worried: 

I know about the documentation, which is quite lengthy and complex, and well, I wished there is a shorter step-by-step guide for the specific case of multi-user environments with one single global julia installation. Have you seen any of that? So far, my entire limited takeaway is to set an env variable that tells Julia about two "depots". The global one (at the expected location, nothing installed yet) and a local one at the usual location. As of today, that's

```
~$ echo $JULIA_DEPOT_PATH
/home/user/.julia:/ext/julia/julia-1/share/julia/site
```
