### ISSUE TITLE
new user with many unread notifications (optimize quickly marking all notification read, or only show notifications up to the join date)

### ISSUE THREAD

**Issue by chrmiles** [sagemathinc/smc#631]
I am a new user. When Tim helped me set up my account, the bell/notifications icon showed 120+ unread items. This seems odd having never used it before. When I attempted to mark them all read, it went very slowly and froze Chrome. Upon refreshing the page, only two notifications had been "read."

**Comment by williamstein** [comment]
There are two distinct issues here:

1. When computing the notifications for a project, should we only show the ones that go back to when the person joined the project (or SMC itself)?  Right now that "join time" isn't even known, so we would have to add it somewhere.   But we could, and in future we could use that.

2. Marking all read is inefficient.  Fixing this is a matter of understanding precisely what is happening and doing it better.  My guess is that there is some UI redux loop, where it completely updates the UI every time a single one gets marked read... and that is inefficient.

**Comment by johnjeng** [comment]
Yup, the culprit looks to be [these lines in `file_use.cjsx`](https://github.com/sagemathinc/smc/blob/65a0cfa35b707340e8de48a2a582cbc9d7cdede0/src/smc-webapp/file_use.cjsx#L76-L88). It marks each file individually.

**Comment by chrmiles** [comment]
I don't know how much this has already been discussed behind the scenes (Tim tells me I bring up things you already know) or what capabilities you have in terms of editing and revising these things... But, my initial thought is to only show notifications from the person's start or that pertain to the person - though I'm guessing the latter is already in place? That way, you don't have to go through and read things that may not be relevant to your work. 
 
I'm sure as I go along, I'll have a better idea of issues and insight into them etc.

**Comment by williamstein** [comment]
We currently have no way to define "relevant" yet.  Implement it.

On Thursday, June 16, 2016, chrmiles <notifications@github.com> wrote:

> I don't know how much this has already been discussed behind the scenes
> (Tim tells me I bring up things you already know) or what capabilities you
> have in terms of editing and revising these things... But, my initial
> thought is to only show notifications from the person's start or that
> pertain to the person - though I'm guessing the latter is already in place?
> That way, you don't have to go through and read things that may not be
> relevant to your work.
>
> I'm sure as I go along, I'll have a better idea of issues and insight into
> them etc.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/631#issuecomment-226567944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dswz22ordprvhny7ysrP0DnQYuhLks5qMZJwgaJpZM4I3c_Y>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by haraldschilly** [comment]
120 notifications are definitely too many, but I wouldn't outright eliminate showing notifications before joining the projects. this could be nice for those joining later, such that they see where the activity is?  hmmm ... maybe this should be solved in a more general sense, such that only notifications from the past two weeks or so are shown. this should also apply to **everyone**, i.e. not only those with a new account, but also those who haven't logged in for some time.

"two weeks" is just my metric for "relevant", maybe there is a better one.

**Comment by johnjeng** [comment]
I think chat notifications we can presume are "always" relevant. But maybe not. The files edited is pretty useless I think. Not that seeing files changed is useless but our implementation of it as it is feels useless. Ideally it would get moved to the Team Collaboration UI whenever that gets made (more and more excited about it..).

**Comment by haraldschilly** [comment]
> I think chat notifications we can presume are "always" relevant. 

hmm, I'm not sure, but weren't those 120 notifications about all our 120 work chats from the past 120 days?

**Comment by williamstein** [comment]
Right now you get info about the last 120-ish files and no more.  It has
nothing to do with *time*.

On Thursday, June 16, 2016, Harald Schilly <notifications@github.com> wrote:

> I think chat notifications we can presume are "always" relevant.
>
> hmm, I'm not sure, but weren't those 120 notifications about all our 120
> work chats from the past 120 days?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/631#issuecomment-226603396>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dk6AQi0lq1hNPOTQSMCIpe-Cq0-cks5qMbFtgaJpZM4I3c_Y>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by timothyclemansinsea** [comment]
Turns out we have a join datetime afterall         created :
            type : 'timestamp'
            desc : 'When the account was created.'

**Comment by timothyclemansinsea** [comment]
Oh wait a join time for the project. Well we could start with when account created.

**Comment by williamstein** [comment]
To fix, add to the projects table (under users) additional info, namely the join time of when each user last joined the project.  When showing notifications about a project, only go back as far as the join time.

**Comment by williamstein** [comment]
@DrXyzzy I believe I **fixed** this recently via introducing some throttling/debouncing of synctable notifications.   If you can test/confirm that comehow, it would be helpful... and you could close this.

**Comment by DrXyzzy** [comment]
I added one of my accounts to a project, brought up notifications, scrolled to the bottom to select "Show 180 more", and clicked "Mark all as read" and the response was immediate.
