### ISSUE TITLE
When lines highlighted, search & replace should only search/replace inside the highlighted text

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#633]

**Comment by williamstein** [comment]
Why?  Can you justify this?  The current behavior is the default (and maybe only) behavior that Codemirror (http://codemirror.net/) provides, and pretty much all of the behavior of Codemirror establishes standard conventions with editors.  What editors do what you are requesting?  Which don't?

**Comment by timothyclemansinsea** [comment]
I had to use Notepad++ in order to fix a mistake in a bunch of lines without effecting a bunch of other lines. As far as the popularity of Notepad++ this is what I found: http://lifehacker.com/five-best-text-editors-1564907215/1567287033 (Voted highest in a poll with 16K+ votes)

**Comment by williamstein** [comment]
I assume notepad++ has this behavior?    You're not saying so explicitly
below.

Changing this in sage is prob east - it will require changing the code
mirror search plugin further.    The code could even get submitted to
codemirror.

On Thursday, June 16, 2016, Tim Clemans <notifications@github.com> wrote:

> I had to use Notepad++ in order to fix a mistake in a bunch of lines
> without effecting a bunch of other lines. As far as the popularity of
> Notepad++ this is what I found:
> http://lifehacker.com/five-best-text-editors-1564907215/1567287033 (Voted
> highest in a poll with 16K+ votes)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/633#issuecomment-226668549>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dpmpXWhbjdryL_RsUIITzz0tVI97ks5qMgyQgaJpZM4I3-y9>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by timothyclemansinsea** [comment]
Yes this is in notepad++

**Comment by johnjeng** [comment]
So only when multiple lines are highlighted?

**Comment by timothyclemansinsea** [comment]
@johnjeng if lines highlighted then search/replace would only search/replace within these lines. Otherwise it would search/replace all lines. 

I didn't know about double click CTRL-F. That'll make things easier for me when doing searches. Thank you for teaching me that.

**Comment by johnjeng** [comment]
I'm going to reject this proposal unless someone offers a compelling use case that isn't solved by using `ctrl + g`

**Comment by williamstein** [comment]
I think it would be good to possibly include a little text in the find (and find/replace) display about the existence of ctrl/command+g. Otherwise, I agree with you.
