### ISSUE TITLE
improve how we provide Julia systemwide

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#636]
I spent a few hours with Jiahao Chen, of the Julia project, recently.  We talked about ways to provide Julia to users "systemwide".    He says:

> To precompile modules functions in Julia, start with a source build of Julia. In the base/ directory, create a new userimg.jl file and fill it in with lines like `require("PyPlot.jl") #build the PyPlot package` then run make and it will build a custom Julia with a system image with all those packages built in.

He told me in person that this helps clarify that "making a package install available systemwide" problem, and it also has a surprise advantage, namely that these packages may in some cases load significantly more quickly for users.

**Comment by haraldschilly** [comment]
interesting, and this is related to issue #629

**Comment by williamstein** [comment]
One surprise (to me) -- building Julia takes 2+hours on a single CPU.   It builds a lot of the same sort of dependencies as Sage as part of its build process.

**Comment by tkelman** [comment]
> create a new userimg.jl file

This method is more or less obsolete and not recommended any more from Julia 0.4 onward (which implemented the automatic `.ji` file precompilation for packages). Not sure where you're using Julia from right now, but I'd recommend just using our binary builds if you can.

**Comment by haraldschilly** [comment]
Thanks for the info, we are not using this trick anyways. (smelled like to
be brittle to me)

**Comment by williamstein** [comment]
My impression is that @haraldschilly has solved this completely in the new k8s image, etc.
