### ISSUE TITLE
Title in generated pdf from Sage Worksheet

### ISSUE THREAD

**Issue by billpage** [sagemathinc/smc#64]
Currently using the print icon in a Sage Worksheet prompts for the "Heading" (actually I think better called a title).  By default this is the file name.  It is often inconvenient for the file name and the document title to be identical and as a result it is necessary to over ride the default when producing a "printed" copy of a worksheet for distribution.

If I understand correctly, the pdf is generated by pandoc.  pandoc's extension of markdown supports the concept of metadata blocks

http://pandoc.org/demo/example9/pandocs-markdown.html#metadata-blocks

including

```
Extension: pandoc_title_block

If the file begins with a title block

% title
% author(s) (separated by semicolons)
% date

it will be parsed as bibliographic information, not regular text. (It will be used,
for example, in the title of standalone LaTeX or HTML output.)
...
Title blocks will always be parsed, but they will affect the output only when the
--standalone (-s) option is chosen. 
```

Would it be possible to use `%title` to provide the default?

**Comment by haraldschilly** [comment]
Hmm, there is no pandoc involved, at least as far as I can tell. Rather, I would suggest that the title is the very first heading in the markdown parts of the sage worksheet.

**Comment by williamstein** [comment]
You're right - pandoc isn't used for printing sage worksheets.  Pandoc is used for printing markdown files in the .md editor.

**Comment by williamstein** [comment]
What we should do is let the user customize the header (it is a header, not title). and that should get stored as a comment in the worksheet (just like special stuff in latex documents at the end). That's it.

**Comment by haraldschilly** [comment]
the sagews to html exporter I wrote looks at header html tags in the output and uses the first one for the title. in the future, we'll switch to this as a default, and hence it will work much better than now. so, in my eyes, this ticket is then solved. 

if there is really a need for a `%title`, we could implement it (i.e. it is essentially a `<h1>` title tag) and I suggest that as a follow up ticket.
