### ISSUE TITLE
Optimize landing page for signing up educators

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#641]
* Move video to about page
* Merge sign up/sign in to free up space and to reduce confusion "I watched [*redacted] try to log into SageMathCloud today and he was totally confused by the landing page. He immediately started putting his sign-in information in the create account section."
* Put benefits of SMC for teaching front and center
* Consider making tabs for features group. Track clicks of these so we know want's important to people
* Make login/sign up fixed so as scroll on desktop it's always right there for the quick conversion
* Embed https://github.com/mikecroucher/SMC_tutorial

**Comment by williamstein** [comment]
On Tue, Jun 21, 2016 at 12:57 PM, Tim Clemans <notifications@github.com>
wrote:

>
>    - Move video to about page
>    - Merge sign up/sign in to free up space and to reduce confusion "I
>    watched [*redacted] try to log into SageMathCloud today and he was totally
>    confused by the landing page. He immediately started putting his sign-in
>    information in the create account section."
>
>
Comparing our page to the Facebook landing page, and watching users myself,
I agree that the current SMC landing page is confusing.   The Facebook page
addresses precisely this confusion in a few ways:

1.  "Sign Up" is the largest text on the Facebook landing page.
2. Autofocus the login email address field (as proposed by John), maybe due
to Facebook knowing that most people are logging in now?

3. The sign in part of the page has a blue background -- it is very clearly
visually separated from account creation.  We don't do that.

4. The input placeholder text reinforces account sign up, e.g., "New
password".  Also the input placeholder text is big and bold, and I bet they
aren't not the normal input hinting provided by the browser.

5. The "Sign up" button is ridiculously clear with a big bold font.




>
>    - Put benefits of SMC for teaching front and center
>    - Consider making tabs for features group. Track clicks of these so we
>    know want's important to people
>    - Make login/sign up fixed so as scroll on desktop it's always right
>    there for the quick conversion
>    - Embed https://github.com/mikecroucher/SMC_tutorial
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/641>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dre8PBg8bVdBV8PMEGZ1FPZBZ9RZks5qOEIwgaJpZM4I7HLQ>
> .
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
I think you did this already.
