### ISSUE TITLE
Trim origins of Sagemath video 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#642]
https://www.youtube.com/watch?v=6eIoYMB_0Xc trim first 2:19 using https://support.google.com/youtube/answer/183851?hl=en

**Comment by GregoryBard** [comment]
Alternatively, just distribute this link instead, which trims that:

https://youtu.be/6eIoYMB_0Xc?t=2m18s

Problem solved? :)
---Greg

**Comment by haraldschilly** [comment]
no, jumping to a timecode is not really helpful. the editor is here: https://www.youtube.com/editor

**Comment by williamstein** [comment]
Should be fixed as soon as the re-render is done.
