### ISSUE TITLE
preview chat messages before sending

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#644]
when typing in a new message in chat, preview it with rendered markdown+mathjax to avoid malformatted entries.

requested by Marcelo Forets

**Comment by williamstein** [comment]
Just a note, learned from experience, is that it is critical to debounce the "realtime" preview, to avoid slowing down typing.

**Comment by johnjeng** [comment]
My implementation plan for this was to simulate GitHub's comment box. ie. the one I'm using to type this. Add tab that says Preview. Yeah, live preview is cool, but I don't think it's necessary in this case.

**Comment by williamstein** [comment]
I disagree -- I don't like github's so much -- it's extremely annoying to me, especially if the text is at all large (due to position resetting).   Also, we already have live preview for markdown in the task list and the markdown editor and html editor, so it is natural to have live preview everywhere else.

**Comment by haraldschilly** [comment]
@johnjeng implementation idea: use the actual chat-area, where the chat bubbles appear, to render the preview. e.g. the box is grey and clearly distinct, and has a debounced preview with 2-3 secs. that doesn't occupy additional real estate, and when those "does it has to rerender" updates are computed correctly, only the very last box should update. 

(and just for confused users, maybe add an additional send button at the bottom ...)

**Comment by johnjeng** [comment]
>due to position resetting

Do you mean when going from Preview to to Write? That's fixable like lost scroll position in chat when changing smc tabs. 

My problem with live preview is that for longer messages, I have to scroll up and down to check out what I've been editing. Live preview for the markdown editor and html editor make a lot of sense since the screen real estate exists. In chat and task list, it doesn't really. I think neither should have live preview.

>use the actual chat-area

Okay, I'm down with this idea. I think coloring it differently and having some sort of warning will adequately communicate that it is a *preview* and not sent yet. I think there should also be an option  to toggle the preview (default on). I personally don't actually care to see my changes typed live.

**Comment by haraldschilly** [comment]
> Okay, I'm down with this idea.

I understand that you think this is a good idea? you can also split the main window, or somehow limit the vertical height by "50%" or so, to add scrollbars if it is really more a full email than a chat message.

also, the main use-case is when someone is writing latex formulas. there are users, who have no hesitation to write super large ones, but without a preview it does go awfully wrong. so, don't forget of mathjax :see_no_evil:

**Comment by williamstein** [comment]
On Fri, Jun 24, 2016 at 12:24 PM, John Jeng <notifications@github.com>
wrote:

> due to position resetting
>
> Do you mean when going from Preview to to Write? That's fixable like lost
> scroll position in chat when changing smc tabs.
>
> My problem with live preview is that for longer messages, I have to scroll
> up and down to check out what I've been editing.
>
For this to be a problem with @hsy's design, the message would have to be
so long that it takes up the entire page.  That's unlikely.

To add to @hsy's remark.... we could actually show that preview to
everybody as well.  That would be consistent with Sage.  Yes, I know, we're
recreating google wave...



> Live preview for the markdown editor and html editor make a lot of sense
> since the screen real estate exists. In chat and task list, it doesn't
> really. I think neither should have live preview.
>
Disagree.  With tasks it's very useful.


> use the actual chat-area
>
> Okay, I'm down with this idea. I think coloring it differently and having
> some sort of warning will adequately communicate that it is a *preview*
> and not sent yet. I think there should also be an option to toggle the
> preview (default on). I personally don't actually care to see my changes
> typed live.
>



-- 
William (http://wstein.org)

**Comment by johnjeng** [comment]
>we could actually show that preview to everybody as well.

-1  I don't need everyone seeing random stuff I may or may not decide to send. What's the use case?
>Disagree.  With tasks it's very useful.

I will yield since I don't feel too strongly about my position.

**Comment by haraldschilly** [comment]
> I don't need everyone seeing random stuff ...

me neither, however, there is a whole startup in the messenger area about this: http://www.beammessenger.com/

**Comment by williamstein** [comment]
On Fri, Jun 24, 2016 at 1:45 PM, John Jeng <notifications@github.com> wrote:

> we could actually show that preview to everybody as well.
>
> -1 I don't need everyone seeing random stuff I may or may not decide to
> send. What's the use case?
>

(1) people see random stuff you may or may not evaluate in a worksheet, so
this is no different

(2) I've always planned to extend what one can do in chatrooms (and task
lists), e.g., what if a chat starts with
```
%sage
a = 5
...
```
You could have it run code.  Multiple people might contribute to writing
the input.  A whole class might watch as an instructor types input...



> Disagree. With tasks it's very useful.
>
> I will yield since I don't feel too strongly about my position.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/644#issuecomment-228457556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dsBzD8hyvbd10fLTXSEl6my_TrAjks5qPEHygaJpZM4I7elR>
> .
>



-- 
William (http://wstein.org)

**Comment by johnjeng** [comment]
>so this is no different

The difference being content. With chat, you're communicating ideas and emotions. Incorrectly communicating them the first time can lead to a lot of hassle and trouble. Here are some responses of people I just asked about.

> I already have a tough time communicating ideas and emotions properly over text

>One of the best things about text medium is that it lets me move through my thoughts at a relaxed pace where I can explore them and take time to adequately translate ideas from the abstract space in my brain into actual words. Seeing and reviewing them is important for me.

>Yep that's dumb

>If I was forced to use that for some reason, I would type my messages in another program and copy them in

**Comment by johnjeng** [comment]
If it gets implemented, it should be **off by default**. I do not see the upsides for general chat. 

>(2) I've always planned to extend what one can do in chatrooms (and task
lists), e.g., what if a chat starts with ...

This is a valid use case but very outside what people normally consider to be chat. I will think about this more.

**Comment by williamstein** [comment]
On Fri, Jun 24, 2016 at 2:08 PM, John Jeng <notifications@github.com> wrote:

> so this is no different
>
> The difference being content. With chat, you're communicating ideas and
> emotions.
>

Chatrooms can be used to to communicate ideas/emotions, in which case live
sync is probably not useful.  Chatrooms can also be used for other things,
e.g., code, in which case live could be extremely useful.



> Incorrectly communicating them the first time can lead to a lot of hassle
> and trouble. Here are some responses of people I just asked about.
>
> I already have a tough time communicating ideas and emotions properly over
> text
>
> One of the best things about text medium is that it lets me move through
> my thoughts at a relaxed pace where I can explore them and take time to
> adequately translate ideas from the abstract space in my brain into actual
> words. Seeing and reviewing them is important for me.
>
> Yep that's dumb
>
> If I was forced to use that for some reason, I would type my messages in
> another program and copy them in
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/644#issuecomment-228462433>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5doiu9kNeZgTaYTAqPSBq5IslhmYZks5qPEc2gaJpZM4I7elR>
> .
>



-- 
William (http://wstein.org)

**Comment by mforets** [comment]
Guys, I find that live preview as it works in stackexchange (you know, http://mathoverflow.net/questions/ask )
is pretty cool; for usual plain text communication I would just use e-mail.
