### ISSUE TITLE
sagews renders data uri image briefly, replaces with missing image icon

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#651]
Try the following in a sage worksheet:
```
%html(hide = False)
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="red dot" />
```
The red dot will appear for a moment then be replaced by a missing image icon.
Re-running the cell will not cause the dot to appear unless you edit the cell.

**Comment by williamstein** [comment]
Confirmed here: https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/tmp/2016-09-22-140024%20--%20issue%20651.sagews
