### ISSUE TITLE
Going to published worksheet unauth redirects to homepage

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#652]
Go to https://cloud.sagemath.com/projects/d0e29931-912d-474a-abc0-fbbb9735e2eb/files/1.sagews while logged out

**Comment by johnjeng** [comment]
I see it.

**Comment by timothyclemansinsea** [comment]
@johnjeng looks like it got fixed. I was getting redirected to homepage for some reason when not logged in.
