### ISSUE TITLE
Create a site availability status Twitter and show the last message from it when there are connections issues

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#654]

**Comment by williamstein** [comment]
Actually, we should just update the static content at CloudFlare, right?  Harald, have you looked into that.

**Comment by timothyclemansinsea** [comment]
I'd still like a system message I get even when SMC completely down. So if I'm working and SMC goes down I'd like to still see a blue popup.

**Comment by williamstein** [comment]
You have a good point.  So you mean that some javascript thing periodically runs in your browser (in smc) checking for something (say on twitter, but maybe somewhere else), and if it finds it, then it shows you a notification?

**Comment by timothyclemansinsea** [comment]
Yes please.

**Comment by haraldschilly** [comment]
we have our appengine instance running, that would be a good place to run such a monitoring. the real IP addresses of the hubs could be there, etc... the real question is, what the test should really do and how the data is synced up.

**Comment by timothyclemansinsea** [comment]
If you setup a custom error page via Cloudflare the Twitter feed could be embedded on it.

**Comment by timothyclemansinsea** [comment]
I think this needs to be done today as we've already gotten 4 people messaging about this.

**Comment by timothyclemansinsea** [comment]
I started a twitter account https://twitter.com/smcstatus Note I was able to put a + in my email so I think we can use office email account with + to have multiple twitter accounts.
