### ISSUE TITLE
Add to help dialog how to get help for non-SMC issues

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#655]
Support gets requests for support on programming. The reply is usually to use ask.sagemath.org I just looked at the help dialog and see no mention that one needs to use other outlets for programming support.

**Comment by williamstein** [comment]
On Tue, Jun 28, 2016 at 11:40 PM, Tim Clemans <notifications@github.com>
wrote:

> Support gets requests for support on programming. The reply is usually to
> use ask.sagemath.org I just looked at the help dialog and see no mention
> that one needs to use other outlets for programming support.
>
>
>
We could also consider providing more support for that sort of thing
too.... not sure.



-- 
William (http://wstein.org)

**Comment by haraldschilly** [comment]
It also depends on what you're doing. It's like likely that it is with SageMath, but as well it could be for R, matplotlib related, pandas, etc. I'm actually happy to see those questions and do a quick triage, because then I know what users are up to.

**Comment by johnjeng** [comment]
My concern is that then users have to decide if they think it's an SMC issue or problem with the underlying software. I think it's value added that we receive these support requests. At worst, it's quick to point them in the right direction. And at best people like us a lot more.

**Comment by GregoryBard** [comment]
I could put a handful more references to " ask.sagemath.org " throughout
the wiki/FAQ system, if desired.
---Greg

p.s. My redesign of the wiki/FAQ system is almost finished. I'm just having
some thoughts about the best ways to format one particularly tricky page:
Questions about the mathematical syntax of Sage.

**Comment by williamstein** [comment]
On Tue, Jul 5, 2016 at 2:39 PM, GregoryBard <notifications@github.com>
wrote:

> I could put a handful more references to " ask.sagemath.org " throughout
> the wiki/FAQ system, if desired.
>

I think the decision above was to not do that.   Often we can provide
vastly better help in SMC anyways, since we have access to user work.


> ---Greg
>
> p.s. My redesign of the wiki/FAQ system is almost finished. I'm just having
> some thoughts about the best ways to format one particularly tricky page:
> Questions about the mathematical syntax of Sage.
>
> On Wed, Jun 29, 2016 at 1:40 AM, Tim Clemans <notifications@github.com>
> wrote:
>
> > Support gets requests for support on programming. The reply is usually to
> > use ask.sagemath.org I just looked at the help dialog and see no mention
> > that one needs to use other outlets for programming support.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/sagemathinc/smc/issues/655>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ASgz1Q7xOf9bf-rDCFDW9x7GOHHfvExjks5qQhNYgaJpZM4JA0TB
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/655#issuecomment-230611087>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dvmG6kVnpthFEiIlEOJSnu4uPPUnks5qSs7_gaJpZM4JA0TB>
> .
>



-- 
William (http://wstein.org)

**Comment by GregoryBard** [comment]
On Tue, Jul 5, 2016 at 4:42 PM, William Stein <notifications@github.com>
wrote:

> On Tue, Jul 5, 2016 at 2:39 PM, GregoryBard <notifications@github.com>
> wrote:
>
> > I could put a handful more references to " ask.sagemath.org " throughout
> > the wiki/FAQ system, if desired.
> >
>
> I think the decision above was to not do that. Often we can provide
> vastly better help in SMC anyways, since we have access to user work.
>
>
Very good then. I will leave it out.

If this ever changes later (e.g. if the number of SageMathCloud users goes
up by a factor of 100) then we can always add that link later.
---Greg

**Comment by williamstein** [comment]
> If this ever changes later (e.g. if the number of SageMathCloud users goes
up by a factor of 100) then we can always add that link later.

We would either hire more people to answer support questions, or only provide support to paying users.
