### ISSUE TITLE
in account settings make the buttons (e.g, sign out, sign out everywhere, delete account) have "..." (three dots) at end to indicate that they bring up a dialog

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#657]
This is for consistency with other places, e.g., course management.

**Comment by williamstein** [comment]
Also, after clicking delete account, the Delete Account button should *NOT* disappear.   See what happens with the other buttons like sign out -- they don't vanish.

**Comment by johnjeng** [comment]
But `Change email` and `Change password` do. So change those too then?

**Comment by williamstein** [comment]
> But Change email and Change password do. So change those too then?

Yes.  Those were literally my first ever react buttons.    Look at how the link/unlink accounts buttons work (on the live site).

**Comment by johnjeng** [comment]
Cool. I'll also make the button disabled when the extra dialogue box is open. This is consistent with Course Editor.
