### ISSUE TITLE
Misleading timestamps in chat when two consecutive messages are from the same person, but very far apart in time.

### ISSUE THREAD

**Issue by GregoryBard** [sagemathinc/smc#661]
Currently, if someone types several consecutive messages in chat, with perhaps large amounts of time between each message, the visual grouping of the messages is misleading. It makes it appear as though all those messages were sent *at the timestamp of the last message*.

Perhaps an easy way to make the timestamps honest would be to move the timestamp *inside* the almost-rectangle, after the last line of text. that way, if you merge three consecutive almost-rectangles, then each can still have its own distinct and accurate timestamp.

Two screen-shots are attached.

<img width="1041" alt="screen shot 2016-06-29 at 4 43 52 pm" src="https://cloud.githubusercontent.com/assets/19411925/16469941/3a7799ca-3e19-11e6-8280-6ed079c8eac4.png">
<img width="1038" alt="screen shot 2016-06-29 at 4 43 44 pm" src="https://cloud.githubusercontent.com/assets/19411925/16469942/3a7c993e-3e19-11e6-9c8c-2f39a1ae4b3a.png">

**Comment by johnjeng** [comment]
So how about moving it into the lower right corner of each chat box?

An alternative is to show timeago (and a chat head) whenever the timestamp between 2 messages is longer than 1 min. 

I think I'm in favor of the former though.

**Comment by GregoryBard** [comment]
Personally, I would be in favor of the first option.

Have the timestamp be at the lower-right corner of each chat box. (What I
called an "almost-rectangle" since it isn't really a rectangle---it has
rounded corners.)
---Greg

**Comment by johnjeng** [comment]
Great, we're in agreement. I'll have Simon change this today.

**Comment by haraldschilly** [comment]
I'm rather for merging consecutive chats into the same single box (like slack or so), but only if it is less than 1 minute apart and nobody else did talk. (the delimiter is just two newlines). Reason is, that I quite often just add a sentence to what I just wrote, which would fit well right into my last box.

**Comment by johnjeng** [comment]
I am closing this due to the initial request being fixed. If anyone feels strongly about another position, we can discuss it in a separate thread.
