### ISSUE TITLE
Have an option to auto scroll to bottom of chat

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#665]
I leave my chat open on a dedicated screen. I'd like to have a checkbox to auto scroll chat to bottom when checked. When I scroll up I'd like the checkbox to become unchecked.

**Comment by johnjeng** [comment]
We will have it auto scroll when you're at the bottom. Simon is implementing this today. Will this be sufficient for your needs?

**Comment by timothyclemansinsea** [comment]
Yes

**Comment by johnjeng** [comment]
Great. Closing this issue then.
