### ISSUE TITLE
On an iPhone using Google Chrome with SMC chatrooms, it is not possible to type input.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#669]
This is for chatrooms. You can focus the input field, but then the keyboard starts fickering like crazy and you can't type.  It's probably something involving scrolling or rendering on click, which makes an assumption that is wrong (or a bug in mobile chrome that we should maybe work around).

Note: safari on iPhone works fine.

**Comment by johnjeng** [comment]
Also on Android using mobile Chrome. Seems to continually redraw and refocus the text box. Sometimes you get time to fit in a letter or there.

**Comment by williamstein** [comment]
Works now.
