### ISSUE TITLE
Courses --  ignore deleted assignments when adding new assignments

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#67]
Reported by: Jane Shevtsov

**Comment by johnjeng** [comment]
This is already true.

**Comment by williamstein** [comment]
Do you mean you fixed this in some branch not in master?   It's definitely broken in Master.  I just made  a course and tested it with the simplest example and it failed.

**Comment by johnjeng** [comment]
Interesting. I added an assignment, deleted it in the .course file, and then it doesn't show up in add assignment search.

**Comment by williamstein** [comment]
> Interesting. I added an assignment, deleted it in the .course file, and then it doesn't show up in add assignment search.

Which is the whole point!  That's the problem.   You just confirmed that the bug is still there.

Imagine you are Jayadev Arethraya and you get access to our math 480 course file for a day (like he did).   Then you add the directory `assignments/` as an assignment (like he did).  Then you notice that this is a mistake and delete that assignment (like he did).  Then you're me and you try to add `assignment/assign8`, like I did, but it won't show up!  URGH.  The reason is because assignment search won't show anything that is contained in any existing assignment, both deleted or not.   When this happened last quarter to us, I had to manually edit the .course file with vim to remove `assignments` as an assignment.    Having a way to permanently delete all deleted assignments would also be good (we have that for students, but I never got around to implementing it for assignments).

**Comment by johnjeng** [comment]
Ah. I get it. I thought that was intentional behavior. lol

I'm 100% on board with this. Will fix it tomorrow.

**Comment by williamstein** [comment]
On Tue, Jun 21, 2016 at 8:18 PM, John Jeng <notifications@github.com> wrote:

> Ah. I get it. I thought that was intentional behavior. lol
>
> I'm 100% on board with this. Will fix it tomorrow.
>

Awesome, thanks!  Because I really want this fixed, but I'm trying to
architect an iscsi storage backend thing... and it's really far away from
this.  THANKS!


> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/67#issuecomment-227632555>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABN5dqajy0KR6oeCTV4PYEiHcz_qu3k2ks5qOKmSgaJpZM4Ftwvw>
> .
>



-- 
William (http://wstein.org)

**Comment by johnjeng** [comment]
Okay, clarification request on this ticket.
Is it "We want to include deleted assignments in the list" or is it "We want to be able to still add subfolders of deleted assignments as new assignments?" 

My thoughts right now are:
1. Do **not** show deleted assignments
2. However, include sub-directories of deleted assignments.

My alternative to (1) is include deleted assignments. If selected, just undelete them. Maybe mark them as deleted.

**Comment by johnjeng** [comment]
Another alternative is to implement "true" deletion of assignments and rename the current stuff as "trash", "recycle", "stashed", or "hidden". The problem being fixed is that when I delete an assignment, I expect the manager to forget about it. This means that I should be able to add it again. This has come up while showing an instructor how to use assignments.

**Comment by williamstein** [comment]
Implement true deletion is definitely the way to go.

Also, if an assignment doesn't show up in the list due to a trashed one
hiding it, show a message saying so, with a button to delete all trashed
assignments.

That would probably nicely solve all these problems.

On Fri, Jun 24, 2016 at 12:46 PM, John Jeng <notifications@github.com>
wrote:

> Another alternative is to implement "true" deletion of assignments and
> rename the current stuff as "trash", "recycle", "stashed", or "hidden". The
> problem being fixed is that when I delete an assignment, I expect the
> manager to forget about it. This means that I should be able to add it
> again. This has come up while showing an instructor how to use assignments.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/67#issuecomment-228443987>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABN5dk3IfCILtX75ahFSk1WbBNkQ3zxRks5qPDQegaJpZM4Ftwvw>
> .
>



-- 
William (http://wstein.org)

**Comment by johnjeng** [comment]
Original issue fixed in #680 (True deletion and trash not implemented).

**Comment by williamstein** [comment]
@johnjeng -- can you close this and make issues for what isn't done yet?   I think the problem described in the title is something you completely solved already

**Comment by johnjeng** [comment]
Yup. I'll add that to my todo's for today.
