### ISSUE TITLE
On mobile, do not autofocus most forms.

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#670]
Automatically pulling up the keyboard is awful.

**Comment by timothyclemansinsea** [comment]
For now don't change this for chat as without autofocus=true for chat it doesn't work at all in Chrome on Mobile.

**Comment by williamstein** [comment]
Make a specific list or I'll close.  This seems too vague.  I also frequently use SMC on mobile, and am not actually that annoyed by the current autofocus behavior.  Anyway, this too vague.

**Comment by johnjeng** [comment]
Fine with me.
