### ISSUE TITLE
it should not be possible to add any collaborator on the project that contains a course as a student to that course

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#677]
Right now the own/collaborators on a project that contains a course can also be added to the course.  This leads to all kinds of problems and is not intended behavior.

**Comment by johnjeng** [comment]
I'm not sure where and how this should take place. Options
1. They should not show up in search
2. They show up in search but are greyed out.
3. They show up but don't get added when attempting to do so.
4. Filtering occurs hub side
5. Filtering occurs client side.
6. Prevention occurs in the hub

I'm liking the combination of 2. and 5.

**Comment by johnjeng** [comment]
To me this case supports the idea that there should be a separate notion of "Widgets" in a tab for a project like "Files" or "Settings". It can manage the things that manage files in your project. For example so far, Courses and Git. 

Then it can do things like keep an aggregate list of all the courses' students you have on your project. But this is probably further down the line if we want it.

**Comment by williamstein** [comment]
2 and 5 with an explanatory message

On Tuesday, July 5, 2016, John Jeng <notifications@github.com> wrote:

> I'm not sure where and how this should take place. Options
> 1. They should not show up in search
> 2. They show up in search but are greyed out.
> 3. They show up but don't get added when attempting to do so.
> 4. Filtering occurs hub side
> 5. Filtering occurs client side.
> 6. Prevention occurs in the hub
>
> I'm liking the combination of 2. and 5.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/677#issuecomment-230629459>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dg0pR2yr2Tz_5Cdotlvi6EUk6KU9ks5qSuR4gaJpZM4JErnp>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by johnjeng** [comment]
Okay. Here's my plan for implementation which is not as robust as it could be:

Have the project store students added to any course and removed if the student is deleted. When adding collaborators, the project will check to see if its files have ever been scanned for courses. If it hasn't, it will do so and add those students to the no-add list. If it has been scanned before, it will just use the current no-add list that is on the project.

Concerns:
- Old courses copied from another project after scanning happens once
- Old courses where a current TA was a past student. Relevant for instructors who keep all their courses in the same project. 

Not really sure how to solve the first problem.

For the second problem, old courses are also useful for keeping a record of students and activity. Thus I would not like to just delete the old course or any of its students. My thought is to allow courses to be "Archived" -- marked as old/finished (maybe with slightly different UI in the future, who knows?).

**Comment by johnjeng** [comment]
Unless I don't have to scan for `.course` files at all for some reason.

**Comment by williamstein** [comment]
Seeing everything above and thinking about this, I've completely changed my mind.   Let's support allowing collaborators on the project containing the course to also add themselves.  Probably the only thing that is broken now is whether the student project is hidden or shown -- it should currently shift back and forth, because different parts of the code want each.  Instead, it should never get hidden when the account is also a collab on the course.

**Comment by johnjeng** [comment]
So we want the following behavior:
- Students in a course can be added to the course's project
 - That student's project should become unhidden to all collaborators
 - Upon removal of the student from the course's project, the student's project should become hidden again
- Collaborators on a course's project can be added as a student on the course.
 - The new student project should be visible to all collaborators instead of hidden. 

I think only the latter doesn't exist right now.

**Comment by williamstein** [comment]
> Collaborators on a course's project can be added as a student on the course.

I'm not going to implement this; instead, I'm going to implement what the title of this issue says: "it should not be possible to add any collaborator on the project that contains a course as a student to that course".   And that's it.  

Right now, that is implemented properly when you do a name search, but not on doing an email search -- there is a clear bug in an attempt to implement what is described in the title of this issue.  I will fix that bug, then close this.   

Later we may have something new that implements a way for collaborators to also be students.
