### ISSUE TITLE
Make function of cell input/output display toggle buttons in Sage Worksheet more obvious

### ISSUE THREAD

**Issue by ursulawhitcher** [sagemathinc/smc#68]
Sage Worksheets have a group of 3 buttons for toggling display of input, toggling display of output, and deleting output, respectively.  From their icons, it is not obvious what they do.  In particular, the toggle output button looks like it is used for inserting graphs or images.

Change the icons or add text to make the functions of this group of buttons more obvious.

**Comment by williamstein** [comment]
Maybe way better now due to side toggles.
