### ISSUE TITLE
If user has no projects at all, open "create new project"

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#684]

**Comment by kcrisman** [comment]
+1 especially since the setting page is kind of busy.

**Comment by GregoryBard** [comment]
Yes, definitely a +1 from me too... the current system might be
intimidating to many new users. "Create new Project" is much less
intimidating.
---Greg

**Comment by williamstein** [comment]
changed title, since projects/ is already the default...

**Comment by kcrisman** [comment]
Awesome.

**Comment by williamstein** [comment]
Closed because already implemented a while ago.

**Comment by kcrisman** [comment]
Yes, I understand that - just celebrating!
