### ISSUE TITLE
make a docker container version of single-user SMC-for-development

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#693]

**Comment by dimpase** [comment]
doc in docker/ does not say which OS one needs... (not any, right)?

**Comment by williamstein** [comment]
> doc in docker/ does not say which OS one needs... (not any, right)?

This is like asking about which OS one needs to run VirtualBox.

**Comment by williamstein** [comment]
https://github.com/sagemathinc/smc/tree/master/src/dev/docker

**Comment by dimpase** [comment]
hmm, should it it least be capable of running Sage?
