### ISSUE TITLE
install mpl3d for python3

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#695]
Requested by a user.  Did via --user for them.  Might as well make available systemwide.

**Comment by GregoryBard** [comment]
mpl3d as in ...

http://www.mpl3d.com/solar.htm

?

If so, then COOL!
---Greg

**Comment by williamstein** [comment]
Nope

On Monday, July 11, 2016, GregoryBard <notifications@github.com> wrote:

> mpl3d as in ...
>
> http://www.mpl3d.com/solar.htm
>
> ?
>
> If so, then COOL!
> ---Greg
>
>
> On Mon, Jul 11, 2016 at 5:30 PM, William Stein <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Requested by a user. Did via --user for them. Might as well make
> available
> > systemwide.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/sagemathinc/smc/issues/695>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ASgz1TuKjEIfo7H2n-5DynnHuNDYYhsRks5qUsPzgaJpZM4JJ3Vs
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/695#issuecomment-231889914>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5du2RhC8YC8FTSZEcrgCxONHWJJDgks5qUsnRgaJpZM4JJ3Vs>
> .
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by haraldschilly** [comment]
yes, good idea to have that

**Comment by haraldschilly** [comment]
ok, well, it was already installed for python 2 and for anaconda. maybe we should direct such users to use anaconda? having an python3 environment two times is a bit of an overlap. but ok, now it's also in python3.
