### ISSUE TITLE
add syntax highlighting and editing support (?) for jsx files

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#718]
I opend a .jsx file recently in SMC and it isn't even syntax highlighted.   

Doing this means editing editor.coffee a little, and should be easy.

**Comment by johnjeng** [comment]
It appears that CodeMirror doesn't have jsx defined in `CodeMirror.modes` or `CodeMirror.mimeModes`. I don't know how to require it in codemirror.coffee. Imitating the other requires doesn't work. 

Maybe it's in a newer version of codemirror? I'll look into it more.

**Comment by williamstein** [comment]
> Maybe it's in a newer version of codemirror? I'll look into it more.

Yep, it's in a slightly newer version.  https://github.com/codemirror/CodeMirror/issues/3122  

We need to upgrade codemirror...  Maybe @haraldschilly  already did in something that is bitrotting.

**Comment by williamstein** [comment]
time: 0:10
