### ISSUE TITLE
window.smc sometimes doesn't get set, or gets deleted (?)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#720]
`window.smc` is defined in the constructor in `smc-webapp/client_browser.coffee`; no clue how it gets deleted.

**Comment by haraldschilly** [comment]
that's interesting, I'm currently looking into it

**Comment by williamstein** [comment]
Solved in 28 minutes :-).   Surprising solution to #720 -- http://stackoverflow.com/questions/3275816/debugging-iframes-with-chrome-developer-tools/8581276#8581276   - you have to set the Chrome context to top sometimes.
