### ISSUE TITLE
Various URLs not working/redirecting

### ISSUE THREAD

**Issue by GregoryBard** [sagemathinc/smc#721]
Edited by John:

The following are working:
- [x] sagemath.cloud
- [x] sagemathcloud.com 
 - "This site can’t be reached www.sagemathcloud.com’s server DNS address could not be found." 
- [ ] sagemathcloud.org
  - "This site can’t be reached, sagemathcloud.org took too long to respond."
- [ ] sagemath.academy 
 - "This site can’t be reached www.sagemath.academy’s server DNS address could not be found."

Ideally, these should all redirect to whatever URL we are using, presumably cloud.sagemath.org

**Comment by williamstein** [comment]
sagemathcloud.org should work in an hour.  
sagemath.academy doesn't make sense -- there's hundreds of other tld's.
