### ISSUE TITLE
change "magic" to "mode" in sagews Help menu, and also replace the command "magics()" by "modes()"; search docstrings and replace

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#722]
Why?

"magics" is a really bad name.  It is non-descriptive, suggests something that can't easily be understood, and can cause confusion with Jupyter.   Our %mode's are very easy to understand.

The dictionary definition of "magic" is "the power of apparently influencing the course of events by using mysterious or supernatural forces."

Much better is the word "mode".  That's why the first menu is called "modes".  The dictionary definition of mode is "a way or manner in which something occurs or is experienced, expressed, or done."   That's pretty much what %foo does.

**Comment by DrXyzzy** [comment]
.Done

**Comment by GregoryBard** [comment]
The good news is that I can confirm that the word "magic" does not occur
anywhere in the wiki/FAQ, except one file (that exists in two versions). I
checked this using "grep."

The bad news is that it does appear in both the new and old versions of
sagejupyter.md.

Unfortunately, I know nothing about Jupyter. For example, I cannot
determine how to rewrite the following lines:

1. If `default_mode` is enabled for the jupyter magic and a cell starts
with a jupyter magic command, the cell needs to start with a comment or
mode decorator, or the jupyter magic will be interpreted as a sagews magic.
1. Long docstring and `magic` create scrollable div, but there is no close
button.

Hal, perhaps you could edit this file:
https://cloud.sagemath.com/projects/c096352d-b392-499a-8899-6bfa794d7504/files/smc.wiki/new_SageJupyter.md
which is the new version.

There's no need to update the old version.
---Greg

**Comment by DrXyzzy** [comment]
@GregoryBard, updates done.
