### ISSUE TITLE
sagews: implement `search_doc` and `search_src`

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#724]
I don't think this cheap approach is worth doing:
```
def f(*args, **kwds):
    kwds['interact'] = False
    html(search_doc(*args, **kwds), hide=False)
```
I couldn't even find an input that was less than 100K+ characters. 
We really should just have it maybe paste in a link or something that uses what Harald setup on sagemath.org for searching the docs (via google).  It'll be faster and vastly better than the slow grep-based thing builtin.  

Similar remarks for search source, but maybe use github?

Ideas?  For starters it would be good on this issue to at least give URL's that would provide useful searches.

A point here is that users of SMC worksheets are *assumed* to be on the public internet and probably just want to search the latest source code -- it's different than command line users that are possibly offline.  Our docs should reflect that.

**Comment by haraldschilly** [comment]
So, I don't really know what this is supposed to really search, but that search on the sagemath website is broken for a long time, since the API was deprecated and has been turned off. I briefly looked into the new api, but I didn't got far. They also clearly try to monetize it. The second issue is, that I'm working with paul masson for the last couple of weeks to properly index the documentation pages with google -- which is surprisingly hard since there are so many broken links etc.

Personally, for searching code I always use `git grep`, which is way faster and more accurate than the file based search -- I guess, it doesn't read each file but goes through the storage packs. The code search at github is definitely not good, since it seems to be based on elastic search or so, and doesn't index everything either. My impression is, that it stops with larger files at a certain threshold.

**Comment by williamstein** [comment]
> git grep...

This would work for `search_src`, which searches the source code of Sage.   It isn't useful for `search_doc`, which searches the autogenerated html docs.

> API...

Instead of using some fancy API, we can easily just make a URL like https://www.google.com/search?q=site%3Adoc.sagemath.org+modular+form&oq=site%3Adoc.sagemath.org+modular+form and embed it in the output of a cell as an iframe (or just display a link that opens in a new tab).

**Comment by GregoryBard** [comment]
I would like to suggest a different approach, for search_doc.

We should explain something like this, after I explain the "question mark
operator."

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Question: How can I get help for a command, if I've forgotten the name
of that command?

If you remember the name of a command, such as A.right_kernal(), then you
can use the question mark operator to get help for it. However, if you've
forgotten the command to compute a null space, you have several options.

   - Search in Google for: null space "sage reference manual"
   - Search in Google for: null space site:sagemath.org
   - Download a copy of *Sage for Undergraduates, *by Gregory Bard,
   published by the American Mathematical Society. The electronic version is a
   100% free pdf file.

That middle option deserves some further information. The term site:
sagemath.org, with no spaces on either side of the colon, will restrict
Google to search on webpages whose URL ends in sagemath.org and therefore
your search is far more focused. Of course, you can use this with any URL
that you like.

There used to be a command called search_doc, but in many cases it has been
rendered inoperative, for technical reasons.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Of course, I'd link to the downloading of the book, using the [xxxx](yyyy)
feature of markdown.

For sure, I know from experience, that my students do not know about the
"site:url.com" operator, and are very surprised to learn that it exists.

I also know from experience that users transitioning to Sage from other
computer algebra systems, particularly mid-level faculty, used that
search_doc( command quite often... at least the ones at Fordham and at UW
Stout. Therefore, I really regret that it is not working at the moment.

Thoughts?
---Greg

**Comment by GregoryBard** [comment]
I have added the question from the email below. This was the one about
using the "site:sagemath.org" trick in Google, to search for commands when
you can't remember their name. This will appear in two spots.
---Greg

**Comment by GregoryBard** [comment]
I like William's idea. It would be really superb, if the output when a user types...

search_doc("null space")

could be something like ...

```
Unfortunately, the `search_doc` command is no longer operating. Instead, try this link to search:

https://www.google.com/search?q=site%3Adoc.sagemath.org+null+space&oq=site%3Adoc.sagemath.org+null+space
```

where the URL is hot linked to open a new tab with the results of that search.

Thoughts?
---Greg

**Comment by DrXyzzy** [comment]
Done.
