### ISSUE TITLE
in sagews worksheets support tab completion with jokers 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#734]
For example `*prime<TAB>`.

**Comment by williamstein** [comment]
I think Jupyter does this.  The Sage terminal in recent copies of Sage definitely does support this, so adding it to sagews is probably very easy.    Type `sage-develop` in a terminal, then `*prim<tab>` and see it work.

**Comment by DrXyzzy** [comment]
1. I don't think the `*` in `*prime<TAB>` is treated as a glob in sage-develop; I think completion is the same as if there was a space, i.e. `* prime<TAB>`. For example, `*_factors<TAB>' does not offer any completions. Absence of completions in sagews here is probably just another limitation of the simplified parser.
1. On the other hand, `*_factors?` (no TAB) offers matches in sage-develop, while neither `*_factors?<Shift+Enter>` nor `*_factors?<TAB>` yield any result in sagews. Similarly with `*le_prim*?`.

So I think there are two things to look at here. The second case looks more interesting and potentially more valuable.

**Comment by GregoryBard** [comment]
+1 This would really help people like me, who have trouble remembering the
exact names of commands.
---Greg

**Comment by DrXyzzy** [comment]
Implemented in PR753, for tab completion, not help (question mark) mode.

The following now allow tab completion:
- `*_factors[tab]`
- `*le_pr*[tab]`
- `list.re*e[tab]`
