### ISSUE TITLE
create a new sage worksheet, type si[tab] and see it doesn't work

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#735]
Tab completion is broken in a blank new worksheet for some reason.

Evaluating so there is a cell and then it works fine hence.

**Comment by DrXyzzy** [comment]
Problem is also reproducible in worksheet after it has been opened:
```
pi.n()[shift-enter]
  -- get output, worksheet starts new cell --
sig[tab][esc]
  -- completions are offered, user rejects with ESC, worksheet starts another cell
sig[tab]
  -- completions not offered
```

Log messages between UI and sage server for working completion of `sig[tab]`:
```
14333 (2016-07-31 22:28:04.151): handling message  (u"{u'preparse': True, u'line': u'sig', u'top': u'sig', u'event': u'introspect', u'id': u'a69c73d8-
0170-4313-aea5-1bebf594de43'}", False)
14333 (2016-07-31 22:28:04.154): sending message ' ('{"id": "a69c73d8-0170-4313-aea5-1bebf594de43", "event": "introspect_completions", "completions":
["_on_count", "ma", "n"], "target": "sig"}', False) '
```

Log messages between UI and sage server for failed completion, when `sig[tab]` is at top of cell:
```
14333 (2016-07-31 22:34:49.003): handling message  (u"{u'preparse': True, u'line': u'\\ufe200c', u'top': u'sig', u'event': u'introspect', u'id': u'233
14392-3afd-462b-b5d2-4779b1cf1c3d'}", False)
14333 (2016-07-31 22:34:49.006): sending message ' ('{"id": "23314392-3afd-462b-b5d2-4779b1cf1c3d", "event": "introspect_completions", "completions":
[], "target": "\\ufe200c"}', False) '
```

**Comment by DrXyzzy** [comment]
A second issue is: if completions are requested from top line of cell and none are accepted, the cell is closed and a new cell started. This happens whether completions are offered or not, i.e. whether the bug in this issue is evoked or not.

**Comment by DrXyzzy** [comment]
A third issue:
- Move to bottom of Sage worksheet
- type `fact[tab][esc]` in a new cell; a new empty cell will be started below the current cell
- put cursor at start of empty cell and type:
```
pi
fact[tab]
```
BUG: completions offered will be `pi`,`pickle_function` and so on, not completions for `fact`.

**Comment by DrXyzzy** [comment]
Problems above happen when the cell where completion is attempted does not start with a marker line.

**Comment by williamstein** [comment]
On Sun, Jul 31, 2016 at 8:41 PM, Hal Snyder <notifications@github.com>
wrote:

> Problems above happen when the cell where completion is attempted does not
> start with a marker line.
>

NICE.  There's a function that I think will go through and ensure all cells
start with a marker line -- we could just run it before doing the
completion.  Alternatively... use your observation to fix some other
relevant code in this case.


-- 
William (http://wstein.org)

**Comment by DrXyzzy** [comment]
Looks as if this was a bug introduced by me, adding support for tab completion with jupyter modes. I didn't realize that `topline = cm.getLine(@cell(pos.line).start_line()+1)` in sagews.coffee could cause lines to be renumbered in the current cell. Testing a fix now.

**Comment by DrXyzzy** [comment]
Done.
