### ISSUE TITLE
when I change a chat the time I last edited it doesn't update

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#750]
After changing a chat message, it still says "Last edit by William A. Stein;  7 minutes ago".  However, I edited it just now.

**Comment by simonluu** [comment]
I asked John when we were first implementing this if the time should also change with the edited message but he said no.

**Comment by williamstein** [comment]
Let me clarify.

Writing
```
Last edit by William A. Stein                                                7 minutes ago
```
across the bottom of a chat immediately after it has been edited is misleading and confusing.

What would make sense is 
```
Last edit 1 minute ago by William A. Stein                             7 minutes ago
```
The change is putting another time right after "Last edited".  The original chat time in the bottom right always stays unchanged.

**Comment by simonluu** [comment]
ok, yeah that makes sense
