### ISSUE TITLE
integrate geogebra

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#754]
requested at  http://ask.sagemath.org/question/34261/run-geogebra-in-the-sagemath-cloud/ and probably a nice idea, but it would not only be highly nontrivial but it is also not "free software" open source. (not sure if it is even open source at all)
see https://www.geogebra.org/license

**Comment by williamstein** [comment]
Out of curiosity I've written to them to ask about their commercial use costs...

**Comment by williamstein** [comment]
Their "noncommercial license" says "The GeoGebra source code is licensed to you under the terms of the GNU General Public License (version 3 or later)".  If there is a single dependency of Geogebra that is GPL3 licensed that they don't control, then they absolutely legally cannot restrict commercial use as that would be a clear violation of GPL3.   They might just be confused.   In fact, they include GIAC as a dependency, and that is (1) GPL3 licensed, and (2) not under their control via copyright.

**Comment by williamstein** [comment]
I sent them this:
```
Followup question: You include dependencies such as GIAC in Geogebra
which are GPL3 licensed.  Thus GeoGebra, as a derived work, must also
be distributed under the terms of GPL3, hence it would be a violation
of the GPL3 to require a commercial license for commercial use of the
source code of GeoGebra.

I remember back in the old days GeoGebra was completely open source,
but the documentation was restricted.  What's the current situation?

Thanks for any clarification.  I'll also write to the FSF in case you
guys don't know the answers.
```

**Comment by kcrisman** [comment]
Whoah, Geogebra is no longer open source?  Since when?  Aargh.

> This is because the restrictions on commercial use that apply to the GeoGebra installers, web services and language files add-ons might be seen to be a restriction on the software as a whole (thus making it "non-free"), even though the GeoGebra source code is made available under the GNU General Public License without restriction. 

So I guess in principle one could use it 'free'ly.  Though I have no idea how hard it would be to use Geogebra without the web services or installer.  Perhaps this is their version of SMC, in some sense - how to make enough money to improve Geogebra?

**Comment by williamstein** [comment]
> Perhaps this is their version of SMC, in some sense - how to make enough money to improve Geogebra?

SMC is 100% open source -- there's no special installers or language files that are restricted.

GeoGebra has had these restrictions on "language files add-ons", etc., since forever (we've looked into this a few times before).

>  Though I have no idea how hard it would be to use Geogebra without the web services or installer.

We should find out.   It could very well be that for SMC we would only *want* to use Geogebra without that extra stuff, which sounds (except for language add ons) like it just conflicts with what SMC already provides.

**Comment by williamstein** [comment]
Their fee is about $2/user (but goes down some for quantity).  I don't know if this is $2/user per year.

**Comment by kcrisman** [comment]
> SMC is 100% open source -- there's no special installers or language files that are restricted.

Sorry, what I meant was it was their business model.  Nothing about licenses was implied 😄 

It's true that is SMC is really morphing into "SuperMathCloud" that having Geogebra in it would be valuable, particularly for educational applications.

**Comment by GregoryBard** [comment]
+1 for adding GeoGebra. I've noticed that at conferences, GeoGebra is very
popular for a wide swath of courses, from high school geometry up to
mid-undergraduate linear algebra.
---Greg

**Comment by williamstein** [comment]
I don't think we can add GeoGebra.  Either we have to fight around their licensing terms, really clearly going against their wishes (though maybe technically legal), or we have to pay them an **absolutely unreasonable** license fee.

**Comment by GregoryBard** [comment]
Perhaps if SageMathCloud really takes off, you could negotiate a "special
relationship" and suggest a flat fee-per-month, regardless of the number of
users. Until such a time, well... it seems that nothing can be done about
it. Better to focus on other things.
---Greg

**Comment by williamstein** [comment]
> Perhaps if SageMathCloud really takes off, you could negotiate a "special
relationship" and suggest a flat fee-per-month, regardless of the number of
users.

I might not, even if I could -- the SMC software and its deps itself should be 100% open source.   By "buying into" SMC you should also know that you can legally -- no matter what -- run the entire stack yourself if need be.   GeoGebra's closed source approach is on the wrong side of history.  It may be better for the world to create something to compete with GeoGebra that is truly free (and compatible with user content).  Not sure.

**Comment by williamstein** [comment]
Closing this -- we can't legally have Geogebra in SMC.
