### ISSUE TITLE
install asymptote ipython magic for 3d plots

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#755]
see https://groups.google.com/d/msg/sage-cloud/hcRSlDTewc0/6DdYIjcBAgAJ

**Comment by DrXyzzy** [comment]
@haraldschilly I am able to run [this asy demo jupyter notebook](http://nbviewer.jupyter.org/github/azjps/ipython-asymptote/blob/master/examples/asymptote_magic_examples.ipynb) after adding config.asy and uploading sample file fin.asy. Here's an SMC link showing the file: https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/ASYMPTOTE/asymptote_magic_examples.ipynb

So I am not sure there is any SMC admin work to do. Would you like me to make an FAQ entry on how to use asy with jupyter notebooks, with a link to a public version of the demo above?

**Comment by haraldschilly** [comment]
hmm, I don't know. The first command did download and install this extension magic, maybe that could be pre-installed? But `UserWarning: %install_ext` is deprecated, please distribute your extension as a python package.` suggests, that it isn't a proper package, so then that's not so good.

Ok, so, writing down your steps in the FAQ is a good idea. Gregories changes are already online, so don't hesitate to edit right inside github.

**Comment by DrXyzzy** [comment]
Wiki updated here https://github.com/sagemathinc/smc/wiki/sagejupyter

**Comment by GregoryBard** [comment]
That update looks entirely fine, so... well done!

However, we could also add a link to this new question and answer, at this
location (in the same file):

"Note: As of July 2016, Sage interacts and 3d plots do not work in Jupyter;
however, this may change soon."

You could add, "However, you can make 3d plots in Jupyter notebooks using
xyz, see [this](where) for details."

That way, someone disappointed in the lack of 3D Sage plots in Jupyter
notebooks can use the package you describe.
---Greg
