### ISSUE TITLE
The command license() appears to be broken.

### ISSUE THREAD

**Issue by GregoryBard** [sagemathinc/smc#757]
The command license() appears to be broken.

This is called for if

1. You type help(). The fifth option calls for license().

2. While in a Sage worksheet, if you click on the white pull down menu called "? Help", (not the blue button marked "? Help"), then you get six options. The first one pulls up help(). The fifth option there calls for license()

Of course, I'm not sure that this command is even necessary.

**Comment by haraldschilly** [comment]
Strange, this calls IPython's pager. However, the correct command is to either show the string or we have to patch this.

Try this: `print str(license)`

```
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 947, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/misc/copying.py", line 10, in __call__
    pager.pager()(str(self))
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/page.py", line 273, in page
    return pager_page(data, start, screen_lines, pager_cmd)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/page.py", line 233, in pager_page
    pager_encoding = pager.encoding or sys.stdout.encoding
AttributeError: 'BufferedOutputStream' object has no attribute 'encoding'
```

**Comment by haraldschilly** [comment]
@DrXyzzy pinging you, maybe you have seen a function calling this ipython pager before? 

upon looking at the source code, the key might be to switch this embedded mode flag when sage starts. see https://github.com/sagemath/sage/blob/master/src/sage/misc/pager.py

**Comment by williamstein** [comment]
`BufferedOutputStream` is just a class I wrote in sage_server.py, not necessarily knowing what I was doing or what was expected.   Let's just add an encoding attribute to it to make it compatible with the pager.

**Comment by DrXyzzy** [comment]
Done.
