### ISSUE TITLE
project looks empty when not logged in

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#760]
When opening a directory in a project without being signed in, it looks empty. That's confusing, and even just a error bubble message might not avoid that irritation about all files being gone.

Better would be, to add a larger "maybe you have to sign in" information below the "No Files Found" info.

**Comment by GregoryBard** [comment]
+1 This seems like the type of thing that might annoy/panic a user.
---Greg

**Comment by timothyclemansinsea** [comment]
This is addressed in a PR I made yesterday.
