### ISSUE TITLE
Editor feature : close environments and indent

### ISSUE THREAD

**Issue by JCBustamante** [sagemathinc/smc#77]
Most LaTeX editors have the option to automatically clos an environment opened by the user. For instance if one types \open{enumerate}, Kile would automatically write \end{enumerate}, and \item at the right positions. Also, in this circumstance, tne \item would be indented, and all the code that is part of that item would have the same indentation. Further, the same would apply to other items at the same level. nestes lists would lead to increasing indentations. Could be nice to have something  like this!

**Comment by williamstein** [comment]
dup of #79
