### ISSUE TITLE
chat: edit a chat, then edit another chat, and the previous closes but does not submit -- I think it should submit chat

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#771]
Try editing a past chat, then -- before saving it with shift+enter -- just try editing another chat in the same chatroom.   The previous editing chat closes, which is OK.  However, it doesn't actually submit the change.     If you double click to edit again you see the old version.  I think this is wrong -- it should submit the change.   

I'm sure this will be an easy 1-2 lines to fix.

**Comment by simonluu** [comment]
I was thinking that you are editing a message and you go and edit another one, the first edit input would close and be saved, so it doesn't just send if you are not finished.

**Comment by simonluu** [comment]
But I can make it so it submits the change

**Comment by williamstein** [comment]
On Mon, Aug 1, 2016 at 6:40 PM, Simon Luu <notifications@github.com> wrote:

> But I can make it so it submits the change
>

One could easily loose work with the current design.  You edit, go to
another, and don't even realize that your little edit wasn't saved.  Also,
what happens with the current design if you edit a little, then you close
editing by opening another, then somebody else edits that same cell?  It's
unclear.

-- 
William (http://wstein.org)
