### ISSUE TITLE
sometimes files get blanked by the project when connection gets bad

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#772]
Sometimes a file will get set to be empty, which is very disconcerting!

**WORKAROUND:** You can always work around this by going one step back in the revision history. Click the TimeTravel button, go back a step and click revert live version to this.  Also, of course, all files are backed up in the Backups page (snapshots).

Fixing this properly is obviously an absolutely top priority for me.

**Comment by GregoryBard** [comment]
Should I add this workaround to the Help/FAQ/Wiki? Or have you fixed it
already?
---Greg

**Comment by williamstein** [comment]
This should be "mostly fixed" now.  However, I'm still not 100% done, as there may be an edge case remaining.

**Comment by williamstein** [comment]
I think this should be 100% fixed now.
