### ISSUE TITLE
Themes for cocalc subdomains

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#778]
sage.cocalc.com
jupyter.cocalc.com
python.cocalc.com
julia.cocalc.com
r.cocalc.com
etc

**Comment by timothyclemansinsea** [comment]
with javascript determine subdomain and load up right "theme"

**Comment by williamstein** [comment]
And maybe... seattlepolice.cocalc.com ?

**Comment by timothyclemansinsea** [comment]
do we want to include user creatable subdomains/themes under this ticket? I assume seattlepolice.cocalc.com would be a user created subdomain?

**Comment by williamstein** [comment]
> do we want to include user creatable subdomains/themes under this ticket?

No, you're right -- that should be different/later.
