### ISSUE TITLE
subdomains for teams/organizations

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#780]
Make it possible for a team or organization to create a subdomain ____.cocalc.com For starts make it so team/organizations admin(s) can set what projects each user has, whether or not the team allows public joining, etc, file types to list etc on new file page.

**Comment by williamstein** [comment]
This would be copying what slack does.  It is very unclear that we would want to go this way or do this (e.g., github doesn't, do they?).

**Comment by timothyclemansinsea** [comment]
This would be way different from Github projects because we would be giving a team/organization the ability to customize things like what editors to emphasize when creating a file. Github.io uses subdomains.

**Comment by timothyclemansinsea** [comment]
I'm closing this because only I wanted it.
