### ISSUE TITLE
reword "create or upload" button in files to not suggest uploading

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#782]
reported by todd:

> In an empty directory, the large "+Create and Upload" button looks like you can drag and drop files on to it. The large size of the button is what makes it look like a drag-and-drop box.

I'm not suggesting to implement an upload area there -- that should be done in general for all files, not just the case where there are no files -- hence just a neat rewording or some stile fixes.

**Comment by williamstein** [comment]
How about instead make it a dropzone target?

**Comment by haraldschilly** [comment]
Well, I thought this is a really easy one and I would have done so already, if I had a good idea what to write there. I'm not against issue #61, just for clearing up this little confusion. But ok, let's close this one here and do the dropzone.
