### ISSUE TITLE
if you try to add an existing collaborating on a project again it says "No matches. Send email invitation..." but should say that the person is already a collaborator. 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#792]
This is just dumb behavior.

**Comment by simonluu** [comment]
Someone already fixed this bug. I tried adding an existing collaborator to a project and It says Existing Colaborator(s): "name of person I tried to add"

**Comment by haraldschilly** [comment]
Yes, this was https://github.com/sagemathinc/smc/commit/12a42eadfb69e9b050b05d5d1864b2dd3ba0973c and it was part of fixing #851 ... I should have referenced this one here.
