### ISSUE TITLE
Make chat preview be off, by default.

### ISSUE THREAD

**Issue by GregoryBard** [sagemathinc/smc#796]
As suggested by William: The chat preview should not, by default, be shown. It should be shown only if a user clicks on some "preview" link, shown when typing a message.

Copy of the chat on this topic, from August 9th:
-----

> > Holy crap this preview is annoying.

> Yep, it is worse than nothing sometimes since it obstructs your view of what you're replying too and there is no x to kill it.  Maybe it should be something that must always be manually popped up.  After all you only need preview when things get harry.

+1 I'd be very much in favor of this change. I think it would be much better if the preview, by default, was not shown... and you have to specifically click to open it. I think the preview has made our chat tool much more annoying to use than before. Just being honest. :shrug:

**Comment by haraldschilly** [comment]
for me, the only issue is, that it is an "floating overlay" and not an integrated part of the linear list of messages. would it be like other messages, and you scroll a bit up, the preview is hidden below.

maybe there should also be a height limitation, like 30% of the window or so. (with overflow-hidden in css)

**Comment by williamstein** [comment]
> for me, the only issue is, that it is an "floating overlay" and not an integrated part of the linear list of messages. would it be like other messages, and you scroll a bit up, the preview is hidden below.

Just to make this clear, it is also a big issue for me.  The concrete consequence is it makes writing a new large message while viewing existing messages impossible.

**Comment by simonluu** [comment]
>+1 I'd be very much in favor of this change. I think it would be much better if the preview, by default, was not shown... and you have to specifically click to open it. I think the preview has made our chat tool much more annoying to use than before. Just being honest. :shrug:

I did implement a button that turns off the preview.

>for me, the only issue is, that it is an "floating overlay" and not an integrated part of the linear list of messages. would it be like other messages, and you scroll a bit up, the preview is hidden below.

maybe there should also be a height limitation, like 30% of the window or so. (with overflow-hidden in css)

I had it so it is part of the list of messages, but I made it float so that is an easy fix.

**Comment by johnjeng** [comment]
>and you scroll a bit up, the preview is hidden below.

My problem with this is that you can't see preview and read a message at the same time. Imagine that you are replying to something point by point reading and typing. To see your preview, you'd have to *scroll to the bottom*. This is strictly worse than Github's preview tab at the top of a comment box.

I think it should start expanding downward after a certain size so that you can preview a long message while reading old messages but short messages don't make the chat window jump around.
