### ISSUE TITLE
link to ssh key generation instructions point into the void

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#799]
in project settings → ssh keys → generate keys points to https://github.com/sagemathinc/smc/wiki/SSH-Instructions which does not exist.

**Comment by haraldschilly** [comment]
fixed by adding a link to where it is. maybe we should have a second look about other broken links …

**Comment by GregoryBard** [comment]
On the microscopic scale, I'd have changed the link to this...

https://github.com/sagemathinc/smc/wiki/AllAboutProjects#create-ssh-key

On the macroscopic scale, yes, it would be **excellent** to check all the
links, and to find out how many I have inadvertently broken. Would it
suffice to search for the substring "/sagemathinc/smc/wiki/" everywhere? Or
perhaps, is there a better way?
---Greg

**Comment by haraldschilly** [comment]
I did this just now:

It's filename, line-number, and the line where it matches. So, if they work, all links work.

```
$ git grep 'smc/wiki/'
smc-webapp/editor.html:84:                            <a href="https://github.com/sagemathinc/smc/wiki/sagews" target="_blank" class="btn btn-info btn-lg" data-original-title="" title="">
<i class="fa fa-question-circle"></i></a>
smc-webapp/editor.html:104:                                <a href="https://github.com/sagemathinc/smc/wiki/sagews" target="_blank" class="btn btn-info" data-original-title="" title=""><i
 class="fa fa-question-circle"></i> Help</a>
smc-webapp/landing_page.cjsx:382:                            (<a href="https://github.com/sagemathinc/smc/wiki/Teaching" target="_blank">SMC used for Teaching</a> and <a href="http://www.
beezers.org/blog/bb/2015/09/grading-in-sagemathcloud/" target="_blank">learn more about courses</a>).
smc-webapp/project_settings.cjsx:893:                    <a href="https://github.com/sagemathinc/smc/wiki/SSH-Instructions" target="_blank">
smc-webapp/r_help.cjsx:151:        href : 'https://github.com/sagemathinc/smc/wiki/Teaching'
smc-webapp/r_help.cjsx:159:        href : 'https://github.com/sagemathinc/smc/wiki/FAQ'
smc_sagews/smc_sagews/sage_jupyter.py:77:        https://github.com/sagemathinc/smc/wiki/sagejupyter
```

**Comment by haraldschilly** [comment]
and sure, I'll fix that link, now I know it's just one place.

**Comment by GregoryBard** [comment]
The good news is that none of these links are broken.

However,

smc-webapp/r_help.cjsx:159:        href : '
https://github.com/sagemathinc/smc/wiki/FAQ'

should probably point elsewhere, because FAQ.md is now the "miscellaneous"
category... how about Portal.md instead?

What is the context of that line of code?
---Greg

**Comment by haraldschilly** [comment]
> context

here, it's in the about page: [smc-webapp/r_help.cjsx](https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/r_help.cjsx#L159)

**Comment by GregoryBard** [comment]
Well, that page is going away, anyway, so ... no worries. However, if you
have a moment, then Portal.md would be a good temporary choice.
---Greg
