### ISSUE TITLE
ipynb hangs at "Kernel starting, please wait ..."

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#802]
Reported by Peter Luschny:  sometimes, loading an ipynb after logging in hangs at that status message. One has to restart the kernel to get it running. This happens with the python 2 sagemath kernel.

I wasn't able to replicate the issue, and the only maybe relevant error I saw was an `Failed to load resource: net::ERR_INVALID_URL data:image/png;base64,smc-blob::b84e6128-badf-4cae-bea7-ab83f611356f` in the console. Such an uncaught error could be the culprit ...

**Comment by williamstein** [comment]
I'm worried about: "I wasn't able to replicate the issue".  To add, I can't replicate this on Chrome or Firefox.

**Comment by williamstein** [comment]
Peter is using "OS is Windows 10 and browser is Chrome."

**Comment by williamstein** [comment]
Closing due to "I wasn't able to replicate the issue" and no other reports.
