### ISSUE TITLE
User-editable error messages.

### ISSUE THREAD

**Issue by vivekv2** [sagemathinc/smc#808]

**Comment by vivekv2** [comment]
It would be useful to allow users to edit error messages inline to improve their quality. Also possible: auto-linking stackoverflow or other search results.

**Comment by timothyclemansinsea** [comment]
When in a worksheet, if you get an error message then look up the message in a user contributable database.

**Comment by williamstein** [comment]
I plan to make error messages more useful, but this shotgun crowd sources is not the approach that I think makes sense.  Much better would be to classify the messages into groups (using "machine learning" applied to all errors ever in SMC), then manually improve the error messages for each category.

**Comment by williamstein** [comment]
I think this is too vague to be a ticket.
