### ISSUE TITLE
Do another round of development on the print to pdf functionality of Sage worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#81]
Requested by: Juan Carlos Bustamante

1. Customizing .pdf creation from a .sagews So far the basics are there, but some more options could be usegul. For instance,  give some more advanced options to be passed as parameters to the LaTeX compiler : font-size, margins, sizes of the figures, the possibility of not numbering sections. In RStudio one can, from a .Rmd file create either a .pdf, a .tex or a ,html file. Few dialog boxes allow to have more flexibility.

2. In the same vein, I know that during this process, a .tex file is created somewhere, it would be great if that file could easily be located, and in fact be the output of some "export" process.

**Comment by srdoty** [comment]
Some of the Markdown conversions are not rendered properly in the PDF version; e.g., *emphasized* text loses its emphasis. Also, apostrophes are stripped away in the PDF version; e.g., let's is typeset as lets, and so on.

**Comment by williamstein** [comment]
this is way vague and there are other more precise tickets now.
