### ISSUE TITLE
When user joins a project stored the join datetime

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#811]
add joined_at to "schema.collaborators =
    primary_key : 'account_id'
    anonymous   : false
    virtual     : 'accounts'
    user_query:
        get :
            all :
                method : 'getAll'
                args   : ['collaborators']
            fields :
                account_id  : null
                first_name  : ''
                last_name   : ''
                last_active : null
                profile     : null"

**Comment by williamstein** [comment]
ALSO (or instead) add to the Project log, saying *who* invited the user and when...

**Comment by timothyclemansinsea** [comment]
OK after discussing with William will store this in in the project's log instead of the collaborators schema. The log can track every time a user is added/deleted
