### ISSUE TITLE
The command cmap_help(), which does not exist, is called for in the density_plot? documentation (doc_string)

### ISSUE THREAD

**Issue by GregoryBard** [sagemathinc/smc#816]
The help for density_plot has the following line for the optional parameter cmap. In density_plot? we see the following:

"cmap" -- a colormap (type "cmap_help()" for more information).

This is a very important option, because it determines the color mapping when making a heat map (a color density plot). However, when you type the command cmap_help() in SageMathCloud or in SageMathCell, the command is undefined. :(

Meanwhile, in contour_plot, the same parameter exists. In contour_plot? we see

"cmap" -- a colormap (default: "'gray'"), the name of a
  predefined colormap, a list of colors or an instance of a
  matplotlib Colormap. Type: "import matplotlib.cm;
  matplotlib.cm.datad.keys()" for available colormap names.

which does work. 

I recommend we change the density_plot help file to match the contour_plot help file instead.

**Comment by williamstein** [comment]
Close this and open an issue at https://trac.sagemath.org/

**Comment by fchapoton** [comment]
https://trac.sagemath.org/ticket/21279
