### ISSUE TITLE
sagews: Comment at indentation 0 taken as start of new block

### ISSUE THREAD

**Issue by cben** [sagemathinc/smc#819]
In SMC sage notebook:
```
def never_called(a):
    print 'should not execute 1', a
     # comment
    # comment
    print 'should not execute 2', a
   # comment - why red color BTW?
    print 'should not execute 3', a
  # comment - why red color BTW?
    print 'should not execute 4', a
 # comment - why red color BTW?
    print 'should not execute 5', a
# comment at indent 0
    print 'should not execute 6 BUT DOES', a
```
The last line should be part of the function by Python rules, but instead gets executed immediately!
And *if* that causes an exception, the lines numbers are wrong (from start of cell, not notebook).

![screenshot-cloud sagemath com 2016-08-16 11-38-09 comment 0](https://cloud.githubusercontent.com/assets/273688/17693174/30870c4a-63a6-11e6-9f74-dac00b042b79.png)

public share: https://cloud.sagemath.com/projects/328c4733-2f1a-4e40-9d7c-ba21ea605f6f/files/python_0_indent.sagews

**Comment by cben** [comment]
cc @anpc who bumped into this.

**Comment by haraldschilly** [comment]
yes, that seems like a bug in the block parser for the code. I'm assigning this to @DrXyzzy

**Comment by DrXyzzy** [comment]
Thanks for the detailed report. Looking at it now. I suspect the sample program is creating problems with both the Sage worksheet block parser and Codemirror syntax highlighting.

**Comment by williamstein** [comment]
Fixed by PR https://github.com/sagemathinc/smc/pull/823, which is now merged.

I'm closing this.  The syntax highlighting part of this is an issue with the CodeMirror Python mode, as you can confirm here: https://codemirror.net/mode/python/index.html  You might submit a bug report to CodeMirror.  (If so, let us know.)

**Comment by DrXyzzy** [comment]
Reported it here: codemirror/CodeMirror#4276.
