### ISSUE TITLE
jupyter server broken for directory name F:\yi\2015\english

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#824]
when a subdirectory in a project is called `F:\yi\2015\english` (yes, exactly that!) the jupyter server doesn't serve the ipynb file. (404 doesn't exist error)

**Comment by williamstein** [comment]
Is this a bug in Jupyter?  If so, shouldn't it get reported upstream?

**Comment by williamstein** [comment]
If it is a jupyter issue, we can at least warn the users properly with a message.

**Comment by haraldschilly** [comment]
observations:

1. this problem also triggers, when the file has a single backslash in the name. it also happens regardless if there is a backslash in the directory or name, it only matters that it is in the path. so, simples example is `cp a_working_working.ipynb 'back\slash.ipynb'` and then trying to open the copy.
2. the problem does not happen if one uses the jupyter server directly, it also works locally in my own linux. hence the problem must be in SMC itself.
