### ISSUE TITLE
sage_eval allows non-string inputs -- support this

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#825]
`smc_sagews/sage_salvus.py` defines a wrapped `sage_eval` that assumes input is a string.  But tuples are now also supported by sage_eval.  So maybe this will be a better sage_eval:

```
def sage_eval(x, locals=None):
    if isinstance(x, str):
        x = str(x).strip()
        if x.isspace():
            return None
    from sage.all import sage_eval
    return sage_eval(x, locals=locals)
```

**Comment by williamstein** [comment]
Example input:

sage_eval(('f (x) = (x ^ 2-1) / (x-1)', 'f (1.000000000000001)'))

**Comment by DrXyzzy** [comment]
Thanks for detail. Issue related to this [sage-cloud thread](https://groups.google.com/d/msg/sage-cloud/t1AZGdocj10/GJkqVg2vBwAJ)

**Comment by DrXyzzy** [comment]
Also this example from [sage docs](http://doc.sagemath.org/html/en/reference/misc/sage/misc/sage_eval.html) causes an error in sagews:
```
sage_eval('2^3', preparse=False)

==>

TypeError: sage_eval() got an unexpected keyword argument 'preparse'
```

**Comment by haraldschilly** [comment]
I've not time to look into it right now, but your last comment somehow tells me, that we should start writing tests. It doesn't need to be sophisticated, but something simple based on e.g. py.test should be sufficient.

**Comment by DrXyzzy** [comment]
Done.
