### ISSUE TITLE
Sync selected files to assignment after assigned

### ISSUE THREAD

**Issue by swnesbitt** [sagemathinc/smc#83]
After an assignment is copied to students (containing multiple files), it would be handy to redeploy selected files to the class (say after a class discussion or bug fix) rather than re-assign the whole assignment, which might overwrite notes the student has made there, etc.

**Comment by haraldschilly** [comment]
Yes, I was also thinking that this could be a use-case, but it's currently not implemented. Maybe it's better to split this up in two parts for now. However, even if your re-assignment overwrites student's notes, they can recover the previous state through the **snapshot feature**. That's generally not so common, and probably not really that visible, but the old versions of the files are there and hence not lost.

**Comment by swnesbitt** [comment]
Ahh, that is handy.  The snapshot feature certainly will work for now.  Thanks.

From: Harald Schilly
Reply-To: sagemathinc/smc
Date: Wednesday, August 26, 2015 at 4:17 AM
To: sagemathinc/smc
Cc: Steve Nesbitt
Subject: Re: [smc] Sync selected files to assignment after assigned (#83)


Yes, I was also thinking that this could be a use-case, but it's currently not implemented. Maybe it's better to split this up in two parts for now. However, even if your re-assignment overwrites student's notes, they can recover the previous state through the snapshot feature. That's generally not so common, and probably not really that visible, but the old versions of the files are there and hence not lost.
