### ISSUE TITLE
searching for assignments in courses is broken 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#832]
when I click on the search box in "assignments" in a course, it spins and in the console I get 

    Uncaught TypeError: e.trim is not a function

that prevents anyone from creating assignments.

@alinabucur has the same issue in her new project, too...

**Comment by johnjeng** [comment]
Should be fixed at https://github.com/sagemathinc/smc/commit/a002e71f8adf54b599a1d7760d9f7431ef6f2a0b
