### ISSUE TITLE
In the course editor, the add searchbox (for assignments and handouts) often instantly disappears which drives users crazy

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#835]
For some reason after some time, the results box closes itself after a little bit.

My guess is that something is rerendering it? Or data is getting updated somewhere incorrectly.

**Comment by williamstein** [comment]
Course editor?  Add students?  Or Assignments? Or handouts? (or all three?)

**Comment by johnjeng** [comment]
Assignments and Handouts (they use the same component).

**Comment by williamstein** [comment]
Upped to high on witnessing this and getting complaints from users.  It is **frickin' infurating!**.

Not to me (william): to replicate, just go [here](https://cloud.sagemath.com/45f4aab5-7698-4ac8-9f63-9fd307401ad7/port/54249/projects/12b6b7ec-7f20-45ef-9650-73c56431f93d/files/2016-10-04-112116.course), then go to the assignment tab, search, hit enter, and watch in horror.

**Comment by williamstein** [comment]
To replicate this, I think you have to have a deleted homework assignment.
