### ISSUE TITLE
Python profiling tools prun and lprun don't work

### ISSUE THREAD

**Issue by jaiagreen** [sagemathinc/smc#840]
I'm trying to profile [some code](https://cloud.sagemath.com/projects/cce6e543-045d-4d8a-baa1-a7c79793d8f2/files/Code/Figuring%20Out%20Fourier%20Transforms.sagews), but lprun doesn't work at all and prun just outputs a bunch of boxes with the text "Salvus Profiler".

**Comment by haraldschilly** [comment]
Hello Jane, besides that problem, the worksheet is also corrupted. Can you
tell us more exactly what you were doing and trying to do? I am not really
able to follow the detail. You should also email to help@sagemath.com and
not here, such that we can properly triage this into technical issues and
keep this here as a bug report.
