### ISSUE TITLE
in R, Sys.which('cmd') returns empty vector

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#857]
The R function call `Sys.which()` returns empty paths for all commands, even those that are clearly in the command search path.

_This causes the `pandoc()` function in `knitr` package to fail. The [R function does](https://github.com/yihui/knitr/blob/master/R/pandoc.R#L48) `Sys.which('pandoc')`, which fails even though pandoc is installed and reachable via PATH._

Example from a .term session:

```
$ R

R version 3.2.2 (2015-08-14) -- "Fire Safety"
...
> Sys.which('ls')
ls
"" <== should be "/bin/ls"
> Sys.getenv('PATH')
[1] lots of paths, ending with "...:/usr/local/sbin:/usr/l
ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/projects/data/homer/bin:/projects/data/weblogo"
```

PATH environment appears set correctly in R.

This problem occurs in the following settings:
- term session with `R` command
- term session with `sage -R` command
- sage worksheet in `%r` cell
- sage worksheet in jupyter cell using `ir` kernel
- jupyter notebook with r kernel

**Comment by haraldschilly** [comment]
Yes, I was puzzled by that and I blame this R version for having a bug or there is something going wrong with compiling R in Sage. It works in the newer container image for the compute nodes, though. 

Also, right now on the compute nodes, when you specify the system R, it works. Watch this:

```
/usr/bin/R -q
> Sys.which("ls")
       ls
"/bin/ls"
```

This is definitely something we have to check in the future.

**Comment by haraldschilly** [comment]
see commit above, which contains a test for exactly this

**Comment by DrXyzzy** [comment]
Thanks for the info and possible workaround for now. There is a newer release of R, also.

**Comment by haraldschilly** [comment]
Just to clarify, since this got an I-bug tag: this most likely either a sagemath problem or something inside R itself. In particular, running this `Sys.which('ls')` command in `/usr/bin/R` of ubuntu works. Sad part about this ticket here is, that we would need more R developer experience to actually know what's going on -- or to find out where the problem actually happens (it's probably one of those integration issues, where a low-level issue leaks into the high-level as a symptom)

**Comment by DrXyzzy** [comment]
Recent R update didn't help. From a .term session just now:
```
~$ R <== this is /usr/local/bin/R
 
R version 3.2.4 Revised (2016-03-16 r70336) -- "Very Secure Dishes"
...
> Sys.which("ls")
ls
""
```
And /usr/bin/R, still on the old R, is still correct
```
~$ /usr/bin/R
 
R version 3.2.2 (2015-08-14) -- "Fire Safety"
...
> Sys.which("ls")
       ls
"/bin/ls"
```

**Comment by dimpase** [comment]
with current Sage beta (7.4.beta5), which has R 3.2.4, all seems to be OK (on my laptop).

**Comment by dimpase** [comment]
IMHO it points at the direction of an SMC proper problem, rather than anything to do with either Sagemath or R.

**Comment by haraldschilly** [comment]
just tested it with the fresh-of-the-compile-bench sage 7.4:

```
$ sage-7.4 -R -q
> Sys.which("ls")
ls
""
>

**Comment by dimpase** [comment]
@haraldschilly this is on SMC, I presume, right?

**Comment by haraldschilly** [comment]
@dimpase yes. I compiled 7.4 to days ago and added our "extensions" and additional packages on top of it. It looks good, but this detail remained.

**Comment by williamstein** [comment]
Labeling this as blocked, since switching to k8s or waiting for a fix in sage (?), would help.  But it's not an SMC itself bug, maybe.

**Comment by haraldschilly** [comment]
I've digged my way through the R source code (fortunately, there is a mirror on github) ... it looks as if there is a "make" pre-processing step, that replaces the string `@WHICH@` before the compilation even starts. Hence my feeling is, that this is detecting the wrong which … i.e. https://github.com/wch/r-source/blob/trunk/share/make/basepkg.mk#L61

Looking at the source code of the function here as it is compiled in SMC's sage, the substitution of the code above ends up like that:

```
which <- "/home/salvus/smc/src/node_modules/.bin//which"
```

**Comment by dimpase** [comment]
there is also something going on with WHICH in toplevel configure.ac
(and that's probably where it should be fixed...)
I guess you might be looking at files which are generated.

**Comment by haraldschilly** [comment]
@dimpase I think the referenced file: https://github.com/wch/r-source/blob/trunk/share/make/basepkg.mk#L61 is the one responsible for this. I.e. there is a sed command in there. That's what I mean.

What I'll look into is to just fix the `$PATH` before sage is compiled. that should be sufficient ...

**Comment by haraldschilly** [comment]
I'm pretty sure 	ca7dcc0 but it means to recompile r and all packages. Just recompiling R didn't work. Hence, I have to come up with a plan how to do this, or we just leave it and focus on fixing this just in the yet-not-live sage 7.4 version.
