### ISSUE TITLE
Following %!TEX root directives in the TeX editor

### ISSUE THREAD

**Issue by semorrison** [sagemathinc/smc#86]
I often have multiple files when writing TeX (e.g. a preamble.tex that I \input into the main file).

The subsidiary files aren't meant to be compiled separately, and I usually indicate this using the %!TEX root directive (as described, e.g. at http://tex.stackexchange.com/a/78103/77). Could the TeX editor please respect this directive, to make the experience of editing these subsidiary files cleaner?

**Comment by williamstein** [comment]
closed in favor of https://github.com/sagemathinc/smc/issues/904
