### ISSUE TITLE
terminal autosizing too wide

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#860]
for a while now, my terminal is always about 2 columns too wide (no matter if resized narrow or wide). anyone else noticing that? maybe font related? I don't have any funny zooming going on.

screenshot for illustration, you can see that "16" of 2016 is missing.

![smc-terminal-too-wide](https://cloud.githubusercontent.com/assets/207405/18198718/86b3908e-70fd-11e6-999d-882a19190590.png)

**Comment by haraldschilly** [comment]
The referenced PR #861 fixes this above and also works for me for very very tiny to quite large fonts.

**Comment by williamstein** [comment]
fixed, right?

**Comment by haraldschilly** [comment]
Yes, no more issues for me and I haven't heard anything negative from
others.
