### ISSUE TITLE
labelled cursors and highlighting in TeX editor

### ISSUE THREAD

**Issue by semorrison** [sagemathinc/smc#88]
I've recently switched from using Google Docs to the SageMathCloud TeX editor when doing real-time collaborative writing with other mathematicians. It's superb.

The one thing I really miss, however, is being able to see where the other editors' cursors are. A really useful feature in Google Docs is that one editor can say "We need to fix this sentence here", and highlight it, and on everyone else screens that sentence is instantly highlighted, in a colour corresponding to the speaker.

Is there any chance of labelling the cursors of other editors (even making them thick coloured bars, instead of the anemic grey)? And of displaying the current text selection of other editors?

**Comment by williamstein** [comment]
done
