### ISSUE TITLE
implement table in typeset_mode

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#89]
There are problems for producing a table out of a nested list, in typeset_mode on or off and via table or html.table. All these permutations should work. Reported [here in SO](http://stackoverflow.com/questions/32252290/creating-tables-in-sage-math-cloud).

```
rows = [[100,2,3], [4,5,60]]
html.table(rows)

table(rows)

typeset_mode(True)
typeset_mode(False)
```

**Comment by novoselt** [comment]
Fixing HTML on the Sage side: http://trac.sagemath.org/ticket/18292

**Comment by williamstein** [comment]
html.table is not implemented: https://github.com/sagemathinc/smc/issues/195

**Comment by williamstein** [comment]
Typeset for normal table doesn't work:

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-120437%20issue%20195.sagews

**Comment by haraldschilly** [comment]
Did rollout the #1056 PR, verified in prod using:

```
rows = [[1,2,3],[2,3,4],[7,6,5]]
typeset_mode(True)
table(rows)
```
