### ISSUE TITLE
traitlets deprecation warning on opening jupyter bridge

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#890]
Invoking jupyter kernel from sagews, e.g.,  _foo = jupyter("bash")_, causes this deprecation warning:  
`/projects/sage/sage-7.3/local/lib/python2.7/site-packages/traitlets/traitlets.py:954: DeprecationWarning: object.__init__() takes no parameters
  super(HasTraits, self).__init__(*super_args, **super_kwargs)`

**Comment by haraldschilly** [comment]
found a hint: bashkernel uses ipykernel (and is a wrapped instance for it), and [here are hits for traitlets](https://github.com/ipython/ipykernel/search?utf8=%E2%9C%93&q=traitlets) ... in particular, we have to find  where `HasTraits` is used.

**Comment by DrXyzzy** [comment]
Thank you. Will have a look. 
Also tempting to sweep it under the rug:
```
import warnings

with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=DeprecationWarning)
    import ipython-modules-with-deprecations
```

**Comment by haraldschilly** [comment]
oh yes, sure. if it turns out to be some version incompatibility or
something purely in that ipython world, go ahead and mute it!
