### ISSUE TITLE
Install XGBoost system-wide

### ISSUE THREAD

**Issue by slel** [sagemathinc/smc#891]
Install XGBoost Python package system wide.

XGBoost implements machine learning algorithms under the Gradient Boosting framework

Code: https://github.com/dmlc/xgboost
Pypi: https://pypi.python.org/pypi/xgboost
Docs: https://xgboost.readthedocs.io/en/latest/
Demo: https://github.com/dmlc/xgboost/tree/master/demo

[Requested by iScienceLuvr on gitter](https://gitter.im/sagemath/cloud?at=57ce0792fe284f6c3029dea1).

**Comment by haraldschilly** [comment]
![smc-xgboost](https://cloud.githubusercontent.com/assets/207405/18409636/5d3328aa-774c-11e6-9bea-0d5b9caf4cc8.png)
