### ISSUE TITLE
Add Google speech recognition support via free Chrome webspeech api 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#893]
Christine really needs voice recognition in general because of issues with her hands and thinks that this a common accommodation for students with disabilities.

**Comment by williamstein** [comment]
I don't think this belongs in SMC. Isn't this something that should or is provided at the operating system level?  E.g., it's part of accessibility of the OS.

**Comment by timothyclemansinsea** [comment]
This is a feature that Google Docs has. This is not something that Windows offers.

**Comment by williamstein** [comment]
https://en.wikipedia.org/wiki/Windows_Speech_Recognition

**Comment by timothyclemansinsea** [comment]
Christine claims it doesn't do what she needs it to do like work in a Sage
worksheet. She tried it. It may have something to do with codemirror.

**Comment by williamstein** [comment]
Test vanilla codemirror at http://codemirror.net/mode/python/index.html (say).  If it doesn't work there, that is an issue to fix in codemirror...

**Comment by timothyclemansinsea** [comment]
OK we'll try it later today.
