### ISSUE TITLE
Embedded Codemirror in Tasks editor doesn't respect account settings default font size

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#895]
Render size changes appropriately but double clicking to edit the task results in a smaller default font size.

**Comment by DrXyzzy** [comment]
Assigning to @williamstein - I think this will be addressed by rewrite under way.

**Comment by DrXyzzy** [comment]
@johnjeng can you add steps to reproduce the bug?

**Comment by williamstein** [comment]
time: 8 minutes
