### ISSUE TITLE
sagews search_src is broken after upgrade to sage-7.3

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#898]
As implemented in #724, search_src() depended on a sage git repository mounted to SMC. That does not seem to be the case now. Will re-implement, based on system `find` command:
```
$ time find /projects/sage/sage-7.3/src/sage -type f| xargs grep -l "Berlekamp-Zassenhau"
/projects/sage/sage-7.3/src/sage/rings/polynomial/polynomial_element.pyx
 
real    0m0.058s
user    0m0.032s
sys     0m0.028s
```

**Comment by haraldschilly** [comment]
Hmm, there is a git repo, what was the real problem? Maybe just the path? Grep alone is not only slower, but it also shows non-source files.

That's me running (what I think) is the old command:
```
$ cd /projects/sage/sage-7.3/src/sage; git grep -il 'Berlekamp-Zassenhau'
rings/polynomial/polynomial_element.pyx
```

**Comment by DrXyzzy** [comment]
Done.
