### ISSUE TITLE
files/move: surrounding spaces in dir name confuse the move command

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#902]
in particular, moving a file "abc xyz.ipynb" to a directory named "foo 2 " (notice the additional space after the "2".

**Comment by williamstein** [comment]
Yes, this is broken.  I bet a trim is done on the frontend to remove spaces from the front and back of the filename.

**Comment by williamstein** [comment]
Fixed in https://github.com/sagemathinc/smc/commit/16fef153720aa79098301430b2edd5d753484420
