### ISSUE TITLE
fix upgrade limit message

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#906]
After https://github.com/sagemathinc/smc/pull/896, when you apply a big upgrade it gives a triply mysterious error message:
<img width="634" alt="screen shot 2016-09-15 at 2 25 23 pm" src="https://cloud.githubusercontent.com/assets/1276278/18568125/5cd487ac-7b50-11e6-9272-d07dc43b8315.png">

Mysterious because:

1. is it "not enough upgrades" or is it "exceeding limit"?
2. if "exceeding limit", what is the limit?  It's very hard to know.
3. if "not enough upgrades", how do I get more?  How do I move them from other projects?

**Comment by williamstein** [comment]
Gees our whole upgrade page is really confusing...   It would be way better to have something to edit each individual quota integrated with the quotas below, and with appropriate controls.

**Comment by williamstein** [comment]
In fact, this is flat out wrong and buggy!  This is just nonsense:

<img width="641" alt="screen shot 2016-10-04 at 1 08 32 pm" src="https://cloud.githubusercontent.com/assets/1276278/19090525/be9d6660-8a33-11e6-85fe-e024d4280f3c.png">

Adding something gets even crazier:

<img width="618" alt="screen shot 2016-10-04 at 1 08 39 pm" src="https://cloud.githubusercontent.com/assets/1276278/19090531/c9a27f5a-8a33-11e6-8832-7008af78b432.png">

**Comment by williamstein** [comment]
OK, I'm going to fix this mess asap.

**Comment by williamstein** [comment]
Actually, the display isn't buggy. It's just really, really confusing. E.g., when it says something like

"1 of 17 upgrades remaining"

it means "You may apply 1 upgrade to this project of the 17 upgrades that you have left".

When you apply it and it switches to

"0 of 16 upgrades remaining"

it means "You may apply 0 upgrade to this project of the 16 upgrades that you have left"
since you already applied an upgrade.

It's so confusing I couldn't even understand it.

**Comment by drewyoungren** [comment]
I'm not even convinced that last interpretation makes sense. Look at the Idle timeout example above. "[You may apply 18 of the 18 hours remaining to this upgrade" should become "17 of 17" not "16 of 17".

**Comment by williamstein** [comment]
I agree -- definitely wrong in some cases.
