### ISSUE TITLE
you can't copy a file to the top level directory of another project (button is disabled)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#917]
Try copying a file to the top level of another project. FAIL.  This is probably due to fixing the issue with spaces at the end of path names.

A workaround is to put a single period `.` for the target path.

**Comment by haraldschilly** [comment]
duplicate of #822

**Comment by williamstein** [comment]
Yep, dup.  I was thrown off by how verbose Greg's description was....
