### ISSUE TITLE
%sh default_mode autocomplete and capture not working

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#920]
New problems since PR #911 

- [x] fix autocomplete
- [x] fix capture

**Comment by DrXyzzy** [comment]
Autocomplete fixed. Still working on %capture.

**Comment by haraldschilly** [comment]
made you two checkboxes, such that we know that this is half done

**Comment by DrXyzzy** [comment]
Capture might be broken with default_mode in general, not just with the new sh:
```
%default_mode r
... new cell ...
x <- c(9,7,44)
... new cell ...
%capture(stdout='foo')
mean(x)
... new cell ...
%sage
print(foo)
NaN
```

**Comment by DrXyzzy** [comment]
Done, verified in production.
