### ISSUE TITLE
add a link from the "Help/Support" popup to the wiki documentation

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#929]
1. Put a link when making a support ticket to https://github.com/sagemathinc/smc/wiki
2. Also change the link at the top of https://cloud.sagemath.com/help to point to https://github.com/sagemathinc/smc/wiki

Why - I'm tired of frustrated people contacting support just for this link!

**Comment by timothyclemansinsea** [comment]
This appears to be fixed?

**Comment by williamstein** [comment]
Yep, works.
