### ISSUE TITLE
Ideas for making Sage processes use less memory (so we can have more simultaneous users)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#93]
Suggested by pipeep on Hacker News: https://news.ycombinator.com/item?id=10147401

1. I thought sage used a ton of RAM partly because of the huge amount of statically linked libraries. I see you said you're using fork to maximize shared memory. Have you tried KSM (Kernel Samepage Merging)?

2. Have you looked at zram? Certain matrices and such may be easily compressible.

**Comment by haraldschilly** [comment]
I've never heard of KSM, but I've suggested zram before. It's this in-memory swapping tool, used by ChromeOS and Android. By default, it creates a block per cpu core ... maybe that's something that should be decreased a bit when trying it out.

**Comment by haraldschilly** [comment]
regarding KSM: I found this page helpful http://serverascode.com/2012/11/11/ksm-kvm.html

**Comment by williamstein** [comment]
too vague
