### ISSUE TITLE
Add togglable support for browser notifications of new chat messages

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#936]
Add to account settings a checkbox to enable chat browser notifications. We would use a generic API discussed at http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example Anytime there is a new message, a browser notification would have the sender's name, project name where chat file is, path for the chat file, and sender's message. Clicking on the notification would open up the chat.

I personally really hate leaving tabs just to find out that a chat message was not relevant to me. Notifications could fix this.

**Comment by williamstein** [comment]
We would also have to add some state to the database **or** localStorage, which says "a notification for this thing has been shown to the user"....

**Comment by williamstein** [comment]
Basically this dupes #113.
