### ISSUE TITLE
Clearing chat notification in bell by clicking the chatbox is not working anymore

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#937]
This was implemented in https://github.com/sagemathinc/smc/pull/596.  Now that it doesn't seem to work anymore it is now a bug.

**Comment by haraldschilly** [comment]
I just tested it, and it works.

What might be the issue is the following: was your cursor already in the box and focused? Maybe clicking again to re-focus doesn't trigger an event. only blurring and then focusing again causes it.

**Comment by williamstein** [comment]
This does work. Closing.
