### ISSUE TITLE
open any subdirectory in the file browser and refresh the browser completely -- it will never finish

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#941]
Opening a directory directly doesn't work.

This fails whether or not the user is signed in, public, private, admin etc.  You have to always refresh once.

[EDITED: I thought this was a public only issue, but it always happens.  Very serious.]

**Comment by williamstein** [comment]
The code that is broken is this with nontrivial target in projects.cjsx.  It just fails in all cases on first load:
```
    # Open the given project
    open_project : (opts) =>
        opts = defaults opts,
            project_id : required
            target     : undefined
            switch_to  : undefined
        if window.FULLY_REACT
            @set_project_state_open(opts.project_id)
        else
            opts.cb = (err) =>
                @set_project_state_open(opts.project_id, err)
            open_project(opts)
            if opts.switch_to
                @foreground_project(opts.project_id)
```

Notice that the `@set_project_state_open(opts.project_id)` line ignores `opts.switch_to`.  

Anyway, this is a high priority bug and it is definitely blocked on the react rewrite.

**Comment by williamstein** [comment]
Fixed by react rewrite

**Comment by johnjeng** [comment]
Rewrite merged so this is fixed! :+1:
