### ISSUE TITLE
sage chat can sometimes become corrupted when several users simultaneously try to edit the same past chat -- make this impossible

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#944]
(workaround: use timetravel)

**Comment by timothyclemansinsea** [comment]
Do we know for sure if this was corrupted JSON in the file?

Is getting rid of the json in the file (the data is in the db right?) a possibility? I know we like to edit these chats by hand sometimes but that makes it likely there will be corruption.

**Comment by williamstein** [comment]
Changing to insanely hard -- the right fix here is to implement a version of the whole "syncstring"/patches framework that uses patches on json documents, rather than on strings. Then corruption is not possible.

**Comment by williamstein** [comment]
Instead of a general json diff/patch, we could also make a list of the valid actions/ transforms one can make to a chat.  E.g., 
  - append message with given timestamp
  - edit message with given timestamp -- this means applying a normal string patch to the version before the editing.

 Anything else?

Then, in the patches log for the chatroom, instead of storing an ordered sequences of [timestamp,patch] pairs, we store an ordered sequence of [timestamp, transform] pairs.
Then the state of the chatroom at a given time is the result of applying that sequence in order. 
There is no possible notion of conflict and no actual underlying json string structure, etc.

So this would work fine.  The drawback is that it's probably a few days work to implement.   
Defining the actions clearly above of course corresponds to the notion of REDUX actions.

**Comment by williamstein** [comment]
Another idea: maybe lock so only one person an edit a past chat at a time?  Lame, but would address the issue I saw.

**Comment by williamstein** [comment]
Now done!!!   I properly re-implemented syncdb from scratch using a much more sophisticated version of patching.

**Comment by williamstein** [comment]
time: 10 days
