### ISSUE TITLE
Create a custom file editor plugin system based on Horizon

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#947]
Custom editors would save data in their own database on a project-wide RethinkDB server and follow a basic protocol. 
- A directory of custom editors with flag for "confirmed safe"
- A component on project settings that maps file extension to editor's path and port number
- A component on project settings for installing RethinkDB and editors
- When open a file with a mapped custom editor: SMC ensures RethinkDB and editor's web server is running, SMC calls editor's url with given SMC user info and path for the file being edited, loading message shows until connected, an iframe appears showing editor
- Write a guide to how to make a custom editor

**Comment by williamstein** [comment]
This is a proposal and may conflict with some basic design principles for SMC.  E.g., in SMC all editors have realtime sync and are multiuser, and giving editors direct rethinkdb access is not possible due to security issues.   Also, Horizon isn't a part of SMC.

**Comment by timothyclemansinsea** [comment]
Guess "project-wide RethinkDB server" wasn't clear. There would be a RethinkDB server running in the project if one installs an editor via Project Settings. As far as "may conflict with some basic design principles" just have an approval process like Apple for iOS.

**Comment by williamstein** [comment]
> There would be a RethinkDB server running in the project if one installs an editor via Project Settings.

I'm against doing that.

>  As far as "may conflict with some basic design principles" just have an approval process like Apple for iOS.

I'm talking about the design being proposed here for apps, not the apps themselves.

**Comment by williamstein** [comment]
What does "based on Horizon" mean?

**Comment by timothyclemansinsea** [comment]
> I'm against doing that.

I am looking for a rapid way to make my own editors. And really all that's really needed to make this work at all is file extension to port mapping.

> What does "based on Horizon" mean?

The editors would be written using Horizon. Our template would demonstrate the basic design principles like multi-user and realtime sync. I think "SMC calls editor's url with given SMC user info and path for the file being edited" is all the editor would need for doing multi-user and realtime sync.

**Comment by haraldschilly** [comment]
I don't know horizon at all, but regarding custom app-like plugins I'm all in favor of designing a low-level library that is neutral to the used technology. Not that I have a specific idea at hand right now, but I wouldn't impose a specific tool at all.

Besides that, I'm opposed to running a rethinkdb instance inside a project at all. It would be better to use our existing cluster setup.

**Comment by timothyclemansinsea** [comment]
Well for a MVP of this just implement extension to port mapping and dead
simple protocol. See if this is a good thing at all before exploring
storing data via cluster.
