### ISSUE TITLE
%octave: special character problem

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#953]
Not sure if this is a simple python2 problem or more complicated and something for upstream

```
%octave
printf("ä→ßµ")
```

gives

```
'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

(btw: `%sh` with `echo "ä→ßµ"` works)

**Comment by DrXyzzy** [comment]
Error also appears with jupyter notebook running octave kernel. Does not appear if `printf("ä→ßµ")` is entered in .term running octave session.
```
$ /usr/bin/octave
...
octave:1> printf("ä→ßµ")
octave:2> ä→ßµ
```

**Comment by haraldschilly** [comment]
probably a dup of #415

**Comment by haraldschilly** [comment]
reported it here: https://github.com/Calysto/octave_kernel/issues/46

**Comment by haraldschilly** [comment]
discussion on that ticket kind of ping-pongs back to us. my next idea is to try updating that lib or see if I can triage it to a specific line in the code.

**Comment by williamstein** [comment]
Seems like a hard problem due to being upstream.

**Comment by haraldschilly** [comment]
ok, this is fixed. took me more than an hour to figure out, that it was a mix of an outdated metakernel package, stale cached files, and that the pip-installation switched from those "egg" archives to wheel (?).
