### ISSUE TITLE
the avatar counter is still wrong

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#964]
<img width="546" alt="screen shot 2016-09-28 at 3 03 54 pm" src="https://cloud.githubusercontent.com/assets/1276278/18934106/d6e7eec6-858c-11e6-92bc-db97a6adcede.png">

Above it says +2 but should say +1...

**Comment by haraldschilly** [comment]
I merged #1081 since I think it fixes this. We should keep an eye on that, though, maybe some corner case comes up.
