### ISSUE TITLE
Add hover text to the new arrows showing up on sagews on the left side

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#965]
It took me a moment or two to figure out what these arrows are supposed to do. It looks like they are for toggling a cell.

**Comment by williamstein** [comment]
I'm not sure about adding hover text -- it'll slow things down, use memory, and you did figure it out in a moment or two.

**Comment by williamstein** [comment]
It would be good to have an optional non-forced "tour" feature or something, like other sites have.

**Comment by haraldschilly** [comment]
> It would be good to have an optional non-forced "tour" feature or something, like other sites have.

Reminds me of what I tried to do some time ago with intro.js, i.e. https://github.com/sagemath/cloud/issues/76

I only remember that it was acting funny, because of the overlay and positioning. I bet there are better options available now, or this one works better with bootstrap, etc.

**Comment by williamstein** [comment]
Just to be clear, I'm imagining something like that, but only for a specific editor (sagews in this case).

**Comment by timothyclemansinsea** [comment]
@williamstein if we did a tour then we would need a tour of new features for long time users

**Comment by williamstein** [comment]
>  we would need a tour of new features for long time users

Indeed, it would also be nice to have a tour of new features for long time users.

**Comment by timothyclemansinsea** [comment]
I'm closing this issue because we're going to do something different like a tour.
