### ISSUE TITLE
chatroom: type a message, click preview, hit escape to close preview --> and your message is GONE. Forever.  Not even in undo.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#967]
For some reason, I often try to submit a chat by "tab, enter" for some reason... instead that previews, so I go -- what? why preview?  -- and hit escape, and boom, I just lost my message.

**Comment by simonluu** [comment]
when you open the preview, it auto focuses to the input and when you click the escape key it clears the input. So it doesn't actually turn off the preview, it just shows nothing since you cleared the input.

**Comment by williamstein** [comment]
@simonluu  -- Very good point.  Then the fix is to not clear the input on escape.  It has nothing to do with preview.  That's the real bug.    For example, while typing in the box here in github, when you hit escape, it does nothing -- it doesn't clear the input.
