### ISSUE TITLE
the "Auto close brackets: automatically close brackets" in haskell mode is buggy

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#972]
When enabled (which it is by default), typing
```
    "hello"
```
inserts a " suddenly at the very end (and only then).  Probably the best solution for this issue for now is just never enable Auto close brackets: automatically close brackets" for `.hl` haskell files.

This could also get reported to Codemirror upstream...

**Comment by DrXyzzy** [comment]
Reported it here: codemirror/CodeMirror#4277.
