### ISSUE TITLE
when printing a sagews file that has markdown with images, make the images appear in the resulting pdf file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#98]
Example:

   https://cloud.sagemath.com/projects/8aa6ebbd-0222-4e49-8470-829d9393b2d0/files/Tracking%20off%20axis%20at%20parallactic%20angle.sagews

The problem here is that the image is a file foo.png locally, but it's not being properly included in the latex file right now... simply because of not thinking about dealing with this case.

**Comment by haraldschilly** [comment]
this should be solved by my recent work on sagews2pdf. in fact, this worksheet also includes those matrices, which should also work now.

**Comment by williamstein** [comment]
Is this solved???

**Comment by williamstein** [comment]
works!
