### ISSUE TITLE
fix the download button to always download a file

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#982]
If you try to download a file there is a button and a link. The button may or may not work depending on browser, file type, etc.,  Using buttons to initiate a download robustly is really only possible using (crappy) Flash, I think.

**Comment by timothyclemansinsea** [comment]
Can we call this Raw version? if chrome then we could download button using
http://superuser.com/questions/868818/how-to-instruct-chrome-to-download-pdf-rather-than-preview-in-browser

**Comment by williamstein** [comment]
Sure.  You can try the rabbit hole of hacks to make this work. We obviously did and failed a year ago when we first implemented this.  Maybe things are better now.

**Comment by haraldschilly** [comment]
The proper way for downloading always  is to send binary as the mime type. I can fix this, just assign this to me.

**Comment by haraldschilly** [comment]
I've assigned this to myself, but I actually want to fix the implementation of downloading, such that it really always downloads when it is supposed to do so. Is this ok?

**Comment by williamstein** [comment]
> Is this ok?

YES!

**Comment by timothyclemansinsea** [comment]
I use SMC for making web pages. It would suck to no longer be able to display a webpage directly because it gets auto downloaded. I use Windows split screen to have SMC editor on left and page on right and I refresh the right side a lot.

**Comment by haraldschilly** [comment]
@timothyclemansinsea did you read my patch? please do it, ad then you would see that it doesn't touch the current behavior. I'm well aware that someone would like to run some general webservice through smc and that case should still work.

**Comment by timothyclemansinsea** [comment]
ok so I can go any raw file without ?download and it'll show up in browser if say it is HTML.
