### ISSUE TITLE
setup jupyter nbextensions_configurator

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#985]
Investigate how to set [it](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) up globally, what would then be necessary for individual projects, and also investigate which [other extensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) make sense.

e.g. the one that limits output sounds like something we definitely want to have!

ref: zd #2176

**Comment by mforbes** [comment]
Could you please explain how I can customize the jupyter notebook that is running so I can play with various configuration options?  William [mentioned installing `smc_sagews`](https://gitter.im/sagemath/cloud?at=57f056220ff4ef7a50f8c526) and hinted that you might provide a way to [customize smc-jupyter](https://gitter.im/sagemath/cloud?at=57f07d2dbe5dec7550113416) but I have had no luck so far.  (I won't be able to play with this for about a week, but it would be nice to know how to start.)

**Comment by haraldschilly** [comment]
@mforbes I'm not sure how to do this, either. I have an idea but might not work. Can you email me the link to the project where you are working on this to hsy@sagemath.com ? Then I can have a look right there.

**Comment by williamstein** [comment]
this will not be supported going forward -- instead we plan to reimplement all POPULAR extensions.  If you need a particular extension, please create a new issue for it.
